### ISSUE TITLE
Add license file and headers

### ISSUE THREAD

**Issue by Alex-doc** [Zylann/godot_voxel#1]
Hi, I'm interested in tryng out your module but I'm unable to find License file or headers.
Would you please add them?

**Comment by Zylann** [comment]
I just added the license file.
This module was working in 2.0.3, I'm not sure about 2.1. I changed my PC recently so I have to setup my Godot development environment again :p

**Comment by Alex-doc** [comment]
Thank you!
Now trying to figure out how to use it :)

**Comment by Zylann** [comment]
I made a test project here, if you want to take a look https://github.com/Zylann/voxelgame

**Comment by Alex-doc** [comment]
Looking good! 
I've seen you have a pretty nice TODO list, are you planning to work on it or to move on something else?

I'm making a game which is procedurally generated, if you are willing to continue the support on this module I could try to help you.

**Comment by Zylann** [comment]
I'm not working on it right now, because of other projects such as a terrain editor and a 2D game I was working on way before I started this module^^
But I may continue its development in the future, as I have design ideas in mind but simply no time yet to implement them :)

**Comment by Alex-doc** [comment]
Please ping me when you are back on this ;) 
Good luck with your projects!

**Comment by Zylann** [comment]
License was added, closing.
