### ISSUE TITLE
Number of blocks

### ISSUE THREAD

**Issue by Hromon** [Zylann/godot_voxel#106]
Hello, the number of blocks is 256, can it be bypassed or configured somehow?
And how is it with multi-threaded rendering of the Godot? I remember that he had problems

**Comment by tinmanjuggernaut** [comment]
> And how is it with multi-threaded rendering of the Godot? I remember that he had problems

Voxel Tools + Multithreaded or Vsync on is no good. #48
I can't speak to multithreaded outside of VT.

**Comment by Zylann** [comment]
You can change the view distance by modifying the `view_distance` property.

**Comment by blockspacer** [comment]
@Zylann 
I think that he asks about max. number of block types (materials, textures) for blocky mesher

**Comment by Zylann** [comment]
Yes the limit is 256, current voxels cannot contain values greater than this because they are 8-bit. It is planned to have 16-bit voxels in the future.
Note that if you need this to store extra data for your game, you can use a different channel.

**Comment by blockspacer** [comment]
`It is planned to have 16-bit voxels in the future.` - do we have separate issue about it?
Can it be fixed by simply changing some data types in voxel_buffer.h ?

**Comment by Zylann** [comment]
> do we have separate issue about it?

Someone opened one but closed it. Nevertheless it is still planned and there is work in progress in the `depth` branch.

> Can it be fixed by simply changing some data types in voxel_buffer.h ?

This is what I am doing in the `depth` branch. The data remains stored in `uint8` but will be interpreted as a different type depending on the depth setting for that channel.
The only problem is that current meshers are optimized for 8-bit data, and I need to find a way to bring them support for more without altering their properties (especially Transvoxel, which even relies on integer math).

**Comment by blockspacer** [comment]
> Minecraft doesnt even have that many.

Minecraft with mods may have a lot of block types (default 0﻿-4095, configurable 0-32767﻿) https://gaming.stackexchange.com/questions/271642/can-i-increase-the-maximum-forge-vanilla-id-limit-or-remove-it-entirely/271643

Thanks for response.

**Comment by Hromon** [comment]
> Why do you need more than 256 types? Minecraft doesnt even have that many.
If work to Large project, we need more. What is the problem? Using lot RAM or reduce performance?

**Comment by blockspacer** [comment]
> RAM

I think that RAM may be the main problem for huge block id range

BTW Technically in 1.8 there are 65535 block ids. https://github.com/MinecraftForge/MinecraftForge/issues/1769#issuecomment-89503629

**Comment by Zylann** [comment]
I just added support for up to 65536 blocks in the `depth` branch, you can give it a try.
For this to work, your `VoxelStream` must call this before generating voxels:
```gdscript
voxels.set_channel_depth(VoxelBuffer.CHANNEL_TYPE, VoxelBuffer.DEPTH_16_BITS)
```

**Comment by Zylann** [comment]
Branch `depth` was just merged to `master`.

**Comment by Zylann** [comment]
I'll close this now, until more comes up about block counts / channel depth

**Comment by nic96** [comment]
I tried using this, but it doesn't seem to work. In my custom VoxelStream I tried this code to set the channel depth to 16:
```
func emerge_block(buffer:VoxelBuffer, origin:Vector3, _lod:int) -> void:
	buffer.set_channel_depth(VoxelBuffer.CHANNEL_TYPE, VoxelBuffer.DEPTH_16_BIT)
```
But when I  try to use a voxel above 256 I get an invisible block which I'm assuming is air, but I'm not sure. The invisible block does create ao though.

It might not be at the right location. I couldn't find any current examples of setting the channel depth for custom streams or generators.

**Comment by Zylann** [comment]
The code you posted isn't enough to figure it out. I need to see how you actually set/get voxels, and eventually have a reproduction project.

**Comment by nic96** [comment]
Alright, so I have this script attached to a VoxelTerrain node:
```
extends VoxelTerrain

const VoxelStream = preload("voxel_stream.gd")

func _ready():
	self.stream = VoxelStream.new()
```
I tried calling `self.stream.set_channel_depth(VoxelBuffer.CHANNEL_TYPE, VoxelBuffer.DEPTH_16_BIT)`
right after the above last line, but I just get Nonexistent function error. 


and in voxel_stream.gd I have this code which is pretty much just put together from examples:
```
extends VoxelStream

export var channel:int = VoxelBuffer.CHANNEL_TYPE

var noise = OpenSimplexNoise.new()
var noise_multiplicant = 20

func get_used_channels_mask () -> int:
		return 1<<channel

# emerge_block(out_buffer: VoxelBuffer, origin_in_voxels: Vector3, lod: int)
func emerge_block(buffer:VoxelBuffer, origin:Vector3, _lod:int) -> void:
	buffer.set_channel_depth(VoxelBuffer.CHANNEL_TYPE, VoxelBuffer.DEPTH_16_BIT)
	var ox = int(floor(origin.x))
	var oy = int(floor(origin.y))
	var oz = int(floor(origin.z))
	
	var x = 0
	var z = 0
	
	var bs = buffer.get_size_x()
	
	var dirt = 1

	while z < bs:
		while x < bs:
			var h = floor(noise.get_noise_2d(ox+x, oz+z) * noise_multiplicant - (oy))
			if h > 0:
				if h > bs:
					h = bs
				buffer.fill_area(dirt, Vector3(x,0,z), Vector3(x+1,h,z+1), channel)
			x += 1
		z += 1
		x = 0
```
So the first line in the emerge_block function is where I'm trying to set the channel depth.

The player placing blocks is the same as in this voxelgame example except that I'm trying to place blocks with IDs above the 255 limit:
https://github.com/Zylann/voxelgame/blob/master/project/blocky_terrain/avatar_interaction.gd#L74

Any IDs below that work fine although, but I'm guessing integer overflow is happening. One thing to note though is whenever I'm adding a blocking in my voxel_library.tres I get the following output in the Godot output window:
```
 modules/voxel/meshers/blocky/voxel.cpp:109 - Condition "id < 0 || id >= 256" is true. Returned: Ref<Voxel>(this)
```
<img width="603" alt="image" src="https://user-images.githubusercontent.com/8008902/86541200-46df5700-bec8-11ea-9391-f09aa001fbca.png">

Another thing I'm wondering about is when to use VoxelGenerator and when to use VoxelStream. I've been able to produce the same results with either the only difference seems to be in the naming. So which one should I use for generating blocky voxel worlds?

Finally the get_used_channels_mask function doesn't seem to be documented anywhere what exactly I can do with it. It seems like I should be able to set multiple things here by using a bitwise or operation and is it maybe here that I'm supposed to set the channel depth as well or is it simply for specify blocky or smooth terrain?

I'm tempted to for now just change `DEFAULT_CHANNEL_DEPTH` in [voxel_buffer.h](https://github.com/Zylann/godot_voxel/blob/master/voxel_buffer.h#L50) and recompile with that until I get a better understanding of how everything in this module works

**Comment by Zylann** [comment]
Your generator code looks correct.

> One thing to note though is whenever I'm adding a blocking in my voxel_library.tres I get the following output in the Godot output window:

    modules/voxel/meshers/blocky/voxel.cpp:109 - Condition "id < 0 || id >= 256" is true. Returned: Ref<Voxel>(this)

That check is outdated, the maximum should be 65535.

> Another thing I'm wondering about is when to use VoxelGenerator and when to use VoxelStream.

`VoxelStream` is more abstract than `VoxelGenerator`. If you make a generator, use the latter. A "stream" can be many things. The reason to have such separation is clarity, and knowing that a stream is just a generator allows to do extra things that would be much harder to maintain otherwise. It becomes especially useful with smooth LOD terrains, where being able to query a single voxel on the fly from the generator has specific advantages when producing meshes.

> Finally the get_used_channels_mask function doesn't seem to be documented anywhere what exactly I can do with it.

That function was added recently. It basically tells which channels your `VoxelStream` is going to produce. If you don't specify it, some blocks might have such channels, some not, which makes it harder for the terrain node to know what to do (leading to waste of CPU if it had to assume they were all used). The function is expected to return a bitfield where each bit represents one channel.

> I'm tempted to for now just change DEFAULT_CHANNEL_DEPTH

You shouldn't need to. From the moment you set the depth at the beginning of your function, you basically changed it correctly. The problem likely happens later. You can check if that actually works by doing a `set_voxel`, then a `get_voxel` at the same position and see if you get the same value. If you do, then the problem likely came from `VoxelLibrary`, as you pointed out.

**Comment by nic96** [comment]
So I added this code to to my VoxelGenerator:
```
	if !set_a_test_voxel:
		buffer.set_voxel(256, 0, 0, channel)
		print("And the voxel is: %s" % buffer.get_voxel(0, 0, 0, channel))
		set_a_test_voxel = true
```
And I got back `255` when calling `get_voxel` on any number above 255

Here's the full generator now:
```
extends VoxelGenerator

export var channel:int = VoxelBuffer.CHANNEL_TYPE

var noise = OpenSimplexNoise.new()
var noise_multiplicant = 20
var set_a_test_voxel = false

func get_used_channels_mask () -> int:
		return 1<<channel

func generate_block(buffer:VoxelBuffer, origin:Vector3, _lod:int) -> void:
	buffer.set_channel_depth(VoxelBuffer.CHANNEL_TYPE, VoxelBuffer.DEPTH_16_BIT)

	if !set_a_test_voxel:
		buffer.set_voxel(256, 0, 0, 0, channel)
		print("And the voxel is: %s" % buffer.get_voxel(0, 0, 0, channel))
		set_a_test_voxel = true

	var ox = int(floor(origin.x))
	var oy = int(floor(origin.y))
	var oz = int(floor(origin.z))
	
	var x = 0
	var z = 0
	
	var bs = buffer.get_size_x()
	
	var dirt = 1

	while z < bs:
		while x < bs:
			var h = floor(noise.get_noise_2d(ox+x, oz+z) * noise_multiplicant - (oy))
			if h > 0:
				if h > bs:
					h = bs
				buffer.fill_area(dirt, Vector3(x,0,z), Vector3(x+1,h,z+1), channel)
			x += 1
		z += 1
		x = 0

```

My godot version is checked out at the 3.2.2-stable tag
And the godot_voxel module is on commit  [60d32ec](https://github.com/Zylann/godot_voxel/commit/60d32ec00697c48f126e48a4ed5ca7f76606e874) which as of writing is the latest commit on master

**Comment by Zylann** [comment]
Note: make sure `channel == VoxelBuffer.CHANNEL_TYPE`, there is still a possibility that `channel` has the wrong value.

Had a look at `set_channel_depth`, looks like there is a really stupid error there. `channel.depth` was not assigned^^
https://github.com/Zylann/godot_voxel/blob/60d32ec00697c48f126e48a4ed5ca7f76606e874/voxel_buffer.cpp#L700

It just needs a `channel.depth = new_depth` at the end.

**Comment by nic96** [comment]
So I added `channel.depth = new_depth` at the end of the `set_channel_depth` method and `set_voxel` and `get_voxel` are now the same value of 256 with my test in the above generator, but Now all the blocks are invisible. The blocks are there though cause I can see the outline of the blocks that raycast hits. If I set it to DEPTH_8_BIT the blocks are visible again.

**Comment by Zylann** [comment]
Might be a problem in `VoxelMesherBlocky` now, but I have no idea what. It should already handle 16-bit voxels.

**Comment by nic96** [comment]
If I set the `DEFAULT_CHANNEL_DEPTH` to 16 bit it works so I'm not sure what's happening with set_channel_depth

**Comment by Zylann** [comment]
`DEFAULT_CHANNEL_DEPTH` should have had the exact same effect as you setting the depth in the generator... and it's used nowhere near the meshing code :/
There is something really stupid going on, but it needs debugging.

**Comment by Zylann** [comment]
Looks like an issue with `VoxelMap::get_buffer_copy`. It copies a part of the terrain into a `VoxelBuffer`, however it doesn't initialize depth (left to default then). Which means it converts internally back to 8-bit, which is also a bit slower.
Initializing depth is easy when a block with data is found, but I don't know what to do for cases where there is no block found.

**Comment by Zylann** [comment]
@nic96 does it work if you add this to `voxel_map.cpp`?

```cpp
dst_buffer.set_channel_depth(channel, src_buffer.get_channel_depth(channel));
```
Just below this: https://github.com/Zylann/godot_voxel/blob/8b4bd1d853f3272d45d9ba433f6b3451f8a601a5/terrain/voxel_map.cpp#L203

**Comment by nic96** [comment]
No, I still get block 255.

<img width="466" alt="image" src="https://user-images.githubusercontent.com/8008902/87110412-390d3700-c224-11ea-9741-25cf80c1db0d.png">

**Comment by Zylann** [comment]
> https://github.com/Zylann/godot_voxel/issues/106#issuecomment-653965175

You had it fixed earlier by assigning `depth` in `VoxelBuffer`, which I did submit in 8b4bd1d853f3272d45d9ba433f6b3451f8a601a5. How come you still get 255 Oo (The extra in `VoxelMap` is for the copy to the meshing system also preserve that depth and then show stuff)
Did you try that after getting latest?

**Comment by nic96** [comment]
I might not have been on latest master. I thought I did a git pull, but I'm unsure now. I might have done a git pull on my own fork 🤦‍♂️

**Comment by nic96** [comment]
I'll check after work

**Comment by nic96** [comment]
> ```c++
> dst_buffer.set_channel_depth(channel, src_buffer.get_channel_depth(channel));
> ```

That fixed the invisible blocks problem. Without it I'm getting this in the Godot debugger:
<img width="313" alt="image" src="https://user-images.githubusercontent.com/8008902/87214890-f0ba4b80-c2ed-11ea-8c77-5c05cf87a7f9.png">
`copy_from: Condition "other_channel.depth != channel.depth" is true.`

**Comment by Zylann** [comment]
I pushed the change.
