### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by hotpeperoncino** [Zylann/godot_voxel#11]
when compiling, StaticObject does not have set_shape method, it is not found. Can I have an advice to rewrite correctly?

**Comment by Zylann** [comment]
I fixed it in my local fork by basically removing physics support... it fixes compilation but as a result there is no physics anymore. I need to rewrite it to use PhysicsServer directly.

**Comment by hotpeperoncino** [comment]
Thank you for your comment

**Comment by Zylann** [comment]
It should compile now, but there is no physics anymore. Will add them later.
