### ISSUE TITLE
Blocky voxels - Non-cube voxels

### ISSUE THREAD

**Issue by spacechase0** [Zylann/godot_voxel#112]
I noticed in the screenshot [here](https://github.com/tinmanjuggernaut/voxelgame/blob/master/screenshots/2016_04_27_2037_half.png) there was apparently a way to have voxels not be a cube. But from what I've read that was from the pure GDScript version, and hasn't been reimplemented yet.

I just looked at the `full_gdscript` branch on tinmanjuggernaut's fork and it looks like it was done just with another voxel type, but to me it seems a more flexible solution that took in a static mesh or something to allow more types (like, Minecraft slabs or stairs) without having to edit the module each time would be more useful. I don't know how practical that is with hiding connected faces and whatever else is required for performance though.

**Comment by Zylann** [comment]
There is some degree of non-cubic voxels capability in the current blocky mesher, but the interface to set them up is just missing.

> don't know how practical that is with hiding connected faces and whatever else is required for performance though.

Non-cubic voxels in general won't benefit from face occlusion indeed. There is some research to be done to find eventual techniques to make it work while conserving a decent meshing speed.

There is an issue open about it already: https://github.com/Zylann/godot_voxel/issues/78

**Comment by spacechase0** [comment]
Sorry, I thought I looked through the issue list a couple times. I must've passed right over that.

**Comment by tinmanjuggernaut** [comment]
@spacechase0 FYI, the only thing different between my fork and Zylann's is the fps_demo directory on master.

**Comment by spacechase0** [comment]
Ah, okay. I found the `full_gdscript` branch there.
