### ISSUE TITLE
VoxelGeneratorNoise not found when exported

### ISSUE THREAD

**Issue by CammiePone** [Zylann/godot_voxel#114]
I was messing around with the voxels and encountered a totally separate issue that might be my fault, but when I decided to try exporting it to see if that would change anything, and running it, I got an error saying that the class VoxelGeneratorNoise wasn't found. It runs in my workspace, so I'm not sure why it throws this error.

I'm using the master branch from here, and Godot's 3.2 branch.

The screenshot I was able to capture before both closed:
![image](https://user-images.githubusercontent.com/16853086/73799541-4198a780-4784-11ea-9d5c-b8185ec8d601.png)

**Comment by Zylann** [comment]
It looks like you used a vanilla export template. You need to compile export templates too, including the module.

**Comment by CammiePone** [comment]
Oh I did not know that. My bad. Thanks for the info!
