### ISSUE TITLE
[Bug] VoxelStreamRegionFiles & VoxelStreamBlockFiles generators fail to load data

### ISSUE THREAD

**Issue by TheMisteryMan** [Zylann/godot_voxel#116]
I attempted using VoxelStreamRegionFiles, and then VoxelStreamBlocksFiles with VoxelGeneratorNoise as a fallback stream.

VoxelGeneratorNoise works fine standalone, and also works fine on the first run with either file stream, but upon subsequent sessions, voxels file to generate/load, and I get 103 of the following in the debugger.
```
E 0:00:01.056   load_meta: Condition ' depth_from_json_variant(channel_depths_data[i], meta.channel_depths[i]) ' is true. returned: ERR_PARSE_ERROR
  <C++ Source>  modules/voxel/streams/voxel_stream_region_files.cpp:536 @ load_meta()
```
On a second note, it seems you can only set the File generator's save locations to locations within the `res://` folder, not the `user://` folder, which is a bit problematic, due to you not being able to save to `res://` in exported builds.

**Comment by Zylann** [comment]
Did you use both formats on the same location? They are not compatible formats, maybe one clashed with the other.
There seems to be an issue with one of them though.

**Comment by Zylann** [comment]
Ah, looks like there is a missing `!`

**Comment by TheMisteryMan** [comment]
Seems you already figured it out, but jsut for the record, I did clear my saves folder between switches, and only tried a different save format stream (VoxelStreamBlocksFiles), because the the first one I used didn't work (VoxelStreamRegionFiles).

**Comment by Zylann** [comment]
Just pushed a8c5fed29d0abc5fb85de4874b8bb2bf3f6a0ceb with fixes in it, you can check again

**Comment by TheMisteryMan** [comment]
VoxelStreamRegionFiles seems to work, but VoxelStreamBlockFiles is still broken upon attempting to load.
```
E 0:00:01.200   load_meta: Condition ' depth >= VoxelBuffer::DEPTH_COUNT ' is true. returned: VOXEL_FILE_INVALID_DATA
  <C++ Source>  modules/voxel/streams/voxel_stream_block_files.cpp:209 @ load_meta()
```

**Comment by Zylann** [comment]
Can you send your `.vxbm` file?

**Comment by TheMisteryMan** [comment]
[meta.vxbm.zip](https://github.com/Zylann/godot_voxel/files/4177215/meta.vxbm.zip)

**Comment by Zylann** [comment]
Looks like channel depths are corrupted:
![image](https://user-images.githubusercontent.com/1311555/74106981-84cb8f80-4b63-11ea-9202-28bf98155d7c.png)
It's possible that they were not initialized at the time they were written in here.

**Comment by TheMisteryMan** [comment]
I'm going to be using the Region format myself, so I'll be fine, just wanted to test BlockFiles so that you don't have to wait for someone to need/want to use it, and run into this.
Also, as for how I earlier said 

> it seems you can only set the File generator's save locations to locations within the res:// folder

It seems that's just if you use the folder picker by clicking the folder icon, putting in a path like `user://saves/` works fine.

**Comment by TheMisteryMan** [comment]
Just tested with the latest commit, VoxelStreamBloockFiles also works fine now, so I'll close this.

**Comment by Zylann** [comment]
I'll submit a few more fixes soon, but I don't really know what to do about the file dialog.
There are two use cases with it: either you design a terrain which is part if the game and in which case it makes sense to have it in `res://`. Or, it is generated as a savegame, in which case it makes no sense to set it from the inspector.

**Comment by TheMisteryMan** [comment]
My use-case is the 2nd, in which you are right, I didn't even think about that.
