### ISSUE TITLE
Can't build Godot and export templates w/ Voxel Tools w/o tools

### ISSUE THREAD

**Issue by CammiePone** [Zylann/godot_voxel#122]
I get this error when attempting to build Godot with Voxel Tools without tools. This also happens when trying to build the export templates.

Compiling Godot:
![image](https://user-images.githubusercontent.com/16853086/74554319-4a793e00-4f27-11ea-98e3-928041a16ad2.png)

Creating build templates:
![image](https://user-images.githubusercontent.com/16853086/74554462-a17f1300-4f27-11ea-93c8-1ca862eb865f.png)

**Comment by Zylann** [comment]
I need to get rid of some of those functions.

**Comment by Zylann** [comment]
Should be fixed in 17e3651d0ee5ee75b4a67727a0884fe9558491da
