### ISSUE TITLE
VoxelGeneratorTest needs support for LOD

### ISSUE THREAD

**Issue by tinmanjuggernaut** [Zylann/godot_voxel#125]
With the increasingly complex functionality going into the VoxelGenerators, I think it's a good to maintain `VoxelGeneratorTest` as a very simple example case for both VT and VLT, including LOD.

With PR #118 `VoxelGeneratorTest` now shows at least something on all supported permutations. However, VLT/Smooth is wonky and not fully implemented. It doesn't support LOD for instance. And even for VT/Smooth, it could have rounder peaks and troughs.

VT Blocky

![image](https://user-images.githubusercontent.com/632766/74607513-62fa7b80-5114-11ea-825b-d1feb5b15775.png)

VT Smooth

![image](https://user-images.githubusercontent.com/632766/74607525-773e7880-5114-11ea-861f-2ac0ae889ac9.png)

VLT Smooth

![image](https://user-images.githubusercontent.com/632766/74607537-9210ed00-5114-11ea-9bdd-8b71b87b229c.png)

[my gdscript version](https://github.com/tinmanjuggernaut/voxelgame/blob/detect_channel/project/fps_demo/scripts/MyStream.gd) removed the upper and lower caps, but still doesn't implement lod.

![image](https://user-images.githubusercontent.com/632766/74607828-14021580-5117-11ea-887e-3c4a42e37db4.png)

**Comment by Zylann** [comment]
I think the easiest route is to move the Waves mode into its own generator extending `VoxelGeneratorHeightmap`, and rename the `Test` one to be only `VoxelGeneratorFlat`

**Comment by Zylann** [comment]
Just done that in c33f46a4373de8d25068ff689e377456da7a0eb1

**Comment by tinmanjuggernaut** [comment]
Looks good, thanks.
