### ISSUE TITLE
Doesn't compile yet in Godot 4.0

### ISSUE THREAD

**Issue by jomiq** [Zylann/godot_voxel#127]
Failed compilation.

Output:
```
[Initial build] Compiling ==> modules/voxel/register_types.cpp
scons: *** [modules/voxel/cube_tables.x11.tools.64.o] Error 1
In file included from modules/voxel/edition/../math/vector3i.h:4,
                 from modules/voxel/edition/../math/rect3i.h:4,
                 from modules/voxel/edition/voxel_tool.h:4,
                 from modules/voxel/register_types.cpp:2:
modules/voxel/edition/../math/../util/utility.h:4:10: fatal error: core/pool_vector.h: No such file or directory
    4 | #include <core/pool_vector.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
Godot (master) branch:
```
git rev-parse HEAD
5bbb057cc9107d0585ab9e6b236919fa4b7023c4
```
Voxel tools (master) branch:
```
git rev-parse HEAD
9f7a081dd409e703dff6bb9318cef99cb297b5f3
```

**Comment by Zylann** [comment]
Voxel tools does not work yet on the master branch of Godot, due to the breakage that is currently going on since the Vulkan merge (amongst other core changes).

To use the module you need to build it against the 3.2 branch of Godot.

**Comment by jomiq** [comment]
Suspected that, thanks for clarifying.

**Comment by Zylann** [comment]
Reopening because it has correct title and is relevant.
At the moment there is a 4.0 branch, which is largerly untested and not up to date. I'll come back to it when Godot 4.0 will be more stable, and eventually switch my main development on it.

**Comment by Zylann** [comment]
The master branch is now compiling with Godot 4.
