### ISSUE TITLE
build issue with godot 3.2 branch

### ISSUE THREAD

**Issue by token-cjg** [Zylann/godot_voxel#128]
Godot branch: 3.2

Commit: https://github.com/godotengine/godot/commit/f4e3701893bdf6b304ee114745def2f8ac4aa822

Godot_Voxel commit: https://github.com/Zylann/godot_voxel/commit/9f7a081dd409e703dff6bb9318cef99cb297b5f3

Tried to build Godot with godot_voxel cloned and renamed to voxel in modules via command `scons platform=osx`.

Received error:

```
modules/voxel/voxel_memory_pool.cpp:83:94: error: conversion from
      'std::__1::vector<unsigned char *, std::__1::allocator<unsigned char *>
      >::size_type' (aka 'unsigned long') to 'const Variant' is ambiguous
  ...size {1}: {2} blocks").format(varray(i, *key, pool->blocks.size())));
```

Edit: Looks like there was a similar issue encountered in (and solved for) in https://github.com/godotengine/godot/pull/36436 that is merged into the master branch but hasn't been cherry-picked to 3.2 yet? So this looks like it isn't a godot_voxel bug, but a godot problem caused by a compiler problem...

**Comment by Zylann** [comment]
In the meantime you can try to cast the argument to `int`:
```cpp
static_cast<int>(pool->blocks.size())
```

**Comment by token-cjg** [comment]
Ah, great, thanks! I was just about to remark that commenting out this line https://github.com/Zylann/godot_voxel/blob/master/voxel_memory_pool.cpp#L83 works equally well, but of course retaining the debug functionality probably is important.  With that change I was able to build your project and run tinmanjuggernaut's example project.

Thanks for having a look 🙇
