### ISSUE TITLE
SimplexNoise with Non Smooth blocks does not work ?

### ISSUE THREAD

**Issue by Norrox** [Zylann/godot_voxel#131]
node VoxelTerrain - stream new VoxelStreamNoise - noise new SimplexNoise

That does not generate any terrain, but as soon as i check Smooth Meshing it starts to work.

is this a bug ?

**Comment by tinmanjuggernaut** [comment]
When channel is sdf, smooth meshing is required. When channel is type, it is not.

However, the Smooth meshing checkbox was removed. Are you using an old version? If you're using my binaries they are quite old. I'm building new ones right now.

**Comment by tinmanjuggernaut** [comment]
I've put up new binaries here, http://tokisan.com/godot-binaries/. You can try them and see if they work. I'm still in the building process, but you can get the sneak peek.

**Comment by Norrox** [comment]
thanks, i will check them out :)

**Comment by Norrox** [comment]
It works!
I see FastNoise is added, is that faster to use than OpenSimplexNoise ?

**Comment by tinmanjuggernaut** [comment]
Good. You can close this issue then. Email notifications still work, even after closing if you have other questions. 

What system are you on? I'd like to know which of my binaries have been tested. 

FastNoise perlin fractal is visually similar to open simplex noise and they are about the same speed. The benefit to FastNoise is the extreme amount of options. FastNoiseSIMD is considerably faster than either. FN and SIMD can also each do a few things the other cannot.

**Comment by tinmanjuggernaut** [comment]
Look out for my tutorial video coming in a week or so where I'll explore FN/simd for textures and voxels. TokisanGames on yt and Twitter.

**Comment by Norrox** [comment]
Great thanks :)
Yeah i will, i've watched your previous videos

**Comment by tinmanjuggernaut** [comment]
If you downloaded a windows version, please grab the latest from just now. It didn't build in FastNoiseSIMD. Linux/osx should be fine.

**Comment by Norrox** [comment]
alright, thanks!

**Comment by Norrox** [comment]
@tinmanjuggernaut im looking at the materials and voxels for the blocky voxel scene.
is it necessary to code some to get a specific voxel and material on different heights? (grass, rock, snow and so on)
there are no shortcuts for that ? :)

**Comment by tinmanjuggernaut** [comment]
Currently there is no multiple material support. You have to do it all in shaders. In my demo the shader gives two types of materials based on the normal, the direction a face is facing. You could write a simpler shader that colors based upon vertex.y, or the height of the vertex. My shader is designed for smooth voxels. If you look in the issues for multi materials you'll find other discussions including someone who was doing much nicer materials in blocky.
