### ISSUE TITLE
[Q] How to add custom terrain generator?

### ISSUE THREAD

**Issue by TheMisteryMan** [Zylann/godot_voxel#134]
I'l looking at making my own custom generator (in CPP eventually, but GDScript for basic testing), and was wondering what to do to add a GDScript, or CPP terrain generator to a VoxelTerrain node?

**Comment by tinmanjuggernaut** [comment]
Follow the example in my demo, linked in the documentation. It generates an endless sine wave field in gdscript. Or look at the C++ generators in the generator directory.

**Comment by TheMisteryMan** [comment]
Thanks, I'll take a look at those, forgot to check out your demo.
Also, I forgot to ask, but do I have to compile the engine (to compile the module) just to add my own C++ generator?

**Comment by tinmanjuggernaut** [comment]
It might be possible to create a gdnative C++ generator. I haven't tried it. Maybe @Zylann can answer affirmatively. Compiling the engine to use your own C++ generator definitely works.

**Comment by Zylann** [comment]
There are 3 ways to code a custom generator:

- Using one of the official script languages (GDScript or C#) and extending `VoxelGenerator`. The rest is pretty much the same pattern as seen in built-in generators or @tinmanjuggernaut examples.

- Using C++ NativeScript : this is the same as with an offical script language, but through the GDNative API. You may want to learn how to use NativeScript in the Godot documentation.

- Using a C++ module : similar to NativeScript, but directly in engine. You'll need to learn how to write your own module from Godot docs. This needs to recompile the engine.

Most of this isn't news, that's the common ways to extend the engine in general.
I am working on a 4th way which involves a node-based editor to create your own generator. It will be a bit more limited than actually coding it, but should allow much more things than the current built-in generators.

**Comment by TheMisteryMan** [comment]
Ah, I think I understand now, thank you.

I'll probably go the NativeScript route then, at least for testing, and then bake it in a module when it's finished (I assume I can use any language with a GDNAtive binding, such as Rust, or D, or Nim?), not sure due to you singling out C++, but with how GDNative works, any language should be fine I belive?

**Comment by Zylann** [comment]
Yeah with GDNative you could use any language, depending if you use `PluginScript` or `NativeScript`.

**Comment by TheMisteryMan** [comment]
OK, thanks for all the information, I'd be open to trying to open a PR for some docs info on this once I've gotten a handle on it.
