### ISSUE TITLE
C# API Support?

### ISSUE THREAD

**Issue by thorlucas** [Zylann/godot_voxel#135]
I was just following the tutorial when I noticed that some methods on VoxelTerrain appear to not be exposed in C#. For example: VoxelTerrain.Raycast does not exist in C#. Are there any plans to support this API in the future? It seems kind of a dealbreaker to use a fast C++ library but then only expose slow GDScript API.

**Comment by tinmanjuggernaut** [comment]
You can use the raycast built into the physics engine.

You can extend some of the classes in gdscript, C++ or other supported languages. See #134.

Otherwise, I don't know about what can or can't be accessed in C#.

**Comment by thorlucas** [comment]
It appears that the Raycast function is available — but has been moved to the VoxelTool object. Documentation should be updated to reflect this. I would do it myself but I'm not knowledgable enough about this project yet to say anything clever!
