### ISSUE TITLE
VoxelTool Raycast does not work with integer raycast origin

### ISSUE THREAD

**Issue by thorlucas** [Zylann/godot_voxel#136]
The VoxelTool Raycasting is mean to allow raycasting without needing to use colliders, as this can enhance performance in games that do not require physics.

Unfortunately it does not return the right results. Here I have set up a simple raycast from the mouse:

``` C#
using Godot;
using Godot.Collections;
using System;

public class Spatial : Godot.Spatial
{
    private VoxelTerrain ter;
    private Camera cam;
    private Vector2 mousePos;
    private Vector3? hoveredVoxel;

    public override void _Ready()
    {
        ter = GetNode<VoxelTerrain>("VoxelTerrain");
        cam = GetNode<Camera>("Camera");

        mousePos = Vector2.Zero;
        hoveredVoxel = null;
    }

    public override void _Input(InputEvent @event) {
        if (@event is InputEventMouseMotion mouseMotionEvent) {
            mousePos = mouseMotionEvent.Position;
        }

        if (@event is InputEventMouseButton mouseButton && mouseButton.IsPressed() && (ButtonList)mouseButton.ButtonIndex == ButtonList.Left) {
            GD.Print("Clicked on ", hoveredVoxel);
            ter.GetVoxelTool().SetVoxel(hoveredVoxel.Value, 0);
        }
    }

    public override void _PhysicsProcess(float delta) {
        Vector3 from = cam.ProjectRayOrigin(mousePos);
        Vector3 to = cam.ProjectRayNormal(mousePos);

        VoxelRaycastResult result = ter.GetVoxelTool().Raycast(from, to, 1000);
        if (result != null)
            hoveredVoxel = result.Position;
    }
}
```

[Lets look at the results.](https://streamable.com/hefeex) Excuse the poor visibility — I have yet to get the ambient occlusion working properly as the "simply enable vertex color/as albedo" in the docs appears to be incorrect.

As you can see, the raycast works fine for voxels on the lefthand side of the screen. However, on the right side of the screen, the raycast is off by one or two blocks to the right.

**Comment by thorlucas** [comment]
Here I have [more clearly marked the hovered block red](https://streamable.com/a8aknm) so you can see the point where it breaks. It appears to break past the exact center of the camera.

**Comment by Zylann** [comment]
Is your camera perfectly positionned at integer coordinates?

**Comment by thorlucas** [comment]
Aha! This is indeed the issue. Adding 0.1 to each camera coordinate fixed this problem. I would be happy to try to work on this bug if you are currently prioritizing other things.

Thanks for the great library by the way! Much needed for Godot!

**Comment by Zylann** [comment]
Yeah I didn't fix this yet because after spawning and moving the problem basically never happens again (unless your player dimensions and camera positions are integer).
The algorithm used is a grid-raytrace which I generalized from 2D to 3D. Later on, I improved the 2D version to handle those integer cases, which can be seen here: https://github.com/bulletphysics/bullet3/blob/3dbe5426bf7387e532c17df9a1c5e5a4972c298a/src/BulletCollision/CollisionShapes/btHeightfieldTerrainShape.cpp#L418
Maybe porting those improvements to 3D would fix the problem
