### ISSUE TITLE
Built in Ambient Occlusion does not work on macOS with prebuilt binary

### ISSUE THREAD

**Issue by thorlucas** [Zylann/godot_voxel#137]
The docs says ambient occlusion can be added easily ["by enabling the Vertex Color/Use As Albedo flag in your material."](https://github.com/Zylann/godot_voxel/blob/master/doc/04_materials.md)

So I've created an empty project and did the following:

1. Added a camera. Adjusted transform.
2. Added voxel terrain with open simplex noise generation. didn't change anything else.
3. Added a material to slot 0. I didn't change *anything* on this material, except checked the "Use As Albedo" flag.
4. Added a directional light pointing directly downwards, otherwise completely default.

This is what we get:

<img width="1136" alt="Screen Shot 2020-04-23 at 8 19 58 PM" src="https://user-images.githubusercontent.com/25698466/80171669-cfc04500-859f-11ea-806c-bc7377458103.png">

This is what the docs claims this should look like:

<img width="1136" src="https://github.com/tinmanjuggernaut/voxelgame/raw/master/screenshots/blocky-vertex-color.jpg">

Ok, so maybe they forget to say "check ambient occlusion." Checking ambient occlusion in my material yields the same exact thing. I also tried enabling triplanar in UV1 as it says to do. Nothing. 

Commit 9f7a081dd409e703dff6bb9318cef99cb297b5f3 says that AO will be disabled for non-cube blocks, but it appears it is also disabled for cube blocks too?

**Edit:**

I downloaded [tinmanjuggernaut's demos](https://github.com/tinmanjuggernaut/voxelgame) and it appears his ambient occlusion is also broken. So this is definitely something that broke in the code rather than me misunderstanding the docs. I would try to fix this myself but the rendering code goes a little over my head. Here's a screenshot of what his demo looks like now:

<img width="1136" alt="Screen Shot 2020-04-23 at 10 41 41 PM" src="https://user-images.githubusercontent.com/25698466/80178771-e6709700-85b3-11ea-9b64-d42f984eb0df.png">

It still has shadows but no AO.

**Comment by tinmanjuggernaut** [comment]
My demo, built from the latest 3.2 branch last night, latest voxel commit:

![image](https://user-images.githubusercontent.com/632766/80198266-65b4a800-8652-11ea-9da1-6188ceef7835.png)

I see you're on OSX, maybe that's the issue, though neither windows or Linux has given me a problem. What version of Godot and commit did you use to build your binaries? Did you try [mine](http://tokisan.com/godot-binaries)?

**Comment by thorlucas** [comment]
Yes I used the binary provided on your website: `v3.2.2.rc.custom_build.cd8d43714`. Perhaps being on OSX is the issue — though I struggle to see how this could be the case (I assume Godot Voxel is platform agnostic?)

I'm not getting any errors in the console running `heightmap_blocky.tscn`, only a couple warnings about unused variables.

**Comment by tinmanjuggernaut** [comment]
Godot and voxel tools should work fine on all platforms. My mono and regular binaries for Linux and windows and the new one I made last night all display AO properly through my demo. 

I'm not sure what else you can try. Maybe test using vertex color in non voxel. You can paint vertex colors in blender and import those meshes into Godot and see if you can get vertex color to work outside of voxels.

**Comment by thorlucas** [comment]
I built it from source and I got AO this time. 

<img width="1136" alt="Screen Shot 2020-04-24 at 12 38 37 PM" src="https://user-images.githubusercontent.com/25698466/80250381-91bb3380-8628-11ea-86ea-7a79fe1f7d94.png">

Perhaps your cross-platform builds aren't working properly. I would be happy to contribute my computer as a macOS build machine :) Let me know how I can help with this.

**Comment by tinmanjuggernaut** [comment]
I'm using the official build environment and scripts. It seems like such an odd thing that is unlikely to be affected by building. If it was a build problem, you'd likely have whole modules not working, or the engine not working, if it ran or built at all. It's more likely that there was a bug in the engine that was fixed between the commits. 

What did you find out about vertex painting? Can you try that on a basic mesh and compare between my build, the 3.2.1 official build, and your new one? That will help to determine if it is an engine problem, a build problem, or a voxel tools problem.

**Comment by thorlucas** [comment]
So I can't seem to get vertex painting to work at all in Godot. I export a painted cube as both COLLADA and gltf and neither of them want to work with voxel terrain. The mesh clearly has vertex coloring because I can see it in the preview of the custom mesh in the voxel tab:

<img width="239" alt="Screen Shot 2020-04-25 at 1 00 52 PM" src="https://user-images.githubusercontent.com/25698466/80289647-cdbbca80-86f4-11ea-8b8a-a7c41de421bb.png">

But even if I add a material with use vertex color as albedo turned on it doesn't work on any build — not mine, not yours, and not the official godot build.

If I create an empty spatial scene with a mesh instance using my mesh, and attach an empty material that just says use vertex color as albedo, I do get color:

<img width="358" alt="Screen Shot 2020-04-25 at 1 04 18 PM" src="https://user-images.githubusercontent.com/25698466/80289715-4753b880-86f5-11ea-9d80-23e93bd26f41.png">

But this refuses to work on voxel terrain no matter what build I use.

**Comment by tinmanjuggernaut** [comment]
The only test I was suggesting was testing vertex color in a mesh instance with the official 3.2.1 build, mine and yours to see if there was a difference between the osx builds without considering voxel tools at all. What was the result of that test? 

As far as vertex colors in the custom meshes in the voxel library, I've never used that, so don't know anything about it. It may not be implemented. Or maybe VT is overwriting the vertex color with AO, which I think it's supposed to do.

**Comment by Zylann** [comment]
Vertex colors in the voxel model meshes are not supported. They can only be coloured uniformly and textured.

**Comment by EIREXE** [comment]
Can confirm I have the same issue on linux with the prebuilt binaries.

**Comment by Zylann** [comment]
Checked in master branch, AO works fine.

**Comment by tinmanjuggernaut** [comment]
@EIREXE I see you're right. My linux binaries indeed don't show AO. The windows binaries do show it. There must have been something in the upstream 3.2 beta branch that broke vertex color. I built from the latest 3.2 just now and it works fine on Linux, and on Mac as reported by Op earlier. This is a Godot material rendering problem, not a Voxel Tools problem. 

3.2.2 will be released soon enough, so I'll release a new build after that with the latest updates of Zylann's VT and my fastnoise modules.

**Comment by Zylann** [comment]
Can this be closed? There doesnt appear to be any problem in the code (as far as the module is concerned) and my tests work fine.

**Comment by tinmanjuggernaut** [comment]
I'd say so. It looks like an upstream issue on the engine. My binaries will be rebuilt after 3.2.2.
