### ISSUE TITLE
Can't access VoxelMap of a VoxelTerrain node

### ISSUE THREAD

**Issue by rilpires** [Zylann/godot_voxel#138]
First of all, I would like to thank you for such an AMAZING module.

I would like to access the "VoxelMap" object from GDScript, but I didn't see any GDScript function like "get_voxel_map" or any property "voxel_map", is it supposed to not be accessed from GDScript? If this was just a mistake I could simply add a binding in voxel_terrain file, right?

**Comment by thorlucas** [comment]
I'm curious what you need the direct voxel map for? You can get the voxel tool from the VoxelTerrain by calling get_voxel_tool(). VoxelTool allows you to set and remove blocks, query blocks, etc.

**Comment by rilpires** [comment]
Oops, I didn't know it, that's almost what I was looking for, but it doesn't has a "has_block()" method (since "immerge_block" isn't working in my GDScript code, as I opened an issue about it [here](https://github.com/Zylann/godot_voxel/issues/139)).
Anyway I'm closing it since I don't think we are not expected to use VoxelMap anyway (why bind it to GDscript btw?)

**Comment by Zylann** [comment]
> why bind it to GDscript btw?

It is bound because you can still use it as a data structure on your own. The one used by terrain nodes is encapsulated because modifying it directly is error-prone.
