### ISSUE TITLE
Build instructions missing

### ISSUE THREAD

**Issue by goatchurchprime** [Zylann/godot_voxel#142]
This could be really stupid of me, but I can't find any build instructions for this library in the README.md file.

Also, is there possibly a way to build and run it in isolation from the command line in a crude way, which could make it easier to develop and run regression tests?  What is the preferred way to develop and debug this code?  

Just to introduce myself, I wrote loads of proprietary C++ code to make CNC toolpaths (most of it now unfortunately owned by Autodusk).  One of the components is the cutting simulation.  Here's an example video of one in operation (**not one I wrote**)  https://www.youtube.com/watch?v=u5kv40N76H8&feature=emb_title

If I get round to doing an open source version of one of these subtractive models, I feel it would get more use in a place like here, than lost in the bowels of somewhere like FreeCAD where it would be used to make very boring shapes for toolpath verification.  Gaming software is 20 years ahead of engineering software, and is what drives the hardware development, and could be used as a visual client back in any CAM system.

**Comment by tinmanjuggernaut** [comment]
This section of the Readme links directly to the instructions in the /doc folder. The first document has build instructions. 

https://github.com/Zylann/godot_voxel/blob/master/README.md#how-to-install-and-use

**Comment by Zylann** [comment]
Build instructions are pretty much the Godot build instructions themselves. If you can compile the engine, compiling the module is the same: place the module into Godo't source, invoke `scons`. A module is just a bunch of C++ files added to Godot, really. It can't really be built in isolation like a dynamic library would.

**Comment by goatchurchprime** [comment]
Well that shocked me for working, given how many headaches I've had trying to build code over the years!  

Step 4 is out of date on the Build Godot from source https://github.com/Zylann/godot_voxel/blob/master/doc/02_build-voxel-tools.md where the instructions say to look for "3.2dev.custom_build.ee5ba3e".  I found that git checkout 3.2.1-stable worked fine.

Confusingly, the repo is called godel_voxel, not voxel_tools.  Do you think it would be easier to clone a fork of godot with godel_voxel as a submodule?  (I am not a git expert, but it looks like that's what it's for.)

I might need help trying to build the windows version later.  My linux machine is quite old, and I've borrowed someone's gaming machine to experiment with VR.  I didn't know what I was missing. :(

But on the matter of developing a computational geometric library, you can't really be doing it by linking and booting up the whole of godot every time you try and debug an edge case of a marching cube.  Surely you've got some of the C-code hacked and isolated in another place so you can work on it?  Otherwise it would just be too hard to develop, wouldn't it?

**Comment by tinmanjuggernaut** [comment]
> where the instructions say to look for "3.2dev.custom_build.ee5ba3e"

The version number changes multiple times a day (using the master repo). The instructions list this filename using E. G. which means for example.

> Confusingly, the repo is called godel_voxel, not voxel_tools. Do you think it would be easier to clone a fork of godot with godel_voxel as a submodule? 

You can rename any folder you clone a git repo into. When you clone, it tells you what folder it is cloning into. The instructions say to rename the folder you get to `voxel`. 

One could presumably maintain a fork with voxel as a submodule. But that would always be out of date (relative to Godot master) and is an unnecessary amount of work for Zylann to maintain. You don't know what you're asking for. You can certainly setup the module as a submodule in your own fork, and update it on demand. Though I find managing the main repo and the other modules I use independently is not an issue.

The build process for voxel tools is the same on windows or Linux. The Godot build instructions are a little different if you're using MSVC, but Godot's documentation can get you there.
