### ISSUE TITLE
Ability to save changes without using LOD?

### ISSUE THREAD

**Issue by wacyym** [Zylann/godot_voxel#146]
Can i save terrain changes using VoxelTerrain (not VoxelTerrainLod)?
I try to do this with this settings using VoxelStreamRegionFiles:
![image](https://user-images.githubusercontent.com/6958185/82463834-5ea47c80-9ace-11ea-87ee-8ccd9c6f6c98.png)

But changes not saved after restart level.

Edit: using VoxelTerrainLOD + VoxelStreamRegionFiles works...

**Comment by Zylann** [comment]
Do you get any errors?

**Comment by menip** [comment]
Are we supposed to be able to save/load blocky terrain (`VoxelTerrain`) with, for example, `VoxelStreamRegionFiles`? 
I've tried, but it seems to not work. As shown in OPs screenshot, `VoxelTerrain` has warning saying "`VoxelTerrain` supports only stream channels 'Type' or 'SDF'."

There are no errors being printed to console. What I noticed is that when option `Save Fallback Output` is enabled, some files do get saved. When it is not, nothing gets saved. Additionally, terrain modifications don't get saved: try to add/remove voxels, restart level, then you see that only terrain from fallback stream is there, modifications are not.


I was originally thinking I have to make my own generator to have persistent terrain modifications, but would much prefer for a built in solution, such as `VoxelStreamRegionFiles`.

**Comment by Zylann** [comment]
> Are we supposed to be able to save/load blocky terrain (VoxelTerrain) with, for example, VoxelStreamRegionFiles?

Yes.

> What I noticed is that when option Save Fallback Output is enabled, some files do get saved

That option saves blocks as they are generated. When turned off, it only saves modified blocks and generates the others again in the next session.

If you run the game in verbose mode (`-v`) you should see a console log when a block is detected as being modified. They are normally saved when they get unloaded. If not then there is probably a bug in `VoxelTerrain`.

**Comment by menip** [comment]
>They are normally saved when they get unloaded. I'm not sure if they will if you use the Stop button from the editor (as it kills the game ungracefully?).

Ah, this was the important bit. I tried modifying blocks, flying out of view distance so my modified block gets unloaded, then restarting game. Modifications were loaded as expected. However, changes do not get saved by just exiting the game, gracefully or not. I expected that by default, if you exit any any way, changes would be saved (autosaving, but I guess this can just be triggered via script).

**Comment by Zylann** [comment]
> Note I'm only testing inside Godot, maybe with full on export, terrain will get saved on window close?

I doubt exporting will change it.

**Comment by menip** [comment]
Exposing `VoxelTerrain.save_all_modified_blocks(with_copy)` and having below GDScript code, saves modifications on window close, as is expected. Note when stopping via editor (not graceful exit), modifications not saved.

```
func _notification(what):
	if what == MainLoop.NOTIFICATION_WM_QUIT_REQUEST:
		$VoxelTerrain.save_all_modified_blocks(false)
		get_tree().quit() # default behavior
```

**Comment by Zylann** [comment]
My guess is that something makes the `_stream_thread` stop when the game closes, before the terrain gets destroyed. That would explain why it doesn't get to the conditional and fails to save automatically.

**Comment by menip** [comment]
@Zylann Can you specify which conditional you are talking about?

**Comment by Zylann** [comment]
This one https://github.com/Zylann/godot_voxel/blob/071c5ee5c0862eef18a1faeda1c7ba4902d8fcf4/terrain/voxel_terrain.cpp#L39

**Comment by menip** [comment]
No, it gets there. I have both lines printed from inside conditional, but upon restarting, I don't see modifications.

```
if (_stream_thread != nullptr) {
		// Schedule saving of all modified blocks,
		// without copy because we are destroying the map anyways
		PRINT_VERBOSE("About to do the save");
		save_all_modified_blocks(false);
		PRINT_VERBOSE("Save should be done");

		memdelete(_stream_thread);
	}
```

**Comment by Zylann** [comment]
Must need more debugging from there then. The problem shouldn't be far from here.

**Comment by menip** [comment]
Yea, that `Requesting...` line gets printed. From what I see, the call goes into `BlockThreadManager::push(...)` and the push function does run, as I'm getting some debugg prints from start and end of `push` function. I'll try to use a debugger, so far have been debugging with prints. Trying to get experience with C++, so hopefully can figure out whats wrong.

**Comment by Zylann** [comment]
Then the problem might be in the thread then. Perhaps it stops without having processed the remaining input.

**Comment by menip** [comment]
> Then the problem might be in the thread then. Perhaps it stops without having processed the remaining input: when long inactive, the streaming thread waits for a semaphore. When destroyed, the semaphore gets raised, and the thread exits right away without actually checking the remaining input queue, and it should be fixed there because forcing save manually from outside doesnt guarantee that (timing luck).


After more testing, it's seems that whether save happens is "random", which would indicate that the issue is indeed due to thread things. Gonna keep playing with debugger, see if I can find out whats up.

**Comment by menip** [comment]
The issue seems to be that in `VoxelBlockThreadManager` destructor, when we have a job whose semaphore value is not 0 (eg it is 1). My understanding is that we need to have semaphore value be 0, before we can act on the job, so I think we need to wait until semaphore value is 0.

**Comment by Zylann** [comment]
> thread ending before call Thread::wait_to_finish(job.thread)

That's not an issue, it's actually very good (usually) because that means no blocking occurs.

Meanwhile while reading the code I'm more confident about how to fix it, just need to find the time to do it properly.

**Comment by menip** [comment]
@wacyym eef3818 seems to have fixed the issue. Can you confirm that your issue is resolved?
