### ISSUE TITLE
custom voxel library problem

### ISSUE THREAD

**Issue by Tzian** [Zylann/godot_voxel#148]
As requested a simple repo with my problem regarding usage of a custom voxel_library.

i have left in my custom generation script, but it is set to use a VoxelGeneratorFlat atm, if using default library and setting voxel_type to 1 it renders using my material, set it to use my custom library and set to 0 (which is solid block in mine) then i get nothing rendered and player does not land on anything.

i am getting no errors so i am at a loss as to where i have gone wrong, maybe i have not correctly created the library or am setting it wrong i am not sure

Any advice you can give me as to where i went wrong, is very much appreciated

https://github.com/Tzian/SimpleTerrain

**Comment by nonchip** [comment]
`VoxelLodTerrain` only supports channel SDF (1), for channel Type (0) you need `VoxelTerrain`.

**Comment by Zylann** [comment]
Did you try setting up your scene from the editor, instead of doing it all from script?

**Comment by Tzian** [comment]
Sorry this is so long ago now, i cannot remember everything i did, i believe that dragging and dropping into the custom library was ok tho.
