### ISSUE TITLE
Implement Support for Dual Marching Cubes

### ISSUE THREAD

**Issue by zauberparacelsus** [Zylann/godot_voxel#15]
Dual Marching Cubes is an algorithm for meshing voxel data that uses an octree to optimize the mesh, resulting in a mesh that uses less geometry where less is needed.  It also (as far as I can tell) supports both smooth and blocky geometry.  This would potentially provide better rendering performance compared to transvoxel.

There are two implementations I know of which can be useful to study:

First is this one, which solves an issue with non-manifold geometry sometimes being generated: https://github.com/dominikwodniok/dualmc

The second is the VolumeComponent from Ogre3D, which is more game-oriented and additionally has a LOD mechanism: http://wiki.ogre3d.org/VolumeComponent

Document from volume-gfx.com - https://www.volume-gfx.com/volume-rendering/dual-marching-cubes/

Original paper: https://www.cs.rice.edu/~jwarren/papers/dmc.pdf

**Comment by Zylann** [comment]
I would tend to prefer a solution with LOD, but I have no dedicated time to work on this at the moment.

**Comment by zauberparacelsus** [comment]
Well, the implementation in Ogre3D's VolumeComponent does have a LOD mechanism, but yeah, can't work on stuff if you don't have the time for it :-/

**Comment by Zylann** [comment]
I started investigating this algorithm, but I have a concern about the way it uses the octree to detect surface features. Let's say you have an empty volume, and the player places a small sphere in the middle:

![image](https://user-images.githubusercontent.com/1311555/56433398-aacc2e80-62c8-11e9-80e7-632364c22e37.png)

The algorithm goes by checking the corners of the octree node, and if they differ by some policy, splits the node recursively. But in that situation I can see it won't detect anything, and no voxels will be polygonized...

**Comment by zauberparacelsus** [comment]
Maybe the paper's explanation was vague?  I think it's not checking the actual corners, but rather checking to see if there is *any* geometry within the volume of the cube, and then subdividing.

Though, that portion of the algorithm I think is for voxelizing an existing mesh.  For terrain, that probably won't be needed except maybe when the player is digging or building.  Generating the terrain from noise or existing data, you'd basically be able to just generate a chunk of terrain data as a 3D array, and build the octree in a "bottoms up" fashion.

**Comment by Zylann** [comment]
@zauberparacelsus I'm actually not using the paper much, I'm following the explanations from `volume-gfx.com`, in parallel with Ogre's implementation and so far that's what I realized from it.

**Comment by zauberparacelsus** [comment]
Yeah, I had been attempting to write a custom voxel algorithm a while back, not going off of references to anything else (so probably a lot of mistakes and way too many ifs).  I was using an octree just for storage rather than using it to generate the mesh, though when I was generating the octree I did it purely by "bottoms up" from an input 3D array.

**Comment by zauberparacelsus** [comment]
One additional thought: I don't know if the algorithm is designed to handle volumes containing multiple materials.  Like, if you have a large flat area with nothing but dirt except for one block of stone.  Would the algorithm ensure that the single bit of stone was preserved, or would it get optimized out?  If the latter, the algorithm might need to be coded to handle volumes with multiple materials.

**Comment by Zylann** [comment]
@zauberparacelsus my guess is, it will probably have two material IDs and a blend value, and the shader will use a texture array with triplanar sampling. But like heightmap rendering, and due to how Godot rendering works, having two actual materials will be quite hard without splitting the mesh.

**Comment by Zylann** [comment]
Another thing I'm not used to, is the use of Hermite data. So far my voxels only needed 8 bytes per value. Now, they need WAY more, like 64 bytes (if using 16-bit floats), for the value and the gradient's X, Y and Z, which appears to not even be a normalized vector.

**Comment by Zylann** [comment]
Ok, that doesn't look too bad for a sphere
![image](https://user-images.githubusercontent.com/1311555/56442645-7a48bc80-62e9-11e9-8b52-d19fe4177d8e.png)

**Comment by zauberparacelsus** [comment]
Oh, by material I hadn't meant in the sense of a 3D shader, but rather in a more conventional sense.  Like, dirt, clay, stone, and wood are all different materials in the perspective of the player.

**Comment by Zylann** [comment]
Got to the stage of deriving the dual grid, using very similar code to Ogre. I have a hunch something isn't right...
![image](https://user-images.githubusercontent.com/1311555/56459906-745ae600-6392-11e9-8b72-a22547b5818c.png)

**Comment by Zylann** [comment]
Might have been the debug draw, it wasn't making cubes properly
![image](https://user-images.githubusercontent.com/1311555/56460186-98b8c180-6396-11e9-9d30-dfa26198a011.png)

**Comment by Zylann** [comment]
Making good progress, finally got a mesh :) But it has holes in it, I don't understand why
![image](https://user-images.githubusercontent.com/1311555/56461852-5cdf2580-63b1-11e9-85cb-1a7accb27f8f.png)

**Comment by Zylann** [comment]
Also, turns out my fear really happens: I found a case where the sphere is larger than a voxel, but small enough to make nothing generate.

**Comment by Zylann** [comment]
I'll close this, as I don't plan to work more on the DMC implementation for now. More specific issues or PRs can still be opened later.
