### ISSUE TITLE
Raycast get transparent blocks

### ISSUE THREAD

**Issue by nic96** [Zylann/godot_voxel#153]
Currently the raycast method in the voxel tool only hits blocks that aren't transparent, but in some cases you'd want the raycast to also hit transparent blocks like leaves or glass. I have a pull request #152 where the solution is for the raycast to also hit transparent blocks that have a collision aabb.

There might be a better solution such as having a raycast option in the voxel library perhaps or have a parameter in the raycast method that allows you to specify if you want the raycast to hit transparent blocks, but I think if the block has a collision aabb the raycast should hit it.

**Comment by nonchip** [comment]
> I have a pull request
then why do you file a duplicate issue?

@Zylann since that PR was merged this can probably be closed.

**Comment by nic96** [comment]
I guess on GitHub a pull request and issue are kinda the same thing? I'm used to gitlab where when a pull request mentions that it closes a certain issue that the issue automatically gets closed when the pull request gets merged. I was thinking maybe Zylann left it open since someone might want further customization for the raycast by passing a funcref, but I guess my specific issue I fixed with that pull request so I'll close this issue for now. If someone needs further customization of raycast in the future they can open a new issue.

**Comment by Zylann** [comment]
I'm considering to add a customizable mask to voxel types. I had a completely different use case recently which would benefit from something like that, so it might just be done like that in the future.
