### ISSUE TITLE
`get_used_channels_mask` gave an error: 1 Argument: 0 Expected: nil

### ISSUE THREAD

**Issue by nonchip** [Zylann/godot_voxel#156]
I'm extending a `VoxelGenerator` in GDscript, like shown in the example in the docs:

```gdscript
extends VoxelGenerator

enum ChannelId{
	TYPE = VoxelBuffer.CHANNEL_TYPE,
	SDF = VoxelBuffer.CHANNEL_SDF
}

export(ChannelId) var channel:int = VoxelBuffer.CHANNEL_TYPE

func get_used_channels_mask () -> int:
		return 1<<channel
```

While the terrain gets generated completely fine, completely randomly (most often after adding the generator to a new terrain, as if the export didn't get correctly initialized or something, switching to SDF and back to TYPE fixes it about half the time) I do get multiple error messages on the console:
```
 voxel_stream.cpp:get_used_channels_mask gave an error: 1 Argument: 0 Expected type: Nil
```
Which according to the gdscript `Error` docs is a `FAILED = 1 --- Generic error.`, which doesn't really make sense because how can `return 1<<0` fail?

also the arguments do seem to match (`nil` in the function, `nil` in the call as far as i can see in `VoxelStream.cpp`).

**Comment by Zylann** [comment]
That looks wrong indeed. I can't see any problem with your code.
The only case where I think it could be logged is if the script wasn't compiled, like in editor. However the module currently doesn't run generation at all in the editor for safety reasons, so I don't know how it would get called there.

Also this error print is very misleading. It doesn't mean 1 argument was expected, and it doesn't mean it expected a type that mismatched. All that message contains is the value of `CallError`:

```cpp
	struct CallError {
		enum Error {
			CALL_OK,
			CALL_ERROR_INVALID_METHOD, // This is the actual error code
			CALL_ERROR_INVALID_ARGUMENT,
			CALL_ERROR_TOO_MANY_ARGUMENTS,
			CALL_ERROR_TOO_FEW_ARGUMENTS,
			CALL_ERROR_INSTANCE_IS_NULL,
		};
		Error error;
		int argument;
		Type expected;
	};
```

**Comment by Zylann** [comment]
> but it shouldn't really run as a tool should it? 

It kind of does since the terrain node asks its generator which channels it generates, in order to display a warning in case it doesn't supports some of the channels. That still matters regardless of generating in editor or not. That was @tinmanjuggernaut 's call.

> also those error messages happen when running the game (via the debug "play" button in the editor), not while editing.

I guess that's because the node configuration warning happen to get updated at this time. It probably also happens when you assign the stream property, close and reopen the scene, or just save it.

> so it doesn't even find the get_used_channels_mask method, i guess? but that would only make sense when not running the game (due to the lack of tool mode)?

Due to the lack of tool mode, the in-editor checks can't run, but the module doesn't know if your script is tool or not. Maybe a check for this can be added, but then those checks will not operate.

**Comment by nonchip** [comment]
> It kind of does since the terrain node asks its generator which channels it generates, in order to display a warning in case it doesn't supports some of the channels. That still matters regardless of generating in editor or not.

aaaah ok yeah that makes sense. so much hassle for a little yellow warning sign :P

> Maybe a check for this can be added, but then those checks will not operate.

maybe just make a check that warns "your generator isn't a `tool`" instead of just erroring out with a generic "can't find" trying to use it. i can live with it being a `tool` just fine, but if that's a requirement there should probably be a warning (just like with unsupported channels)

**Comment by Zylann** [comment]
I pushed something to improve this case 404de21c9b53b2454786d95558259f00db83131f

**Comment by Zylann** [comment]
Can this be closed?
