### ISSUE TITLE
material access to channels?

### ISSUE THREAD

**Issue by nonchip** [Zylann/godot_voxel#157]
I'd like to save on resources (and also because 8 textures would be way too few for my game) by making most materials for my cell Types the same one with e.g. texture atlases, for which i'd like to use both the Type (though this should be applicable to SDF too, just with interpolation) and "user data" channels.

skimming through your code i couldn't find anything about this, ideally it would just be checking whether a `uniform` of the same name as the channel exists (maybe prefixed, such as e.g. `VoxelType`, `VoxelData3`...) and if so set it on the vertex. is that a thing?

if so could you tell me how that works?
and if not, i guess, could you add it or would you mind if i try&PR it?

**Comment by Zylann** [comment]
> 8 textures would be way too few for my game

If you refer to the blocky voxels workflow, the intent is really to use atlasing as much as possible. 8 is actually a *material* limit (and by this I almost mean "shader"). If blocky voxels get too many different materials the module won't be able to batch them and performance will go down. So I figured 8 is a good limit. It can be increased for sure but I wouldnt recommend it.

> skimming through your code i couldn't find anything about this, ideally it would just be checking whether a uniform of the same name as the channel exists (maybe prefixed, such as e.g. VoxelType, VoxelData3...) and if so set it on the vertex. is that a thing?

Voxel channels have nothing to do with shader uniforms. Channels are just ways to store voxel data, whatever it is. 2 of them are used by the module, the others are purely user data.

There is no way to access voxels from a shader. If you really want you could create a 3D texture and copy the whole data in there just so it can be accessed on the GPU, but for texturing it's not really an efficient way to go. Volumetric data is heavy, though it could have different interesting applications which aren't about your issue.

The blocky workflow is based on materials declared in `VoxelLibrary`, I don't plan to change that for now.
The smooth workflow doesn't expose materials yet, but it's going to work a bit differently. There will be a `MATERIAL` channel in the future, for which the information will be included in the generated vertices, which then the shader can access.
One issue with this, is that Godot has a fixed amount of vertex attributes and it doesn't allow to define custom ones, so I will likely re-use one, like `UV` or `WEIGHT`.
Only then, I might add an option to the blocky mesher to include that data as well, thought it's usually not always needed depending on the game.

**Comment by nonchip** [comment]
> If you refer to the blocky voxels workflow 

i did

> the intent is really to use atlasing as much as possible

that's exactly what i'm planning to do, because using different materials for just swapping textures would be a) horribly inefficient and b) impossible with only 8 materials

> There is no way to access voxels from a shader.

and this is where i run into an issue, because how would i do atlasing if i have no way of telling the material which (sub)texture i want on my blocks.

even with your 3d texture idea the material doesn't know which voxel it's currently dealing with so i couldn't look up info in said 3d texture.

**Comment by Zylann** [comment]
> and this is where i run into an issue, because how would i do atlasing if i have no way of telling the material which (sub)texture i want on my blocks?

With the blocky workflow you just do uv-mapping in the voxel types. It's fancy batching or meshes, really. This is something you can't do with smooth voxels because there are no "predefined" items, hence why the latter uses the vertex attribute approach.
Minecraft has hundreds of different blocks with various textures and yet uses very few materials, because each block simply uses a diferent region of an atlas, and chooses among a limited amount of materials (like "transparent" or "opaque").

> even with your 3d texture idea the material doesn't seem to know which voxel it's currently dealing with so i don't think i could look up info in said 3d texture

You could know by looking at the world position of the vertex but like I said I'd not do that for texturing.

**Comment by nonchip** [comment]
> With the blocky workflow you just choose uv-mapping in the voxel types. 

ok yeah i do feel kinda silly here, yesterday i thought to myself "strange to have custom UVs per voxel type, what would one ever need that for" and now i was wondering how to tell my material where to index the atlas :'D

> because each block simply uses a diferent region of an atlas, and chooses among a limited amount of materials (like "transparent", "opaque" or "alpha cut").

yeah that was my plan to begin with, i just totally didn't make the mental connection between the UV setting and that being literally what i need for the atlas.

ok yeah thanks a lot, turns out everything i needed those "material parameters" for is already solved by that :D
