### ISSUE TITLE
issue with included headers

### ISSUE THREAD

**Issue by harraps** [Zylann/godot_voxel#16]
Hello,
I wanted to try your library so I cloned the latest Godot repo and added your repo into the `modules/` folder (and I renamed it `voxel`). However when I tried to compile it with Clang on ArchLinux, I couldn't do it straight away. I had to look into your sources and change the path of each include referencing Godot's sources.

Should I make a pull request, even though it is just a matter of changing the paths ?

**Comment by NewNodeGames** [comment]
I can't compile too, using Archlinux.

**Comment by Zylann** [comment]
@NewNodeGames I can't PR that module because it is too specific, experimental, probably has bugs, not user-friendly, and would be seen as bloat for a general-purpose engine.

**Comment by harraps** [comment]
Sorry, I was away... The only includes that didn't work were the one referencing core headers. But you figured that out already. I tried compiling with your changes again and it works now.
