### ISSUE TITLE
What are semaphores used for in VoxelBlockThreadManager?

### ISSUE THREAD

**Issue by menip** [Zylann/godot_voxel#162]
I'm not experienced with threading. While looking over code, I saw both mutexes and semaphores being used. I understand locking inputs/outputs with mutexes, but don't understand purpose of semaphores. They seem to be used to schedule threads, or signal to other threads when active one is done, but I'm not sure.

**Comment by Zylann** [comment]
The semaphore is used to suspend the thread to not fry CPU, and resume it when it's needed. I could put it to sleep but it would cause unnecessary latency.

**Comment by menip** [comment]
Ok so semaphores are indeed used for some sort of signaling. Does this also mean the semaphore value is equal to the number of jobs a thread has queued?

**Comment by Zylann** [comment]
I don't know what the value of a semaphore is, I just know it unlocks threads waiting for it when it gets raised. So it is implemented with some form of refcounting but I'm not really bothering about it.
