### ISSUE TITLE
Custom meshes do not render with attached material

### ISSUE THREAD

**Issue by Werevector** [Zylann/godot_voxel#164]
Hi
I have the problem where i want to render more advanced meshes, that still fit inside the voxel-cube
With a voxelterrain using Type (not smooth) i can create cube shaped voxels that reference the materials attached to the voxel terrain. But when i use custom shapes instead of cubes i don't want to use these materials, i want to use the material attached to the custom shape itself, but the rendering defaults to the referenced material
![image](https://user-images.githubusercontent.com/5551138/88656877-47d36500-d0d1-11ea-9b56-3e2261263dd4.png)

**Comment by Zylann** [comment]
Voxel library materials don't work that way. The material you set on the mesh itself won't be used, what determines it is the material ID. That ID matches with the list of materials set on the `VoxelTerrain` node. If the slot is not set, it won't apply it. This workflow expects you to re-use materials and rely on atlased UV-mapping.

**Comment by Werevector** [comment]
I understand, thank you for the quick reply Zylann. I understand the limitation now and will change my approach.
_Added question:_
I know some blocks in minecraft are also animated, is this possible in your mod with just making a custom mesh?

**Comment by Zylann** [comment]
I know it's possible with a particular material with a shader that animates the UVs, although I never actually put that into practice yet.
