### ISSUE TITLE
javascript build error: ambiguous conversion in voxel_graph_runtime/_editor / PRINT_VERBOSE

### ISSUE THREAD

**Issue by nonchip** [Zylann/godot_voxel#170]
* godot_voxel: 96c4a5bd0b0e6bf881419746419e51e82cbd0614
  * godot: godotengine/godot@6a9fbafcbbd7954761fb17554ed08fb62e3554dd:
* emscripten: `1.39.19`
  * tools: `node-12.18.1-64bit`
* command: `scons -j8 use_llvm=yes use_lld=yes platform=javascript target=release bits=64 tools=no`

```
[ 36%] Compiling ==> modules/voxel/terrain/voxel_data_loader.cpp
modules/voxel/generators/graph/voxel_graph_runtime.cpp:477:40: error: conversion from 'unsigned long' to 'const Variant' is ambiguous
                                                  .format(varray(_program.size() * sizeof(float), _memory.size() * sizeof(float))));
                                                                 ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~
modules/voxel/generators/graph/../../util/macros.h:10:14: note: expanded from macro 'PRINT_VERBOSE'
                print_line(msg);                            \
                           ^~~
./core/variant.h:251:2: note: candidate constructor
        Variant(bool p_bool);
        ^
./core/variant.h:252:2: note: candidate constructor
        Variant(signed int p_int); // real one
        ^
./core/variant.h:253:2: note: candidate constructor
        Variant(unsigned int p_int);
        ^
./core/variant.h:259:2: note: candidate constructor
        Variant(signed short p_short); // real one
        ^
./core/variant.h:260:2: note: candidate constructor
        Variant(unsigned short p_short);
        ^
./core/variant.h:261:2: note: candidate constructor
        Variant(signed char p_char); // real one
        ^
./core/variant.h:262:2: note: candidate constructor
        Variant(unsigned char p_char);
        ^
./core/variant.h:263:2: note: candidate constructor
        Variant(int64_t p_int); // real one
        ^
./core/variant.h:264:2: note: candidate constructor
        Variant(uint64_t p_int);
        ^
./core/variant.h:265:2: note: candidate constructor
        Variant(float p_float);
        ^
./core/variant.h:266:2: note: candidate constructor
        Variant(double p_double);
        ^

modules/voxel/editor/graph/voxel_graph_editor.cpp:404:68: error: conversion from 'size_t' (aka 'unsigned long') to 'const Variant' is ambiguous
                        _undo_redo->add_undo_method(*_graph, "set_node_param", node_id, j, param_value);
(same candidates)
```

works for x11, server, and windows builds, so seems to be something being `typedef`ed in emscripten which you don't handle.

**Comment by Zylann** [comment]
This again... I honestly don't know how Godot can deal with time and byte sizes as `unsigned long` and somehow manage to turn it into a `Variant` without failing in this way :|

**Comment by nonchip** [comment]
just for the record, [Variant.cpp](https://github.com/godotengine/godot/blob/3.2/core/variant.cpp#L2179) hides the "long ints" behind a flag, that's being set by the iOS platform config because they had a similar issue apparently, guess other `libc`s do some typedef magic there, dunno if your `SCsub` for example could just set that on javascript platforms?

**Comment by menip** [comment]
Compiling for javascript I get this error as well as 86 `-Winconsistent-missing-override` warnings, perhaps both could be addressed at the same time.

**Comment by Zylann** [comment]
The `-Winconsistent-missing-override` is because Godot doesn't use `override` throughout its codebase.

**Comment by Zylann** [comment]
So how do we fix this? How can I turn a `uint64_t` or a `size_t` (which are the same in 64 bits) into `Variant`?

**Comment by nonchip** [comment]
> which are the same in 64 bits

that's the problem, they apparently are not in emscripten.

because there's a `Variant::Variant(uint64_t p_int)`, but `Variant::Variant(unsigned long p_int)` only if you define `NEED_LONG_INT`. and since the compiler complains about `unsigned long` being missing, they do not appear to be `uint64_t`s.

**Comment by Zylann** [comment]
Is this still a problem with the current codebase? I haven't heard of a fix so I wrapped all places where a `uint64` is sent to `Variant` using a `SIZE_T_TO_VARIANT` macro.

**Comment by Zylann** [comment]
I guess this is fixed since there has been fixes done for clang. It might resurface from time to time as there is no wasm CI but if it does just open an issue or PR.
