### ISSUE TITLE
Explain run_blocky_random_tick?

### ISSUE THREAD

**Issue by menip** [Zylann/godot_voxel#171]
Recently `run_blocky_random_tick` function was added, but I'm having trouble understanding how/when to use it. Description says it can be used to implement "slow 'natural' cellular automata behavior" so I'm thinking you can do stuff like water/fire/ivy spreading, but would like clarification.

https://github.com/Zylann/godot_voxel/blob/96c4a5bd0b0e6bf881419746419e51e82cbd0614/edition/voxel_tool_terrain.cpp#L99

**Comment by Zylann** [comment]
The function almost does what it says: given an area, it runs a function on a certain amount of random voxels inside that area, if these have been marked as "random tickable" in `VoxelLibrary`. This is a mechanism found in Minecraft: https://minecraft.gamepedia.com/Tick
While it can be implemented in pure GDScript, the iteration takes a long time so moving it in C++ makes it significantly faster.

**Comment by menip** [comment]
Wow, thats some really cool stuff! Thanks for the links. I didn't understand voxel_tool before, and didn't think about getting neighboring voxels information. Very nice!
