### ISSUE TITLE
Per voxel shader uniforms

### ISSUE THREAD

**Issue by menip** [Zylann/godot_voxel#173]
I recently came across [this](https://godotengine.org/article/godot-40-gets-global-and-instance-shader-uniforms) dev blog, that says per instance shader uniforms will arrive with Godot 4.0. I'm wondering if it would be possible at that point to have per voxel shader uniforms. 
The use case I'm looking at is visualizing sparse selections: the player can select voxels, and those would then be tinted a certain color. This would be persistent, and the "Selected" view can be toggled on and off.

There are other ways to show this information, but doing it via per-voxel uniforms would be cool.

**Comment by Zylann** [comment]
> per instance shader uniforms will arrive with Godot 4.0. I'm wondering if it would be possible at that point to have per voxel shader uniforms.

Voxels are not instances, so no.

> The use case I'm looking at is visualizing sparse selections: the player can select voxels, and those would then be tinted a certain color. This would be persistent, and the "Selected" view can be toggled on and off.

You could do this with a second layer of voxels rendered on top using wireframes or transparency, or by replacing said ones with tinted ones, but it's really not straightforward to apply an arbitrary material to an arbitrary amount of existing voxels, especially when they aren't even blocky ones. When rendered, current terrain is really just a big batched mesh.
