### ISSUE TITLE
on_block_load signal

### ISSUE THREAD

**Issue by menip** [Zylann/godot_voxel#174]
I'm working on pathfinding for my project. My idea was grab a block/chunk after it was loaded and do what I want with it. However, I'm having trouble with this. At first I thought I could achieve it by having custom stream with code in emerge function to do what I want. But with my setup this has not been succesfull, and I don't think is the way to go, seeing as I'm using `VoxelStreamRegionFile` where you are reading from disk or loading from secondary stream.

Ideally once a block is loaded I get a signal fired from `VoxelTerrain` or `VoxelTool` that also includes the just loaded `VoxelBuffer`.

I could alternatively do some looping with just `VoxelTool::get_voxel(...)` but this seems less nice.

If there is a different way to do this, I'm all ears. If signals is the way to do this, I'd be down to work on a PR.

**Comment by Zylann** [comment]
I plan to do this https://github.com/Zylann/godot_voxel/issues/99

**Comment by menip** [comment]
Well look at that, I've already reacted to it! Seems like I read that issue at one point and forgot about it; probably where "my" idea came from in the first place :D
