### ISSUE TITLE
Loading project in Godot v3.2.2 stable + latest godot_voxel halves FPS

### ISSUE THREAD

**Issue by Favkis** [Zylann/godot_voxel#181]
I'm not sure it's even module issue, but maybe new version have something that might be activated by default? Starting same project with godot made with binaries from march gives me 800 FPS with VoxelTerrain with 128 draw distance. Starting this same project with newer module gives 340 FPS. 

Tried on 2 PCs. On second 120 FPS on march binaries and 60 FPS on built today with Godot 3.2.2 debug_release

It's likely my issue of course but in case I'll ask here.

**Comment by Zylann** [comment]
> built today with Godot 3.2.2 debug_release

You mean `release_debug`?

**Comment by Favkis** [comment]
Was totally my mistake both times. 
target=debug makes halve the FPS
target=release_debug made back 800 FPS

The problem was that I added debug icon to windows bar shortcut, recompiled as release_debug thinking it rewrote exe file and started again old exe. 

Yes, it was that dumb, but can confirm that starting same project with current new build works just fine, same 800 FPS, everything works great on both i7 6700k / rtx 2080 / 24 ddr 4 ram (800 fps with voxelterrain 128 blocks (marching cubes) distance), and AcePC AK1 Mini PC (~130 FPS with 128 blocks (marching cubes) render distance)

**Comment by Zylann** [comment]
Closing as solved then
