### ISSUE TITLE
Building the player, enemies and other elements with voxels

### ISSUE THREAD

**Issue by acs** [Zylann/godot_voxel#194]
I am following all the tutorials and, right now, I am reading the code to have a more detailed understanding of the project.

But I have not yet a clear answer for this question: Is it possible to create the player, enemies and other elements of the world with voxels? One of the pipelines I am thinking of is to import voxeled models from MagicaVoxel and use them in Godot. A short term goal for me is to implement something like this demo in Godot:

![penguin_voxel_collision](https://user-images.githubusercontent.com/209533/93396488-10369d00-f878-11ea-9530-8f39b2610666.gif)

In my mind, in a voxel supported engine with physics, this should be trivial. It is just physics applied to voxelized models. But I understand that in Godot right now the voxel support is the one provided for godot_voxel. And you are more focused in terrain generation. But reading the code maybe using the blockly mesher something can be done.

Any insights will be appreciated. And thanks for this great project!

**Comment by Zylann** [comment]
While this module is not going to help simulating the cubes you are showing in the gif, it is actually planned to have tools for importing colored voxels, including from MagicaVoxel.

As of today, the master branch has a colored cubes mesher and a script helper which can load `.vox` files, so you can currently get them in your game. However, in their current state, you have to handle the voxel pipeline from scripts:

```gdscript
extends Node


const _materials = [
	preload("./opaque_color_material.tres"),
	preload("./transparent_color_material.tres")
]

var _mesh_instance : MeshInstance
var _mesher = VoxelMesherCubes.new()


func _ready():
	_mesh_instance = MeshInstance.new()
	add_child(_mesh_instance)

	var voxels = VoxelBuffer.new()
	voxels.set_channel_depth(VoxelBuffer.CHANNEL_COLOR, VoxelBuffer.DEPTH_8_BIT)
	var palette = VoxelColorPalette.new()
	
	var loader = VoxelVoxLoader.new()
	var err = loader.load_from_file("res://local_tests/vox/monu1.vox", voxels, palette)
	if err != OK:
		push_error(str("Error: ", err))
		return

	_mesher.palette = palette
	_mesher.color_mode = VoxelMesherCubes.COLOR_MESHER_PALETTE
	
	# Padding of 1 voxel required for now, a bit verbose but quite simple.
	var padded_voxels = VoxelBuffer.new()
	padded_voxels.create(
		voxels.get_size().x + 2, 
		voxels.get_size().y + 2, 
		voxels.get_size().z + 2)
	padded_voxels.set_channel_depth(
		VoxelBuffer.CHANNEL_COLOR, voxels.get_channel_depth(VoxelBuffer.CHANNEL_COLOR))
	padded_voxels.copy_channel_from_area(
		voxels, Vector3(), voxels.get_size(), Vector3(1, 1, 1), VoxelBuffer.CHANNEL_COLOR)

	var mesh = _mesher.build_mesh(padded_voxels, _materials)

	_mesh_instance.mesh = mesh
```

**Comment by acs** [comment]
@Zylann thank you very much for your explanation. After thinking about it my next steps are:

* Load MagicaVoxel models over the terrain following your recommendations
* Interact with them using the FPS demos as if the models are terrain (firing them to destroy them or to make them "grow")

Once I have achieved that the next natural step will be to animate the MV models. But this will be a different issue.

There are big challenges around creating games based on Voxels. My current bet (I come from Minecraft and from the project https://github.com/Voxelers/mcthings) is playing with Godot + this module (godot_voxel). Let's see how far we can go in this voxels workflows.

**Comment by acs** [comment]
@Zylann I close this issue because I have an answer to my question. I will add other issues in the future if I need it. Also, is it the right approach to reach the godot_voxel community? Is there other channel (discord, forums, telegram ...) to interact?

**Comment by acs** [comment]
> @Zylann I close this issue because I have an answer to my question. I will add other issues in the future if I need it. Also, is it the right approach to reach the godot_voxel community? Is there other channel (discord, forums, telegram ...) to interact?

After talking with Zylann, it is ok to use the github issues as a kind of support system.
