### ISSUE TITLE
Raycast get_voxel_tool().raycast()

### ISSUE THREAD

**Issue by slakibk** [Zylann/godot_voxel#196]
Hi. Can't figure out how get_voxel_tool (). Raycast () works. In the demo "blocky_terrain" raycast () works, but in the "blocky_game" it does not work correctly. Could this be related to custom-generator?

**Comment by Zylann** [comment]
It should work in the blocky game too. The only special thing to know about it is that it is only implemented for `VoxelTerrain` and does not raycast anything else. It also doesn't use classic Godot physics, it's a specialized voxel-based raycast.
