### ISSUE TITLE
Broken link in Getting started documentation

### ISSUE THREAD

**Issue by acs** [Zylann/godot_voxel#197]
In the [Getting started doc](https://github.com/Zylann/godot_voxel/blob/master/doc/01_get-started.md) the **Region files specification** link is broken: https://github.com/Zylann/godot_voxel/blob/master/doc/specs/region_format.md

**Comment by Zylann** [comment]
Should be fixed by 04df05854a79c3a074562888e533baf641c46d0b

**Comment by acs** [comment]
Cool, thanks!
