### ISSUE TITLE
Issues with VoxelGeneratorFlat and VoxelTerrain

### ISSUE THREAD

**Issue by acs** [Zylann/godot_voxel#198]
I am playing with VoxelTerrain and I am using VoxelGeneratorFlat as a first experience. I am having some issues.

One issue is trying to define the bounds: it seems that the size defined in bounds does not use the same units than the grid. For example in this case:

![Screenshot from 2020-09-30 07-25-04](https://user-images.githubusercontent.com/209533/94734549-afc05900-0369-11eb-9399-fb370f04cbe9.png)

the x axis should go from -10 to 10 (x=-10, w=20) but according to the grid it goes from -16 to 16.

Other issue appears if I press the "Re-generate" button: the terrain is not shown anymore. 

And a third issue is that I can not play with the y-axis because it start to consume CPU and memory. The related traces are:

```
Failed method: LineEdit:select_all target ID: 30272
TOTAL BYTES: 1048560
NULL count: 0
CALL : 43687
CALL show_modal: 1
CALL grab_focus: 1
CALL select_all: 1
ERROR: push_call: Message queue out of memory. Try increasing 'memory/limits/message_queue/max_size_kb' in project settings.
   At: core/message_queue.cpp:55.

```

I am working with godot_voxel master branch and godot 3.2.3.

**Comment by acs** [comment]
I have other issue this time when rendering. I have assigned a material to the terrain (albelocolor red) and I can see it in the editor window:

![Screenshot from 2020-09-30 23-19-24](https://user-images.githubusercontent.com/209533/94740710-64ab4380-0373-11eb-9c9d-5af3c126a0a9.png)

But if I try to render the scene, the terrain is not rendered at all. You can see the sphere failing without the terrain displayed. How can I configure the terrain to make it visible during rendering?

**Comment by Zylann** [comment]
> the x axis should go from -10 to 10 (x=-10, w=20) but according to the grid it goes from -16 to 16.

Bounds are a recent feature and can be a bit misleading: internally, `VoxelTerrain` uses blocks of 16x16x16 voxels and while bounds can be defined as any voxel units, the volume will snap to multiples of block size since a block can't be cut in half.

> if I press the "Re-generate" button: the terrain is not shown anymore.

That's a completely different problem. You should post another issue so it's tracked more consistently. Obviously it's not supposed to happen, unless the stream parameters made it generate empty void.

> And a third issue is that I can not play with the y-axis because it start to consume CPU and memory

Different issue again, see https://github.com/godotengine/godot/issues/42037

> But if I try to render the scene, the terrain is not rendered at all. You can see the sphere failing without the terrain displayed.

Yet another different problem. The cause is likely due to a recent change which redefines how voxels get polygonized. You need to place a `VoxelViewer` in the scene to tell the voxel engine where you are and which area must calculate voxels. I thought I made it have some default but not in game apparently.

**Comment by acs** [comment]
> > the x axis should go from -10 to 10 (x=-10, w=20) but according to the grid it goes from -16 to 16.
> 
> Bounds are a recent feature and can be a bit misleading: internally, `VoxelTerrain` uses blocks of 16x16x16 voxels and while bounds can be defined as any voxel units, the volume will snap to multiples of block size since a block can't be cut in half.
> 

Understood! I have imaged something like that, but I want to confirm.

> > if I press the "Re-generate" button: the terrain is not shown anymore.
> 
> That's a completely different problem. You should post another issue so it's tracked more consistently. Obviously it's not supposed to happen, unless the stream parameters made it generate empty void.

Ok, I will recheck it and open a different issue with it if I reproduce it another time!


> 
> > And a third issue is that I can not play with the y-axis because it start to consume CPU and memory
> 
> Different issue again, see [godotengine/godot#42037](https://github.com/godotengine/godot/issues/42037)

Cool! I will read about this limitations in Godot engine.

> 
> > But if I try to render the scene, the terrain is not rendered at all. You can see the sphere failing without the terrain displayed.
> 
> Yet another different problem. The cause is likely due to a recent change which redefines how voxels get polygonized. You need to place a `VoxelViewer` in the scene to tell the voxel engine where you are and which area must calculate voxels. I thought I made it have some default but not in game apparently.

I have added the VoxelViewer node to the scene and it just works! Cool. Now I have my first scene testing physics with voxel working.

![VoxelPhysics](https://user-images.githubusercontent.com/209533/94746720-9f19de00-037d-11eb-9b92-75432c55d86c.gif)

Thanks @Zylann (closing the issue)
