### ISSUE TITLE
VoxelGeneratorScript

### ISSUE THREAD

**Issue by slakibk** [Zylann/godot_voxel#206]
Hi! I can't run VoxelGeneratorScript. The project closes with an error:
ERROR: VoxelServer :: BlockDataRequest :: run: FATAL: Condition "stream.is_null ()" is true.
    At: modules \ voxel \ server \ voxel_server.cpp: 552
test project - https://github.com/slakibk/voxel_test/tree/main/test_voxel
Godot - 3.2.4 beta.

**Comment by Zylann** [comment]
Your script should implement its function with `_`:
```gdscript
func _get_used_channels_mask () -> int:
func _generate_block(buffer:VoxelBuffer, origin:Vector3, lod:int) -> void:
```

Otherwise I'll need to test that when I get the time. It's weird that the stream is shown as null when you have it properly set on the node.
Did any error occur before all this? (including the editor?)

**Comment by Zylann** [comment]
I just gave it a test, and could not reproduce your error. As I suspected, the game starts with no terrain visible.
If I correct the function names, it works as expected:
![image](https://user-images.githubusercontent.com/1311555/98297717-bff0d700-1fac-11eb-8c6c-7d0b29680b07.png)

**Comment by Zylann** [comment]
Tracked it down to a bug likely introduced by Godot's 3.2 branch https://github.com/godotengine/godot/issues/43341

**Comment by slakibk** [comment]
Thanks for the helpful answer. While I will use GD 3.2.3. Although I have a problem with it, it won't compile in VS.

**Comment by Zylann** [comment]
What's not compiling?

**Comment by slakibk** [comment]
I get the vc-project (scons p=windows vsproj=yes). If build a project, an error appears - "Error	MSB3073	The command "C:\Windows\System32\chcp.com 65001 >NUL". But it doesn't bother me yet.

**Comment by Zylann** [comment]
I don't know about the vsproj command, maybe you have to ask to Godot devs. The engine should compile fine with the regular procedure `scons -p=windows target=release_debug`.

**Comment by slakibk** [comment]
scons p=windows vsproj=yes
https://docs.godotengine.org/en/stable/development/compiling/compiling_for_windows.html#development-in-visual-studio-or-other-ides
I thought that with the help of the project I could get the engine debugging. And understand how the voxel module is made.

**Comment by Zylann** [comment]
Alternatively you can use VSCode https://docs.godotengine.org/en/stable/development/cpp/configuring_an_ide/visual_studio_code.html

**Comment by slakibk** [comment]
Thank you!
