### ISSUE TITLE
Compilation without tool fails

### ISSUE THREAD

**Issue by NoFr1ends** [Zylann/godot_voxel#218]
Currently compiling godot with godot_voxel without tools fails to compile.

https://github.com/Zylann/godot_voxel/blob/master/editor/terrain/voxel_terrain_editor_plugin.cpp#L75
https://github.com/Zylann/godot_voxel/blob/master/editor/terrain/voxel_terrain_editor_plugin.cpp#L87
https://github.com/Zylann/godot_voxel/blob/master/editor/terrain/voxel_terrain_editor_plugin.cpp#L98

Surrounding these with ``#ifdef TOOLS_ENABLED`` fixes the issue.
I can create a PR for this, but I think that the terrain editor plugin shouldn't be compiled at all when tools are disabled.

Also it would be helpful to add a github action to build without tools to find these issues faster.

**Comment by slapin** [comment]
I'd expect some editing tools to work from code though.

**Comment by Zylann** [comment]
@slapin what's under `editor` uses APIs from Godot that are not available in exports anyways (EditorPlugins, bottom panel UIs etc). You will still be able to edit terrain in the exported game.

**Comment by NoFr1ends** [comment]
@Zylann I can work on the PR for that if you want help

**Comment by Zylann** [comment]
Should be fixed with e73cdaa7071d424e0ef0a1da458cc00a708b8d29

**Comment by NoFr1ends** [comment]
It's fixed for me, thanks.
