### ISSUE TITLE
Editor crashes when trying to make VoxelLodTerrain invisible

### ISSUE THREAD

**Issue by killerjustin** [Zylann/godot_voxel#221]
using one of the latest commits: [860c0a2](https://github.com/Zylann/godot_voxel/commit/860c0a2f1d94d397732fd70ee172622b4cbfef24)

Steps to Reproduce:
-Create A VoxelLodTerrain Node
-Click the little Eye Icon to set visible = false

Doesn't seem to happen with the VoxelTerrain Node

**Comment by Zylann** [comment]
Should be fixed by edfc96e4a5507997c4a90c4e27eb3734349eaadc
