### ISSUE TITLE
Voxel instancer

### ISSUE THREAD

**Issue by Zylann** [Zylann/godot_voxel#223]
Here is another exciting feature I'm working on currently: an instancing system.

What it does
---------------

Instead of trying to modify meshes, this system allows to spawn stuff on top of it, and this allows to use multimeshes (aka hardware instancing), maybe even scenes and static bodies. It's still WIP, but here is an example of what it can do:

![instancer8](https://user-images.githubusercontent.com/1311555/103369982-7eb80780-4ac3-11eb-8226-b8f0b9247b16.png)

It is currently worked on in the `instancing` branch, not ready yet. At the moment it only has a script API, it can't be used in editor. It also only works on smooth terrain and `VoxelLodTerrain`.

How it works
----------------

`VoxelInstancer` is a new node you can add as child of a `VoxelLodTerrain`.
When a ground mesh comes into view, the output of the mesher is turned into a mesh. This is the only time vertex data is available (the module does not store it otherwise). If the terrain has an instancer, it passes that data to it, then the instancer iterates over that data to decide where to spawn things. This produces an array of transforms, which can be used to populate `MultiMeshes`.
When the ground mesh is unloaded, the associated multimesh is destroyed.

This process can happen at multiple LODs, and is tied to the LOD system of `VoxelLodTerrain`. Each LOD uses a sparse grid of different size containing specific kinds of instances, allowing for efficient frustum culling, while keeping a low amount of drawcalls thanks to `MultiMesh`.
Small LOD indexes are seen from closer and are best for tiny objects such as pebbles and grass, while high LOD indexes can be seen from very far away and are best used with large models like trees or boulders. Note, contrary to ground meshes (which subdivide if you get close), instances spawned for a high LOD index can still be seen if you get close.

A `VoxelInstancer` can contain multiple layers. Each layer defines which mesh will be used, the logic of where to spawn it, and which LOD it will use.
Among the spawn logic, you can configure:
- Density
- Alignment to ground or towards global up vector
- Min and max random scale
- Random flip (nice for pebbles so you can have two faces faking variety)
- LOD: not done yet, Godot MultiMeshes don't have that built-in, and apparently Godot 4 still doesnt. But I would expect octahedral impostors to be usable for the farthest distance.
- Sphere mode, to alter the up vector based on terrain origin (useful for planets)
- Offset along normal, to workaround floating instances when they are generated from low-resolution meshes
- And more probably to come, like interactions with `VoxelGenerator` or scripts to refine the spawing logic.

Interactions
--------------

This is not just a cosmetic feature. You can use this for grass and pebbles without collision, but one goal would be for these instances to be interactive. They could have a collider assigned, and when you dig under one, it would disappear, or drop off as a rigidbody.

Currently, digging under an instance makes it disappear. The algorithm to detect instances is quite naive, but performance is ok for small player-sized edits.I haven't tested with higher sizes, but I suspect it will be slow.

One problem for which I havent decided a solution for, is what happens when you destroy an instance, and then restart the game. Currently, the instance will come back, maybe snapped lower in the hole you made. This is because so far, the engine does not remember precisely which voxels you edited. So the instancer keeps seeing the surface as brand new.
One way is to store a flag per voxel, and when the instancer tries to spawn something that intersects that voxel, it would skip it. However this means we have to cascade that information down every LOD: remember, instances can already start to appear when you are still kilometers away from the edited place:

![instancer7](https://user-images.githubusercontent.com/1311555/103371284-f8052980-4ac6-11eb-8864-1d4446e11825.png)

Notes about Godot
----------------------

The technique used here is not new. It's actually a simplified approach to Hierarchical Instanced Static Meshes, which exists in UE4 (they use a KDTree instead), and is commonly used for landscaping with thousands of trees, bushes, rocks and foliage.
Sometimes I even think that in addition to `MultiMeshInstance`, Godot could also have a `InstancedMeshInstance` node, but unlike `MeshInstance`, would use hardware instancing internally. So if you use a lot of the same mesh in your game, you would be able to render a lot more of them, while having less draw calls and less time spent in culling (which, btw, could be done on GPU!).
There is a proposal going towards this: https://github.com/godotengine/godot-proposals/issues/2049

Godot 4 is said to improve this, however I havent tested anything there yet, so we'll see when the switch happens.

**Comment by slapin** [comment]
I think for now it would be feasible to use small multilayer MultiMeshInstance with possibility to use MeshInstance when possible (the best on VisualServer side only without producing actual nodes, which should improve performance. Currently using similar approach I produce 50M polygons easily with very primitive geometry so my idea was that some culling is required for instanced geometry produced by MultiMeshInstances. Probably some cached manual batching is needed to produce geometry which is in balande of draw calls and polycount. Or some other cheating techniques.

**Comment by Zylann** [comment]
Here is a progress update on this feature:

I haven't advanced much since the first post, as I've been sidetracked on adding [FastNoiseLite](https://voxel-tools.readthedocs.io/en/latest/api/FastNoiseLite/), optimizing [VoxelGeneratorGraph](https://voxel-tools.readthedocs.io/en/latest/api/VoxelGeneratorGraph/) and making generators use more than one thread (also causing [VoxelStream](https://voxel-tools.readthedocs.io/en/latest/api/VoxelStream/) and [VoxelGenerator](https://voxel-tools.readthedocs.io/en/latest/api/VoxelGenerator/) to finally split in two distinct APIs). I went on this because the test project I was using to test instancing is quite heavy on generation, and I needed it to run faster.

But now I'm back to instancing, with the pending question of persistence... and it looks like I'll have to add another feature before I can truly finish its first usable version. Below are the details.


Persistence design
---------------------

I figured out a design for being able to save modified instances: rocks you destroy, grass that was added or removed etc. will be remembered. So if you close and reopen the scene, or go far away until terrain unloads, and come back, you will not only see terrain you sculpted, but instances will also be the way you left them (so far they re-generated on top regardless).

Instances work using blocks, just like voxels. Each instancing block matches voxel blocks at the moment. In particular, they match the size of terrain meshes, and cannot appear in places where no mesh is generated.

If a block needs to appear and does have pre-existing instance data (coming from the stream), this data will be used directly to render the instances.
If the block does not have instance data, instances will be generated based on the mesh about to be displayed. If the terrain has a stream configured to save generated content, the generated instance data will also be scheduled for saving right away. [This is off by default](https://voxel-tools.readthedocs.io/en/latest/api/VoxelStream/#i_save_generator_output).
It will be possible to move this stage to the meshing thread, but for now it seems to run fast enough on the main thread.

When the user (player or level designer) modifies instances (places them or removes them), the instancing block they belong to will be marked as "modified". Voxel blocks won't be marked as modified, unless the user also modifies the ground, of course.
When an edited instancing block is unloaded and a stream is available, instance data will be extracted and scheduled for saving.
If no stream is setup, instances will not be remembered.


VoxelStream changes
--------------------

To be able to support this, I thought the [VoxelStream](https://voxel-tools.readthedocs.io/en/latest/api/VoxelStream/) API needs to change so that it can save and load instances data. Remember, this class is now related to persistence, not so much voxel generation, so it will influence design choices here.

However, there are a few problems to solve with it:

- Modifying `emerge_blocks` and `immerge_blocks` is a breaking change. It is already planned to change (at least be renamed) once I switch to Godot 4, but I'd like to do this in one go rather than doing it sooner and then again later.
- Making the existing functions handle instances in addition to voxels makes the API complicated. The two are distinct. One can be saved and not the other depending on what actually changed in a given block. Yet the two belong to the same volume so it makes sense to handle them on the same class.
- Changing `VoxelStream` in the `instancing` branch will not be enough, because I need to test it. So far the available stream types cannot store instance data yet, and I would actually like to introduce a new type based on SQLite, which would cover this using dedicated columns.

So I decided that the `instancing` branch would still wait for a bit. Instead, I'm going to add support for SQLite VoxelStreams: these will allow saving and loading volumes into a single file, and should be more reliable that previous formats. It is also much easier to introduce new data, since I can just add new columns and tables.

Once SQLite works, I will merge it to `master`, and then into `instancing`, so I can implement instances saving on top of it.
I won't modify `emerge_blocks` and `immerge_blocks`. Instead, I will add 2 extra functions specialized for the loading and saving of instances, something like `load_instances` and `save_instances`. The two sets of functions might or might not be called together, depending on the context (if the terrain has instances setup or not, and if instances were modified or not).

**Comment by 16millionoctopodes** [comment]
For VoxelLodTerrain - VoxelNode, whenever I set the Stream property (for example, a New VoxelStreamRegionFiles), I'm getting incredibly slow editor performance to the point of unusability. Deactivating "Run Stream In Editor" doesn't help. I assume this is due to the changes being made here to VoxelStream, and will clear up once they're completed?

**Comment by Zylann** [comment]
Please open another issue for this, it's not related to instancing.

I found a design issue with this recently, and the reason is, when you set a stream, it will override LOD count back to `1`, which means the whole terrain will start requesting voxels at super-high resolution over a massive range. This problem can be worked around by commenting out these lines: https://github.com/Zylann/godot_voxel/blob/0b4363135a29460c4df588b1bdf8e365a244898e/terrain/voxel_lod_terrain.cpp#L265-L266
In some cases it makes sense to override node settings if the assigned stream has specific constraints, but in other cases settings must come from the node instead. I need to work out a proper design.

**Comment by Zylann** [comment]
I just pushed the feature to master. I think it still has tons of improvements to make, however it has a lot of features already so I'm settling on this version for now. This should be the last feature I add before I create the `godot3.2.4` branch.

After that, master will still be using Godot 3.2.x for a little while, but it's possible that the switch to Godot 4 happens in `master` before a next version of this module.

**Comment by Zylann** [comment]
Closing since it is an implemented feature, improvements will come over time.
