### ISSUE TITLE
Custom chunk loading, and custom generation?

### ISSUE THREAD

**Issue by Hellknight44** [Zylann/godot_voxel#226]
Hello, Is there a way to implement custom chunk loading (to use my sorter algorithm)? I have searched the documentation but cant find it. I also need to create custom procedural generation by applying multiple noises to the terrain (2D noise, then 3D noise removing voxels). If I am over complicating this please tell me, and thank you for your time.

**Comment by Zylann** [comment]
> custom chunk loading (to use my sorter algorithm)

What do you mean by this?

You can customize how chunks are loaded and saved (usually with files) by implementing your own `VoxelStream` (via `VoxelStreamScript`).

You can create custom generators that run on multiple threads by deriving from `VoxelGeneratorScript`. In there you are given a block of 16x16x16 voxels and you are free to choose what these voxels should be in the requested area, using all noises you want.

Both are called automatically by the terrain system and already sorted by distance to the `VoxelViewer`.

**Comment by Hellknight44** [comment]
> What do you mean by this?
>>
I made a sorter to sort an array made with range(start, end): converts [0 1 2 3 4 5 6 7 8 8 9] to [5 4 6 3 7 2 1 8 0 9] so it loads middle chunks first, then the sides.

> You can create custom generators
>>
Also, is there tutorials or example code on creating a custom generator?

**Comment by Zylann** [comment]
> I made a sorter to sort an array made with range(start, end): converts [0 1 2 3 4 5 6 7 8 8 9] to [5 4 6 3 7 2 1 8 0 9] so it loads middle chunks first, then the sides.

The request system does this already, thread tasks are picked by priority https://github.com/Zylann/godot_voxel/blob/137059f514c25fa0559df494d8ca8ab4a4988cfd/server/voxel_thread_pool.cpp#L138
And for most tasks, priority directly depends on distance to closest viewer: https://github.com/Zylann/godot_voxel/blob/137059f514c25fa0559df494d8ca8ab4a4988cfd/server/voxel_server.cpp#L112

**Comment by Hellknight44** [comment]
I finally got the base code working. Thanks for your help
