### ISSUE TITLE
Instancing of larger structures?

### ISSUE THREAD

**Issue by slapin** [Zylann/godot_voxel#236]
It would be nice to add possibility of instancing larger scene-based structures on the surface automatically.
The structure I use currently is  special generator (based on graph one) which can take parameters with areas, where the surface should be nicer for city to be (smooth parabola surface like cup like or hill/breast-like with monotonic structure), and I have pre-set 2D coordinates for buildings (and roads) to be placed. Currently I do that via raycasts but that is too unreliable having good instancing system. Also it would be nice so that smaller objects would avoid areas for larger ones (should be easy to do with AABBs or spheres).

**Comment by Zylann** [comment]
I thought of adding a type of `VoxelInstanceLibraryItem` which just instances scenes instead of using the internal system. It would be less efficient than spawning foliage and rocks, but it would be fine for larger stuff that spawns in much lower quantities.
Still, I'm not exactly sure if that's the way to go if you want cities.

**Comment by slapin** [comment]
Well, for me I just need coordinates (buildings are generated at run time) so I think 2 modes of operation are needed:
PackedScene instancing for loading data on demand and for run time stuff Spatial-based node could be used and supplied with coordinates. BUT I still need the following magic trick - I have pre-generated coordinates which I would like to fix up using terrain setting up height for them, so it would be nice to get some way to find point closest to sample and instance there...
Some other way is to somehow get all the coordinates beforehand then generate city using them for placement. I'm fine either way, I just need to keep certain structure of concentric circles which is my "artistic vision" of how these towns should look...
Anyway, having points spread equally is quite enough to map coordinates into required structure, should have no problem with that. So basically knowing coordinates for current block I can know the x-z portion of coordinates of spawned large objects which I can spawn in some nice way (and de-spawn as blocks getting destroyed.

Another problem is how to avoid instancing stuff in areas belonging to larger areas, which might require BVH building (or just merged AABBs) to avoid stuff being istanced inside other stuff. But I'm much more in favor of Poisson disc sampling (which is unpopular in game development though which is sad, as it is fast and grid-based).

**Comment by Zylann** [comment]
Looks like this is implemented now (scenes can be spawned with VoxelInstancer). I'll close it for now because you opened more issues about the same topics anyways.
