### ISSUE TITLE
Question about documentation.

### ISSUE THREAD

**Issue by atrdev** [Zylann/godot_voxel#239]
I use [godot_voxel](https://github.com/Zylann/godot_voxel/actions) godot build 'godot.windows.opt.tools.64.exe', and try custom generator with that tutorial [scripting](https://voxel-tools.readthedocs.io/en/latest/scripting/), i dont know what's happen with the code but dont work, the code dont take my custom generator. Maybe that documentation reffer another version, but dont find any where that information.

![image](https://user-images.githubusercontent.com/20692783/110268710-ecd7e980-7fa0-11eb-9648-764d12102a66.png)
![image](https://user-images.githubusercontent.com/20692783/110268742-f9f4d880-7fa0-11eb-89fb-f53891b8a8de.png)
![image](https://user-images.githubusercontent.com/20692783/110268760-01b47d00-7fa1-11eb-88cc-fbd0ab007ba5.png)

**Comment by Zylann** [comment]
I can't believe Godot is still not erroring about these kinds of errofs xD
You are assigning `stream` with a generator. You should assign `generator` instead.

**Comment by atrdev** [comment]
Yeas @Zylann, on documentation still assign stream. 
![image](https://user-images.githubusercontent.com/20692783/110321267-34399680-7ff0-11eb-9aa6-6a378daecc2a.png)

but testing with generator instead, nothing showing.
![image](https://user-images.githubusercontent.com/20692783/110322649-36045980-7ff2-11eb-80df-198293e1af75.png)
![image](https://user-images.githubusercontent.com/20692783/110322885-8f6c8880-7ff2-11eb-8fcf-1ee54ea94ff0.png)

note: @Zylann this plugin is awsome man, greath job!!

**Comment by Zylann** [comment]
> but testing with generator instead, nothing showing.

Nothing showing where? In the game? Or in the editor?
By default the editor won't show anything because of the warning here: https://voxel-tools.readthedocs.io/en/latest/editor/#preview-options

If you manually checked `run stream in editor`, you can try forcing a regen using "Terrain" -> "Re-generate".
Also, if you want to see it running in the editor, your generator should have the `tool` keyword on top.

**Comment by atrdev** [comment]
> Nothing showing where? In the game? Or in the editor?
I try both, on the editor and runing the game.
 
> If you want to see it running in the editor, your scripts should have the tool keyword on top, however I don't recommend it.
I try with tool on the top too, but nothing showing, and i just want see the custom example you maid ond documentation. 

> If you manually checked run stream in editor, you can try forcing a regen using "Terrain" -> "Re-generate". But again, be very careful with multithreaded tool scripts in the editor, from my experience it's not safe, even when you think you're not changing the script while it runs (example: godotengine/godot#46528 (which is not fixed in 3.x)).
Yes, i try this too, but that works fine with another generators you maid(example: VoxelGeneratorNoise). I dont know if i do same wrong, or is a version problem.

**Comment by Zylann** [comment]
Ok there are a few more things missing from the doc, this part is a bit old:

- Put a `_` in front of your methods. It should be `_get_used_channels_mask` and `_generate_block`
- Add a `VoxelViewer` as child of your camera. This node is now used for the voxel engine to know where to load voxels first.

**Comment by atrdev** [comment]
@Zylann now it's works, the method's was wrong!! Thank's for the help and the quickly answer! And again greath plugin man!

**Comment by Zylann** [comment]
Fixed in 5f67d7ac579ba03ee3657da3d15caeb68e8f1bda
