### ISSUE TITLE
[Question] Marching cubes? 

### ISSUE THREAD

**Issue by muevoid** [Zylann/godot_voxel#254]
Hello! Firstly, thanks for the amazing work on this module it is amazing to use! I do have a question about the blocky terrain. Would there be any way to do marching cubes as is? That would allow you to texture individual blocks then have them be smoothed in a "blocky" fashion? Im not sure if this is the best wording. If this isn't fit for the current blocky renderer how hard would it be to implement this around the current code base?

**Comment by zauberparacelsus** [comment]
> That would allow you to texture individual blocks then have them be smoothed in a "blocky" fashion?

That sounds more like Naive Surface Nets, which are basically just cubic voxels that have been smoothed.

**Comment by muevoid** [comment]
> > That would allow you to texture individual blocks then have them be smoothed in a "blocky" fashion?
> 
> That sounds more like Naive Surface Nets, which are basically just cubic voxels that have been smoothed.

Interesting would that allow for something like this with textures?(this is marching cubes i found done in unity):

![maxresdefault](https://user-images.githubusercontent.com/38061852/114631280-e44e8f00-9c81-11eb-8ac7-98f7a5504e6d.jpg)

**Comment by Zylann** [comment]
The module supports Transvoxel by changing the mesher to `VoxelMesherTransvoxel`, which is an extension of marching cubes. It generates smoothly shaded surfaces which can be made hard-edged by [adding a shader](https://voxel-tools.readthedocs.io/en/latest/smooth_terrain/#low-poly-hard-edged-look).

> That would allow you to texture individual blocks

I don't see how that's related. Texturing marching cubes or smooth terrain is harder than the mesh batching done by `VoxelMesherBlocky`. So far the plan is to allow texturing from a mix of voxel information and shader procedural techniques.

See also https://github.com/Zylann/godot_voxel/issues/104 and https://github.com/Zylann/godot_voxel/issues/93

**Comment by muevoid** [comment]
Ok one last question then this issue can be closed. Would it be possible with the smooth terrain generator to have certain voxels not be blocky. For example so one could hace the world be smooth but placed structures are blocks. Thank you for the response by the way!

**Comment by Zylann** [comment]
This is not possible to do that. A different technique like dual contouring might allow for some sharp features but it's quite more complex and won't allow the same things mesh batching can do. So to build blocky things on top of smooth voxels it's easier to just have a second volume.

**Comment by muevoid** [comment]
> This is not possible to do that. A different technique like dual contouring might allow for some sharp features but it's quite more complex and won't allow the same things mesh batching can do. So to build blocky things on top of smooth voxels it's easier to just have a second volume.

I see, so you are saying in theory my world should be two voxel volumes a blocky and smooth one? I didn't think of that to be honest well thank you for the help!
