### ISSUE TITLE
support for multiple collision layers?

### ISSUE THREAD

**Issue by TuxTheAstronaut** [Zylann/godot_voxel#255]
so ive noticed that all the voxels terrain are on layer 1 and i don't see anyway of changing that. is there a way of changing that and if not will this ever be added as a feature

**Comment by Zylann** [comment]
It should be possible to change the collision layer, it needs to be implemented and exposed. 
However I'm not sure what you mean by "multiple".

**Comment by TuxTheAstronaut** [comment]
By multiple I mean being able to collide with more than one collision layer 

example have the voxel terrain collide with body’s on layer 1 and layer 2

**Comment by Zylann** [comment]
I added collision layer and mask properties in fa485230733605a552051aa1b2096489639d402a
