### ISSUE TITLE
Visual bug

### ISSUE THREAD

**Issue by slakibk** [Zylann/godot_voxel#256]
Hey!
Some voxels are not drawn. But they are there and you can interact with them.
What could be the reason for this bug?
[https://youtu.be/z_huexycJd0](url)

**Comment by Zylann** [comment]
Strange, I've never seen that happen in my own demos. Is it from master branch? Do you have a test project I can use to reproduce this?

**Comment by slakibk** [comment]
In VoxelServer :: BlockGenerateRequest :: run, I store voxels that go outside the block into a buffer.
In VoxelTerrain :: _ process () from the buffer I am setting to blocks.
And some of these voxels are not rendered.
Additional voxels installation code:

void VoxelTerrain::_process() {
	VOXEL_PROFILE_SCOPE();

	// print_line(String("D:{0} M:{1}")
	// 				   .format(varray(_reception_buffers.data_output.size(), _reception_buffers.mesh_output.size())));

	ProfilingClock profiling_clock;

	_stats.dropped_block_loads = 0;
	_stats.dropped_block_meshs = 0;


	//TETRA update buffer4
	if (_ext_data.update) {
		_ext_data.update = false;

		int size4 = _ext_data.buffer4.size();

		for (Map<Vector3i, VoxelBuffer::ExtPosVoxel>::Element *E = _ext_data.buffer4.front(); E != nullptr; E = E->next()) {
			VoxelBlock *block = _map.get_block(E->key());
			if (block != NULL) {

				for (Map<Vector3i, int>::Element *E2 = E->value()._voxel_data.front(); E2 != nullptr; E2 = E2->next()) {
					Vector3i p_v = E2->key();
					int d_v = E2->value();
					_map.set_voxel(d_v, p_v);
				}
				_ext_data.buffer4.erase(E->key());
			}
		}		
	}

....

Maybe something else needs to be done?

**Comment by Zylann** [comment]
> In VoxelServer :: BlockGenerateRequest :: run, I store voxels that go outside the block into a buffer.
In VoxelTerrain :: _ process () from the buffer I am setting to blocks.

Oooh so you are not using the API at all? If you hardcode stuff into the pipeline it's harder to understand what's wrong in this case, these places are not supposed to be modified unless you really know what you are doing. This is also a multithreaded pipeline so if not written correctly then things can easily go wrong.

I don't understand what you did here tbh. Usually you should only need to implement your own `VoxelGenerator` without modifying anything in the module.

**Comment by slakibk** [comment]
This code is for storing voxels that go beyond the boundaries of the block. For example when generating flea trees.
