### ISSUE TITLE
multiple voxel viwer nodes for LOD terrain?

### ISSUE THREAD

**Issue by TuxTheAstronaut** [Zylann/godot_voxel#257]
im trying to create a server that will handle most collision events but with the LOD terrain only working with one voxel viewer this breaks all of the servers collision checks since it things the player is flying. 

so will there be a way to have multiple voxel viewers in the LOD terrain in the future or is this already possible

**Comment by Zylann** [comment]
This is a planned feature, I just didnt get around to implement it yet.
