### ISSUE TITLE
Areas nodes overlapping with voxel terrian drops FPS

### ISSUE THREAD

**Issue by TuxTheAstronaut** [Zylann/godot_voxel#258]
so i have a ai enemy with an area for detecting players but when it overlaps with the terrain the FPS drops to 2-6. whats even weirder is it only drops once the player enters the area that already overlapping with the terrain but remove the terrain and the fps gose back to normal

my guess it that some sort of collision trigger that is becoming overloaded when the area overlaps the terrain

**Comment by Zylann** [comment]
I have no idea how that's related to the module 🤔 looks like the physics engine is having a hard time with mesh colliders? Is it Godot or Bullet? I have a game with a ship rigidbody which can land and then spawn a kinematic player capsule, none of which cause such a huge slowdown. I never tried areas though, but it sounds like they are handling this very badly.

**Comment by TuxTheAstronaut** [comment]
I’m using bullet an have the LOD terrain my guess is the moving area node and LOD changing from the player is overloading something in the physics engine

**Comment by Zylann** [comment]
Maybe a possibility is that you have enabled collision for all LODs, which means any location on the surface actually has multiple mesh colliders present (one per LOD), but only one is enabled, the others have their shape disabled so they are not supposed to have any effect on detection. You can decide from which LOD static colliders get created but I'm afraid the module can't do much against this, the Bullet integration might have an issue.
