### ISSUE TITLE
VoxelToolTerrain::paste not working

### ISSUE THREAD

**Issue by KarloNet** [Zylann/godot_voxel#261]
If you try to paste buffer that size is bigger then terrain chunk everything get messed up.
Sometimes nothing even show up. Effects are different if you change paste position.

a) In my opinion internally it copies wrong part of source to wrong part of destination if source break chunk boundaries.
b) void VoxelToolTerrain::paste(Vector3i pos, Ref p_voxels, uint8_t channels_mask, uint64_t mask_value)
Why its trying to use channels_mask with bit operations if channels are declared in VoxelBuffer as 0,1,2,3... 
(it should be then 2,4,8,16... ?)

How to reproduce?
Clean project add VoxelTerrain, VoxelViewer, VoxelGeneratorFlat, VoxelMesherBlock

var voxBuf = VoxelBuffer.new()
voxBuf.create(32,16,32)
voxBuf.fill(1,0)
#_terrain is a VoxelTerrain
var _terrain_tool = _terrain.get_voxel_tool()
_terrain_tool.paste(Vector3(10, 10, 10), voxBuf, 0, 0xFFFFFFFFFFFF)

**Comment by Zylann** [comment]
> Why its trying to use channels_mask with bit operations if channels are declared in VoxelBuffer as 0,1,2,3...
(it should be then 2,4,8,16... ?)

That's to be able to choose which channels will be pasted, although I'm not sure yet if that API should remain like this.

**Comment by KarloNet** [comment]
> Note: your repro steps are inverting the last two arguments, channel mask comes first.

Nop not realy;)
_terrain_tool.paste(Vector3(10, 10, 10), voxBuf, 0, 0xFFFFFFFFFFFF)

Last argument is voxel mask ( blend mode), if its lower then 0xFFFFFFFF, internally it will make slower blend mode on affected chunks. It's check again uint64_t max value so i was thinking thats need to be more then 4xFF but as long as its 0xFFFFFFFF (8xF) its use faster block mem copy.
And zero is for VoxelBuffer.CHANNEL_TYPE == 0. in that particular case there is no need to make any bit shifting on argument.

**Comment by Zylann** [comment]
Hmmm ok, but the channel mask is a mask, so zero means you dont copy any channel (at least now that's what it means), there is bit shifting to do because bit 0 has to be set.
Sending `0xFFFFFFFFFFFF` as the last parameter means to disable blending. So yeah, technically it is faster but then any blank space in the buffer you paste will replace the target area with blank space too.

**Comment by KarloNet** [comment]
As always last arg depends on needs and as for channel mask in this particular case it will inside paste function change to correct bit mask:
void VoxelToolTerrain::paste(Vector3i pos, Ref<VoxelBuffer> p_voxels, uint8_t channels_mask, uint64_t mask_value) {
....
	if (channels_mask == 0) {
		channels_mask = (1 << _channel);
	}
....

**Comment by Zylann** [comment]
Oh, I missed that part... yeah, I guess it's ok then.

**Comment by Zylann** [comment]
I did some fixes in d53e7dd5309e226d0b474c2fc83b523a792cb969, I think it works now

**Comment by KarloNet** [comment]
I'm sorry but you will need to add little fix to it.
Its working if you dont try to mask anything in source buffer but if you try... no no no no good.

Bug are in:
**voxel_buffer.h:**
inline void read_write_action(Rect3i box, unsigned int channel_index, F action_func) 

or in:

**voxel_data_map.cpp:**
void VoxelDataMap::paste(Vector3i min_pos, VoxelBuffer &src_buffer, unsigned int channels_mask, uint64_t mask_value,
		bool create_new_blocks) {
.....
dst_buffer.read_write_action(Rect3i(min_pos - dst_block_origin, src_buffer.get_size()), channel,
								[&src_buffer, mask_value, src_offset, channel](const Vector3i pos, uint64_t dst_v) {
									const uint64_t src_v = src_buffer.get_voxel(**pos + src_offset, channel**);
									if (src_v == mask_value) {
....

or in both places. Can't check it for now :(

**Comment by Zylann** [comment]
One more fix c19b60647c5bd6c813dc4a16544225783848f71b, is it working now?

**Comment by KarloNet** [comment]
Works like a charm!
