### ISSUE TITLE
Compiled Mono version does not run in Windows 7

### ISSUE THREAD

**Issue by FlyveHest** [Zylann/godot_voxel#262]
I just downloaded the latest Mono build from Github Actions, https://github.com/Zylann/godot_voxel/actions/runs/736995822, but when I try and run the editor, I get an error that "api-ms-win-core-synch-|1-2-1.dll" is missing, and the editor doesn't start.

Downloading the regular Godot 3.3 engine with Mono works as intended.

A note, I am on Windows 7, and I have api-ms-win-core-synch-l1-2-0.dll in System32

**Comment by Zylann** [comment]
I'm not experienced in making Mono builds, they even stopped working for several weeks now and I have no idea why. If you can find a way to build Godot properly and fix the CI script with these steps, a PR is welcome.

**Comment by FlyveHest** [comment]
It probably is a Win 7 issue, then, I am pretty sure i've seen this before.

I'm not much of a compiler-type person, but as far as I can see in the errors, it has to do with some issues in modules/voxel/terrain/voxel_lod_terrain.cpp, a signed var is compared to an unsigned one, and some unused variables.

As a sidenote, the non-mono compiled version works fine.

On a whole other note, is it possible to DM you?  I have a basic question or two about the Voxel capabilities (not support related9, but I can totally understand if you haven't got time for that :)

**Comment by Zylann** [comment]
> I'm not much of a compiler-type person, but as far as I can see in the errors, it has to do with some issues in modules/voxel/terrain/voxel_lod_terrain.cpp

This has nothing to do with your issue, I just pushed a commit that GCC is not happy about. Mono builds didnt succeed way before that.

> On a whole other note, is it possible to DM you? I have a basic question or two about the Voxel capabilities (not support related9, but I can totally understand if you haven't got time for that :)

You can ask specific questions as issues, otherwise I'm on Discord's Godot server. Sometimes I'm in voicechat. I rarely answer MPs.

**Comment by FlyveHest** [comment]
> This has nothing to do with your issue, I just pushed a commit that GCC is not happy about. Mono builds didnt succeed way before that (where did you see that actually?).

The errors I was referring to is in the first mono build that failed, not the one that you just pushed. (https://github.com/Zylann/godot_voxel/runs/2371839153?check_suite_focus=true)

> You can ask specific questions as issues, otherwise I'm on Discord Godot server. Sometimes I'm in voicechat. I rarely answer MPs.

I'll try and drop in, and see if I can catch you there, then, its not really questions fit for GitHub issues, as they are pretty general about the capabilities of the module :)

**Comment by Zylann** [comment]
> The errors I was referring to is in the first mono build that failed, not the one that you just pushed. (https://github.com/Zylann/godot_voxel/runs/2371839153?check_suite_focus=true)

Ah yeah, sure. But then I have no idea how to fix the next ones, because I fixed that GCC warning a long time ago now

**Comment by FlyveHest** [comment]
Gotcha, I can see that, the next error is a little more severe.  I can also see that a problem like it has been an issues in the past in Godot upstream, so it seems to be related to Godot itself.

I'll try and take a look at that.

**Comment by FlyveHest** [comment]
This seems to be problematic

> ERROR: _generate_cs_property: Condition "getter->return_type.cname != setter->arguments.back()->get().type.cname" is true. Returned: ERR_BUG
> ERROR: _generate_cs_type: Failed to generate property 'lod_count' for class 'VoxelLodTerrain'.

At least, that is the difference between the latest known good, and the ones that break.

Its in the **Generate Mono Glue** action, in the **Generate Mono Glue** step, if you scroll down to the bottom.

I thinks its a part of the process that generates C# files based on the libaries in Godot, but i'm not entirely sure why this happens.

You probably have a lot better insight into the C code, so maybe it rings a bell?

Complete guesswork on my behalf, it might be somewhere in the **void VoxelLodTerrain::_bind_methods()** function?

Might be this commit that did something, maybe theres an unsigned (or signed) int that doesn't match?

https://github.com/Zylann/godot_voxel/commit/b846194bead4624f76f64a92df7a112a01e7c6d7#diff-16c21f4b11472c237b6df4b3549d5322f6e28755fb61be30174a76502742c701

**Comment by Zylann** [comment]
I just fixed the inconsistency but that didn't seem to make the build succeed

**Comment by FlyveHest** [comment]
Well, at least we can conclude that it was the right place :)

> ERROR: _generate_cs_property: Condition "getter->return_type.cname != setter->arguments.back()->get().type.cname" is true. Returned: ERR_BUG
> ERROR: _generate_cs_type: Failed to generate property 'collision_lod_count' for class 'VoxelLodTerrain'.

Its **collision_lod_count** now, so what you did fixed the first error.

**Comment by Zylann** [comment]
Oooh God I just realized where you spotted this. The Mono Glue job is marked as "succeeded" but it clearly didn't. I've missed this for a month :O
I just pushed a fix for the other property and it seems like it's going to build fine.

**Comment by Zylann** [comment]
So now the glue actually works, the Linux build works, but... the Windows build somehow doesn't succeed https://github.com/Zylann/godot_voxel/runs/2535217522?check_suite_focus=true

**Comment by Zylann** [comment]
Looks like your attempt didn't succeed? https://github.com/Zylann/godot_voxel/actions/runs/823578853

**Comment by FlyveHest** [comment]
No, I got the runner report as well.  I think its because the godot_voxel repository is checked out into a subfolder, so the nuget.config is not in the right place.

Its my first time working with Github Actions, so i'm learning something as well, I run Drone on my own Gitea setup for build pipelines :)

**Comment by Zylann** [comment]
Ok this time the build succeeded. So people have to do this too when they build on their computer? I had a quick glance at the doc, which mentions Nuget but doesnt seem to tell anything about that file you made https://docs.godotengine.org/en/stable/development/compiling/compiling_with_mono.html

**Comment by FlyveHest** [comment]
I think this is more of a problem with NuGet compilation for the Windows platform.  People are reporting that this is an intermittent error that pops up seemingly at random.

I found it [here](https://github.com/actions/setup-dotnet/issues/155#issuecomment-761195782)

But yes, it might be necessary to add it for local compilation.

**Comment by FlyveHest** [comment]
Great, I can confirm its working for me on a Win 10 here 👍
