### ISSUE TITLE
Copy bug

### ISSUE THREAD

**Issue by KarloNet** [Zylann/godot_voxel#264]
Hi.
Just tested "**copy**" function from **VoxelTerrainTool** and it seems to have same bug as paste.
If copy buffer is crossing chunk borders it will fail.

var vBuf = VoxelBuffer.new()
vBuf.create(45,45,45)
vBuf.fill(3, VoxelBuffer.CHANNEL_COLOR)
//paste house
_terrain_tool.paste(Vector3(0, 0, 0), voxBuf, (1 << VoxelBuffer.CHANNEL_COLOR), VoxelTool.CLEAR_VOXEL_MASK)
//copy house
_terrain_tool.copy(Vector3(0,0,0), vBuf, (1<<VoxelBuffer.CHANNEL_COLOR))
//paste copy
_terrain_tool.paste(Vector3(0,0,45), vBuf, (1<<VoxelBuffer.CHANNEL_COLOR), VoxelTool.CLEAR_VOXEL_MASK)

![copy](https://user-images.githubusercontent.com/34028997/118355106-9d98d100-b56e-11eb-9e12-3a403bfc7a38.jpg)

**Comment by Zylann** [comment]
I pushed a fix in 9b3263d68bfd123ab36a50a9672f8a86c1e7bcb3

**Comment by KarloNet** [comment]
Good job. It works now.
