### ISSUE TITLE
Community Communication

### ISSUE THREAD

**Issue by muevoid** [Zylann/godot_voxel#269]
I think it would be awesome if you created a discord server or matrix room for this module. There seem to be enough people using it where it may be nice to have a place to ask questions and possibly get quicker answers for simple questions, showcase what people are doing with the module, etc. Im curious what your thoughts are?

**Comment by Zylann** [comment]
I might do that. I can't guarantee to be more available than I am, but it might be a better place to have some discussions (which for now happen in the issue tracker).
I was thinking it could also host other things I made with Godot such as my heightmap plugin.

**Comment by Zylann** [comment]
I made a server here: https://discord.gg/pvgQvPDS

**Comment by muevoid** [comment]
Awesome! Maybe you could pin this issue or put it in the readme so more people notice it?

**Comment by Zylann** [comment]
Done, I also added CI badges cuz they looked cool

**Comment by muevoid** [comment]
Cool I think this can be closed then
