### ISSUE TITLE
Edge of world errors ( on debug mode tested only)

### ISSUE THREAD

**Issue by KarloNet** [Zylann/godot_voxel#280]
Hi.
On small world if you came to border chunks or view distance is bigger then world, console start spamming errors:

ERROR: VoxelTerrain::_process: Condition "count == 0" is true. Continuing.
   At: modules\voxel\terrain\voxel_terrain.cpp:1098

ERROR: Central buffer must be valid
   At: ERROR: modules\voxel\server\voxel_server.cpp:825

![edge](https://user-images.githubusercontent.com/34028997/121808512-27fd4f00-cc59-11eb-9522-42dfe4417080.jpg)

**Comment by Zylann** [comment]
I pushed d436ed430f7e6072b23d393a38da011700559758, see if that fixes your issue

**Comment by KarloNet** [comment]
works :)
