### ISSUE TITLE
VoxelStreamRegionFiles breaks 

### ISSUE THREAD

**Issue by TrayserCassa** [Zylann/godot_voxel#283]
Issue:

The file `r.-1.-1.0.vxr` has this content:
```
Unsupported file: 

System.IO.IOException: Der Prozess kann nicht auf die Datei "C:\Users\Patrick\Documents\Tivaniera\world\save\regions\lod0\r.-1.-1.0.vxr" zugreifen, da sie von einem anderen Prozess verwendet wird.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   bei GitUI.Editor.FileViewer.<>c__DisplayClass119_0.<ViewFileAsync>g__GetFileText|2()
   bei GitCommands.AsyncLoader.<>c__DisplayClass11_0`1.<LoadAsync>b__0(CancellationToken token)
   bei GitCommands.AsyncLoader.<LoadAsync>d__12`1.MoveNext()
```

I am not quite sure if this is a windows problem or godot. But in the Process Explorer only `godot.windows.opt.tools.64.exe` has opened the file. After starting the game, the saved Voxel data is not visible. 

I checked your example blocky game and this problem is not available there. Also the Editor is not opened the region file. (I checked `r.-1.0.1.vxr` with the process explorer)

How to reproduce:
VoxelStreamRegionFiles (No `Save Generator Output`)
OpenSimplexNoise
MesherBlocky

- I removed the save files
- I start the game and on click I place a Voxel with terrainTool.setVoxel
- save with terrain.save_modified_blocks()
- File created - save/regions/lod0/r.-1.-1.-.vxr
- After restarting the engine I see the block in the Editor but the file has the above exception 

I am missing something stupid I think. If you want, I can create a example Project. But Maybe it is something easy I forgot in the Project settings.

**Comment by Zylann** [comment]
The error you posted seems to originate from C#... which is very strange because region files are only opened by the module's C++ code. What are you doing with it?
Can you create a test project?

**Comment by TrayserCassa** [comment]
I am so stupid... Gitextensions prints the c# exception into the file preview. Anyway, the file is open by the godot editor. But your example works just fine with the blocky_example. So the executable can't be the Problem. 

small test Project:
https://github.com/TrayserCassa/voxel_stream_test

- start game
- Press enter
- close game
- regions/lod generated
- start game again. Works blocks are there
- restart godot engine
- Preview in editor works
- start game - no blocks

I assume the Preview in the editor render this but never closed the file :/

**Comment by Zylann** [comment]
Yeah I suspect the editor actually holds a lock on the files. You should probably close the scene before you start the game, or you may have to turn off the `run_stream_in_editor` option (and then close the scene at least once).

**Comment by TrayserCassa** [comment]
Ah, this is kind of unexpected behavior. Was I to stupid to find a hint in your documentation? If not, I can write a small hint into the docu and make a PR :)

**Comment by Zylann** [comment]
That could require a hint. But also it might be possible to improve this somewhow, I just don't know what yet.

**Comment by TrayserCassa** [comment]
Well improvement is always better, but I think there is much harder stuff for you to do, which I can't code. So programmers like me, can try to fix it :) I will try this the next few days, if I fail, I will update your docs :)

**Comment by TrayserCassa** [comment]
I think this is not relevant anymore
