### ISSUE TITLE
Wrong in editor channels names?

### ISSUE THREAD

**Issue by KarloNet** [Zylann/godot_voxel#284]
In editor generator still show old list of channels.

voxelbuffer.cpp
117 const char *VoxelBuffer::CHANNEL_ID_HINT_STRING = "Type,Sdf,Data2,Data3,Data4,Data5,Data6,Data7";

Should be? 
const char *VoxelBuffer::CHANNEL_ID_HINT_STRING = "Type,Sdf,Color,Indices,Weights,Data5,Data6,Data7";

**Comment by Zylann** [comment]
Yup, gonna update this

**Comment by Zylann** [comment]
Fixed in f74d29280aa3bd46442ad167e702de642f43dcd0
