### ISSUE TITLE
How to get rigidbody collision working?

### ISSUE THREAD

**Issue by UAVwaffle** [Zylann/godot_voxel#292]
I have been unable to get rigid body collision.  Every time I use a rigidbody it just fazes through the ground, as if it's not there.  I couldn't find any other issues/questions about this, so maybe I'm doing something wrong? ¯\_(ツ)_/¯

**Comment by Zylann** [comment]
How are you testing this? There is a checkbox to enable collision on terrain nodes, it should be checked if you want physics.

Note: some demos dont use Godot's physics (blocky game) because it is expensive https://voxel-tools.readthedocs.io/en/latest/blocky_terrain/#fast-collisions-alternative

**Comment by UAVwaffle** [comment]
This is something I slapped together as an example of what I'm experiencing.  I've tried both enabling and disabling collisions (probs should tell me how incase I'm doing it wrong),  What you should see when running the game is a rigidbody sphere falling through the map


[VoxelTerrainTest.zip](https://github.com/Zylann/godot_voxel/files/6795753/VoxelTerrainTest.zip)

**Comment by Zylann** [comment]
```
[node name="VoxelLodTerrain" type="VoxelLodTerrain" parent="."]
generator = SubResource( 2 )
mesher = SubResource( 3 )
material = SubResource( 4 )
generate_collisions = false
```
You disabled collisions on your terrain (if it is present in the tscn, it means you changed it from its default value somehow)

**Comment by UAVwaffle** [comment]
Sorry, but before sending you the file, I tested it by flicking that on and off and I forgot to turn it back on before sending you the file.  As I said before, It behaves the same even with it is turned on.  Here is the same file with it turned back on:  
[VoxelTerrainTest.zip](https://github.com/Zylann/godot_voxel/files/6795785/VoxelTerrainTest.zip)

**Comment by Zylann** [comment]
Ah, looks like `VoxelViewer` defaults to collisions off. Set `requires_collisions` to `true` in your `VoxelViewer`.

**Comment by UAVwaffle** [comment]
It still falls through

**Comment by Zylann** [comment]
Your collision shape is underground
![image](https://user-images.githubusercontent.com/1311555/125174652-c8925080-e1be-11eb-90c8-f1712955d643.png)

**Comment by UAVwaffle** [comment]
Thank you so much!  As a conclusion(incase anyone else has the same problem), my issue was a combination between the voxel viewer not having collisions turned on(for a different project) and me accidently moving the mesh instead of the entire rigidbody.  Before I close this issue, could I ask:  Is it possible to have two voxel terrain, one generates smooth terrain and the other one is used for building with square blocks or generating blocky structures? (not going to open up a new question for this because if the answer is yes, no or maybe, I'm going to do some experimentations and close this one)

**Comment by Zylann** [comment]
> Is it possible to have two voxel terrain, one generates smooth terrain and the other one is used for building with square blocks or generating blocky structures?

Yes

**Comment by UAVwaffle** [comment]
thx :)
