### ISSUE TITLE
Is it possible to change the margin of the collisions of VoxelLodTerrain?

### ISSUE THREAD

**Issue by ultrazar** [Zylann/godot_voxel#293]
In the space thecnic demo I saw that all the collisions had 0.04 of margin. I think that setting it a little bit higher would make a better performance of CPU.
But after searching in the docs I couldn't seem to have any option to change it. Is it possible? If not I think it should be.

**Comment by Zylann** [comment]
That should be added to the API since colliders are created internally.

**Comment by Zylann** [comment]
Added in 8c17a1cf20eb5ac691608cbde95e985d9a35eb7a
