### ISSUE TITLE
VoxelStreamRegionFiles spam errors ( channel depth mismatch)

### ISSUE THREAD

**Issue by KarloNet** [Zylann/godot_voxel#302]
Hi.
When you run first time scene with VoxelstreamRegionFiles enabled it sometimes (usualy if you edit large part of terrain)
start spamm errors of buffer depth mismatch.

part that spamm errors:
**void VoxelStreamRegionFiles::_immerge_block(Ref<VoxelBuffer> voxel_buffer, Vector3i origin_in_voxels, int lod)**
...
204 ERR_FAIL_COND(voxel_buffer->get_channel_depth(i) != _meta.channel_depths[i]);

After a bit of digging I found that the problem is with saving meta data beafore its initialized to depth values used by chunks.
and it happens in:

**VoxelStreamRegionFiles::EmergeResult VoxelStreamRegionFiles::_emerge_block(
		Ref<VoxelBuffer> out_buffer, Vector3i origin_in_voxels, int lod)**
.......
	if (!_meta_loaded) {
		VoxelFileResult load_res = load_meta();
		if (load_res != VOXEL_FILE_OK) {
			//if (!_meta_saved && load_res == VOXEL_FILE_CANT_OPEN) {
				// TODO Is it a good idea to save on read?
				// New data folder, save it for first time
				VoxelFileResult save_res = save_meta();
				ERR_FAIL_COND_V(save_res != VOXEL_FILE_OK, EMERGE_FAILED);
			} else {
				return EMERGE_FAILED;
			}
			return EMERGE_FAILED;
		}
	}
.....

And I just changed it to:

	if (!_meta_loaded) {
		VoxelFileResult load_res = load_meta();
		if (load_res != VOXEL_FILE_OK) {
			return EMERGE_OK_FALLBACK;
		}
	}

**Comment by Zylann** [comment]
Makes sense. I changed the code in 967dcbd04ca595edb1aafb28a974b26187998507
