### ISSUE TITLE
Voxels are only visible in editor, not in game

### ISSUE THREAD

**Issue by Favkis** [Zylann/godot_voxel#311]
![image](https://user-images.githubusercontent.com/46406204/133239473-56f498e6-93d2-4cd4-8676-e72d98e16ee6.png)

I have this error and can't seem to fix it. 

![image](https://user-images.githubusercontent.com/46406204/133239546-ff125c56-eb79-4ee1-a4ec-61394429d7d1.png)
I've tried different settings, different stream, generator and mesher, but no luck. 

Inside generator I have "Type" so it should be blocky.
![image](https://user-images.githubusercontent.com/46406204/133239727-ab5cfe36-5599-4aab-9cdd-7828e6367539.png)

In editor everything works as it's supposed to, I have blocks, generator on Type and no matter what stream I use I still have that error.

**Comment by Favkis** [comment]
Oh... I forgot to add VoxelViewer under the camera...
Not I see voxels both in game and editor, but I still have that error.

**Comment by Zylann** [comment]
I would suggest you don't use `VoxelStreamBlockFiles`, it's getting outdated. The error occurs because this stream is not providing the info about which channels it supports. It should support any, though.

**Comment by Zylann** [comment]
If you still want to use that stream, f0c59acf0bed138438b77860a7cc969553f8b5c0 should fix the warning
