### ISSUE TITLE
Won't compile with gcc

### ISSUE THREAD

**Issue by tinmanjuggernaut** [Zylann/godot_voxel#32]
master
gcc 8.3

I'm moving my dev environment to linux. Gcc won't compile Voxel tools out of the box, but will with the following changes. There are two things to fix, and a whole bunch of warnings. @Zylann, I have some questions for you on how you want to fix things before I submit a PR.

**1. compute_lod_count returns an int but is defined as void.**
Easy. Diff below.

**2. cannot bind non-const lvalue reference of type 'LodOctree<bool>::NoDestroyAction&' to an rvalue of type 'LodOctree<bool>::NoDestroyAction'**

```modules/voxel/terrain/voxel_lod_terrain.cpp: In member function 'void VoxelLodTerrain::set_lod_count(unsigned int)':
modules/voxel/terrain/voxel_lod_terrain.cpp:158:71: error: cannot bind non-const lvalue reference of type 'LodOctree<bool>::NoDestroyAction&' to an rvalue of type 'LodOctree<bool>::NoDestroyAction'
   _lod_octree.create_from_lod_count(bs, p_lod_count, LodOctree<bool>::NoDestroyAction());
```

[This post](https://stackoverflow.com/questions/27172033/invalid-initialization-of-non-const-reference-of-type) says it works fine in MSVC but is not portable. They said it could be fixed by making the referenced argument const. That of course made a whole cascade of other errors, which were fixed by making the operator() itself const. 

I don't know if this is correct, but the changes allowed it to compile, run and my own LOD+raycast demo worked as expected.

However, I noted there were other functions that used the same style of passing "A& destroy_action" such as update(), clear(), etc. Should they have a const argument also? What do you want to do here?

Here is the minimum needed to compile:

```
diff --git a/terrain/lod_octree.h b/terrain/lod_octree.h
index 4ddc646..939d426 100644
--- a/terrain/lod_octree.h
+++ b/terrain/lod_octree.h
@@ -37,7 +37,7 @@ public:
        };
 
        struct NoDestroyAction {
-               inline void operator()(Node *node, int lod) {}
+               inline void operator()(Node *node, int lod) const {}
        };
 
        template <typename A>
@@ -47,7 +47,7 @@ public:
                _base_size = 0;
        }
 
-       static void compute_lod_count(int base_size, int full_size) {
+       static int compute_lod_count(int base_size, int full_size) {
                int po = 0;
                while (full_size > base_size) {
                        full_size = full_size >> 1;
@@ -57,7 +57,7 @@ public:
        }
 
        template <typename A>
-       void create_from_lod_count(int base_size, unsigned int lod_count, A &destroy_action) {
+       void create_from_lod_count(int base_size, unsigned int lod_count, const A &destroy_action) {
                ERR_FAIL_COND(lod_count > 32);
                clear(destroy_action);
                _base_size = base_size;
diff --git a/terrain/voxel_lod_terrain.h b/terrain/voxel_lod_terrain.h
index 7ec903b..aca8c60 100644
--- a/terrain/voxel_lod_terrain.h
+++ b/terrain/voxel_lod_terrain.h
@@ -78,7 +78,7 @@ private:
        bool check_block_loaded_and_updated(const Vector3i &p_bpos, unsigned int lod_index);
 
        template <typename A>
-       void for_all_blocks(A &action) {
+       void for_all_blocks(const A &action) {
                for (int lod_index = 0; lod_index < MAX_LOD; ++lod_index) {
                        if (_lods[lod_index].map.is_valid()) {
                                _lods[lod_index].map->for_all_blocks(action);
```

**3. There are a ton of warnings from the voxel module.**
So many that I had to turn off warnings just so I could see the errors above to fix them. They are only warnings, but should probably be fixed at some point. I can fix some of them now if you like, but some are interwoven throughout the whole module. 

Easy fix: 
```
modules/voxel/terrain/voxel_map.h:96:3: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
   while (key = _blocks.next(key)) {
```

Most have to do with comparing a signed int to an unsigned int. Some are an easy fix:

```
modules/voxel/terrain/block_thread_manager.h:172:37: warning: comparison of integer expressions of different signedness: 'int' and 'unsigned int' [-Wsign-compare]
   for (int job_index = 0; job_index < _job_count && i < input.blocks.size(); ++job_index) {
```

Some have a caveat:
```
_FORCE_INLINE_ bool validate_pos(unsigned int x, unsigned int y, unsigned int z) const {
                return x < _size.x && y < _size.y && z < _size.z;
        }
```
_size is a Vector3i which uses signed ints. So this function is easy to fix. But then you have similar functions that do not compare and do not give warnings, but they still use unsigned ints when the underlying data are signed. Is this a problem?

```
_FORCE_INLINE_ unsigned int get_volume() const {
                return _size.x * _size.y * _size.z;
        }
```

Some sign comparison complaints are in code that looks like this. I don't want to just go through and start changing functions around. Do I change the arguments in hermite_value, or the return type in voxel_buffer? Perhaps it makes sense to change _size to an unsigned vector3i and make everything unsigned ints?
```
meshers/dmc/hermite_value.h:
inline float get_isolevel_clamped(const VoxelBuffer &voxels, unsigned int x, unsigned int y, unsigned int z) {
        x = x >= voxels.get_size().x ? voxels.get_size().x - 1 : x;


voxel_buffer.h:
_FORCE_INLINE_ int get_size_x() const { return _size.x; }
```

What would you like to do about these warnings?

**Comment by Zylann** [comment]
1) compute_lod_count returns an int but is defined as void.

Yes, that one is obvious mistake.

2. cannot bind non-const lvalue reference of type 'LodOctree::NoDestroyAction&' to an rvalue of type 'LodOctree::NoDestroyAction'

I'm not sure what bothers the compiler so much here, nothing is const. Maybe you could try putting the action object in a local var and pass the var?
I should eventually change that to a lambda tbf. I used functors a lot to match Godot C++03 style and the sort of idea that my code would get inlined, but in some places lambdas would be better.

I'll have a look at warnings when I get back home.

**Comment by tinmanjuggernaut** [comment]
> Maybe you could try putting the action object in a local var and pass the var?

What I have (in the diff in #2) compiles fine (with a ton of warnings). Is this quote your preferred solution instead of what I did?

**Comment by Zylann** [comment]
@tinmanjuggernaut both work, but the one I proposed is closer to what my original intention was when writing this class. There is no reason for the functor to be const (even though I never had yet a use case with stateful functors in this particular function).

**Comment by Zylann** [comment]
About warnings:
```
modules/voxel/terrain/voxel_map.h:96:3: warning: suggest parentheses around assignment used as truth value [-Wparentheses]
   while (key = _blocks.next(key)) {
```
Why does GCC want more parentheses? Aren't there enough here?

About signed int stuff, maybe I could do something like Vector3u?
Alternative is to use ints everywhere but it will require more comparisons for negative numbers and still requires casts when std::vector is used.

> But then you have similar functions that do not compare and do not give warnings, but they still use unsigned ints when the underlying data are signed. Is this a problem?

In the example you gave obviously the internal is signed because it's Vector3i, but it should be unsigned. The reason it's not internally is purely convenience.

I wish I could see those warnings using MSVC, I don't have MinGW setup...

**Comment by tinmanjuggernaut** [comment]
> Why does GCC want more parentheses? Aren't there enough here?

It's quite common for people to use conditionals there: `while (key == _blocks...)`, so apparently gcc flags assignments without explicit parentheses in case you're making a typo.

**Comment by Zylann** [comment]
Go for double parenthesis then. I notice it's there in the rest of the Godot codebase...

**Comment by tinmanjuggernaut** [comment]
> @tinmanjuggernaut both work, but the one I proposed is closer to what my original intention was when writing this class. 

This diff uses temp action objects, compiles and runs just fine. Would you prefer this instead? 
```
diff --git a/terrain/lod_octree.h b/terrain/lod_octree.h
index 4ddc646..0284a0f 100644
--- a/terrain/lod_octree.h
+++ b/terrain/lod_octree.h
@@ -47,7 +47,7 @@ public:
                _base_size = 0;
        }
 
-       static void compute_lod_count(int base_size, int full_size) {
+       static int compute_lod_count(int base_size, int full_size) {
                int po = 0;
                while (full_size > base_size) {
                        full_size = full_size >> 1;
diff --git a/terrain/voxel_lod_terrain.cpp b/terrain/voxel_lod_terrain.cpp
index d5f4e7c..3e2bf98 100644
--- a/terrain/voxel_lod_terrain.cpp
+++ b/terrain/voxel_lod_terrain.cpp
@@ -154,7 +154,8 @@ void VoxelLodTerrain::set_lod_count(unsigned int p_lod_count) {
        if (get_lod_count() != p_lod_count) {
 
                int bs = get_block_size();
-               _lod_octree.create_from_lod_count(bs, p_lod_count, LodOctree<bool>::NoDestroyAction());
+               LodOctree<bool>::NoDestroyAction nda;
+               _lod_octree.create_from_lod_count(bs, p_lod_count, nda);
 
                for (int lod_index = 0; lod_index < MAX_LOD; ++lod_index) {
 
@@ -283,15 +284,24 @@ void VoxelLodTerrain::_notification(int p_what) {
                        break;
 
                case NOTIFICATION_ENTER_WORLD:
-                       for_all_blocks(EnterWorldAction(*get_world()));
+                       {
+                               EnterWorldAction ewa(*get_world());
+                               for_all_blocks(ewa);
+                       }
                        break;
 
                case NOTIFICATION_EXIT_WORLD:
-                       for_all_blocks(ExitWorldAction());
+                       {
+                               ExitWorldAction ewa;
+                               for_all_blocks(ewa);
+                       }
                        break;
 
                case NOTIFICATION_VISIBILITY_CHANGED:
-                       for_all_blocks(SetVisibilityAction(is_visible()));
+                       {
+                               SetVisibilityAction sva(is_visible());
+                               for_all_blocks(sva);
+                       }
                        break;
 
                        // TODO Listen for transform changes
```

**Comment by tinmanjuggernaut** [comment]
How would you like to handle this warning?

```
modules/voxel/terrain/voxel_terrain.cpp: In member function 'void VoxelTerrain::_process()':
modules/voxel/terrain/voxel_terrain.cpp:798:12: warning: declaration of 'time_before' shadows a previous local [-Wshadow=local]
   uint32_t time_before = os.get_ticks_msec();
            ^~~~~~~~~~~
modules/voxel/terrain/voxel_terrain.cpp:538:11: note: shadowed declaration is here
  uint64_t time_before = os.get_ticks_usec();
           ^~~~~~~~~~~
```

In _process at 538, you defined time_before as unit64. Then in a sub scope of _process at 798, you redefine it, hiding the original.

**Comment by tinmanjuggernaut** [comment]
I've squashed all warnings with what I believe are non-intrusive fixes. Parentheses warnings, commenting out two unused variables, initializing a few variables, and changing ints to uints or casting comparisons under the assumption that all sizes, array indices, ids, and counts should be positive.

While in the specified files, I changed some functions beyond what had been flagged for consistency.

Some functions like this one:
```
modules/voxel/terrain/../meshers/dmc/hermite_value.h:21:8: warning: comparison of integer expressions of different signedness: 'unsigned int' and 'const int' [-Wsign-compare]
inline float get_isolevel_clamped(const VoxelBuffer &voxels, unsigned int x, unsigned int y, unsigned int z) {
  x = x >= voxels.get_size().x ? voxels.get_size().x - 1 : x;
________^
```
get_size() is built to return a Vector3i. Rather than create a whole Vector3u class, I just cast it.

Sometimes you use std::vector. It's size() returns a uint. Sometimes you use Vector. It's size() returns an int. When comparing in the latter cases, I just cast them.

Once you say what to do with the post above, I'll submit all changes in a PR, broken into different commits based on warning/error type for review. Then I can squash or make separate PRs.

**Comment by Zylann** [comment]
About `time_before` hiding original:
This is actually intented. The outer scope variable is for profiling, the inner scope variable is for actual processing time management. I think both should have been `uint64_t` but hiding is a bit embarrassing. In `voxel_lod_terrain` I used an explicit profiling clock: https://github.com/Zylann/godot_voxel/blob/master/terrain/voxel_lod_terrain.cpp#L409
Another option is to split into functions but I purposedly used scopes here to keep the code linear and ensure it's the only place it runs.

I tried introducing `Vector3u` but it felt a bit forced, so I think besides changing some args to `unsigned int` it should be enough to cast when necessary.

I'd need to setup MinGW on my computer somehow, just so I can check GCC warnings because I'm sure I added more of these in my more recent WIP branch.

**Comment by tinmanjuggernaut** [comment]
> I'd need to setup MinGW on my computer somehow, just so I can check GCC warnings because I'm sure I added more of these in my more recent WIP branch.

It takes 15 minutes.

1. Install this which comes with gcc 8.1 https://sourceforge.net/projects/mingw-w64/
2. Install for x86_64 and posix threads (win32 won't compile the engine)
3. Add the C:\Program Files\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin to your path, or use their provided cmd shell. Once it's in the path, it works fine in gitbash or a windows command shell.

4. You probably already have scons and python installed in your path, so compile like this:
`scons target=release_debug platform=windows use_mingw=yes -j6`

5. To switch compilers, it's probably a good idea to clean files. But that might even be optional. 
gcc will make .o files. msvc makes .obj files. Nothing else is needed.

You can clean under gitbash quickly like this:
```
cd /c/dev/godot
scons.py --clean
find . -iregex ".*/*\.\(64.o\|64.a\|obj\|lib\|exe\)"  -delete
```

With my build-gcc branch, I was able to compile and run just fine. 

Interestingly, the last warning, the shadow warning, did not appear. Maybe its the difference between gcc 8.1 and 8.3. Stock, it wouldn't compile and there were a ton of familiar signed warnings before I merged by branch. 

Also linking takes a while and produced a 230mb executable! Perhaps because it linked with a mingw static library to provide posix and C++11 multithreading.

**Comment by tinmanjuggernaut** [comment]
Actually under linux, gcc produces a large binary also, so it's not a windows thing. 

> About `time_before` hiding original:
> This is actually intented. The outer scope variable is for profiling, the inner scope variable is for actual processing time management. I think both should have been `uint64_t` but hiding is a bit embarrassing. In `voxel_lod_terrain` I used an explicit profiling clock: https://github.com/Zylann/godot_voxel/blob/master/terrain/voxel_lod_terrain.cpp#L409
> Another option is to split into functions but I purposedly used scopes here to keep the code linear and ensure it's the only place it runs.

Ok, after reviewing the code, I replaced the manual timers with your profiling clock. 
On the next line 795, you have uint32_t timeout, which the next for loop compares against os.get_ticks_mset(). That function returns a signed 64-bit int, so I guess uint32_t works. Should it be changed?

...... and no more Voxel Tools warnings!!!

**Comment by tinmanjuggernaut** [comment]
BTW, I don't know if this is related, but I have a ton of trouble running the dmc_terrain demo, with today's profiling code changes or not.

Within Godot it continually breaks on a 'previously freed instance' on a null instance.
```
dmc_terrain/block_debug.gd:92 var now_ms = OS.get_ticks_msec()
Attempt to call function 'get_ticks_msec' in base 'previously freed instance' on a null instance.
```
or `draw_rect` or `get_block_info`

Sometimes my own code breaks on a freed instance, but it's rare and I just restart. But right now the dmc_terrain it crashes almost everytime I run it. Sometimes, if I don't breathe on the mouse, it will run and start drawing, then if I move the camera very slowly it will stay running. But if it's too much, it will crash. Do you see this? or any idea what causes it?

**Comment by tinmanjuggernaut** [comment]
It seems the issue is specifically with main_lod.tscn. I don't seem to have an issue with dmc/main. dmc/main_lod runs much better today. I don't know what's different. My own code crashed once on the freed instance upon an initial start, then not again. It's like the engine isn't clearing all memory between runs, or maybe the autoloaded script is doing something?

**Comment by Zylann** [comment]
> On the next line 795, you have uint32_t timeout, which the next for loop compares against os.get_ticks_mset(). That function returns a signed 64-bit int, so I guess uint32_t works. Should it be changed?

It could be changed to match comparison types. This section deals with very short timings (a few milliseconds) so I didnt bother too much.

About the null instance error in `block_debug.gd`:
I have no idea what's going on. `OS` being a freed instance is just ominous. At least the line you linked only contains the `OS` object.

I never had crashing issues with current master otherwise. When something strange like that occurs, it could be a lucky thread problem, which could originate from errors in a scripted `VoxelStream` or from the module itself. Moving too fast for the computer is bad for performance, but should not crash. Maybe there is an extreme case I didnt think of?

**Comment by tinmanjuggernaut** [comment]
> > On the next line 795, you have uint32_t timeout, which the next for loop compares against os.get_ticks_mset(). That function returns a signed 64-bit int, so I guess uint32_t works. Should it be changed?
> 
> It could be changed to match comparison types. This section deals with very short timings (a few milliseconds) so I didnt bother too much.

I was mistaken. In the docs it says it returns an int, which the docs says are signed 64-bit. However in the C++ code OS::get_ticks_msec() returns a uint32_t, so I will leave it as you have it.

Re: Crashing
I'll see if I can get a reproducable project sometime.
