### ISSUE TITLE
VoxelLODTerrain with VoxelGeneratorGraph suddenly starts generating jagged, uneven terrain

### ISSUE THREAD

**Issue by ciqven** [Zylann/godot_voxel#329]
Greetings, let me just thank you for this awesome add-on before dropping some info:

OS: Windows 10
godot_voxel build: https://github.com/Zylann/godot_voxel/actions/runs/1430272929

### Issue
I am making a game using godot_voxel for the terrain. I have a smooth VoxelLODTerrain, with a VoxelGeneratorGraph. No streams yet at the moment. I deleted the nodes in the Graph in order to start anew, I had been using a non-realistic setup for testing before and wanted to make a better graph. From then onward, the terrain generated by the VoxelGeneratorGraph became 'steppy' or jagged. Trying again in a blank project did not fix this. Rebooting also did not fix this.

This is an old screenshot of how the terrain used to look a couple of days ago, this is how it looked until just now:
![before](https://user-images.githubusercontent.com/60892584/140919921-5b4cb23c-9463-463f-a331-24faaa387225.png)

This is a new project with VoxelGeneratorNoise and 1 directional light, notice the smoothness:
![smooth](https://user-images.githubusercontent.com/60892584/140920151-07b1b2f4-f7ef-419d-9d9d-c7ec4889aa33.png)

This is the exact same new project as the previous screenshot, only with a VoxelGeneratorGraph instead of a VoxelGeneratorNoise. Nothing else was changed:
![jagged1](https://user-images.githubusercontent.com/60892584/140920322-f5f53e8c-61e1-45cf-b604-33c436fb5619.png)

Alternative angle:
![jagged2](https://user-images.githubusercontent.com/60892584/140920347-feb302c4-d897-421c-bbf7-54336438f6db.png)

I am now wondering whether I unknowingly did something really well the first time, or if this is actually a bug. I could not find anything in the docs or in other issues about this.

A minimal project has been attached.
[terraindebug1.zip](https://github.com/Zylann/godot_voxel/files/7504479/terraindebug1.zip)

**Comment by Zylann** [comment]
I think the reason is because you are plugging a noise output directly to SDF. Noise is between -1 and 1, but internally this data is stored with a scale over 16 bits. So -1..1 is too small of a range. For an SDF, it barely varies when the cave patterns are dozens of units large.
So you can fix this by multiplying the output of noise by about 10.

**Comment by ciqven** [comment]
Thanks for the quick reply, that did indeed fix it. I must have somehow multiplied it already in my previous (messy) setup...
