### ISSUE TITLE
renaming nodes in Voxel Graph

### ISSUE THREAD

**Issue by spiro-angelakis** [Zylann/godot_voxel#342]
I may just not be doing it right, but i cant seem to rename nodes within a voxel graph, i saw in your solar system demo there is a graph where some nodes do have custom names, but entering text to the name box in a nodes property does nothing for me.

I need to be able to name nodes in voxel graph so that i can access those nodes in GDscript to do things like randomizing seeds of Noise generators within voxel graph and changing some constant values.

any help is greatly appreciated

**Comment by spiro-angelakis** [comment]
ive managed to list nodes in a graph to find specific node ids i need to edit at runtime and am making it work this way for now

**Comment by Zylann** [comment]
In which version did you try this? Any error in the console?

**Comment by spiro-angelakis** [comment]
i have the godot 3.5 voxel tools release, no error or anything, the entry field for name is a little darker than other text boxes that work, allows you to type into it and hit enter, but upon clicking out of inspecting that node you named, the name will not affect the node in the graph and will not still be written in the text box when returning to that node inspection

**Comment by Zylann** [comment]
> godot 3.5
There is no 3.5, did you mean 3.4? Or latest from compiling master?

**Comment by spiro-angelakis** [comment]
i suppose it may have been the latest from master then, my editor says 3.5beta in the output window

**Comment by Zylann** [comment]
I pushed a fix to the `godot3.4` branch

**Comment by spiro-angelakis** [comment]
i suppose i should go switch to that one then, thank you!

**Comment by Zylann** [comment]
Should be fixed in all branches now.
`master`: 8d6a24833c542de498cab5387d14cb696eadbc55
`godot3.x`: 207c6e72fca46067491a574242b2f388f5d3b8bb
