### ISSUE TITLE
Godot 4.0 VoxelMesherBlocky - in editor can't create new instance of VoxelLibrary 

### ISSUE THREAD

**Issue by KarloNet** [Zylann/godot_voxel#350]
Add VoxelTerrain
mesher -> VoxelMesherBlocky
Library -> only load. No option to create new one.

To work around:
voxel_mesher_blocky.cpp
ADD_PROPERTY(PropertyInfo(Variant::OBJECT, "library", PROPERTY_HINT_RESOURCE_TYPE, "VoxelLibrary", ...

changed to:

ADD_PROPERTY(PropertyInfo(Variant::OBJECT, "library", PROPERTY_HINT_RESOURCE_TYPE, "VoxelBlockyLibrary", ...

**Comment by KarloNet** [comment]
Btw, same problem with voxels list in library.

voxel_blocky_library.cpp
void VoxelBlockyLibrary::_get_property_list(List<PropertyInfo> *p_list) const {
...
p_list->push_back(PropertyInfo(Variant::OBJECT, "voxels/" + itos(i), PROPERTY_HINT_RESOURCE_TYPE, "Voxel"));

changed "Voxel" to "VoxelBlockyModel"

**Comment by Zylann** [comment]
Godot likes strings way too much

**Comment by Zylann** [comment]
Should be fixed in 08f3786ff6a53baba7d25b5225f14628e54cbaab
