### ISSUE TITLE
Just getting ERROR: Condition "mesh_block == nullptr" is true.

### ISSUE THREAD

**Issue by BlotoPK** [Zylann/godot_voxel#352]
Hi. I'm just getting this error and don't know why. It is not always happen, but when occurs it comes with a heavy freezing (due to the number of errors generated: almost 150)...

I just searched about this error but didn't get so much... Can be my VoxelGeneratorScript the cause of this? Honestly don't know where start...

Thanks in advance.

**Comment by Zylann** [comment]
No, it cannot be caused by your generator (assuming it doesn't do thread-unsafe stuff like accessing nodes in the middle of `generate_block`).

Which version are you using? Can you post the whole error including, not just the message? I remember fixing some occurrences of this according to the changelog.

**Comment by BlotoPK** [comment]
I think I'm using the last windows build: Windows Build #347. I will download it again and check it.

The full error is:

> E 0:01:06.477   VoxelTerrain::process_meshing: Condition "mesh_block == nullptr" is true. Continuing.
  <C++ Source>  modules\voxel\terrain\voxel_terrain.cpp:1140 @ VoxelTerrain::process_meshing()

The reason I mentioned the Generetor was because I know I'm not using it properly, somehow...
I'm just locking the thread and then filling the chunks (with the idea of later having more variety of voxels and put them precisely where I want), but I know that the func is called almost continuously, even if the voxels are all already set.
This is my func _generate_block:

`	mutex.lock() #we lock the thread
	
	if lod != 0:
		return
	
	number_of_calls += 1
	
	for h in range(0, tam_z):
		for i in range(-tam_x, tam_x): #4 to the left, 4 to the right, 'cause the chunks
			#rise to the right, the 0 chunk is also right.
			if origin == Vector3(i*16, 0, h*16): #for every chunk origin...
				if origin.x == -tam_x*16: #if we are at the first chunk on the left...
					for j in range(1, 16): #we just jump the first step...
						for k in range(16):
							buffer.set_voxel(1, j, 0, k, channel)
							buffer.set_voxel(1, j, 1, k, channel)
							buffer.set_voxel(1, j, 2, k, channel)
							number_of_voxels_created += 3
				else: #otherwise...
					for j in range(16): #the blocks are of 16, so every "origin" have a max of 16
						for k in range(16):
							buffer.set_voxel(1, j, 0, k, channel)
							buffer.set_voxel(1, j, 1, k, channel)
							buffer.set_voxel(1, j, 2, k, channel)
							number_of_voxels_created += 3
							
	print("there were ",number_of_calls," calls and ",number_of_voxels_created, " voxels created.")
	mutex.unlock()`

**Comment by Zylann** [comment]
From the code you posted, I don't see anything wrong. Just something suboptimal indeed, the mutex will reduce all concurrency to a single thread, so generation might be 4 times slower than it could be, while occupying all threads of the pool needlessly: other tasks that are not generation, like meshing, will also be slowed down by that.
So in a way... you are affecting meshes, but it is not supposed to be a problem as long as they eventually get through, they would just be slower...
So again I believe your code is legit but it might highlight an edge case that's not being handled right.

**Comment by BlotoPK** [comment]
You're right, the mutex was a bad idea... but honestly I had to try. It's gone now.
I pass through a kind of process triying to solve this:

- First notice that when "generate collision" is unchecked, the error occurs, but fewer.

- Then I thought about the calls, and I'd reduce the bounds of the voxel terrain to only the necessary. It works in a certain way: the amount of errors was reduce significantly (even when "generate collisions" opt is checked).

- I'm now receiving errors but ocassionally and a it does not freeze the game at all (comparing with the original case, 150 errors vs 7 and not so frequently). I think that the problem implies some kind of overlapping collisions between the voxels and the player, but I need to do some more tests.

**Comment by BlotoPK** [comment]
[New Game Project.zip](https://github.com/Zylann/godot_voxel/files/7998350/New.Game.Project.zip)

That is a simple project. Just with a third person controller and a floor made with voxels.
You can move with WASD and rotate the camera with the mouse. Eventually (after 10 or 20 seconds of moving forward) you will get 16 errors...
You can also quit with Esc.

**Comment by BlotoPK** [comment]
I'm unable to replicate the error in the #346 build (3.x)...
I'm very sorry... what can I say... :$ ...I somehow downloaded the latest version, but continued to use one from december... what a shame. Sorry for your time.

**Comment by Zylann** [comment]
Indeed I havent tested your project yet but it is very likely I fixed that in the 3.x (after commits f560910a68992e6ee61b8551fd63dc7ad90e8e67 and 05f5aa429f5e65a6561688ac7215b16b52796b7f)
