### ISSUE TITLE
Custom VoxelGenerator (in C++)

### ISSUE THREAD

**Issue by MadMartian** [Zylann/godot_voxel#353]
How would I go about implementing a custom VoxelGenerator type in my C++ GDNative module and then use it in the Godot editor?  I have already successfully built and tested a GDNative module and I am already interacting with it in the Godot editor.  However, I have not been able to implement a custom VoxelGenerator and I think it's because the API headers are missing all the Voxel plug-in headers necessary for developing against it.  How would I go about rectifying this?

**Comment by Zylann** [comment]
To do this you need to compile a version of Godot including this module. Then you need to generate `api.json`, generate binding classes and recompile the C++ bindings library using this specific JSON file (instead of whatever might be provided by default). Then you should be able to access the headers for classes of this module.

**Comment by MadMartian** [comment]
I neglected to mention that I think I tried that but I wasn't paying very close attention to what happened.  I also didn't want to confuse this issue if it wasn't relevant.  But I believe I did do this, the steps I followed were:

1. Compile Godot project
2. Add the Voxel module to Godot beneath the `modules` folder
3. Re-compile Godot (again)
4. Generate the bindings `api.json`
5. Compile the Godot-CPP project pointing it to the new `api.json` and `godot_headers` folder
6. Include the headers (generated and existing) from Godot-CPP in my GDNative module

After doing this I did manage to see some Voxel-specific API headers show-up in Godot-CPP, but I could not get it to compile.  Since then I checked out Godot v3.2.3 (stable) tags from the respective repositories, and then it was compiling, but I haven't seen those Voxel-specific API headers since.

Are those the correct steps? am I missing a step?  I will try again later today this time keeping careful track of what happens at each step.

**Comment by Zylann** [comment]
Step 1 is not necessary.
Assuming step 5 includes generating class bindings, I don't see what else would be missing. But if you are not seeing voxel-specific headers again, maybe you have a mistake around there? (like forgetting to re-generate the classes, or not giving the right api?)

**Comment by MadMartian** [comment]
Yes, step 5 includes generating class bindings (I believe it's a Python script that consumes the `api.json` and spits out C++ headers).  Will try again later and report back.

**Comment by MadMartian** [comment]
Looks like PEBCAK, I was using the wrong binary to generate the `api.json`, looks like everything is working as expected now, thank you for clarifying the steps!
