### ISSUE TITLE
Some error messages appear when runing a scene

### ISSUE THREAD

**Issue by SneaK1ng** [Zylann/godot_voxel#355]
Some error messages appear when runing a scene:

Godot_4.0_233699f9e7
voxel_tool_1.x_79ba0f2

---
_E 0:00:00:0801   ClassDB::bind_methodfi: Method definition provides more arguments than the method actually has 'VoxelTerrain::try_set_block_data'.
  <C++ error>       Method/function failed. Returning: nullptr
  <C++ source>      core\object\class_db.cpp:1430 @ ClassDB::bind_methodfi()
E 0:00:00:0802   ClassDB::add_property: Invalid setter 'VoxelViewer::set_requires_data_block_notifications' for property 'requires_data_block_notifications'.
  <C++ error>       Condition "!mb_set" is true.
  <C++ source>      core\object\class_db.cpp:1051 @ ClassDB::add_property()_

---
I changed the code to the following.
-voxel_terrain.cpp **Deleted "replace_if_exists"**
  ClassDB::bind_method(D_METHOD("try_set_block_data", "position", "voxels", "replace_if_exists"),

-voxel_viewer.cpp: **Add bind_method of requires_data_block_notifications**
 ClassDB::bind_method(D_METHOD("set_requires_data_block_notifications", "enabled"), &VoxelViewer::set_requires_data_block_notifications);
 ClassDB::bind_method(D_METHOD("is_requiring_data_block_notifications"), &VoxelViewer::is_requiring_data_block_notifications);

**Comment by Zylann** [comment]
Should be fixed in 91bbe56cea7670ebda3d163bee2f56bdf02bc17f and 27a9c94e444acbff7f2b71a815ea4a10537d4cdb

**Comment by SneaK1ng** [comment]
> Should be fixed in [91bbe56](https://github.com/Zylann/godot_voxel/commit/91bbe56cea7670ebda3d163bee2f56bdf02bc17f) and [27a9c94](https://github.com/Zylann/godot_voxel/commit/27a9c94e444acbff7f2b71a815ea4a10537d4cdb)
thx
