### ISSUE TITLE
Is it possible to have non-full blocks using this voxel library?

### ISSUE THREAD

**Issue by Darker** [Zylann/godot_voxel#356]
I wanted to make a simple minecraft client. I attempted this when I was in high school and sort-of suceeded (ie. rendered the downloaded blocks in OpenGL and crashed my laptop). I want to try again, but this time I don't have so much time on my hands.

I was wondering if I could use this tool and if it would support non-full blocks that Minecraft has, like slabs and fences. I understand that it generates chunk meshes from the blocks, so I wanted to know if it can handle more complicated geomethry.

**Comment by Zylann** [comment]
Non-full blocks still occupy a full voxel in the grid. They are not "half voxels". In Minecraft, when you pile up two slaps, you don't get two blocks, it actually replaces the slab with another "full slab" block type.
Their *model* just happens to not fill up all the space. It is possible to do this with `VoxelMesherBlocky` by defining such models (requires to make their mesh yourself, there is no shortcut geometry).

**Comment by Darker** [comment]
Yeah, that's what I meant. I was just asking if a non full block can exist and be rendered. One block per voxel of course.

**Comment by SneaK1ng** [comment]
> Yeah, that's what I meant. I was just asking if a non full block can exist and be rendered. One block per voxel of course.

You can see the demo
[https://github.com/Zylann/voxelgame](url)

**Comment by Darker** [comment]
I am closing this, the answer clearly is that blocks that are not full cubes can be added and rendered without issue.
