### ISSUE TITLE
Can't build newest Godot after update with "Remove EditorNode* argument from editor plugin constructors"

### ISSUE THREAD

**Issue by KarloNet** [Zylann/godot_voxel#361]
When i try to build newest godot with voxel got some errors about  plugin editor and build fail.

Error	C2664	'zylann::voxel::VoxelTerrainEditorPlugin::VoxelTerrainEditorPlugin(const zylann::voxel::VoxelTerrainEditorPlugin &)': cannot convert argument 1 from 'EditorNode *' to 'const zylann::voxel::VoxelTerrainEditorPlugin &'

After revert changes made in:  
"Remove EditorNode* argument from editor plugin constructors"
I can build godot again.

**Comment by Zylann** [comment]
This change was made precisely because recently Godot has removed this argument from editor plugins. So I had to remove it from mines to make it compile. Are you sure you are using the latest Godot master version? Or did they revert that change and the argument is back?

**Comment by KarloNet** [comment]
Sorry I updated from my repository not from godot..... It's working with latest godot.
