### ISSUE TITLE
Question about the Padding

### ISSUE THREAD

**Issue by tangziwen** [Zylann/godot_voxel#367]
hi~ I'm just a bit confused about this line [transvoxel.h Line 18: ]:
// How many extra voxels are needed towards the positive axes
static const int MAX_PADDING = 2;
What I don't understand is why the MAX_PADDING is set to 2, i think the padding is used for getting neighbor's chunk voxel, so maybe the MAX_PADDING equal to MIN_PADDING = 1 is enough?

**Comment by Zylann** [comment]
It is 2 because not only the neighor voxel are needed, but also their gradient. To compute the gradient of a neighbor voxel, neighbors are needed, which means it needs neighbor's neighbors, hence 2.

**Comment by tangziwen** [comment]
Thanks!!
