### ISSUE TITLE
Calling "Re-generate" at runtime / rebuild the terrain on demand

### ISSUE THREAD

**Issue by anti-matt-er** [Zylann/godot_voxel#369]
I suspect this is a simple matter and I'm just missing something obvious, what method should be called to do the same thing that "Terrain > Re-generate" does in the editor?

For context, I wish to have the terrain be randomly generated every time the game runs. I have a `VoxelTerrain` node with a `VoxelGeneratorGraph` as the generator, and my player has a `VoxelViewer`. I have looked at each of these classes, and what they inherit, in the docs and there doesn't seem to be a relevant method. I do not need LODs, so if they're relevant at all then (I assume) I'm only concerned with LOD0.

I followed said button in the source code to here:
https://github.com/Zylann/godot_voxel/blob/8d8d8b336dc099c06399e76b54f947fb1baeb021/editor/terrain/voxel_terrain_editor_plugin.cpp#L183-L186

However, I believe this `restart_stream` method isn't exposed, isn't mentioned in the docs, or I'm being blind. The docs seem to imply that Streams are mostly used for persistence (and specifically "They don't hold voxel data in memory"), so is there instead a "main"/internal Stream that I need to uhh... poke?

Also worth asking while I'm here: to generate random terrain each time I am modifying the `VoxelGeneratorGraph` using `set_node_param` with a modified copy of the Noise resource with a new random seed and then `compile`. Is this the correct approach?

**Comment by anti-matt-er** [comment]
It seems that Streams were indeed what I was missing. Assigning a `VoxelStreamBlockFiles.new()` to `VoxelTerrain` each time I run my generate method successfully recreates the terrain.

However, I do not (yet) require persistence, which seems to be the entire point of `VoxelStreamBlockFiles`. My guess is that I should instead use a `VoxelStreamScript` but I'm not sure how to implement that. If this is the correct approach: what is the bare minimum implementation of `VoxelStreamScript` to mimic the default behaviour?

**Comment by Zylann** [comment]
Streams have nothing to do with resetting or generating the terrain. You dont need a `VoxelStreamScript` either. You should not need them if you dont want persistence. The code you saw is something internal, so can be confusing.

So... you say you want the terrain to randomly generate when the game runs. It already does tho. So if you want such a function, it means your game already runs, and you want to wipe out the whole terrain to generate it again?
There is already a simple way to do that: destroy the node, and re-instance it. Or reload your scene.
`Re-Generate` doesnt go this way in the editor because there were use cases requiring it, like when prototyping a generator. But in game? Haven't had any use so far, hence why there is indeed no function exposed doing that in particular.
Is there a specific reason you want to re-generate the whole thing?

If this is really what you want, it could be exposed I guess.

**Comment by anti-matt-er** [comment]
Thanks for the swift reply!

> destroy the node, and re-instance it. Or reload your scene.

This seems obvious now. I'll try that tomorrow and get back to you.

To clarify, the terrain _wasn't_ randomly generating each time I run the game because it used the seed already present in the noise resource and modifying this in runtime didn't re-generate the terrain. Assigning a Stream seemed to "nudge" the terrain into updating, which I guess is just a side-effect. Somehow it didn't occur to me to try reloading the scene after the modification.

As for my use case: the game will have matches that take place on a small island unique to each match, therefore requiring the terrain to be generated fresh each time. Of course, knowing now that it's automatic - this would eventually not be an issue as all this stuff would happen in menus _before_ the scene is loaded, but your suggestion will work nicely for my debug method of re-generating the terrain so I can see multiple variations for quick prototyping.

**Comment by Zylann** [comment]
> To clarify, the terrain wasn't randomly generating each time I run the game because it used the seed already present in the noise resource 

You should be able to randomize its seed in `_ready`, or add the terrain from a script and set the seed before adding it to the tree? It's really not a good idea to let the terrain generate and yet wipe out the work it did just to set the seed afterward.

**Comment by anti-matt-er** [comment]
> add the terrain from a script and set the seed before adding it to the tree

Indeed, that's what I'm doing now.

> It's really not a good idea to let the terrain generate and yet wipe out the work it did just to set the seed afterward.

This wasn't my intention for the final build, I'm only rebuilding the terrain for my debug "re-generate" function so I can test multiple variations of the terrain (to do this now I'm removing the node from the Tree, re-instantiating it and adding it back to the Tree).

I can confirm this all works. Thank you very much for your help! This can be closed now if you wish.
