### ISSUE TITLE
Missing library in editor/graph/voxel_graph_node_inspector_wrapper.cpp

### ISSUE THREAD

**Issue by HUSKI3** [Zylann/godot_voxel#370]
Hello!
I noticed that there was a missing library when building for main
The error was the following
`error: no matching function for call to 'std::find(std::....`

This can be fixed by adding `#include <algorithm>` to the file.

After building with that added everything works. Just wanted to point it out in case anyone else runs into this.

Correction: main branch, not 3.x

**Comment by Zylann** [comment]
This was already fixed in 118563d5453f946a1b575794364f81b17ef7ed28

**Comment by HUSKI3** [comment]
Ah I see it now, thanks!
