### ISSUE TITLE
Blocky mesher extremely buggy whith high coordinates

### ISSUE THREAD

**Issue by TheToto** [Zylann/godot_voxel#377]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/12860648/166166468-4a4a26a2-b73e-4115-85c8-d3c048e1d523.gif)

Hello, 

The world become very unstable with with high coordinates in a blocky world.

I can reproduce it in the demo "blocky_terrain", I just add 
`translation = Vector3(5000000, 100, 5000000)`
in the ready function of the character controller.

Latest Godot 3.4
Latest godot_voxel commit on godot 3.x branch

**Comment by Zylann** [comment]
This has nothing to do with this module. Godot 3 does not support large coordinates.
In Godot 4 you can compile with double-precision support to improve stability (`float=64`) but the renderer itself is still a problem, as everything still *visually* jitters.
See https://github.com/godotengine/godot/issues/58516

**Comment by TheToto** [comment]
Oh, okay, i didn't know that. I can workaround that anyway.
Thank you
