### ISSUE TITLE
Linux build fails on HashMap.set on my local machine with latest commits (godot: 35596e6b74, voxel: a4abfc7)

### ISSUE THREAD

**Issue by duchainer** [Zylann/godot_voxel#383]
I'm using the same compilation command as[ the last commit build](https://github.com/Zylann/godot_voxel/runs/6396168745?check_suite_focus=true) though I may be using a more recent godot commit : ( 35596e6b74 origin/master Merge pull request #60569 from snailrhymer/shape-collision-description-improvements)
While the latest build was using Godot commit 516ec892b43a89ac19dfa608b9d754f630a646cc.
Though it seems like a missing dependency in that case I suppose, I'm going diner and I'll try identifying the issue more precisely. Also, I'll fix it if I can :smile:.
Thanks for your time.

```
➜  godot git:(master) ✗ scons -j4 verbose=yes warnings=all werror=yes platform=linuxbsd tools=yes tests=no target=release_debug production=yes float=32
[...]

modules/voxel/meshers/blocky/voxel_blocky_model.cpp: In function 'void zylann::voxel::bake_mesh_geometry(zylann::voxel::VoxelBlockyModel&, zylann::voxel::VoxelBlockyModel::BakedData&, bool)':
modules/voxel/meshers/blocky/voxel_blocky_model.cpp:396:32: error: 'class HashMap<int, int>' has no member named 'set'; did you mean 'get'?
  396 |       added_side_indices[side].set(src_index, next_side_index);
      |                                ^~~
      |                                get
modules/voxel/meshers/blocky/voxel_blocky_model.cpp:438:29: error: 'class HashMap<int, int>' has no member named 'set'; did you mean 'get'?
  438 |       added_regular_indices.set(src_index, next_regular_index);
      |                             ^~~
      |                             get
scons: *** [modules/voxel/meshers/blocky/voxel_blocky_model.linuxbsd.opt.tools.64.o] Error 1
scons: building terminated because of errors.
[Time elapsed: 00:00:20.861]
```

**Comment by Zylann** [comment]
Godot master keeps breaking stuff. I was about to have a look this evening but PR #382 came earlier so should fix it

**Comment by Zylann** [comment]
It has been merged now

**Comment by duchainer** [comment]
Thanks I'll retry it and see if that fixes everything.

**Comment by duchainer** [comment]
So with that change I suppose there is now a "before https://github.com/godotengine/godot/commit/8b7c7f5a753b43cec10f72b274bb1d70c253652b" and "after https://github.com/godotengine/godot/commit/8b7c7f5a753b43cec10f72b274bb1d70c253652b" coupling of the repos to keep in mind if others want to compile Godot+Voxel with one of the Godot4.alpha1 to Godot4.alpha8. 

Is there any way to signify this to a newcomer to the repo? 

I'll open another issue about that
