### ISSUE TITLE
Case where `c` can be used not initialized

### ISSUE THREAD

**Issue by MGilleronFJ** [Zylann/godot_voxel#388]
https://github.com/Zylann/godot_voxel/blob/008c38bb6be63858b484101a3b22f1d6b840599b/util/expression_parser.cpp#L75

For the sake of completion, `c` should be initialized, because in theory it can be read while non-initialized later in the function.

**Comment by Zylann** [comment]
Fixed in df25723b20aafa9808734050d2643b3c1a641e68
