### ISSUE TITLE
Invalid Function for Setter: VoxelTerrain::set_material for property: material

### ISSUE THREAD

**Issue by afonsolage** [Zylann/godot_voxel#39]
Hello folks!

After compiling godot_voxel on Ubuntu 18.04, with GCC 7.4, I got the following error on console, when starting godot:

```
Godot Engine v3.2.dev.custom_build.e14e08cfc - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GT 710/PCIe/SSE2
 
ERROR: add_property: Invalid Function for Setter: VoxelTerrain::set_material for property: material
   At: core/class_db.cpp:934.
```

Even so, the Voxel module seems to be [working fine](https://i.imgur.com/zHzkMZl.png).

**Comment by tinmanjuggernaut** [comment]
This has already been addressed in #36 and can be closed. Thanks for the report though.
