### ISSUE TITLE
Graph nodes cannot be deleted

### ISSUE THREAD

**Issue by MGilleronFJ** [Zylann/godot_voxel#391]
Something broke in the recent Godot API, I can't delete nodes in the `VoxelGeneratorGraph` editor.
It prints this error:
```
core\object\object.cpp:1131 - Error calling from signal 'delete_nodes_request' to callable: 'VoxelGraphEditor::VoxelGraphEditor::_on_graph_edit_delete_nodes_request': Method expected 0 arguments, but called with 1..
```
Likely caused by https://github.com/godotengine/godot/pull/61112

It might also break the `godot3.x` branch because it was backported.

**Comment by Zylann** [comment]
Fixed in 6ed48654f48e03831c8a29aa1c504ab07dc09983
