### ISSUE TITLE
Mesh block size 32 is broken

### ISSUE THREAD

**Issue by MGilleronFJ** [Zylann/godot_voxel#392]
Setting `mesh_block_size` to 32 in `VoxelLodTerrain` produces bad results. Probably forgot some variable to update when the size is changed. 
Workaround: default size 16 works.

![image](https://user-images.githubusercontent.com/105369548/169822959-d1785892-c582-4f84-abf8-889d50d7b53b.png)

**Comment by Zylann** [comment]
Fixed in 1cb030ede68e1f9a685557bb58c6545b272c4ec4, but see #394
