### ISSUE TITLE
Holes in geometry

### ISSUE THREAD

**Issue by MGilleronFJ** [Zylann/godot_voxel#393]
Some generator settings seem to be more likely to produce holes in geometry with `VoxelMesherTransvoxel`, here with cellular 3D noise producing very smooth, regular surfaces:
![image](https://user-images.githubusercontent.com/105369548/169824121-b7eef927-37d3-4899-8f9e-d4c49306e4ca.png)

It seems to be caused by a bug in triangulation, because technically the faces are not missing, but attached to the wrong vertices. See the other side of the hole:
![image](https://user-images.githubusercontent.com/105369548/169824343-55f7e705-66d6-4dae-9739-27386f0fdbfe.png)

Note: in this case the generator is fine, it is a meshing issue.

**Comment by Zylann** [comment]
Should be fixed in 8966ad5b1f68cb57bb51a142b4b5c61375bf5cfd
Voxel Plugin has done a similar fix.
