### ISSUE TITLE
The test project test seems wrong

### ISSUE THREAD

**Issue by poikilos** [Zylann/godot_voxel#397]
The Test Project output (See [runs](https://github.com/Zylann/godot_voxel/actions/workflows/test_project.yml) of the test) appears to have a problem related to case sensitivity:
```
  inflating: regression-test-project-3.x/project.godot  
mv: cannot stat 'RegressionTestProject-3.x': No such file or directory
```

The archive is from github.com/garmin but don't see the word "garmin" anywhere in [the .github/test_project](https://github.com/Zylann/godot_voxel/blob/master/.github/workflows/test_project.yml) so I wouldn't know where to start fixing it. Maybe the issue is in something that the test downloads before it downloads the file being inflated in the quote. The script in question expects "RegressionTestProject-3.x" but the folder is actually called "regression-test-project-3.x" so it is a case sensitivity issue.

The following branches don't have the issue:
- godot3.1
- godot3.2.3
- godot3.3

After the following branches are fixed, the issue could could be closed:
- [x] https://github.com/Zylann/godot_voxel/pull/399 (godot3.x)
- [x] https://github.com/Zylann/godot_voxel/pull/398 (master (godot4))
- [x] https://github.com/Zylann/godot_voxel/pull/402

**Comment by Zylann** [comment]
> The archive is from github.com/garmin

It's `qarmin`, with a Q

**Comment by poikilos** [comment]
Thanks, the accepted pull requests seem to cover this. If there are other branches you can reopen it and I can work on them.
