### ISSUE TITLE
do_sphere with radius=1.0 has little effect between vertices

### ISSUE THREAD

**Issue by rcorre** [Zylann/godot_voxel#404]
https://user-images.githubusercontent.com/2496231/175781039-be18a530-21a7-4b07-863a-6633df0495c2.mp4

I'm using godot 3.4 and voxel_tools ce2ae79ad4f3653ac69b23712f8bb593c67efb83 (3.x branch).

When using `do_sphere` to remove SDF terrain, setting the radius to exactly 1.0 often produces little effect on the terrain, especially when the position is between vertices. Slightly higher or lower values both produce a more significant effect.

[example.zip](https://github.com/Zylann/godot_voxel/files/8985077/example.zip)

The example project has these bindings:
1. left mouse button: do_sphere(0.9)
2. right mouse button: do_sphere(1.0)
3. middle mouse button: do_sphere(1.1)

Notice that if you right click between vertices (in the middle of a face), it barely modifies the terrain at all. Left or middle clicking the same spot will produce a noticeable effect.

**Comment by Zylann** [comment]
Should be fixed in 5c720cda667c1d9059391ba515e49e963a700ebb, and ported to godot3.x

**Comment by rcorre** [comment]
I can confirm that fixed it, thanks!
