### ISSUE TITLE
Add a way to pin the Voxel Graph Editor

### ISSUE THREAD

**Issue by rcorre** [Zylann/godot_voxel#414]
Some builtin editors in Godot, like the AnimationPlayer editor, allow you to "pin" the editor so it is always visible, even if you select a different node. It would be nice if the Voxel Graph panel could be "pinned" in the same way. When working on a graph-based world, I often switch to different nodes (especially the instancer), and it is a bit of a pain to navigate back to the graph and get it open again.

**Comment by Zylann** [comment]
*Wonders why this has to be coded in every single editor using the bottom panel container*

**Comment by Zylann** [comment]
Added in f81e64dd14f31eca6c31720f5ce4e656babd8964

**Comment by Zylann** [comment]
I got distracted and made the editor undockable too

https://user-images.githubusercontent.com/1311555/182471557-3fdddc3e-0c05-4c32-a01a-3ef3c78467fb.mp4

**Comment by rcorre** [comment]
Neat! I'm not sure if I'd ever want to undock it, but I can confirm the pinning works as expected in the latest version. Thanks!
