### ISSUE TITLE
Noise texture previews in graph editor are blank

### ISSUE THREAD

**Issue by rcorre** [Zylann/godot_voxel#415]
Godot: 8cb51a642e7c34a73e7ed877ab46c041521205e5
Voxel: 6f75baebde5e3f4906caae8da0e454bb51ef6683

When I add a `FastNoise_2D` or `FastNoise2_2D` node to the graph and open the `Noise` resource in the right panel, the preview is blank.
A preview does show up for `Noise2D`, using a `FastNoiseLite` noise resource.
![1659273233](https://user-images.githubusercontent.com/2496231/182028134-86ccf5ab-663f-49bf-9205-05b8797b7bf4.png)

**Comment by Zylann** [comment]
I fixed this locally, I'll push it soon

**Comment by Zylann** [comment]
Should be fixed by b5257f0f4810752a430d54e8cedb8b94c5663db8

**Comment by rcorre** [comment]
Fixed, thanks!
