### ISSUE TITLE
Cannot "Update from Scene" in latest voxel tools with godot4

### ISSUE THREAD

**Issue by rcorre** [Zylann/godot_voxel#417]
Godot: 8cb51a642e7c34a73e7ed877ab46c041521205e5
Voxel: https://github.com/Zylann/godot_voxel/commit/6f75baebde5e3f4906caae8da0e454bb51ef6683

I clicked on the "Item 1" label, but `get_editor_interface()->get_inspector()->get_selected_path();` just returns "library" here:

https://github.com/zylann/godot_voxel/blob/6f75baebde5e3f4906caae8da0e454bb51ef6683/editor/instance_library/voxel_instance_library_editor_plugin.cpp#L178-L180

![1659295933](https://user-images.githubusercontent.com/2496231/182042244-6bfbd2e5-c257-4ad3-a6ad-91becbe64f11.png)
![1659295921](https://user-images.githubusercontent.com/2496231/182042245-5f1f95d5-560f-4604-b51a-7a96cb7cba3f.png)

**Comment by Zylann** [comment]
This is a known issue, Godot 4 and sub-inspector dont give a way to make this work. The only workaround is to edit the library so that it is not in a sub-inspector.

**Comment by MGilleronFJ** [comment]
Tracked here https://github.com/godotengine/godot/issues/54467

**Comment by Zylann** [comment]
Since 90dbf9418ec3ca45c5c25878e225d76e38dc5639, "Update from scene" has moved to the item inspector itself, so it can work with sub-inspectors too.
But I also added a way to reference a scene directly, which will be converted to multimesh at runtime.
