### ISSUE TITLE
Building for godot 3.4 - cannot resolve constants and enums

### ISSUE THREAD

**Issue by Dunkhan** [Zylann/godot_voxel#418]
Linux Mint 20.3 Cinnamon

When attempting to build using the godot3.4 build and the 3.4 build from godot the build fails with the following errors

Generating VoxelTool.cs...
ERROR: Cannot resolve enum reference in documentation: 'VoxelBuffer.CHANNEL_SDF'.
   at: bbcode_to_xml (modules/mono/editor/bindings_generator.cpp:372)
ERROR: Cannot resolve enum reference in documentation: 'VoxelBuffer.CHANNEL_SDF'.
   at: bbcode_to_xml (modules/mono/editor/bindings_generator.cpp:372)
ERROR: Cannot resolve enum reference in documentation: 'VoxelBuffer.CHANNEL_SDF'.
   at: bbcode_to_xml (modules/mono/editor/bindings_generator.cpp:372)
ERROR: Cannot resolve enum reference in documentation: 'VoxelBuffer.CHANNEL_TYPE'.
   at: bbcode_to_xml (modules/mono/editor/bindings_generator.cpp:372)
ERROR: Cannot resolve enum reference in documentation: 'MODE_REMOVE'.
   at: bbcode_to_xml (modules/mono/editor/bindings_generator.cpp:372)

Generating WebRTCPeerConnection.cs...
ERROR: Cannot resolve constant reference in documentation: 'OK'.
   at: bbcode_to_xml (modules/mono/editor/bindings_generator.cpp:461)
ERROR: Cannot resolve constant reference in documentation: 'OK'.
   at: bbcode_to_xml (modules/mono/editor/bindings_generator.cpp:461)

Generating File.cs...
ERROR: Cannot resolve constant reference in documentation: 'PROPERTY_USAGE_STORAGE'.
   at: bbcode_to_xml (modules/mono/editor/bindings_generator.cpp:461)

Generating Mutex.cs...
ERROR: Cannot resolve constant reference in documentation: 'OK'.
   at: bbcode_to_xml (modules/mono/editor/bindings_generator.cpp:461)
ERROR: Cannot resolve constant reference in documentation: 'ERR_BUSY'.
   at: bbcode_to_xml (modules/mono/editor/bindings_generator.cpp:461)
ERROR: Cannot resolve constant reference in documentation: 'OK'.
   at: bbcode_to_xml (modules/mono/editor/bindings_generator.cpp:461)

Generating Semaphore.cs...
ERROR: Cannot resolve constant reference in documentation: 'OK'.
   at: bbcode_to_xml (modules/mono/editor/bindings_generator.cpp:461)
ERROR: Cannot resolve constant reference in documentation: 'ERR_BUSY'.
   at: bbcode_to_xml (modules/mono/editor/bindings_generator.cpp:461)
ERROR: Cannot resolve constant reference in documentation: 'OK'.
   at: bbcode_to_xml (modules/mono/editor/bindings_generator.cpp:461)
ERROR: Cannot resolve constant reference in documentation: 'ERR_BUSY'.
   at: bbcode_to_xml (modules/mono/editor/bindings_generator.cpp:461)

Generating Thread.cs...
ERROR: Cannot resolve constant reference in documentation: 'OK'.
   at: bbcode_to_xml (modules/mono/editor/bindings_generator.cpp:461)
ERROR: Cannot resolve constant reference in documentation: 'ERR_CANT_CREATE'.
   at: bbcode_to_xml (modules/mono/editor/bindings_generator.cpp:461)

The resulting build runs and has the version 'v3.4.5.rc.mono.custom_build[code]' but it does not have the voxel module.

I understand this might be because I did something wrong but I have no idea what it could be  so any support would be appreciated. I also failed to build with voxel build godot4 and godot master but I assumed that was because master is unstable.

**Comment by Zylann** [comment]
I have no idea what is up with Godot 3.4 either. I assume that's because you are trying to do a Mono build? Such builds have always been a nightmare to get right...
Note that some of the errors you listed don't even come from this module.

**Comment by Dunkhan** [comment]
I was able to build it without the voxel module present. But after a few tries I managed to get this working with it present too. I guess sometimes it takes a couple of goes.
