### ISSUE TITLE
Development setup of module

### ISSUE THREAD

**Issue by afonsolage** [Zylann/godot_voxel#42]
Hello folks!

I want to add a lighting system like Minecraft has, that uses a baked lighting value (0-15), has sun lighting and artifical lighting and uses flood-fill to spread it around. 

But my question is: How do you guys develop it on godot? I saw [this guide](https://docs.godotengine.org/en/3.1/development/cpp/custom_modules_in_cpp.html#improving-the-build-system-for-development) on official docs, but just wondering if that's the way or if there is another.

I'm using VSCode on Ubuntu 18.04

Thanks!

**Comment by tinmanjuggernaut** [comment]
Hi. Yes and the docs I wrote (in /doc) are the right information. You already have voxel compiled into godot. All the code for this module is in godot/modules/voxel.

You should be aware of the PR workflow:
https://docs.godotengine.org/en/latest/community/contributing/pr_workflow.html#doc-pr-workflow

You basically fork Zylann's repository on github, download and build your fork, make a local branch, make changes, submit changes to your branch on your repository, then github gives you the option to submit a PR to Zylann's master branch. He can look at it and approve or comment. This is the same process for working on the engine itself.

**Comment by afonsolage** [comment]
@tinmanjuggernaut Thanks for the info, but I mean how to run godot_voxel while developing, because I don't think it's pratical to recompile godot every time I made some change on module, so I think there can be some way to fast apply my changes while developing, o even so debug.

Sorry if I didn't asked the right question.

**Comment by tinmanjuggernaut** [comment]
No, that's the way it's done. As a module, you must recompile every time and close and reopen godot. You can run a project from the godot command line, so you can setup scripts to get your project or debugger open faster.

Also some things can be developed in godot gdscript, to build the logic first, then be ported to C++.

GDNative allows you to leave godot open and it just reloads the plugin, but VT is not a GDNative plugin. GDNative is a little clunky currently, so maybe one day VT will be ported over.

**Comment by tinmanjuggernaut** [comment]
Also, your compiles should be pretty quick. If your scons cache is setup properly, scons will only recompile the few files you changed.

**Comment by afonsolage** [comment]
It was a way better than I tought! Thanks. I've managed to add a custom build task on vscode with the following on tasks.json:

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Run godot",
            "type": "shell",
            "command": "cd ../../ && scons -j8 platform=x11 voxel_shared=yes && bin/godot.x11.tools.64 --path ~/projects/godot/another_project/ Spatial.tscn",
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

Now I just need to press CTRL + SHIFT + B and it'll build and run my custom game with the fresh voxel module. The whole build process take around 10s, so it's fine for me.
