### ISSUE TITLE
Voxel tools fails to build with set_shader_param

### ISSUE THREAD

**Issue by kilon** [Zylann/godot_voxel#421]
I just got the latest build from github godot, for godot 4, it seems a rename of a method forces voxel tools to fail to build with godot 4 latest source code , I am on linux Manjaro . I attach the error 

-----

modules/voxel/terrain/variable_lod/voxel_mesh_block_vlt.cpp: In member function 'void zylann::voxel::VoxelMeshBlockVLT::set_shader_material(Ref<ShaderMaterial>)':
modules/voxel/terrain/variable_lod/voxel_mesh_block_vlt.cpp:153:35: error: 'class ShaderMaterial' has no member named 'set_shader_param'; did you mean 'get_shader_rid'?
  153 |                 _shader_material->set_shader_param(VoxelStringNames::get_singleton().u_block_local_transform, local_transform);
      |                                   ^~~~~~~~~~~~~~~~
      |                                   get_shader_rid
modules/voxel/terrain/variable_lod/voxel_mesh_block_vlt.cpp: In member function 'void zylann::voxel::VoxelMeshBlockVLT::set_transition_mask(uint8_t)':
modules/voxel/terrain/variable_lod/voxel_mesh_block_vlt.cpp:190:35: error: 'class ShaderMaterial' has no member named 'set_shader_param'; did you mean 'get_shader_rid'?
  190 |                 _shader_material->set_shader_param(VoxelStringNames::get_singleton().u_transition_mask, tm);
      |                                   ^~~~~~~~~~~~~~~~
      |                                   get_shader_rid
modules/voxel/terrain/variable_lod/voxel_mesh_block_vlt.cpp: In member function 'bool zylann::voxel::VoxelMeshBlockVLT::update_fading(float)':
modules/voxel/terrain/variable_lod/voxel_mesh_block_vlt.cpp:289:35: error: 'class ShaderMaterial' has no member named 'set_shader_param'; did you mean 'get_shader_rid'?
  289 |                 _shader_material->set_shader_param(VoxelStringNames::get_singleton().u_lod_fade, p);
      |                                   ^~~~~~~~~~~~~~~~
      |                                   get_shader_rid
modules/voxel/util/godot/direct_mesh_instance.cpp: In member function 'void zylann::DirectMeshInstance::set_shader_instance_uniform(StringName, Variant)':
modules/voxel/util/godot/direct_mesh_instance.cpp:100:12: error: 'class RenderingServer' has no member named 'instance_geometry_set_shader_parameter'; did you mean 'instance_geometry_set_shader_uniform'?
  100 |         vs.instance_geometry_set_shader_parameter(_mesh_instance, key, value);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |            instance_geometry_set_shader_uniform
scons: *** [modules/voxel/terrain/variable_lod/voxel_mesh_block_vlt.linuxbsd.opt.tools.64.o] Error 1
scons: *** [modules/voxel/util/godot/direct_mesh_instance.linuxbsd.opt.tools.64.o] Error 1
modules/voxel/terrain/variable_lod/voxel_lod_terrain.cpp: In function 'Ref<ShaderMaterial> zylann::voxel::{anonymous}::allocate_shader_material(std::vector<Ref<ShaderMaterial> >&, const Ref<ShaderMaterial>&, unsigned int)':
modules/voxel/terrain/variable_lod/voxel_lod_terrain.cpp:45:21: error: 'class ShaderMaterial' has no member named 'set_shader_param'; did you mean 'get_shader_rid'?
   45 |                 sm->set_shader_param(VoxelStringNames::get_singleton().u_transition_mask, transition_mask);
      |                     ^~~~~~~~~~~~~~~~
      |                     get_shader_rid
modules/voxel/terrain/variable_lod/voxel_lod_terrain.cpp:46:21: error: 'class ShaderMaterial' has no member named 'set_shader_param'; did you mean 'get_shader_rid'?
   46 |                 sm->set_shader_param(VoxelStringNames::get_singleton().u_lod_fade, Vector2(0.0, 0.0));
      |                     ^~~~~~~~~~~~~~~~
      |                     get_shader_rid
modules/voxel/terrain/variable_lod/voxel_lod_terrain.cpp: In member function 'void zylann::voxel::VoxelLodTerrain::set_mesh_block_active(zylann::voxel::VoxelMeshBlockVLT&, bool, bool)':
modules/voxel/terrain/variable_lod/voxel_lod_terrain.cpp:469:38: error: 'class ShaderMaterial' has no member named 'set_shader_param'; did you mean 'get_shader_rid'?
  469 |                                 mat->set_shader_param(VoxelStringNames::get_singleton().u_lod_fade, Vector2(0.0, 0.0));
      |                                      ^~~~~~~~~~~~~~~~
      |                                      get_shader_rid
modules/voxel/terrain/variable_lod/voxel_lod_terrain.cpp:478:38: error: 'class ShaderMaterial' has no member named 'set_shader_param'; did you mean 'get_shader_rid'?
  478 |                                 mat->set_shader_param(VoxelStringNames::get_singleton().u_lod_fade, Vector2(0.0, 0.0));
      |                                      ^~~~~~~~~~~~~~~~
      |                                      get_shader_rid
modules/voxel/terrain/variable_lod/voxel_lod_terrain.cpp: In function 'void zylann::voxel::copy_shader_params(const ShaderMaterial&, ShaderMaterial&)':
modules/voxel/terrain/variable_lod/voxel_lod_terrain.cpp:1309:43: error: 'class RenderingServer' has no member named 'shader_get_param_list'; did you mean 'shader_set_path_hint'?
 1309 |         RenderingServer::get_singleton()->shader_get_param_list(shader->get_rid(), &properties);
      |                                           ^~~~~~~~~~~~~~~~~~~~~
      |                                           shader_set_path_hint
modules/voxel/terrain/variable_lod/voxel_lod_terrain.cpp:1311:21: error: 'class ShaderMaterial' has no member named 'set_shader_param'; did you mean 'get_shader_rid'?
 1311 |                 dst.set_shader_param(property.name, src.get_shader_param(property.name));
      |                     ^~~~~~~~~~~~~~~~
      |                     get_shader_rid
modules/voxel/terrain/variable_lod/voxel_lod_terrain.cpp:1311:57: error: 'const class ShaderMaterial' has no member named 'get_shader_param'; did you mean 'get_shader_rid'?
 1311 |                 dst.set_shader_param(property.name, src.get_shader_param(property.name));
      |                                                         ^~~~~~~~~~~~~~~~
      |                                                         get_shader_rid
modules/voxel/terrain/variable_lod/voxel_lod_terrain.cpp: In member function 'void zylann::voxel::VoxelLodTerrain::process_fading_blocks(float)':
modules/voxel/terrain/variable_lod/voxel_lod_terrain.cpp:1886:55: error: 'class ShaderMaterial' has no member named 'set_shader_param'; did you mean 'get_shader_rid'?
 1886 |                                 item.shader_material->set_shader_param(
      |                                                       ^~~~~~~~~~~~~~~~
      |                                                       get_shader_rid
scons: *** [modules/voxel/terrain/variable_lod/voxel_lod_terrain.linuxbsd.opt.tools.64.o] Error 1
scons: building terminated because of errors.
[Time elapsed: 00:01:32.330]

----

From the looks of it , it seems that godot devs have renamed get and set_shader_param to get_shader_rid. I dont know if this is related with the latest addition of unique identifiers for nodes in general.

**Comment by Zylann** [comment]
They renamed `shader_param` occurrences to `shader_uniform`.
I pushed a fix in a9752362cdf6bae92ab598ceb39e9a03c602defb
