### ISSUE TITLE
Add on docs to enable vertex color in order to enable AO

### ISSUE THREAD

**Issue by afonsolage** [Zylann/godot_voxel#43]
Hello folks!

Maybe I missed something, but I discovered by reading the source that we got a nice Ambient Occlusion if we just enable Vertex Color (Use as Albedo) on Material. When I first read the getting started, this wasn't obvious for me, so I think this should have a better emphasis on docs.

Thanks!

**Comment by tinmanjuggernaut** [comment]
Do you want to contribute to the docs? 
I wrote the docs, but I've never used the AO. It's mentioned but only because Zylann wrote it in his notes to me. I don't actually know how to use it.

**Comment by afonsolage** [comment]
Here is it: #44, hope I did it right
