### ISSUE TITLE
Live update does not update when adding a second connection for a connected node

### ISSUE THREAD

**Issue by rcorre** [Zylann/godot_voxel#430]
![1660648950](https://user-images.githubusercontent.com/2496231/184868092-424e7fff-be81-4081-9ded-22175d556778.png)

If you connect `FastNoise2D` to `Multiply` with `live update` enabled, the terrain will not update. I suspect the graph hash is not changing?

**Comment by MGilleronFJ** [comment]
Connections are not hashed, I think connected inputs should be part of the hash using the ancestor node ID and port index

**Comment by Zylann** [comment]
Should be fixed in 7101233ce65455dc90e6af4351bc3c8b23a5264d

**Comment by rcorre** [comment]
Seems fixed, thanks!
