### ISSUE TITLE
Missing Enums from Generated API Bindings

### ISSUE THREAD

**Issue by MadMartian** [Zylann/godot_voxel#432]
We recently migrated to Godot v4 and I'm noticing there are some missing (not all, some) enums from the generated API bindings.  This may be a bug with the Godot repository itself, but I wanted to report the finding here first.  When compiling against a _GDExtension_ project:

```
.../gen/include/godot_cpp/classes/voxel_node.hpp:60:19: error: ‘godot::VoxelNode::GIMode’ has not been declared
```

**Godot Repository** is at _11abffbf "Merge pull request #64215 from Calinou/editor-allow-numpad-zoom-shortcuts"_
**Godot-CPP Repository** is at _f4542530 "Merge pull request #814 from YuriSizov/object-expose-property-revert"_
**Zylann / godot_voxel** is at _84494497 "Support setting a scene on multimesh instance items which is converted at runtime"_

The generated `extension_api.json` is indeed missing the enum for the `VoxelNode` class.  Other classes such as `VoxelLodTerrain` appear to have their nested enums declared in the corresponding generated API class, so the API bindings generator _appears_ to be cherry-picking enums to generate for some strange reason.

**Comment by MGilleronFJ** [comment]
What's special about this class? It very well seems like a big from the Godot API generator.

**Comment by MGilleronFJ** [comment]
Actually that's an issue with the class registration. The property is registered with an enum hint here https://github.com/Zylann/godot_voxel/blob/90dbf9418ec3ca45c5c25878e225d76e38dc5639/terrain/voxel_node.cpp#L183
But the enum constants are not bound. So the inspector works but not the API.

**Comment by Zylann** [comment]
Should be fixed in f5b54defab4d9249608af7bfb3797fc14864c968

**Comment by MadMartian** [comment]
Ok I've updated to include that commit, but now I'm getting a different error:

```
.../godot-cpp/gen/include/godot_cpp/classes/voxel_modifier.hpp:49:21: error: ‘godot::VoxelModifier::Operation’ has not been declared
   49 |  void set_operation(VoxelModifier::Operation op);
      |                     ^~~~~~~~~~~~~
```

The `extension_api.json` doesn't appear to declare it either.

**Comment by Zylann** [comment]
Same issue here, fixed in e7ab73e9d9993db6529c60c1154ba37b6a2be2a9

**Comment by Zylann** [comment]
Is it working now?

**Comment by Zylann** [comment]
Going to close, you can open a new issue if some stuff is still missing.
