### ISSUE TITLE
Transvoxel gaps between lod levels in godot 4

### ISSUE THREAD

**Issue by Deins** [Zylann/godot_voxel#440]
Build: https://github.com/Zylann/godot_voxel/actions/runs/3028543632
When using VoxelLodTerrain node with Transvoxel mesher more often than not there are visible gaps between lod levels. I tested it with default material (no material applied) or custom material with vertex shader  sample code from docs. 
![image](https://user-images.githubusercontent.com/8919956/189547333-7347dacc-f720-40ce-a82d-0a9a84d6b67f.png)
![image](https://user-images.githubusercontent.com/8919956/189547217-9d6872c5-dfd5-4f6e-924f-b881d6b60709.png)

When using no stitching most common gaps dissapear, but still there were some holes (like in first screenshot). 
Is this known bug or am I missing something and different shader has to be used for godot-4?

**Comment by Zylann** [comment]
Transvoxel requires a shader to properly render seams. The engine should use a default shader supporting this if you specify no material, or if you use the shader from the demo project.
![image](https://user-images.githubusercontent.com/1311555/189550561-00a15e97-cb00-4ff4-9422-b2f29526b005.png)

**Comment by Deins** [comment]
Thanks for taking a look. I checked the demo project (https://github.com/Zylann/voxelgame/tree/godot4/project/smooth_terrain) and with default setup it I didn't see any issues (other than out of scope, godot not importing/linking textures to the material). But when I switched the generator to flatgaps: 
![image](https://user-images.githubusercontent.com/8919956/189554398-d9acf3f6-d412-43b7-8f4f-721e4ae4fb10.png)
I guess it only happens flat or axis aligned surfaces.

**Comment by Zylann** [comment]
Not seeing any gap with flat terrain either
![image](https://user-images.githubusercontent.com/1311555/189555322-664eaa43-a2d1-42b2-a2b9-9ca68d3ec76c.png)

**Comment by Zylann** [comment]
I still haven't seen any gaps of that size on flat terrains, but I noticed sometimes transition meshes are not enabling when they should. It seems to be a bit random.

**Comment by MGilleronFJ** [comment]
Is it still happening? If so, can you provide a test project reproducing it?

**Comment by Deins** [comment]
Sorry for delay, didn't have time to look at it. But I tested it again with latest release https://github.com/Zylann/godot_voxel/actions/runs/3123916598 and its still happens.
![image](https://user-images.githubusercontent.com/8919956/192352590-c1bb8dbd-af2a-4450-adc1-4c77bb0961e7.png)

I don't think test scene will give you anything for me its easy to reproduce: 
* Create new project and new scene
* Add VoxelLod node
* Set generator to flat. no gaps yet
* Enable follow camera toggle and bam, gaps appear at lod seams.  Follow camera can be disabled to take closer look at gaps.

Have tested  on 2 windows machines one with Intel HD and one with AMD gpu and both times gaps appeared. 
What I have found out is that the gaps  mostly (not sure if only) appear on horizontal or vertical planes when X=0 or Y=0 or Z=0.  When offsetting the plane only by 0.1 the gaps don't appear. 

It seems that the shader code that offsets the vertices pulls away and creates holes there. But interestingly at the points where octree nodes cross there are no holes:
![image](https://user-images.githubusercontent.com/8919956/192354914-d79944ae-b498-4f79-b5e8-e9688b5de2be.png)

I would suspect that maybe there some is math error that happens when x=0 or y=0 or z=0 but I haven't had time to dig into the implementation details.

*Current workaround:* disabling any vertex offset in the shader  other than the culling seems to produce good results. I am not sure what is the purpose of moving seam vertices around. However during short  testing I didn't discover any gaps without them yet.

**Comment by Zylann** [comment]
The holes you see correspond to where transition meshes are supposed to be, which is why I suspect a shader issue.

**Comment by Zylann** [comment]
I reproduced it, but I don't know how this can be avoided yet. It's one of those embarrassingly annoying edge cases that are usually not present in typical use cases...

**Comment by Zylann** [comment]
I just tweaked transition meshing code in dc9f1a7de0c3003f8a2adf5ecd5d231418db0ccf, and it seems to solve that specific case.

**Comment by Deins** [comment]
Awesome, seems that fixed it  🥳
Great work.
