### ISSUE TITLE
Linux build size 

### ISSUE THREAD

**Issue by jomiq** [Zylann/godot_voxel#441]
Between commits [fix GCC warning](https://github.com/Zylann/godot_voxel/tree/625e4536f12579b1c757afa275e19bded2ad9d72) and  [use_lto](https://github.com/Zylann/godot_voxel/tree/d421028a7d3742bfae48239af9280f5d16f5e619) the linux build size changed from ~140 MB to 1.6 GB. This is unexpected.

**Comment by Zireael07** [comment]
Godot itself had a similar issue with use_lto

**Comment by jomiq** [comment]
Ok.

**Comment by MGilleronFJ** [comment]
I have no clue what happened here, but if you know, I'd like to know what I have to change (if anything). But very likely this is something Godot devs changed in the build system?

**Comment by Zireael07** [comment]
Why did you close? This is a valid issue, I was just pointing out this is not unique to this and that use_lto itself is likely the culprit somehow

**Comment by jomiq** [comment]
> Why did you close? This is a valid issue, I was just pointing out this is not unique to this and that use_lto itself is likely the culprit somehow
> 
> EDIT: ninja'd

Sorry, I got fat fingers

**Comment by Zylann** [comment]
Linux build size is back to 135 Mb.
