### ISSUE TITLE
github action builds cannot run on ubuntu 18

### ISSUE THREAD

**Issue by skaiware** [Zylann/godot_voxel#444]
The artifacts build generated by github actions:
https://github.com/Zylann/godot_voxel/actions/workflows/linux.yml
cannot run on ubunut18:
```
~/godot $ ./godot.linuxbsd.opt.tools.x86_64 
./godot.linuxbsd.opt.tools.x86_64: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./godot.linuxbsd.opt.tools.x86_64)
./godot.linuxbsd.opt.tools.x86_64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./godot.linuxbsd.opt.tools.x86_64)
~/godot $ ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1.6) 2.27

```
It s because the yml builds on ubuntu20:
https://github.com/Zylann/godot_voxel/blob/57abd5c90c7c64d3e2620b79cebbc62ca90bc9bd/.github/workflows/linux.yml#L15

The official godot 4 b1 build
https://downloads.tuxfamily.org/godotengine/4.0/beta1/
correctly runs:
```
$ ./Godot_v4.0-beta1_linux.x86_64 
Godot Engine v4.0.beta1.official.20d667284 - https://godotengine.org
...
```
Would you mind if we switch the linux.yml to use ubunut18 ?
kind

**Comment by Zylann** [comment]
That doesnt make any sense. Why would Godot being built on Ubuntu 20 prevent it from running on past Ubuntu versions? Or even non-Ubuntu distros?
Also the Godot repository is using Ubuntu 20.04 too https://github.com/godotengine/godot/blob/f74491fdee9bc2d68668137fbacd8f3a7e7e8df7/.github/workflows/linux_builds.yml#L18

**Comment by Calinou** [comment]
The way Linux binary compatibility works requires you to use an old enough Linux distribution. Typically, the oldest still-supported Ubuntu LTS is a good baseline (Ubuntu 18.04 as of writing). This however limits which compiler versions you can use.

That said, Godot provides [build containers](https://github.com/godotengine/build-containers) you can use which allow you to use a recent compiler *and* still target old distributions.

**Comment by Zylann** [comment]
Akien suggests to use this on the CI, so an old glibc can be used with a recent toolchain https://github.com/godotengine/buildroot/

**Comment by skaiware** [comment]
> Why would Godot being built on Ubuntu 20 prevent it from running on past Ubuntu versions?
long story/short story: most linux binaries relies on the basic glibc: if an exec has been linked/expects/uses newer libc then it cannot run if the os only provide an older libc :
https://www.gnu.org/software/libc/libc.html
https://en.wikipedia.org/wiki/Glibc

> And what about non-Ubuntu distros?
Usually alright as long as the binary is not linked with a too recent glibc.

> Also the Godot repository is using Ubuntu 20.04
Yes and these bins dont run neither on ubuntu 18:
~/godot $ ./godot.linuxbsd.master.opt.x86_64 
./godot.linuxbsd.master.opt.x86_64: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./godot.linuxbsd.master.opt.x86_64)
./godot.linuxbsd.master.opt.x86_64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./godot.linuxbsd.master.opt.x86_64)
But their release builds do work on ubunut18  because are certainly built on an older OS or different linker.

>Maybe it's not the distro, but rather you need to update your libs or something?
Not really possible : glibc is the very core of Linux (unless using unofficial/hacky OS builds). Latest ubuntu 18 is 'made with' libc 2.27.
  
> I'm not sure I can define a workflow for every single Linux distro
As explained, you dont have to, just setting the github action to use a slightly older OS (eg ubunut18) will generate a binary capable to run on a very large range of linuxes (ubuntu or not).
  
kind

**Comment by skaiware** [comment]
> The way Linux binary compatibility works requires you to use an old enough Linux distribution to compile C/C++ programs you intend to distribute. Typically, the oldest still-supported Ubuntu LTS is a good baseline (Ubuntu 18.04 as of writing). This however limits which compiler versions you can use.
> 
> That said, Godot provides [build containers](https://github.com/godotengine/build-containers) you can use which allow you to use a recent compiler _and_ still target old distributions.

https://github.com/godotengine/build-containers#toolchains
"Linux: GCC 10.2.0 built against glibc 2.19"

**Comment by Zylann** [comment]
I'm trying to use the buildroot used for official builds, but it's not working, I thought it came with `scons` built-in but it's not found for some reason https://github.com/Zylann/godot_voxel/actions/runs/3119371172/jobs/5059291216

**Comment by skaiware** [comment]
Cool. Using the same linux from the godot team is even better.
According to the "setup buildroot" log, scons is in 
12681 x86_64-godot-linux-gnu_sdk-buildroot/bin/scons
https://github.com/Zylann/godot_voxel/actions/runs/3119371172/jobs/5059291216#step:2:12682

**Comment by Zylann** [comment]
Problem is, I added this `bin` folder to the path right here https://github.com/Zylann/godot_voxel/blob/71068b0acfb72b7d146279633ccb77ed632d8871/.github/workflows/linux.yml#L113

**Comment by Zylann** [comment]
Turns out the `checkout` step persistently changes the working directory when not provided a path, so the buildroot ended up in the wrong folder...

Now the build starts, but quickly fails: https://github.com/Zylann/godot_voxel/actions

**Comment by skaiware** [comment]
hum, I see pkgconfig in the bin subfolder so it could it be possible to call it just before calling scons in order to generate dbus-arch-deps.h on the fly locally ?

**Comment by Zylann** [comment]
I thought Godot build scripts already did that though https://github.com/godotengine/buildroot/issues/6#issue-1231467424

**Comment by Zylann** [comment]
Applied a workaround, the build should work now.

**Comment by Zylann** [comment]
@skaiware is it working now?

**Comment by skaiware** [comment]
@Zylann 
just retried and it now works:
```
godot $ ./godot.linuxbsd.editor.x86_64 
Godot Engine v4.0.beta.custom_build.e69b7083d - https://godotengine.org
```
congrats and tks
