### ISSUE TITLE
VoxelGeneratorImage option not working.

### ISSUE THREAD

**Issue by ravennst** [Zylann/godot_voxel#446]
Master branch. I'm attempting to generate terrain in a VoxelTerrain node using a greyscale bitmap but I'm getting nothing. None of the channels seem to work. Is there a size limitation to the image used? A particular format?
![HM scaled](https://user-images.githubusercontent.com/49933013/194654634-1d81c723-389f-4964-b441-041ad1aaaf59.png)

**Comment by Zylann** [comment]
![image](https://user-images.githubusercontent.com/1311555/194674925-12bd522d-920c-449a-85a8-bd8a33a6f3db.png)

Works here.
It depends what kind of mesher you are using, if you want smooth terrain you need `SDF` channel. If you want blocky, you need `Type` and the library on `VoxelMesherBlocky` must have an empty model for type 0 and a solid model for type 1.

**Comment by Zylann** [comment]
Is it still a problem?

**Comment by ravennst** [comment]
No. I got it to work. I didn't know that I need to hit "Re-generate". Once I did that it showed up.
As for the height map, the app I'm using to generate the terrain can't export height maps except in plain text or PNG greyscale. I plan to write a converter to create the proper format. I'm going to have to look up the format for EXR now. :)
