### ISSUE TITLE
something is crashing godot - i think its graph generator

### ISSUE THREAD

**Issue by BaddRadish** [Zylann/godot_voxel#448]
crash, possibly due to output mismatch?

steps to reproduce:

1. downloaded "godot.linuxbsd.editor.x86_64" from this action: "Merge pull request #447 from aaronfranke/misc-fix 🐧 Linux Builds #620" https://github.com/Zylann/godot_voxel/actions/runs/3214980099
2. new blank project
3. add other node, chose Voxel Terrain
4. selected the graph generator
5. selected the blocky mesher
6. voxel count 2
7. index 1: voxel blocky model, geometry is provided cube option, no other changes
8. back to the graph
9. click on output sdf node

crash.

**Comment by Zylann** [comment]
This is not caused by the graph, it's caused by the fact you didn't assign a model at index 0 of the blocky voxel library.
It might cause errors, but it shouldn't crash. Will fix this in a moment.

**Comment by BaddRadish** [comment]
ah here i misunderstood and thought no model at index 0 was for air. it might be worth defaulting to that or something?

**Comment by Zylann** [comment]
Empty entries should probably just be considered air.

**Comment by BaddRadish** [comment]
i dunno might cause bugs that way when people forget to add something and the engine just assumes they meant air. maybe have a built in air option to clarify instead?

**Comment by Zylann** [comment]
If entries are empty, it could add a warning on the node. No need to add more options.

**Comment by Zylann** [comment]
Should be fixed by 2f3d4a7aaa0c7d9f47c21c6d9934992eae2e33ed

**Comment by BaddRadish** [comment]
fixed! <3
