### ISSUE TITLE
feature request: comments in the graph editor

### ISSUE THREAD

**Issue by BaddRadish** [Zylann/godot_voxel#449]
could we get some way for us to add some form of text into the graph generator's editor? then we could do things like label noise maps as "caves" or "heightmap" or "biome". like in the quick start guide. maybe file it under the "debug" section or something.

**Comment by Zylann** [comment]
You can give names to nodes, but there is no "comment" nodes available currently.

**Comment by Zylann** [comment]
Added in 56511b33d7187543dadce126df4181f8506ebe57
