### ISSUE TITLE
Help understanding main blocky flow

### ISSUE THREAD

**Issue by afonsolage** [Zylann/godot_voxel#45]
Hello folks!

I'm trying to master the blocky creating flow, because I'll need to add some extra work on it in order to add light data. I think I've understand in general lines how it works, so to check I've build the following image (sorry for not following none UML). Can someone help me to check if is that so?

![image](https://user-images.githubusercontent.com/1176452/62838529-ef9f1b00-bc53-11e9-839f-ef392f09b4cb.png)

- There are three threads: The main thread and two processor threads, one for the loader and another for updater (mesh);
- First the `VoxelTerrain` calculate the current bounds of the viewer, then it separates into two bounds, the new bounds and the old bounds;
- For the old bounds, just do the immediate unload of the blocks that are on it;
- For the new bounds, request the load. By request I mean call `VoxelDataLoader::push`;
- At this point, we have loaded and unloaded the necessary blocks, we just need to handle our responses;
- Get block load responses using the `VoxelDataLoader::pop` and update the block stats to `BLOCK_UPDATE_NOT_SENT`;
- If the block isn't empty, request update mesh by sending a request to `VoxelMeshUpdater::push` and set block stats to `BLOCK_UPDATE_SEND`;
- Last, but not least, get mesh update responses and update meshes;

What you guys think?

**Comment by Zylann** [comment]
That's close to what happens :)
It could also help understand the LOD version, which only has a few more steps in visibility detection, the rest is just the same with different inputs and actual use of the `lod` parameter.
Also, not sure if it's worth mentionning but the mesh updater can run more than one thread (in fact I think it defaults to 2 for the LOD version, I left it to 1 for the other one, not sure why but it should be configurable in the future).
