### ISSUE TITLE
dual monitor bug?

### ISSUE THREAD

**Issue by BaddRadish** [Zylann/godot_voxel#450]
just set up my second monitor for debugging, and found a weird bug. i believe this might be a problem specifically with the way linux mint fakes dual monitors (by extending the desktop, apparently). but other aspects of godot dont seem to have this problem so it might be fixable. and linux mint is a pretty popular linux option so it might be worth investing some effort. then again, maybe not!

the bug:
with my main monitor on the right, and godot opened on the main monitor, when i right click to add a graph node, the context menu appears not where the cursor is but all the way to the left of my main monitor. when i move godot to the secondary/left monitor and right click, the context menu appears to the left of where it should be. based on poking around im pretty sure its using % of both monitors for cursor location, but then % of only the left monitor for placement of the context menu.

only the graph editor has this problem, not any other right clicking in godot that i could find after some basic testing.

i can add a video if that will help.

**Comment by Zylann** [comment]
There was a difference in the way I positionned it. I changed it to use the same logice as the file system dock, should be fixed in 62532779b546d7bcccb7fe4f3f3a944842e1d204

**Comment by BaddRadish** [comment]
hooray! i'll check to see if its fixed and close it if it is :)

**Comment by BaddRadish** [comment]
fixed!
