### ISSUE TITLE
VoxelGeneratorScript resource quality of life request

### ISSUE THREAD

**Issue by BaddRadish** [Zylann/godot_voxel#452]
the VoxelGeneratorScript type cant directly take a script. theres no exported script box or anything.
![no script field](https://user-images.githubusercontent.com/100538916/196006573-34aa0c49-8cd0-496d-a677-f8deb9c9da27.png)
as it stands now, you have to save the resource, only then can you add a script to it.
![middle man](https://user-images.githubusercontent.com/100538916/196006719-e45049f8-982a-4aa6-b9d1-7829b63aa2d6.png)
ideally this could be doable without the middle man.

i'd consider this a low priority problem unless its a trivial fix.

**Comment by Zylann** [comment]
This has nothing to do with the module, I can't just expose that. It's a Godot problem I think.

Actually, I believe it's a limitation of the sub-inspector "mode" you have on your first screenshot. You can edit the object in a standalone way without having to save it. Right-click on `VoxelGeneratorScript`, and choose `Edit`.

**Comment by BaddRadish** [comment]
ah sorry im still new to godot i dont quite understand how all this stuff comes together and this is the only time ive encountered this problem. great solution thanks!
