### ISSUE TITLE
comment nodes are not saving correctly - easy fix?

### ISSUE THREAD

**Issue by BaddRadish** [Zylann/godot_voxel#453]
the lower right corner of comment boxes are not being saved / are resetting on project close and reopen.
this picture is after reloading the project:
![comment boxes not sticking](https://user-images.githubusercontent.com/100538916/196053298-5569f40c-2993-4d8f-b2b8-0a48319ac70f.png)

also, it might be nice if the lower right corner also snapped to the grid. but this might not be everyone's preference.

**Comment by Zylann** [comment]
Should be fixed in c9d98801145fd0a4475601cefadeeaae9a53cae7, but it's not in the main branch yet.

**Comment by Zylann** [comment]
The fix is now in the main branch.

**Comment by Zylann** [comment]
Will close this as fixed, however starting from Godot 4.2 dev https://github.com/godotengine/godot/pull/79307 comments are no longer supported in the GraphEdit API, therefore comments might no longer show up properly. Will need another issue to track this.
