### ISSUE TITLE
Voxel Generator Script works In game but not in editor

### ISSUE THREAD

**Issue by VynDragon** [Zylann/godot_voxel#455]
Using latest Build from github for godot 4

Simple VoxelGeneratorScript:
```extends VoxelGeneratorScript

class_name WordGen_VoxelTerrain

@export var sphereRadius: float
var sphereRadius_transitionThickness: float

const channel : int = VoxelBuffer.CHANNEL_SDF

#in SDF channel, set voxel takes float, -1 is solid, 1 is air


func _get_used_channels_mask() -> int:
	return 1 << channel

func _generate_block(buffer : VoxelBuffer, origin : Vector3i, lod : int):
	self.sphereRadius_transitionThickness = sphereRadius / 2.0

	var do = sqrt(origin.y*origin.y+origin.x*origin.x+origin.z*origin.z)
	if do < self.sphereRadius - self.sphereRadius_transitionThickness:
		buffer.clear_channel_f(channel, -100.0) #set to very ground
	elif do > self.sphereRadius:
		buffer.clear_channel_f(channel, 100.0)
	else:
		for iz in buffer.get_size().z:
			var z = origin.z + (iz << lod)
			for iy in buffer.get_size().y:
				var y = origin.y + (iy << lod)
				for ix in buffer.get_size().x:
					var x = origin.x + (ix << lod)
					var d = sqrt(y*y+x*x+z*z)
					if d < self.sphereRadius - self.sphereRadius_transitionThickness:
						buffer.set_voxel_f(-1, ix, iy, iz, channel) # set to ground
					elif d > self.sphereRadius - self.sphereRadius_transitionThickness and d < self.sphereRadius:
						var trans = (d - (self.sphereRadius - self.sphereRadius_transitionThickness)) / self.sphereRadius_transitionThickness
						buffer.set_voxel_f((trans * 2 - 1), ix, iy, iz, channel) # set to air
```

Result in editor with a new VoxelLodTerrain and all default settings but generator set to Noise:
![image](https://user-images.githubusercontent.com/3176238/197120180-91400fea-9cb7-430f-af1d-2fa07fb510fc.png)

Result in editor with all default settings but generator set to custom generator:
![image](https://user-images.githubusercontent.com/3176238/197119827-739de125-d003-415a-af91-b2a4a4d5ae88.png)

Result in build:
![image](https://user-images.githubusercontent.com/3176238/197119905-cfec2e2d-c16d-4357-8650-61de7820edec.png)

It seems that 'Run Stream in editor' shows as on but never really enables itself.

Using a parent to the VoxelLodTerrain and doing this:

```self.terrain = VoxelLodTerrain.new()
	self.terrain.material = load("res://WorldGen/Shaders/default_voxel.tres")
	self.terrain.generator = WordGen_VoxelTerrain.new()
	self.terrain.generator.sphereRadius = self.radius
	self.add_child(self.terrain)
	self.terrain.run_stream_in_editor = true
```
seems to work as a workaround.

**Comment by MGilleronFJ** [comment]
You need two things for a script generator to run in editor:
1) You must check `run stream in editor`, and click "Re-generate" in the terrain menu
2) Your script must be `@tool`

**Comment by VynDragon** [comment]
1. Is definitively done
2. in the generator script?

**Comment by MGilleronFJ** [comment]
> in the generator script?

Yes

**Comment by Zylann** [comment]
Gave it a try, and it works.

https://user-images.githubusercontent.com/1311555/197272571-63c7edc8-4a89-4896-a6d2-62e9d112e067.mp4

It could be that the `@tool` keyword doesn't take effect until you reload the scene (related https://github.com/godotengine/godot/issues/25275)

**Comment by VynDragon** [comment]
Well I'm now having the opposite... it works in the editor but not out of it ?

**Comment by Zylann** [comment]
I don't know, it also works in game for me.

**Comment by VynDragon** [comment]
What's happening is that the code bit I posted earlier:
```	self.terrain.material = load("res://WorldGen/Shaders/default_voxel.tres")
	self.terrain.generator = WordGen_VoxelTerrain.new()
	self.terrain.generator.sphereRadius = self.radius
	self.add_child(self.terrain)
	self.terrain.run_stream_in_editor = true```

Suddently doesnt work in game any more... but still in the editor (in game it seems the generator is never called). I am very confused. Meanwhile the raw vertexLODTerrain worked for a bit in the editor and is back to not working neither in game nor in the editor.

I've shortened my generator to this and still works on neither in the game atm and only in the editor with the custom code
```
extends VoxelGeneratorScript

class_name WordGen_VoxelTerrain

@export var sphereRadius: float
var sphereRadius_transitionThickness: float

@export var world: Node3D

const channel : int = VoxelBuffer.CHANNEL_SDF
#in SDF channel, set voxel takes float, -1 is solid, 1 is air

const MAX_ALTITUDE = 10000


func _get_used_channels_mask() -> int:
	return 1 << channel

func _generate_block(buffer : VoxelBuffer, origin : Vector3i, lod : int):
	self.sphereRadius_transitionThickness = sphereRadius / 2.0
	var do = sqrt(origin.y*origin.y+origin.x*origin.x+origin.z*origin.z)
	if do < self.sphereRadius - self.sphereRadius_transitionThickness / 2:
		buffer.fill_f(-100.0, channel) #set to very ground
	elif do > self.sphereRadius + self.sphereRadius_transitionThickness + MAX_ALTITUDE:
		buffer.fill_f(100.0, channel)
	else:
		for iz in buffer.get_size().z:
			var z = origin.z + (iz << lod)
			for iy in buffer.get_size().y:
				var y = origin.y + (iy << lod)
				for ix in buffer.get_size().x:
					var x = origin.x + (ix << lod)
					var feats2 = []
					var v = Vector3(x,y,z)
					var d = sqrt(y*y+x*x+z*z)
					var see = -1.0
					if d >= self.sphereRadius - self.sphereRadius_transitionThickness / 2 and d < self.sphereRadius + self.sphereRadius_transitionThickness / 2:
						var trans = (d - self.sphereRadius) / (self.sphereRadius_transitionThickness / 2)
						see = trans * 2.0
					elif d >= self.sphereRadius + self.sphereRadius_transitionThickness / 2:
						see = 1.0
					buffer.set_voxel_f(see, ix, iy, iz, channel)
```

**Comment by Zylann** [comment]
Note, you still don't have `@tool` at the beginning, so I'm surprised it even works in editor.

**Comment by VynDragon** [comment]
Well it seems to have worked just after another restart (adding tool)

**Comment by Zylann** [comment]
```
@export var world: Node3D
```
I strongly recommend you not to do this in a resource^^" Resources might not retain references to nodes.
Accessing nodes from `_generate_block` is also risky because the scene tree is not thread-safe, and `_generate_block` is called by multiple threads simultaneously.

```
@export var sphereRadius: float
```
This will default to zero, so by default you won't see anything, unless, of course, you write a script setting it manually, like you tried.
I am not able to set any property in the editor for some reason.
![image](https://user-images.githubusercontent.com/1311555/197291795-be3c6195-becf-415c-9230-e98fddc39ea8.png)

**Comment by VynDragon** [comment]
Thanks! I am aware about the thread safety and I'm tyring to design my code to avoid running into issues with it (the world thing is actually to call a function from the script that spawns the voxellodterrain and it already has a mutex to lock every element the generator will need to access), though the export thing is jsut a leftover and i removed it following that.

I'm not seeing anything in the console or log (or by sticking visual studio's debugger on the editor and the test run for the multithread, i needed it to debug issues in the generator) beside stuffs that i'm expecting to see when I improperly mess with the threads (I restart the editor everytime i want to check for sure if a issue is supposed to be there or not).

**Comment by Zylann** [comment]
Another thing to be aware of, it seems GDScript does not report errors occurring inside threads. I'm not sure if that will still be the case since Godot 4 is in beta though.

So far I can mostly see that there is no issue on the side of this module. If you find a reproducible case, you should provide a minimal reproduction project to help fix it. Otherwise, maybe this issue can be closed?
