### ISSUE TITLE
Rename queue_delete => queue_free

### ISSUE THREAD

**Issue by JohnCWakley** [Zylann/godot_voxel#458]
Hello @Zylann, I just attempted to build VoxelTools using `master` from both `godot` and `godot_voxel` and received the following error:

![image](https://user-images.githubusercontent.com/33690133/199040030-5d8ca7d4-437c-45af-9ed5-4a3e3e7a817f.png)

I then went into `godot/scene/main/node.h` and noticed that you have a commit (`7543a5e01451979b5ec72e95e34beb53f6440267`) changing `queue_delete => queue_free`.

I updated `modules/voxel/util/godot/node.h` to match the change in `godot/scene/main/node.h`:

![image](https://user-images.githubusercontent.com/33690133/199041051-fddeef97-6746-4d5f-a4f2-3631e09b7748.png)

That fixed the error for me. I understand that the `#ifdef...#endif` probably aren't needed anymore, but I left them in for now.

This message is just to mention the bug, I'm sure you're probably aware of it, but I thought I might as well be helpful.

**Comment by Zylann** [comment]
Fixed by 8c5065356ebc2f8364be317a4537769f1eab9b8c

**Comment by JohnCWakley** [comment]
Sweet! Thanks! :)
