### ISSUE TITLE
Assertion fails when VoxelTerrain is trying to save blocks.

### ISSUE THREAD

**Issue by MartinSVK12** [Zylann/godot_voxel#465]
Any attempt at saving with any of the `VoxelStream` classes will result in this error and nothing will be saved:
```
ERROR: Assertion failed: "_voxels == nullptr" is false.
   at: zylann::voxel::SaveBlockDataTask::run (modules\voxel\engine\save_block_data_task.cpp:67)
ERROR: Could not save block (-1, 1, -13)
   at: zylann::voxel::VoxelTerrain::apply_data_block_response (modules\voxel\terrain\fixed_lod\voxel_terrain.cpp:1270)
```

**Comment by MGilleronFJ** [comment]
Can you provide a reproduction project or some piece of code that makes this issue happen? This involves the SaveBlockDataTask so it isn't just any situation.

**Comment by MartinSVK12** [comment]
Here: [assertion_error.zip](https://github.com/Zylann/godot_voxel/files/9912812/assertion_error.zip)
Also should mention that I'm using `v4.0.beta.custom_build [e22a1d803]`

**Comment by MartinSVK12** [comment]
That fixed it, thanks!
