### ISSUE TITLE
Error C2039 when compiling

### ISSUE THREAD

**Issue by ravennst** [Zylann/godot_voxel#468]
I get a 
'create': is not a member of 'image' (C2039) [Ln 16, Col 1] on image.h
when compiling in Visual Studio Code. I'm not a good coder and I'm just trying to use Godot with Voxel-Tools so I don't know if this is a big issue or not. I should note that Godot still runs despite this.

![Screenshot_20221109-163205_Microsoft Remote Desktop.png](https://user-images.githubusercontent.com/49933013/200946977-ac6304ac-9f3c-4889-835b-0b717a913f54.png)

**Comment by Zylann** [comment]
Looks like you don't have the latest version or something? This file doesn't look like your screenshot https://github.com/Zylann/godot_voxel/blob/master/util/godot/image.h

**Comment by ravennst** [comment]
> Looks like you don't have the latest version or something? This file doesn't look like your screenshot https://github.com/Zylann/godot_voxel/blob/master/util/godot/image.h

I normally do a full fetch on both Godot and Voxel tools before I compile, Master branch on both, using GitHub Desktop. If what you guys are saying is true, I suspect that the files aren't getting updated locally when I bring up Visual Studio Code. I'll have to look into that.

**Comment by ravennst** [comment]
> Note, there are two ways to build this:
> - As an engine module
> - As a GDExtension
> 
> Either way, you should be using the `master` branch of the repository. The `gdextension` branch is old now, and was used when it was still work-in-progress.
> Note also, that building as a GDExtension is currently not guaranteed to produce a working library. There are a number of [issues](https://github.com/Zylann/godot_voxel/issues/442) with GDExtension at the moment that are making this engine very likely to fail at runtime. As an alternative, you can build this engine as a module, or get one of the CI builds (see https://voxel-tools.readthedocs.io/en/latest/getting_the_module/)

I've been using Master branch on both Godot and Voxel tools and compiling the entire engine. I'm thinking GitHub Desktop isn't updating the files locally properly so I will be looking into that.

**Comment by ravennst** [comment]
Ah HA! I found the problem. I accidentally nested the updated directory in the directory with the older version so fetching the latest build was putting it in the wrong place for the compiler. So instead of putting the files in modules/voxel, it was putting the updates into modules/voxel/voxel_tools. Updated & compiled without errors
