### ISSUE TITLE
Scene with voxels doesn't load

### ISSUE THREAD

**Issue by Andreww011** [Zylann/godot_voxel#470]
I have a scene where i have voxels, it loads and works perfectly while in debug but when i export it the scene doesn't load and just shows a gray scene.

**Comment by Zylann** [comment]
Can you post a simple project reproducing this? There can be a few reasons why this would happen (if the "voxels" you mention come from a save file for example), but it really depends what you have done in your project. I can't help you without more details.

**Comment by Andreww011** [comment]
Ok i fixed it. It was the export templates as you said. I compiled an export template with the voxel module and now it works. Thanks for the help.
