### ISSUE TITLE
compile error 2 - building terminated because of errors.

### ISSUE THREAD

**Issue by AiroHaika** [Zylann/godot_voxel#474]
[Initial build] modules\voxel\tests\test_octree.cpp(28): error C3493: 'block_size' cannot be captured implicitly because no default capture mode was specified
[Initial build] modules\voxel\tests\test_octree.cpp(28): error C3493: 'lod_count' cannot be captured implicitly because no default capture mode was specified
Compiling ==> thirdparty\libvpx\vp8\vp8_dx_iface.c
[Initial build] Compiling ==> thirdparty\libvpx\vp8\common\generic\systemdependent.c
vp8_dx_iface.c
systemdependent.c
scons: *** [modules\voxel\tests\test_octree.windows.tools.64.obj] Error 2
scons: building terminated because of errors.
[Time elapsed: 00:08:02.497]

**Comment by Zylann** [comment]
Which version are you compiling? Line 28 does not contain `block_size` or `lod_count` https://github.com/Zylann/godot_voxel/blob/f3f7241cb0250192d4c6512e9f2abd8d7cf3be33/tests/test_octree.cpp#L28

**Comment by AiroHaika** [comment]
godot 3.x and voxel 3.x

**Comment by AiroHaika** [comment]
Did I do something wrong in compilation? I put the godot in C:, then I put the voxel folder in the modules folder in the godot, and dps in the godot folder, I pressed SHIFT+RIGHT CLICK, I clicked on powershell, and I executed the command "scons -j4 platform=windows". is there any kind of problem using other versions of python, is there any specifics to compile?

**Comment by Zylann** [comment]
I dont know tbh, but it seems the latest MSVC compiler has some weird behavior going on.
![image](https://user-images.githubusercontent.com/1311555/207123420-19e92a2c-a4b0-4fd9-a2ff-df9a354a7806.png)
This makes no sense to me

**Comment by Zylann** [comment]
I don't know how to fix this without rewriting the code in an annoying way... or maybe you need to try an older version of Visual Studio, so far when testing on Compiler Explorer it only creates an issue in the very latest one

**Comment by AiroHaika** [comment]
Thnx, I'll try for the older version of Visual Studio.

**Comment by Zylann** [comment]
I'm using Visual Studio 2019

**Comment by Zylann** [comment]
I changed the code to use `static const`, but the warning is still present in latest Visual Studio 2022.
Seems it's a known issue https://developercommunity.visualstudio.com/t/C5264:-warning-triggered-for-constexpr-f/10198798

**Comment by AiroHaika** [comment]
I tried in 2019 and, still the error remains

**Comment by Zylann** [comment]
Did you try with the latest commit of the `godot3.x` branch? (which compiled fine here https://github.com/Zylann/godot_voxel/actions/runs/3678833528)

**Comment by AiroHaika** [comment]
I had downloaded the latest one, before reporting the issue

**Comment by Zylann** [comment]
I updated the branch [2 hours ago](https://github.com/Zylann/godot_voxel/issues/474#issuecomment-1347223034)

**Comment by Zylann** [comment]
Yes the directory is correct. I have no idea why your Visual Studio specifically produces all these errors when the CI simply doesnt find any...
I pushed another update.

**Comment by AiroHaika** [comment]
it worked now!! 
[100%] Linking Static Library ==> scene\scene.windows.tools.64.lib
[100%] progress_finish(["progress_finish"], [])
[100%] Linking Program ==> bin\godot.windows.tools.64.exe
   Creating library bin\godot.windows.tools.64.lib and object bin\godot.windows.tools.64.exp
[100%] scons: done building targets.
[Time elapsed: 00:13:30,454]
