### ISSUE TITLE
Game Crashes when instance is removed from world

### ISSUE THREAD

**Issue by LVLRGames** [Zylann/godot_voxel#487]
E 0:00:41:0750   zylann::voxel::VoxelInstancer::on_scene_instance_removed: Index instance_index = 2 is out of bounds (block.scene_instances.size() = 0).
  <C++ Source>   modules\voxel\terrain\instancing\voxel_instancer.cpp:1684 @ zylann::voxel::VoxelInstancer::on_scene_instance_removed()

I'm getting this error message when deleting a voxel instance , then moving the voxel viewer far enough to trigger an  LOD change where the instance previously existed.  The destroyed object is a voxelInstanceLibrarySceneItem.  It was destroyed using queue_free() called from a script attached to the destroyed object.

**Comment by MGilleronFJ** [comment]
Does the problem occur if your VoxelInstancer (and all parent nodes) are ensured to be at (0,0,0) ?

**Comment by LVLRGames** [comment]
Yes, the instancer is a direct child of the VoxelLODTerrain which does not move, in editor, or at runtime.  
![image](https://user-images.githubusercontent.com/87674745/222812168-8889874f-b39e-449b-844a-c2f2f4b68e25.png)

**Comment by LVLRGames** [comment]
after properly setting up a VoxelStream I was able to destroy instances without crashing the world.

**Comment by Zylann** [comment]
What did you do wrong? I think it's not supposed to crash

**Comment by LVLRGames** [comment]
I did not set up a voxel stream. and left it null when originally generating the terrain.  After adding a stream to the VoxelLODTerrain script the crashing stopped.

**Comment by Zylann** [comment]
Hmmm VoxelStream is optional, it should not have crashed for that

**Comment by Zylann** [comment]
I was not able to reproduce the error, but the crash should be fixed in 7c93f0d2a504e6a114d9d40262f3c6862c99a967
