### ISSUE TITLE
VoxelGeneratorGraph.find_node_by_name is not exposed

### ISSUE THREAD

**Issue by syncreticgames** [Zylann/godot_voxel#492]
Saw there was a commit to expose VoxelGeneratorGraph.find_node_by_name a few years ago (510d25e604c4d6786063078480c78d3e63797008), but get_method_list doesn't show it in the VoxelGeneratorGraph class, nor many other common functions like create_node

**Comment by Zylann** [comment]
Those functions have moved to the `VoxelGraphFunction` class.

**Comment by syncreticgames** [comment]
Awesome! I saw it broken out in source but didn't realize get_main_function was the conduit..thank you!!
