### ISSUE TITLE
Godot editor crash when regenerating voxelterrain with invalid voxel

### ISSUE THREAD

**Issue by Grify** [Zylann/godot_voxel#494]
When I created a new voxel out of curiosity in the voxel lib and gave it an invalid custom mesh, there was no error in the editor as I would've expected so I regenerated the terrain and the editor crashed.

I've created a pastebin with the crash log: https://pastebin.com/mVUYDjNn

Now I just hope that I can reopen the project and am not hardlocked from my work XD

**Comment by MGilleronFJ** [comment]
What is an "invalid mesh"?

**Comment by Zylann** [comment]
I need to be able to reproduce this in order to apply a proper fix. The call stack isn't enough to see what exactly is breaking.

**Comment by Grify** [comment]
Where are engine crash logs generated to? The internet tells me it is in Userdata > project > logs but these contain only console outputs, no crash information.

**Comment by Zylann** [comment]
You can get logs that stay on screen by running Godot from the command line in your project directory.
Another option is to provide a minimal project that reproduces the issue.

**Comment by Grify** [comment]
I've done as you asked. I will note that a repro case is not possible because the project cannot be saved since the engine crashes when the changes are applied.
Here are the console output logs:
```bash
❯ /Users/grify/Developer/godot-master/launch.command ; exit;
arguments
0: bin/godot.macos.editor.universal
Current path: /Users/grify/Developer/godot-master
Godot Engine v4.1.dev.custom_build.61d2c8551 - https://godotengine.org
OpenGL API 4.1 Metal - 83 - Compatibility - Using Device: Apple - Apple M1
 
Editing project: /Users/grify/Developer/Godot/voxelterranggenerering
arguments
0: /Users/grify/Developer/godot-master/bin/godot.macos.editor.universal
1: --path
2: /Users/grify/Developer/Godot/voxelterranggenerering
3: --editor
Current path: /Users/grify/Developer/godot-master
Godot Engine v4.1.dev.custom_build.61d2c8551 - https://godotengine.org
Vulkan API 1.2.231 - Forward+ - Using Vulkan Device #0: Apple - Apple M1
process done

Saving session...
...saving history...truncating history files...
...completed.

[Processen slutförd]
```
Of note is the fact that these logs do not appear to comment on the cause of the crash beyond simply that a crash occurred. I have identified a specific scenario which can be used to repro the crash. Steps follow.

1. Correctly configure a vanilla VoxelTerrain for cubed terrain
2. In the VoxelMesher's VoxelBlockLibrary, open the prototype of a **visible voxel** which will generate in the scene according to the VoxelGenerator/VoxelStream configuration
3. Alter the properties of the visible voxel prototype as follows:
4. Geometry: CustomMesh, CustomMesh: any of Godot prototype mesh excepting BoxMesh, PrismMesh, PlaneMesh (I personally have been able to confirm with Capsule, Sphere and Cylinder, however it does not crash with BoxMesh, PrismMesh, PlaneMesh)
5. Terrain: Regenerate
6. The editor will crash
7. 
Possible of note: My relevant numbers are: Vulkan API 1.2.231 Godot Engine v4.1.dev.custom_build.61d2c8551 GodotVoxel: 0c56dd88+

**Comment by Zylann** [comment]
In the TSCN/TRES file where your VoxelBlockyLibrary is, you can try to write this:
```
bake_tangents=false
```
That might allow you to load the project. Something is wrong with tangents.

**Comment by Zylann** [comment]
ace40656d10778eb131f8adde96985b76c0876ee should fix the tangents crash.

**Comment by Zylann** [comment]
The crash is fixed so I guess this can be closed
