### ISSUE TITLE
(Docs) Outdated docs contain missing classes and empty files

### ISSUE THREAD

**Issue by Grify** [Zylann/godot_voxel#495]
The docs seem very far behind master (in some cases many months out of date). Will they be updated?
Some basic examples of how they are out of date are as so:
[https://voxel-tools.readthedocs.io/en/latest/streams/](https://voxel-tools.readthedocs.io/en/latest/streams/) does not mention VoxelStreamScript at all
[https://voxel-tools.readthedocs.io/en/latest/api/VoxelGeneratorNoise2D/](https://voxel-tools.readthedocs.io/en/latest/api/VoxelGeneratorNoise2D/) does not mention half of the properties that VoxelGeneratorNoise2d has
[https://voxel-tools.readthedocs.io/en/latest/api/VoxelToolBuffer/](https://voxel-tools.readthedocs.io/en/latest/api/VoxelToolBuffer/) is just empty, there is no content on this page at all

Will the docs see a renovation sometime or are they mostly static on an older version of voxel and kept online for posterity's sake? Or is it just waiting for a willing contributor? I'd be happy to chip in if it meant they may be brought back to currency.

**Comment by Zylann** [comment]
Yeah the API web docs need an update.

**Comment by Zylann** [comment]
I updated the API docs in 13e586c1f94d38f034dd738065bff6d618a681be

**Comment by Zylann** [comment]
`VoxelToolBuffer` is empty because most of its functions come from the parent class.

**Comment by Zylann** [comment]
Will close this, but the doc might get a bit outdated sometimes, as not every commit is followed by a full update of docs. But it should be done from time to time.
