### ISSUE TITLE
VoxelBlock::create does not set buffer size

### ISSUE THREAD

**Issue by ktksgit** [Zylann/godot_voxel#5]
The helper-function
_VoxelBlock::create(Vector3i bpos, VoxelBuffer * buffer)_ 
creates a new VoxelBuffer but does not set _buffer->size_

**Example:**
If you call _VoxelMap::set_voxel([...])_ on a non-existing block, a new VoxelBuffer is created.
But then the function fails in 
_VoxelBuffer::set_voxel([...])_ at _ERR_FAIL_COND(!validate_pos(x, y, z));_

Fixing with initializing buffer with default size:
```
VoxelBlock * VoxelBlock::create(Vector3i bpos, VoxelBuffer * buffer) {
	VoxelBlock * block = memnew(VoxelBlock);
	block->pos = bpos;
	if (buffer) {
		const int bs = VoxelBlock::SIZE;
		ERR_FAIL_COND_V(buffer->get_size() != Vector3i(bs, bs, bs), NULL);
	}
	else {
		buffer = memnew(VoxelBuffer);
		buffer->create(SIZE, SIZE, SIZE);
	}
	ERR_FAIL_COND_V(buffer == NULL, NULL);
	block->voxels = Ref<VoxelBuffer>(buffer);
	//block->map = &map;
	return block;
}
```

**Comment by Zylann** [comment]
I fixed it along a few other changes related to mesh updates.
