### ISSUE TITLE
Unnecessary double check of mesh.is_valid()?

### ISSUE THREAD

**Issue by afonsolage** [Zylann/godot_voxel#50]
Hello folks!

Just walking through the code, I saw the [VoxelBlock::set_mesh](https://github.com/Zylann/godot_voxel/blob/7ced53ba6bcefefb42efe5f458d357932ccdf84a/terrain/voxel_block.cpp#L31) implementation as follows:
https://github.com/Zylann/godot_voxel/blob/7ced53ba6bcefefb42efe5f458d357932ccdf84a/terrain/voxel_block.cpp#L31-L69

Just a minor question, but the ternary operator in the following statement is unnecessary, right?
https://github.com/Zylann/godot_voxel/blob/7ced53ba6bcefefb42efe5f458d357932ccdf84a/terrain/voxel_block.cpp#L48

Since this block will be executed only if the `mesh.is_valid()`, so this statement can be simplified as follows?
```cpp
		vs.instance_set_base(_mesh_instance, mesh->get_rid());
```

Or maybe the right one to be check would be `_mesh` instead of `mesh`?

Thanks!

**Comment by Zylann** [comment]
I think you're right. Probably this code used to not have the enclosing `if` so that was the right code at the time but it was not simplified since.

**Comment by Zylann** [comment]
Fixed in 368e3efd1e486f9d2b0713f0f4f2f425b9c54f3c
