### ISSUE TITLE
[godot3.x]FixedArray conflicts with Godot's one

### ISSUE THREAD

**Issue by Adanelia** [Zylann/godot_voxel#508]
Hi! I compiled the latest godot 3.x (https://github.com/godotengine/godot/tree/716fef79ef1bce05cbb855d4b805c73eba92a563) with your voxel module (dbca142) and got an error:
```
path/to/godot/servers/visual/visual_server_canvas_helper.h(84): error C2977: "FixedArray": too many template arguments
path/to/godot/modules/voxel/util/fixed_array.h(9): note: see declaration of "FixedArray"
... and more
```
(Windows MSVC)
It seemed that there was a conflict between "voxel/util/fixed_array.h" and "core/fixed_array.h".
I found in this commit https://github.com/godotengine/godot/commit/910ddd13c43bfdb024e52bd2ea29e0105f9714f1 a "FixedArray" was added, which resulted in compiling error.
To fix it, maybe use namespace, or switch to another name?

**Comment by Zylann** [comment]
I am no longer maintaining that branch, it is very outdated now.
The latest version of the module is in Godot 4 and uses namespaces everywhere. If you want to use the old version anyways, you have to namespace the class.

**Comment by Adanelia** [comment]
All right, I have fixed it myself. Besides, thank you for your awesome work.
