### ISSUE TITLE
A shortcut to regenerate terrain

### ISSUE THREAD

**Issue by me2beats** [Zylann/godot_voxel#513]
It would be handy to have a keyboard shortcuts to regenerate the terrain

**Comment by Zylann** [comment]
How can a plugin do this?

**Comment by me2beats** [comment]
It's not possible to use Editor settings Shortcuts for that afaik.
But Editor Settings General could be used to store the user shortcut data Imo.
Which is not so nice because it hasn't that "press a shortcut" dialog

**Comment by Zylann** [comment]
Added in a7dd29d1c17543135598fc29b4cc1732b7860aa8
But until the Godot API becomes available, it won't be configurable in GDExtension builds (though GDExtension is too broken for the module to work well at the moment)

**Comment by me2beats** [comment]
thanks, that works!
I can close this now I guess
