### ISSUE TITLE
Add GitHub Discussions

### ISSUE THREAD

**Issue by me2beats** [Zylann/godot_voxel#515]
This is a great tool but configuring it is not simple, so beginners as me will ask a lot.
So I suggest adding github Discussions, it will be mainly for how-to questions, also maybe for tips and tricks etc.

**Comment by Zylann** [comment]
So that means there would be issues, discussions, and Discord all at once?

**Comment by me2beats** [comment]
oh there is a Discord server:)
Then maybe personally I don't need for discussions since I'll ask my questions there
Some people don't prefer discord tho

**Comment by Zylann** [comment]
Will close this as there isn't much incentive to do setup Github Discussions for now.
