### ISSUE TITLE
Custom functions values reset on game start

### ISSUE THREAD

**Issue by me2beats** [Zylann/godot_voxel#518]
It seems setting a value in inspector doesn't work in custom functions - the value resets to 0 I guess.
The result is I cant see the sphere in the game.
The value doesn't reset in the editor tho, and generates correct volumes

![image](https://github.com/Zylann/godot_voxel/assets/16458555/36c633a3-3aad-44a3-a05e-539de4ef3cf5)

The work-round is just using a Constant graph node to set the value.
Now it works - I can see the sphere in the game:

![image](https://github.com/Zylann/godot_voxel/assets/16458555/dabc3ef6-52eb-48de-9ebc-03212d4524d6)

`test_sphere.tres` function for issue reproduction:
```
[gd_resource type="VoxelGraphFunction" format=3 uid="uid://bl3qhnm3xg2lh"]

[resource]
graph_data = {
"connections": [[2, 0, 3, 0], [3, 0, 1, 0], [4, 0, 3, 1]],
"nodes": {
"1": {
"gui_position": Vector2(160, 100),
"type": "CustomOutput"
},
"2": {
"auto_connect": true,
"gui_position": Vector2(-280, 80),
"type": "Distance3D",
"x0": 0.0,
"x1": 0.0,
"y0": 0.0,
"y1": 0.0,
"z0": 0.0,
"z1": 0.0
},
"3": {
"gui_position": Vector2(-22, 132),
"type": "Subtract"
},
"4": {
"gui_position": Vector2(-320, 300),
"name": &"radius",
"type": "CustomInput"
}
},
"version": 2
}
input_definitions = [["x", "InputX", 0], ["y", "InputY", 0], ["z", "InputZ", 0], ["radius", "CustomInput", 0]]
output_definitions = [["", "CustomOutput", 0]]

```

![image](https://github.com/Zylann/godot_voxel/assets/16458555/0089441e-c8bb-45a7-a246-7a9c2120a290)

**Comment by me2beats** [comment]
Ah ok I'll prepare a project

**Comment by me2beats** [comment]
[test bug.zip](https://github.com/Zylann/godot_voxel/files/11681731/test.bug.zip)

**Comment by me2beats** [comment]
hm I can see this error
![image](https://github.com/Zylann/godot_voxel/assets/16458555/d02c88a0-a397-4c0f-a59a-1307036b0d6c)

**Comment by me2beats** [comment]
> not I guess that means your sphere has radius

hmm but I did set it here
![image](https://github.com/Zylann/godot_voxel/assets/16458555/34278357-3675-4bf7-bfd0-caed085a9abc)

It seems the value is reset when you run the game or reload the scene

if I set it to 10 in the tinspector and then run the game, it is resets in the game.

**Comment by me2beats** [comment]
and if I connect that constant, it works

**Comment by Zylann** [comment]
> hmm but I did set it here

> and if I connect that constant, it works

Yes you have to connect it otherwise it won't do anything.

**Comment by Zylann** [comment]
As indicated in https://github.com/Zylann/godot_voxel/issues/518#issuecomment-1581321527, this might just have been the graph not saving when you play the game. This should be fixed in 1071991dd27db5b63b2e8d4dd7fdb2979537f58b

**Comment by Zylann** [comment]
Is it still a problem?

**Comment by Zylann** [comment]
Closing for now, if the problem still happens it can be reopened.
