### ISSUE TITLE
Crash with Expression inside a function

### ISSUE THREAD

**Issue by me2beats** [Zylann/godot_voxel#524]
constant crash when trying to  edit a graph with a function with Expression that has zero division like 1/a

[dividing by zero expression bug.zip](https://github.com/Zylann/godot_voxel/files/11682689/dividing.by.zero.expression.bug.zip)

UPD: not related to division

**Comment by Zylann** [comment]
Does it have to involve a function?

**Comment by me2beats** [comment]
select the node and try to edit the graph

**Comment by Zylann** [comment]
I got a crash but it looks unrelated to the division

**Comment by me2beats** [comment]
hm indeed

**Comment by me2beats** [comment]
it seems that any expressins that have variables inside a function cause crash

**Comment by Zylann** [comment]
Should be fixed in f13d49b70a9557f0a167aad50a5383c2851cc9a7

**Comment by Zylann** [comment]
Is it still a problem?

**Comment by Zylann** [comment]
Closing for now, if the problem still happens it can be reopened.
