### ISSUE TITLE
`VoxelToolTerrain.set_voxel_metadata` doesn't mark block as modified

### ISSUE THREAD

**Issue by sigmastar00** [Zylann/godot_voxel#531]
Using `VoxelToolTerrain.set_voxel_metadata` on a voxel, and then leaving block out of view distance will not save the voxel's metadata to the terrain's stream. Additionally, `VoxelTerrain.save_modified_blocks` and `VoxelTerrain.save_block` won't save the voxel's metadata either.

A workaround for this is after setting the metadata, to use `VoxelToolTerrain.set_voxel` to replace the voxel with itself, after which all of the above methods will cause the metadata to be saved.

**Comment by Zylann** [comment]
Should be fixed in ebe49949743c7a41b1af52a99b65983053d909ba
