### ISSUE TITLE
Allow specifying renering layer in VoxelInstanceLibraryMultiMeshItem

### ISSUE THREAD

**Issue by m4nu3lf** [Zylann/godot_voxel#536]
**Is your feature request related to a problem? Please describe.**
I need to render some instances on a different layer than layer one because they should not be visible from a camera while the terrain must be visible.

**Describe the solution you'd like**
As for collision layers, it's reasonable also to have rendering layers for the multimesh.

**Describe alternatives you've considered**
I couldn't find any alternative.

**Comment by Zylann** [comment]
Probably needs to be exposed somewhat
