### ISSUE TITLE
VoxelInstance node being set to invisible crashes Godot

### ISSUE THREAD

**Issue by Griefchief** [Zylann/godot_voxel#539]
**Describe the bug**
VoxelInstance node being set to visible or invisible crashes Godot

**To Reproduce**
1. Crate a new scene with Node3d/VoxelLODTerrain/VoxelInstancer  nodes
2. Click on the eye on the VoxelInstancer node in the Scene view
3. Godot will crash.

**Expected behavior**
Not Crash

**Environment**
- OS: Windows
- Graphics card RX 590
- Godot version: V4.1.2.rc.custom_build [6884be6b1] as well as v4.0.4.rc.mono_custom_build [fd5dc2524]
- Module version (or commit hash if you got it from Github directly): f345310 and ac64a1c
- Renderer used Forward+ (Vulkan)
[VoxelInstanceBug.zip](https://github.com/Zylann/godot_voxel/files/12283255/VoxelInstanceBug.zip)

**Comment by Zylann** [comment]
Fixed in 6101e1a9491b1af73150c0a20c22edccd590e9b4
