### ISSUE TITLE
Allow disabling culling for block meshes

### ISSUE THREAD

**Issue by spazzylemons** [Zylann/godot_voxel#546]
In Minecraft, certain blocks such as leaves do not cull their faces when placed next to each other. This gives the leaves a fuller appearance. It would be nice to be able to disable culling for specific block meshes to get this appearance. I've tried using a custom mesh but that didn't seem to work. I'm still new to this plugin

Minecraft (no culling):
![2023-09-18_16 59 10](https://github.com/Zylann/godot_voxel/assets/25674682/c85cd4cf-101c-430b-b05b-666559d8f25a)

Godot (culling):
![Screenshot_20230918_165636](https://github.com/Zylann/godot_voxel/assets/25674682/31e50fdf-e1e4-4f66-ba2c-f97c110d8da8)

**Comment by Zylann** [comment]
One way to hack this up is to very slightly inset the faces of the mesh, so that they aren't part of the cube faces anymore. Therefore the engine won't consider them for culling. It might not look best though, so this should be added eventually.

**Comment by Benedani** [comment]
> Leaves don't completely turn off side culling.
Indeed, it is the other way around. It's not leaves that turn off side culling - it's that faces are not culled by leaves.
