### ISSUE TITLE
Mono build for linux?

### ISSUE THREAD

**Issue by Shadowblitz16** [Zylann/godot_voxel#547]
**Is your feature request related to a problem? Please describe.**
I want to use mono but I'm on linux

**Describe the solution you'd like**
Can we have a 4.0 mono release for linux?

**Describe alternatives you've considered**
I considered using the linux version but I really like C#

**Additional context**
none

**Comment by Zylann** [comment]
It's right here? https://github.com/Zylann/godot_voxel/actions/runs/6164178322
It's 4.1 tho.

**Comment by Shadowblitz16** [comment]
ty
