### ISSUE TITLE
Block Size is limited to a minumum of 16 

### ISSUE THREAD

**Issue by Shadowblitz16** [Zylann/godot_voxel#550]
**Is your feature request related to a problem? Please describe.**
BlockSize for voxel terrain lod is limited to 16

**Describe the solution you'd like**
Allow block size of 8

**Describe alternatives you've considered**
Nothing

**Additional context**
![image](https://github.com/Zylann/godot_voxel/assets/2453707/4d8a88ed-86c6-4d75-a518-407a7fc5eb85)

**Comment by Zylann** [comment]
Only two *mesh* block sizes are supported: 16 and 32. There is no plan to support 8, which is also too small.

**Comment by Shadowblitz16** [comment]
Starbound and terraria use block sized of 8 though

**Comment by Zylann** [comment]
Those are 2D games, also likely working differently. I wonder what kind of problem you have that makes you want to use that size for meshes specifically, but the point remains, that there is no plan to add this.
