### ISSUE TITLE
The current generator is providing voxel data only on channels that are not used by the current mesher.

### ISSUE THREAD

**Issue by Shadowblitz16** [Zylann/godot_voxel#551]
What does this mean?
Is there a way to fix it?
![image](https://github.com/Zylann/godot_voxel/assets/2453707/96ffd6e1-6774-4d59-addd-d5df4f0da2c0)

I am using a voxel terrain lod with...
- voxel stream region files
- voxel generator noise
- voxel mesher blocky

**Comment by Zylann** [comment]
It means the generator is outputting voxel data of a certain type that the mesher you chose isn't expecting.

By default, `VoxelGeneratorNoise` outputs signed-distance-field data in the `SDF` channel. `VoxelMesherBlocky` expects integer model IDs stored in the `TYPE` channel. So to fix this, change the generator's `channel` property to match it.

If the warning persists despite the terrain working fine, try to close and reopen the scene, it might be that the warning isn't updating when it should.

**Comment by Shadowblitz16** [comment]
@Zylann thankyou
