### ISSUE TITLE
Is VoxelMesherBlocky broken in 1x Dev?

### ISSUE THREAD

**Issue by Shadowblitz16** [Zylann/godot_voxel#552]
Is VoxelMesherBlocky broken in 1x Dev?
I can get the transvoxel and cube one to work but my blocks are not showing up with the blocky one.

I did make sure there were no errors and warnings and that run stream in editor is on.

I did notice that the numbers in the scene view status bar are counting down

**Comment by Zylann** [comment]
Did you define at least one air (0) and cube (1) models in your library?

**Comment by Shadowblitz16** [comment]
I defined 0 as stone and 1 as stone. 
does 0 have to be specificly a air type resource?

**Comment by Zylann** [comment]
Yes, 0 is used by convention to be air. If all models you defined are stone cubes, then you will see nothing because all space will be filled by them, infinitely.

**Comment by Shadowblitz16** [comment]
thankyou
