### ISSUE TITLE
Please add documentation in how to do multi layer cave generation for blocks

### ISSUE THREAD

**Issue by Shadowblitz16** [Zylann/godot_voxel#553]
**Is your feature request related to a problem? Please describe.**
I don't understand how to generate caves with different blocks at different depths.

**Describe the solution you'd like**
Please add documentation on how to use the graph to generate this.

**Describe alternatives you've considered**
I haven't considered anything other then the fact I have been looking at the documentation on how the graph works.

**Comment by Zylann** [comment]
Regarding cave generation, it was already asked in https://github.com/Zylann/godot_voxel/issues/230, with one way to do it in the docs.

Generating caves and having different block types based on height are two different problems.

If you specifically want to use a graph to place different blocks at different heights, you can do this by chaining `Select` nodes, like so:
![image](https://github.com/Zylann/godot_voxel/assets/1311555/8167cc2f-8d8c-4710-8991-f2db7085c1e8)
Values setup in `a`, `b` and being output to the `OutputType` correspond to IDs in the blocky mesher's library.

If you want variation on these layers, you may insert nodes to modify `Y` before each layer, with noise for example.

But you can also do this with regular code using `VoxelGeneratorScript`. It allows to do more things, but it will just be a bit slower when using GDScript.

**Comment by Shadowblitz16** [comment]
Ok thankyou!

I would have thought gdscript would have been slower since gdscript is interpreted and the graph node seems like it could be accelerated by either the gpu or c++.

**Comment by Shadowblitz16** [comment]
@Zylann quick question what exactly is t? time?

**Comment by Zylann** [comment]
> `Select` nodes are the equivalent of the GDScript code `a if t < threshold else b`.

`t` is the value being tested for. I had to choose a letter. In some cases it could be time yes, but not here. Could have been `x` or `v` for "value".
