### ISSUE TITLE
VoxelLodTerrain causes some blocks to overdraw

### ISSUE THREAD

**Issue by Zylann** [Zylann/godot_voxel#56]
I noticed this for a while, but went creating an issue because that needs to be fixed. This is harmless, but a bit messy.
Here we can see some blocks overlap others:

![image](https://user-images.githubusercontent.com/1311555/63979429-bd454880-cab0-11e9-9197-617ef0b3ae85.png)

**Comment by tinmanjuggernaut** [comment]
Do you think it's a problem with the chunk system building blocks that already exist? 

Or with DMC not being Manifold and it's a mesh issue?

**Comment by Zylann** [comment]
I think it's just a timing issue, as almost everything here is asynchronous. The type of mesh doesn't really matter.

**Comment by Zylann** [comment]
Oh, the cause was simple.
The visibility of `VoxelBlock` was set to `false` before a mesh was assigned to them. This is fine, but the `MeshInstance` is created lazily and was not set proper visibility when it happens.
The same goes for collision.

**Comment by Zylann** [comment]
Fixed by c3bc3561194997f697ed1860b11b3821ef39fbee
