### ISSUE TITLE
I think I am misunderstanding how to use VoxelGraphFunction

### ISSUE THREAD

**Issue by Shadowblitz16** [Zylann/godot_voxel#563]
I think I am misunderstanding how to use VoxelGraphFunction

I have a function like this...
![image](https://github.com/Zylann/godot_voxel/assets/2453707/6bd285ff-8d8d-48cb-89cd-3a5377b0ecb4)

But my function is not showing up in my other VoxelGraphFunction and I don't see a way to add it.
![image](https://github.com/Zylann/godot_voxel/assets/2453707/7f8c807b-e950-440f-9197-9e710e28c6f2)

I also am wondering why input x is counted as a explicit input instead of implicit input?

My plan was to wrap input x which has no inputs around amplitude_x which only has a amplitude and offset input.

Also Forgive me of making so many issues I am trying not to flood this repo like I did in the godot repo.

**Comment by Zylann** [comment]
> my function is not showing up in my other VoxelGraphFunction and I don't see a way to add it.

Functions are separate resources. They currently don't appear as entries in that list, just like scenes you make don't appear in the Add Node menu.
But there is an entry to browse or quick-open a function resource to add to the graph:

![image](https://github.com/Zylann/godot_voxel/assets/1311555/e99db995-7305-4016-8122-df87edc57da7)

**Comment by Shadowblitz16** [comment]
@Zylann  thankyou
