### ISSUE TITLE
Refresh voxelterrain in editor

### ISSUE THREAD

**Issue by TowarzyszFatCat** [Zylann/godot_voxel#565]
Is there any better way to refresh voxelterrain node in editor? I always doing this by removing mesh generator node and assigning it again. For example when I change something in graph how to see results in editor without assigning node again?

**Comment by Zylann** [comment]
There is a menu item for this, in `Terrain -> Re-generate`, which also has a hotkey: https://voxel-tools.readthedocs.io/en/latest/editor/#preview-options
In the graph editor there is also an option to do it every time the graph recompiles, in `Debug -> Live Update`.

**Comment by TowarzyszFatCat** [comment]
Thank You!
