### ISSUE TITLE
Impossible to run godot tests with voxels module

### ISSUE THREAD

**Issue by QuestionAndAnswer** [Zylann/godot_voxel#568]
**Describe the bug**
I'm developing own custom module and have voxels module compiled from sources along. So two modules in total, this repo's  and own. Implemented tests according to godot spec, but can't run them, because voxel module crashes test execution.

**To Reproduce**
Just build godot with voxel module and try run the tests.

```bash
cd godot && scons custom_modules=../godot_modules/voxel debug_symbols=yes tests=yes && cd ..
./godot/bin/godot.windows.editor.x86_64.exe --test
```

You'll see these:

```
ERROR: RenderingServer singleton is null when creating VoxelEngine!
   at: zylann::voxel::VoxelEngine::VoxelEngine (D:\Projects\project\godot_modules\voxel\engine\voxel_engine.cpp:77)

================================================================
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.1.1.stable.custom_build (bd6af8e0ea69167dd0627f3bd54f9105bda0f8b5)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[0] initialize_voxel_module (D:\Projects\project\godot_modules\voxel\register_types.cpp:332)
[1] initialize_modules (D:\Projects\project\godot\modules\register_module_types.gen.cpp:208)
[2] Main::test_setup (D:\Projects\project\godot\main\main.cpp:565)
[3] Main::test_entrypoint (D:\Projects\project\godot\main\main.cpp:687)
[4] widechar_main (D:\Projects\project\godot\platform\windows\godot_windows.cpp:163)
[5] _main (D:\Projects\project\godot\platform\windows\godot_windows.cpp:206)
[6] main (D:\Projects\project\godot\platform\windows\godot_windows.cpp:218)
[7] __scrt_common_main_seh (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[8] <couldn't map PC to fn name>
-- END OF BACKTRACE --
```

I tried to disable godot tests, via ```voxel_tests="no"``` param, but nothing changes.

I've also checked the modules initialization order, and voxel module initializes before mine. So, mine didn't make anything yet to make voxel module to crash.

**Expected behavior**
Voxel module should not affect godot's and other modules tests execution.

**Environment**
- OS: Windows
- Graphics card RTX 3070Ti
- Godot version 4.1.1
- Module version: 02596c14d6ce6a444300284204054de61a00188b
- Renderer used: Forward+

**Comment by Zylann** [comment]
I'm quite confused about the kind of environments `tests=yes` is setting up...

> ERROR: RenderingServer singleton is null when creating VoxelEngine!

This error means the module was unable to initialize rendering features. As in, there is litterally no RenderingServer, not even a dummy one. It's really confusing and I never expected this.
How are tests involving the rendering API (directly or indirectly) even supposed to work if it's not available at all?

I'm told singletons are created and destroyed between each test case, but there is no API for modules to hook into, so I can't even integrate mine to the test system...

I could add some guard checking if `tests=yes` was passed to skip initialization steps, but then if you write *any* test involving classes of the module, things will crash again.

**Comment by Zylann** [comment]
Worked around the crashing line in 2a2e15f106450f35c28160a954b647607dd6128a

**Comment by QuestionAndAnswer** [comment]
I think Godot using the tests here in a unit mode only, like it is not actually bootstrapping the whole core and dependencies tree. So it might be used only for unit tests (only module self dependencies), but no core rruntime dependencies, as there is no actual scene or runtime capabilties.

Thanks for the fix, though.

**Comment by QuestionAndAnswer** [comment]
Unit testing source: https://docs.godotengine.org/en/stable/contributing/development/core_and_modules/unit_testing.html

**Comment by Zylann** [comment]
The voxel module actually has tests that kinda work in a "unit" way, but they were not written with this framework (it didnt even exist when the module started). Instead they are written in quite a crude way where a crash is generated if some condition isn't satisfied.

Currently there is no feature for modules to integrate with other tests of Godot. The docs tell us to write tests under a folder *in the Godot repo outside modules*, so it's not possible to do it self-contained in our repo.
