### ISSUE TITLE
Block loaded. Multiplayer. Client.

### ISSUE THREAD

**Issue by slakibk** [Zylann/godot_voxel#569]
How do I configure the client and what functions to use in order to understand that the block is loaded. The "block_loaded" signal does not work on the client.
I want to prohibit the movement of the player and the calculation of his collision until I am sure that the terrain around him is loaded.

P.S. Thank you for your work.

**Comment by Zylann** [comment]
There is indeed no such signal on clients, as blocks are loaded differently than on the server. If emitting the signal were to be added, it might need to be in `VoxelTerrain::try_set_block_data`.

However to prohibit movement and collisions, signals are not the best fit. You could use `VoxelTool.is_area_editable` or `VoxelTerrain.is_area_meshed`, which can be called anytime from the main thread.
