### ISSUE TITLE
VoxelModifierMesh missing a warning

### ISSUE THREAD

**Issue by NatCracken** [Zylann/godot_voxel#570]
**Describe the bug**
VoxelModifierMesh doesn't warn you about not being a child of VoxelLodTerrain. This requirement is mentioned in the docs and the warning is present on VoxelModifierSphere, so its low priority imo.

**To Reproduce**
Create a VoxelModifierMesh outside of VoxelLodTerrain
Give it a valid mesh to clear the current error
Observe no errors

**Expected behavior**
A warning is seen in the hierarchy, the same as VoxelModifierSphere

**Screenshots**
https://imgur.com/a/40epa5A

**Environment**
Windows 10 Home
RTX 3060
4.1.2 dev mono
Module version 74d6768

**Comment by Zylann** [comment]
It is not missing from `VoxelModifierMesh`, both have it from their base class: https://github.com/Zylann/godot_voxel/blob/60690b377230da3b9e245ec3971ef72eeea2249c/modifiers/godot/voxel_modifier_gd.cpp#L157

For some reason in your specific case, Godot doesnt seem to have updated configuration warnings when you made or moved the nodes. Which steps did you follow to make this happen?

**Comment by NatCracken** [comment]
Update on this, rebuilt for more recent versions and both warnings are present again. Assuming you didn't change anything, something probably got broken and quickly fixed on godot's end
