### ISSUE TITLE
Octree HLOD and texture streaming  

### ISSUE THREAD

**Issue by KoxaKoxama** [Zylann/godot_voxel#574]
Since Godot doesn't have a built-in HLOD system with efficient texture streaming, I was wondering if this module could be used (or modified) for just an octree HLOD system with texture streaming without any voxels? It would be incredibly useful to use it with its chunking feature manually with imported assets.

**Comment by Zylann** [comment]
That sounds out of scope. I haven't even a clue how I would implement streaming textures, when Godot doesn't provide it in the first place.

**Comment by KoxaKoxama** [comment]
Godot's automatic LOD is kinda useless for large scenes because some LOD's should be made manually, especially merging small meshes into large chunks to reduce draw calls at distance.

Can you please explain about features offered by visibility ranges? As far as I know this can be used for simple HLOD structures but all meshes has to be preloaded into memory and stay there forever which is kinda useless, and in big scenes this will create an enormous list of nodes in a scene tree, is there is any way to unload nodes from memory using visibility ranges?

I guess no texture streaming then...

**Comment by Zylann** [comment]
> Can you please explain about features offered by visibility ranges?

It's explained here: https://docs.godotengine.org/en/stable/tutorials/3d/visibility_ranges.html#doc-visibility-ranges
It is a bit more flexible. Also one feature it has is fading between LODs, which I can't re-use apparently, I have to re-implement it and require users to use shaders, which is more work...

> all meshes has to be preloaded into memory and stay there forever which is kinda useless

Unfortunately this is also the case with my LOD system, for the same reason I don't do texture streaming myself: it's a feature the engine is supposed to provide. Implementing these things in userland is suboptimal, and more work both to develop and to use.

**Comment by KoxaKoxama** [comment]
> It's explained here: https://docs.godotengine.org/en/stable/tutorials/3d/visibility_ranges.html#doc-visibility-ranges

They added more details in latter version of the manual: https://docs.godotengine.org/en/latest/tutorials/3d/visibility_ranges.html#visibility-parent 
It turns out visibility ranges is tied to visibility parent parameter and every Node3D has it, so this is indeed quite versatile and parent don't even have to be an actual parent of the node, they all can be anywhere in scene tree.

This really makes me think that some more advanced structure can be made with this, as example there could be some decimated large combined mesh with a single atlas texture and upon getting close to it visibility ranges can trigger visibility parent node to be visible but instead of just turning it on it can start preloading small detailed meshes in a lazy loading manner avoiding blocking main thread, this is way better than just storing a lot of small detailed meshes (with a lot of textures) as a child at all time. As far as i'm aware 4.1 has working threaded scene processing now but I have no idea how to implement this properly to avoid any stuttering while small meshes is loading.

**Comment by Zylann** [comment]
Well, either way in this module I develop things around voxel terrain, and I also don't use nodes internally. If something is independent of that, it should be requested in the engine, or a different plugin.
