### ISSUE TITLE
Cannot delete nodes in generator graph

### ISSUE THREAD

**Issue by NatCracken** [Zylann/godot_voxel#575]
**Describe the bug**
Pressing delete with generator nodes selected doesn't do anything, Node isn't deleted and no errors in console. Upon startup the error message `In Object of type 'GraphEdit': Attempt to connect nonexistent signal 'close_nodes_request' to callable 'VoxelGraphEditor::_on_graph_edit_delete_nodes_request'.` is printed which I assume to be related. This error occurred after rebuilding to updated versions yesterday.

**To Reproduce**
1. matching versions (see environment) might be necessary
2. create a generator graph
3. attempt to delete a generator graph mode

**Expected behavior**
no error on startup, being able to delete generator nodes

**Screenshots**
console on startup
https://imgur.com/a/E45JdGx

**Environment**
Windows 10 Home
RTX 3060
4.1.2 dev mono
godot 214405350f3893bb6960c5200ec6f683dd10b41d
voxel e495b76d577c11acb35a75ec4322d196d34d0d58

**Comment by Zylann** [comment]
Are you sure you're using `4.1.2`?

The name of that signal has been a problem in the development of Godot 4.2:

https://github.com/Zylann/godot_voxel/blob/e495b76d577c11acb35a75ec4322d196d34d0d58/util/godot/classes/graph_edit.h#L30-L41

But in 4.1.x it should be using `delete_nodes_request`, which is the right signal.

Your console screenshot is showing 4.2.
The name of the signal has been later [renamed back to what it was](https://github.com/godotengine/godot/pull/82370), so the workaround just needs to be removed.

**Comment by NatCracken** [comment]
That'll do it. It seems my automation stuff has been grabbing the wrong version of Godot for a while now, but only now did it actually break anything
