### ISSUE TITLE
VoxelAStarGrid3D seems not to work with negatives Vector3

### ISSUE THREAD

**Issue by MathieuRegis** [Zylann/godot_voxel#576]
Hello,

I'm trying to make VoxelAStarGrid3D works, their is not much doc on it so I'm testing the trial and error way.
Feel free to correct me if I'm wrong somewhere or if I'm not using VoxelAStarGrid3D the way it's suppose to be used.
For this I'm testing thing in the blocky_game example.

So I understood that I needed to set terrain and region.
Terrain is the generated VoxelTerrain.
Region is an AABB to define the boundaries where AStar looks for its algorithm.
I'm using the `find_path` method that return `Array[Vector3i]` if a path has been found, else it return an empty Array

**Describe the bug**
When I'm using negative Vector3, to find path in the -x or -z axis of the VoxelTerrain, it's doesn't find any path.

**To Reproduce**
Here is the code I'm using :
this works using positives values :
```
...
var _agrid: VoxelAStarGrid3D = null

func _ready():
	_agrid = VoxelAStarGrid3D.new()
	# set _terrain that is the main VoxelTerrain
	_agrid.set_terrain(_terrain)

	# little aabb box of 20 by 10 by 20
	var aabb := AABB(Vector3(0, 0, 0), Vector3(20, 10, 20)) 
	_agrid.set_region(aabb)

# I'm using _unhandled_input just to trigger the find_path
func _unhandled_input(event: InputEvent):
	if event is InputEventKey:
		if event.pressed:
			match event.keycode:
				KEY_UP:
					# y = 6 because my terrain ground is at y = 5
					var path = _agrid.find_path(Vector3(1,6,1), Vector3(6,6,3)) 
					print('path ', path)
```
I got positive values, it works, the print in console : `path [(1, 6, 1), (2, 6, 2), (3, 6, 3), (4, 6, 3), (5, 6, 3)]`

But if I change the Vectors for : `_agrid.find_path(Vector3(-1,6,-1), Vector3(-6,6,-3))`, it return an empty array, witch I suppose mean that their is no path found. I tried very simple path like `_agrid.find_path(Vector3(-1,6,-1), Vector3(-1,6,-2))`, the print always return `path []`.

I made sure the terrain is flat and with no obstacle (since I'm using the blocky_game example, the grass for example are counted as obstacles).

**Expected behavior**
The path should be found with the list of negative Vector3

**Environment**
- OS: Linux
- Graphics card : NVIDIA GeForce GTX 1070
- Godot version : Godot Engine v4.1.3.rc.custom_build.f80c673cd
- Commit hash : `e495b76`
- Renderer used : Forward+

Thanks for any help, fix or explanation !

**Comment by Zylann** [comment]
![image](https://github.com/Zylann/godot_voxel/assets/1311555/5f57367a-e6c8-485e-82f3-11ca2b454901)

Works in my testing scene. Do you have a test project?

**Comment by MathieuRegis** [comment]
Alright, Thanks for the answer,

After some testing I figure it out that position in AABB was not the center of the box but the corner of the box.
So my AABB config was wrong.

I tested and it works with negatives values indeed.
Also works with positives and a mix of negatives and positives values, very nice !

Quick question, how do you get the blue path to appear in your screen for debug ? is this debug_get_visited_positions method ?

Thanks !

**Comment by Zylann** [comment]
> Quick question, how do you get the blue path to appear in your screen for debug ? is this debug_get_visited_positions method ?

The blue cubes are points of the returned path. I draw them using a MultiMeshInstance.
`debug_get_visited_positions` is shown in my screenshot as transparent yellow cubes.

**Comment by MathieuRegis** [comment]
Tanks you very much for the answers !
