### ISSUE TITLE
Editor frequently crashes when testing a project

### ISSUE THREAD

**Issue by CardboardDog** [Zylann/godot_voxel#577]
**Describe the bug**
Every 5-7th time running the project, the editor and the debugger crashes.

**To Reproduce**
1. Create a scene with a VoxelTerrain, Camera3D, and VoxelViewer.
2. Debug/run the project then stop the project. Then repeat this until it crashes (should be between five to seven times.)

After crashing the console states: `editor\editor_node.cpp:8224 - Condition "plugins_list.has(p_plugin)" is true.`

**Environment**
- Windows 11
- NVIDIA RTX 3050 
- Godot version 4.1.4
- [Module version](https://github.com/Zylann/godot_voxel/actions/runs/6835684579)
- Forward+

**Comment by Zylann** [comment]
`editor\editor_node.cpp:8224 - Condition "plugins_list.has(p_plugin)" is true` is a Godot bug that's been in limbo for months now: 
https://github.com/godotengine/godot/issues/73650

But I haven't linked this to the crashing pattern you are describing. In fact, I haven't got many crashes recently, so not sure what setup you have that make crashes so frequent. But maybe it is that Godot issue, in which case there is nothing I can do in this module...

**Comment by CardboardDog** [comment]
After looking at the problem again it seems like a problem with the Godot engine, (or possibly my code) because it only occurs in one project. If I replicate the scene (and scripts) in another project, it doesn't occur. Also, the release builds don't crash.
