### ISSUE TITLE
Editor Crash When using ArrayMesh/PointMesh on the VoxelBockyModelMesh

### ISSUE THREAD

**Issue by EarthDLL** [Zylann/godot_voxel#578]
**Describe the bug**

**To Reproduce**
Build:https://github.com/EarthDLL/godot_voxel/actions/runs/6836074952

1. Create a VoxelBlockyModelMesh
2. Create a ArrayMesh and use Script to add surface to the Mesh(Empty ArrayMesh will not cause crashing)
3. Adding ArrayMesh to BockyModelMesh or creating a new pointMesh directly can cause a crash

**Screenshots**
![I8T3SSVGAND)CDCZVFD%EGL](https://github.com/Zylann/godot_voxel/assets/100025289/9c73e07a-d13d-4fb7-8eb7-dfaebf427c37)
https://github.com/Zylann/godot_voxel/assets/100025289/b2920f63-52f2-4e48-abca-100ca1555135
![Cache_641d8def88211970](https://github.com/Zylann/godot_voxel/assets/100025289/964c4fce-13a1-45b9-92e0-21726b202246)
![Cache_-431f1dce4b52d356](https://github.com/Zylann/godot_voxel/assets/100025289/67de9c12-0feb-40b5-9746-f8efa8a7ff31)

https://github.com/Zylann/godot_voxel/assets/100025289/78e9b0a4-85bc-47d1-8893-5f93393c3b83

**Environment**
- OS: Windows 10(64bit)
- Graphics card : NVIDIA GeForce MX330
- Godot 4.1.4rc.custom_build
- Module version (or commit hash if you got it from Github directly)
- Renderer used: Mobile & Opengl3

**Comment by Zylann** [comment]
Meshes made only of vertices (and no UVs, no normals, no indices) are not supported.
It should not crash though, instead it should show an error. That should be fixed.

**Comment by Zylann** [comment]
Added more checks in 67a6f0c65c8754a5b740fc5aef8e511967aa875d so it should no longer crash.

**Comment by EarthDLL** [comment]
Thanks
