### ISSUE TITLE
Blocky terrain. Raycast does not work correctly in the place with attributes

### ISSUE THREAD

**Issue by slakibk** [Zylann/godot_voxel#583]
To determine the block the player is looking at, I use raycast. But when I specify the rotation attribute, raycast does not work correctly - it starts working only in 1/4 of the block.

**Environment**
- OS: Win10
- gtx 4070
- Godot version - v4.2.stable.custom_build
- Module version - last

Video:
[https://youtu.be/dZxj5iXQx30](url)

**Comment by Zylann** [comment]
I might have narrowed down the problem you had, pushed a fix in a3af2d089d42adc3668e5a1b3fc396e64c4e1514

**Comment by slakibk** [comment]
Sorry https://www.youtube.com/watch?v=dZxj5iXQx30

**Comment by slakibk** [comment]
The error has been fixed. Thank you very much. The ability to add attributes is an amazing feature.
