### ISSUE TITLE
If you set the "voxel blocky type" name to "fence" the project freezes.

### ISSUE THREAD

**Issue by slakibk** [Zylann/godot_voxel#585]
If you set the "voxel blocky type" name to "fence" the project freezes.

![image](https://github.com/Zylann/godot_voxel/assets/55349540/6c143307-30f3-48ec-93e3-4cf6c003f61a)

https://www.youtube.com/live/LmGm4VMMW-U?si=ClTT_dR-alPddBvt&t=4420 

**Environment**
- OS: Win10 64
- Godot version 4.3.RC1
- Last

**Comment by Zylann** [comment]
I tried that and it didn't freeze. Please provide a minimal reproduction project with all the setup you had to make this bug happen.

**Comment by slakibk** [comment]
A project that stopped running after adding a "voxel blocky type" with the name "fence"
[fence.zip](https://github.com/Zylann/godot_voxel/files/13639343/fence.zip)

**Comment by Zylann** [comment]
Should be fixed in f312d9a2b924a0080769c4cd26eabd4614e8e835

**Comment by slakibk** [comment]
Works. Thank you very much.
