### ISSUE TITLE
Expose SpotNoise

### ISSUE THREAD

**Issue by Elandig** [Zylann/godot_voxel#586]
**Is your feature request related to a problem? Please describe.**
After some prototyping, I switched from from graph to script generator and realized that there's no spots noise. It would be nice if it was exposed.

**Describe the solution you'd like**
Expose spot noise

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Zylann** [comment]
For now you can obtain results of SpotNoise in a 3D grid by generating a VoxelBuffer from a VoxelGeneratorGraph.

**Comment by Elandig** [comment]
Thanks, that's exactly what I'm doing.

**Comment by Zylann** [comment]
Exposed in e3d4abee2e7bd3731869a1d4872e494cf560031b

**Comment by Elandig** [comment]
Thanks!
