### ISSUE TITLE
Occasionally faces won't properly illuminate or work with Godot's triplanar mapping

### ISSUE THREAD

**Issue by tinmanjuggernaut** [Zylann/godot_voxel#59]
Sometimes, some lower LODs have faces that are black when using a texture, or impossibly dark even with a white albedo color and the sun shining directly on it. I wonder if those faces have their normals reversed. 

Present in master, though these pics are from the paged branch. 

I've seen this a lot on the noise world and have even pointed it out in videos I've sent you. I thought it was my shader, because if triplanar map blending is too high, it will cause black sections. But no. This issue is there even when there's no triplanar mapping.

It's also not a lighting issue, or that the lower LODs have a mesh that is just causing more shadow.

Textured w/ triplannar mapping and very low blend (6). Shouldn't have black marks:

![image](https://user-images.githubusercontent.com/632766/64067738-4b176400-cc68-11e9-87eb-35a8edfd47bf.png)

Blank SpatialMaterial. Sun is shining on both faces:

![image](https://user-images.githubusercontent.com/632766/64067748-61252480-cc68-11e9-904b-0f8a23c1ce38.png)

Bottom face has shifted to a new LOD. Shows how much light was there that did not reflect off the face in the picture above.

![image](https://user-images.githubusercontent.com/632766/64067762-84e86a80-cc68-11e9-94c3-4ddd913b39a3.png)

This is from master, sun shining on this pillar. Then I backed up to hit the right LOD from different angles, moving around it from left to right.:

![image](https://user-images.githubusercontent.com/632766/64067916-c67a1500-cc6a-11e9-9685-4bb8d290b022.png)

**Comment by Zylann** [comment]
I've seen this occasionally as well, I honestly don't know where it comes from.

**Comment by tinmanjuggernaut** [comment]
Could those faces have their normals reversed? Isn't there a draw normals debug in Godot or VT? I've seen Reduz post pics of faces with normals poking out. Maybe that would tell us if this is the issue.

**Comment by Zylann** [comment]
It's likely normals are reversed yeah. I'm not aware of any normal debug tool like this. You could check this by changing your shader to `unshaded` and output normals in ALBEDO?

**Comment by tinmanjuggernaut** [comment]
Here I grabbed NORMAL from vertex(), assigned it to a varying, then assigned it to ALBEDO.

1, 3, 5 = LOD0 from left, middle, right side
2, 4, 6 = lower LOD with a black artifact
![image](https://user-images.githubusercontent.com/632766/64068571-eca4b280-cc74-11e9-9783-fa9155360d24.png)

I guess the vertex normals look ok, but the mesh has a strange shape. You can see it has a lip of green
![image](https://user-images.githubusercontent.com/632766/64068572-f201fd00-cc74-11e9-9967-581d232a1f70.png)


Here in fragment I just assigned ALBEDO=NORMAL

![image](https://user-images.githubusercontent.com/632766/64068661-2b873800-cc76-11e9-9463-fc0a45d01d7d.png)


So maybe vertex normals are ok, but face normals are reversed?

**Comment by Zylann** [comment]
I'm unable to see those black spots with my shader
![image](https://user-images.githubusercontent.com/1311555/64068738-27d2c180-cc34-11e9-8347-59a6bb060faa.png)
![image](https://user-images.githubusercontent.com/1311555/64068739-2f926600-cc34-11e9-9980-d96322abf6a6.png)
![image](https://user-images.githubusercontent.com/1311555/64068740-33be8380-cc34-11e9-9380-7bd2697ec90e.png)
![image](https://user-images.githubusercontent.com/1311555/64068742-39b46480-cc34-11e9-9c8a-5348ce20b1c9.png)

**Comment by tinmanjuggernaut** [comment]
After more testing, I decided a video will show some things better:

https://youtu.be/uNVG_49DGNo

**Comment by Zylann** [comment]
Black/dark areas:
I don't know yet what these are. In some rare cases they are just the marching square skirts that sometimes reveal if looked at towards the sun, which would otherwise be a hole into the terrain.
But I am aware that in some cases, geometry itself turns dark, and I suspect it's due to a corner case in the marching cubes implementation. So far I don't know where the bug is.

Holes in the mesh:
These are supposed to be hidden by skirts most of the time, but they can still show up. Either because skirts are too short (but couldnt figure out a better sweetspot), or because adjacent octrees have slightly different outcomes in their subdivisions which makes them not line up as if they were one.
Same here, I don't know where the bug is.

Nubs:
This is due to https://github.com/Zylann/godot_voxel/issues/60
There are some kinds of shapes that won't ever work with the current meshing technique. Marching cubes are good for organic terrain, not geometric or thin shapes like those in the demo. I left them here specifically to test/illustrate that. To handle thin geometric shapes, both data storage and meshing techniques need to be changed.

**Comment by tinmanjuggernaut** [comment]
Should this issue include the mesh holes or should that be a separate issue?

**Comment by Zylann** [comment]
@tinmanjuggernaut which mesh holes?

**Comment by tinmanjuggernaut** [comment]
My/Godot's triplanar mapping method produces black faces. But when it works, allows for triplanar mapped normals (and albedo, AO).

@Zylann 's triplanar mapping method and non-triplanar materials produce darker albedo faces (like the albedo is multiplied with black), but triplanar mapped normals isn't an option.

I've tried the `ensure_correct_normals` shader option and it did not help.

Now that VLT is paged and can reach far clip, this opens up the possibility for high speed, flight based games. This issue becomes more obvious as most of the terrain will be on a lower LOD.

Black faces all over when flying overhead:
![image](https://user-images.githubusercontent.com/632766/64363708-437f0300-d04c-11e9-89d0-215be2d39a6d.png)

**Comment by tinmanjuggernaut** [comment]
This issue isn't limited to lower LODs. I just think they are more common there, and I use Godot's triplanar mapping method which turns the faces black so they are more obvious.

You've posted pics and I've seen other instances that have been on LOD0. On your pics you can see texture applied, they are just very dark.

Today I encountered it on a new shader that does not use triplanar mapping at all. The faces properly apply albedo and vertex displacement. My shader doesn't touch normals or anything else. However, I have a spotlight shining directly on them and they will not illuminate. They accept only ambient light. 

https://youtu.be/fIm7B8KsmEg

So for these faces:
* Godot's triplannar mapping ==> black
* Any other texturing ==> no direct light illumination, only ambient light

**Comment by tinmanjuggernaut** [comment]
I attempted the following unsuccessful tests with a light shining on a 2D plane:
* Enabled `flip_faces`
* Disabled cull render mode and looked at both sides of the plane
* Flipped faces while cull was disabled

All lit properly.

I also figured out how to properly color the terrain with normals (e.g. x=red, y=yellow, z=blue), unlike the garbage I showed above, and don't see oddities here. 

For reference you can display normals by:
```
varrying vec3 vertex_normal;
void vertex() { 
	vertex_normal = NORMAL; 
}
void fragment() { 
	vec3 normal_color  = clamp(vertex_normal,0.,1.);
	ALBEDO = normal_color;
}
```

I don't believe it's a normal problem. I'm wondering if the face isn't being properly constructed and the engine is picking up the slack by displaying something, but the lighting code does not accept it. e.g. It's missing a vertex and the engine is auto-filling the face, or it has something to do with indices.

**Comment by Zylann** [comment]
I believe this really comes from the meshing process, just not sure which part exactly. To debug this we need a simple scene with extremely few voxels that reproduce the case.

**Comment by tinmanjuggernaut** [comment]
It's possible that you implemented DMC perfectly, but the nature of the algorithm is non-manifold.

Today I found an instance that looks like a non-manifold mesh problem. E.g. the vertices were on the same point, or the hermite data went through the voxel but was too narrow and didn't touch any edges or something:
![image](https://user-images.githubusercontent.com/632766/65337209-b4a0e780-dc02-11e9-8363-8a491de5cdc6.png)

I just found a BSD licensed implementation of manifold DMC:
https://github.com/dominikwodniok/dualmc

> Unfortunately, under rare circumstances the original algorithm can create non-manifold meshes. See the remarks of the original paper on this problem. In chapter 3.3.5 of his book "Isosurfaces: Geometry, Topology, and Algorithms" Rephael Wenger proposed the manifold dual marching cubes algorithm as a possible solution, which is also included in this implementation.


```
// If a problematic C16 or C19 configuration shares the ambiguous face 
// with another C16 or C19 configuration we simply invert the cube code
// before looking up dual points. Doing this for these pairs ensures
// manifold meshes.
```
All the code is in /include:
https://github.com/dominikwodniok/dualmc/blob/master/include/

**Comment by Zylann** [comment]
Note: the current implementation is equivalent to marching cubes, so I wonder how that affects the fix to do?

**Comment by tinmanjuggernaut** [comment]
Look at this lovely artifact. There are two nearby sections. Even the skirts are poking out. Here it's using godot's triplanar mapping so turns black.

https://youtu.be/FwOmOXHC_Go

Would it help if there was some debug function that could dump a section of the mesh to disk or console? If there was something like do_sphere, then when I encounter these, I could toss a bullet at it, which could write the mesh or the voxel buffer to disk or console. Then we could reload it as it's own scene and have an isolated test case.

**Comment by Zylann** [comment]
That's what I suggested before: make a scene without terrain, generate a very small VoxelBuffer with a very small size in it and polygonize it directly with `VoxelMesherDMC` (like done in the `test_dmc` scene of the demo project). It may require a minimum size to work though (the mesher needs a margin of 2).

**Comment by tinmanjuggernaut** [comment]
Here's a relocatable reference area for the future small area capture test.

Default 3d noise world settings (e.g. from my demo). 
Location: 1412.63, 122.4, 685.94

The problem faces are not caused by triplanar blend sharpness (which causes black faces in some cases, due to a lack of clamping I believe), nor by features the material can do.

![image](https://user-images.githubusercontent.com/632766/69906413-d1754a80-13fd-11ea-917f-6950ac8e51d0.png)

**Comment by Zylann** [comment]
Something I don't get, is that the artifact appears so sharp. Vertices are supposed to be connected together, and then shading should be smooth. But if they look sharp, there can be two reasons:
- Vertices didn't get shared while they should have
- We are at a block boundary so they can't be shared anyways, meaning the padded voxel data was different from a side to the other, causing the inconsistency

I'm testing both the incomplete Transvoxel implementation and DMC in a test scene, so far I could not find the artifact. Also I found out both algorithms resulted in similar approximation errors when it comes to normals, which a generic mesh-based normal calculation doesn't have.

**Comment by Zylann** [comment]
Normalizing seems to work.

**Comment by tinmanjuggernaut** [comment]
Great work, @Zylann . I did some testing and think you've solved the issue for LOD0. Does this also normalize the mesh for lower LODS?

Here is my testing of the various symptoms brought up in this issue:


**LOD0 Fixed**
* Default 3D noise world: Affected faces on LOD0 in at 1412.63, 122.4, 685.94 

![image](https://user-images.githubusercontent.com/632766/70862298-8880d280-1f75-11ea-90b7-2e70eca8e058.png)


* I think this scene would definitely have had black faces on LOD0. Below 2 is the skirt poking through, it's only paper thin there. 1 and 3 are 3D meshes, but they look unusual enough that I think they would have had problems before.

![image](https://user-images.githubusercontent.com/632766/70863189-5e80dd80-1f80-11ea-8a85-9af5857d77e7.png)


**Questionable LOD0** 

The only oddities I was able to find on LOD0 in any of my scenes was this. Those dark spots have a light shining on them. But they are too small to be a mesh face. This shader is using vertex displacement, so I think the shader screwed them up. I'm only including this for completeness in case it comes up again elsewhere. 

![image](https://user-images.githubusercontent.com/632766/70863372-7e190580-1f82-11ea-8020-90a773079742.png)


**LOD1+ still has an issue**

It seems meshes on lower LODs still show black or dark faces.

* Heightmap: Tower on lower LODs in flat area w/ towers.

Our tower still shows a dark face. This one is difficult to test because on some demos the tower turns into a nub on lower LODs due to #60, and other demos it stays as a tower. I don't know what the difference is in the demos. I've used the same VT settings.

![image](https://user-images.githubusercontent.com/632766/70863076-43619e00-1f7f-11ea-95b9-47c4f3448f19.png)


* In this scene, this far away floating island I think is too dark on the left. This is not triplanar mapped, so shows dark, unaffected by direct light. When the LOD changes, it looks normal on the right. 

![image](https://user-images.githubusercontent.com/632766/70863125-d8fd2d80-1f7f-11ea-8f34-a842ffc9721e.png)


* When viewed from afar the black faces are obvious, especially when fog is turned on. 

![image](https://user-images.githubusercontent.com/632766/64363708-437f0300-d04c-11e9-89d0-215be2d39a6d.png)

![image](https://user-images.githubusercontent.com/632766/70863292-7ad14a00-1f81-11ea-90c8-e94d551eb12c.png)


P.S. Issue #63 Holes in the mesh is unchanged as shown above.

**Comment by Zylann** [comment]
The fact it happens in far lods makes me think of one hypothesis: far lods have a higher isolever factor because they are bigger. On the heightmap example (which, remember, has a faulty stream), values between voxels differ so quickly and so much that they hit their quantified bounds (they are all either -1 or 1). So when computing the gradient between two voxels, the results are very likely to end up as zero, which means the normal also ends up as zero, normalized or not. Maybe you could verify this by checking in the shader?

**Comment by tinmanjuggernaut** [comment]
Vertices with non-normalized normals with length < 0.5 in red: 
![image](https://user-images.githubusercontent.com/632766/70865501-5bdeb200-1f99-11ea-8c0a-6e2280e19ccf.png)

Normal lengths < 0.1 are only small red dots:
![image](https://user-images.githubusercontent.com/632766/70865517-95172200-1f99-11ea-8e81-d3ee8f2a46c4.png)

I can't see any red vertices when length(normal)==0. 

However, the reason the faces turn black is due to this line in Godot's triplanar shader:
`uv1_power_normal/=dot(uv1_power_normal,vec3(1.0));`

The texture sample turns to 0 so the dot product is probably returning zero.

If I put this at the beginning of vertex() it fixes all the black faces (and removes red dots for <0.3, but somehow still has some at <0.5):

`NORMAL = normalize(NORMAL+vec3(0.,0.001,0.));`

With this change using triplanar mapping, or a regular shader material, fog or no, everything looks fine. No artifacts in the fog. There might be some faces that are still a little dark, but they are far away and subtle enough that I can't be sure. Don't see anything on the tower.

If the shader uses `world_vertex_coordinates`, then `ensure_correct_normals` must also be used to get rid of the black faces. Nothing else I could do with the normal or albedo would fix it, except turning on that flag. And actually this is the first time I've ever seen that second flag actually do anything.

**Comment by tinmanjuggernaut** [comment]
@Zylann So we've effectively fixed this problem with a module fix and a shader work around. But there's still an issue with normals apparently. Do you want to keep this open until it is found in the engine? Or, I could just make a note about the shader fix in the docs and we could close it.

**Comment by Zylann** [comment]
I will probably come back to it when investigation terracing. 

There could be a case like this:
```cpp
gx = right - left
gy = top - bottom
gz = front - back
normal = Vector3(gx, gy, gz).normalized()
```
The normal will be zero if the values are equal, even though the middle voxel could be -1.
The fix you did is basically equivalent to give a normal of (0,1,0) if it is null, but maybe it should not have been null in the first place.

Anyways, I was able to fix one cause thanks to reproducing it the `dmc_test` scene. The best way to figure out why it happens in the other case is to do the same.

**Comment by Zylann** [comment]
With the Transvoxel merge, I also introduced a change to how normals are calculated. It seems to still cause darkening, but maybe it won't go completely black this time?

**Comment by tinmanjuggernaut** [comment]
As [mentioned](https://github.com/Zylann/godot_voxel/issues/2#issuecomment-570764824) in #2, faces still go black on distant LODs using triplanar mapping and still require a shader fix.

**Comment by Zylann** [comment]
I submitted a06de157bf633e417c1f3d73266c786c015516ed which changes again how normals are computed. Now they are normalized later in the process (after marching cubes interpolation) and if length is null it falls back on `(0, 1, 0)` instead of `(0, 0, 0)`. So you might be able to remove your shader fix.

**Comment by tinmanjuggernaut** [comment]
I no longer see any faces showing black or unusually dark. The shader fix is no longer necessary. Great work!
