### ISSUE TITLE
GDExtension dumps empty type for VoxelInstanceLibraryMultiMeshItem.hide_beyond_max_lod property

### ISSUE THREAD

**Issue by Superbelko** [Zylann/godot_voxel#592]
**Describe the bug**
Running `godot --dump-gdextension-api` with voxel module emits `extension_api.json` containing `VoxelInstanceLibraryMultiMeshItem` with a property `hide_beyond_max_lod` having empty type.

**To Reproduce**
1. Build godot with voxel module
2. Dump GDExtension API by running `godot --dump-gdextension-api`
3. Open the `extension_api.json` in your preferred text editor, scroll down to `hide_beyond_max_lod` property
4. See error - type field is empty

**Expected behavior**
Property should have correct type, getter method has a `bool` in this case.

**Screenshots**
![screenshot](https://github.com/Zylann/godot_voxel/assets/22953563/178885d1-d1ac-4ce0-9e5c-a30c18ef9169)

**Environment**
- OS: Windows 11 Pro x64 / MSVS C++ compiler v14.3
- Godot version 4.3 dev2
- Module version 7ebf64cd7e9d5e95a7c2e7e4f13010091c7e72eb

**Comment by Superbelko** [comment]
The problem is this line, remove `PROPERTY_HINT_RESOURCE_TYPE` and it will work.

https://github.com/Zylann/godot_voxel/blob/7ebf64cd7e9d5e95a7c2e7e4f13010091c7e72eb/terrain/instancing/voxel_instance_library_multimesh_item.cpp#L657-L658

**Comment by Zylann** [comment]
Fixed in 3e9e4ee35d9feac235cf76c459ef58cfa75266d9

**Comment by Superbelko** [comment]
It seems to work fine since then, I think this can be closed now. Thanks.
