### ISSUE TITLE
Can't find file editor/editor_scale.h.

### ISSUE THREAD

**Issue by Malkverbena** [Zylann/godot_voxel#595]
**Describe the bug**
Seems that the godot file "editor/editor_scale.h" has been moved to another directory  "editor/theme/editor_scale.h".
Because this change it's not possible to compile the module.

**To Reproduce**
1. Just compile the module nortmaly with the latest godot version.

/media/cleber/DATA/COMPILATIONS/godot_modules/voxel/editor/fast_noise_2/chart_view.cpp:4:10: fatal error: editor/editor_scale.h: No such file or directory
    4 | #include <editor/editor_scale.h>

**Environment**
- OS: Ubuntu 22.04
- Graphics card: AMD Radeon RX 580 Series (RADV POLARIS10)
- Godot version4.4.3
- Module version: commit f14552e
- Renderer used: Vulkan

**Comment by Zylann** [comment]
Should be fixed in 71bf9a92c793adb74155b134232df8b22371b08f

**Comment by Malkverbena** [comment]
Thanks! It's working like a charm now!
