### ISSUE TITLE
SDF terrain artifacts near chunk edges

### ISSUE THREAD

**Issue by spiderworm** [Zylann/godot_voxel#603]
**Describe the bug**
I'm not sure how to technically describe this issue, but it seems that SDF terrains generated by the Transvoxel mesher have unwanted artifacts. These artifacts appear to happen at the edges of chunks.

**To Reproduce**
1. Add VoxelTerrain
2. Set min bounds of (-64, 0, -64) and max of (64, 32, 64)
3. Chunk size 16
4. VoxelMesherTransvoxel
5. VoxelGenerator `@tool` script with the following code for `_generate_block`:
```
func _generate_block(buffer : VoxelBuffer, origin : Vector3i, lod : int) -> void:
	var block_size := int(buffer.get_size().x)
	
	for xo in block_size:
		var x = origin.x + xo
		for yo in block_size:
			var y = origin.y + yo
			for zo in block_size:
				var z = origin.z + zo
				
				var v: float = clamp(y - 9.5, -1, 1)
				buffer.set_voxel_f(v, xo, yo, zo, 1)
```
6. Ensure `Run Stream in Editor` is enabled
7. `Terrain > Regenerate`
8. Wait for mesh to build, artifacts should be visible on some of the sides of the mesh

**Expected behavior**
A flat terrain will generate without odd artifacts on the sides

**Screenshots**

[Screencast from 02-20-2024 03:19:16 PM.webm](https://github.com/Zylann/godot_voxel/assets/1002246/39fa9bc0-060c-4844-b7c7-7b82f3bc3302)

**Environment**
- OS: Ubuntu
- Graphics card: NVIDIA GeForce GTX TITAN
- Godot version: ![image](https://github.com/Zylann/godot_voxel/assets/1002246/933c6748-336b-4280-939e-bf4688761c7d)
- Module version (or commit hash if you got it from Github directly): not sure
- Renderer used: Forward+

**Comment by Zylann** [comment]
There is a `VoxelGeneratorFlat` for testing, which doesn't produce the same artifacts, but there is one:

![image](https://github.com/Zylann/godot_voxel/assets/1311555/62d916b7-034a-447b-af71-2a47fc22d29e)

**Comment by spiderworm** [comment]
Thank you for finding that, yes, I believe my error is fixed and I didn't fully understand how to correctly use the buffer.

**Comment by Zylann** [comment]
Found the cause of the [artifact](https://github.com/Zylann/godot_voxel/issues/603#issuecomment-1955739483) in 44c35df6bccf0b99fa6ec61d665858e2ba26861f
