### ISSUE TITLE
Issues to compile due the change of paths of some godot files. 

### ISSUE THREAD

**Issue by Malkverbena** [Zylann/godot_voxel#606]
**Can't find files.**
There was a change in the path of certain files in the Godot tree.
Several files has been moved from  "godot/scene/resources/"  to  "godot/scene/resources/3d"

**Comment by Zylann** [comment]
Should be fixed in 2e918573f5e71e1a3fecb5eb442d8c0f4ecbb7ce

**Comment by Malkverbena** [comment]
It's working!
