### ISSUE TITLE
Smooth terrain - Strange texture blending issues

### ISSUE THREAD

**Issue by AnnanFay** [Zylann/godot_voxel#609]
**Describe the bug**
Wasn't sure if this is a bug, the docs are out of date or I'm misunderstanding how this is supposed to work.

The docs say "There are 4 weights and 4 indices per voxel, each using 4 bits" however it looks like only 3 indices are being stored? If I dump out the CUSTOM1.x bits I get this:

![image](https://github.com/Zylann/godot_voxel/assets/766048/653618f5-a677-4739-9468-8a5a8d1613f3)

This is setting indices to (1,2,3,4) then increasing by one per unit away from camera. (2,3,4,5), (3,4,5,6), etc.

I was having lots of problems with my base texture leaking into stuff. The documentation doesn't list this a limitation, and API is strange in that it allows you to pass in 4 different indices. Below is using example shader from docs setting a single texture per voxel. You can see the bricks (texture 0) are included everywhere.

![image](https://github.com/Zylann/godot_voxel/assets/766048/c2f3965b-903b-4b53-a49b-555fb04b92ac)

Even setting the first texture to have a 0 weight still includes it, so maybe there is an issue with weights.

Hard coding a single texture, with forced weight to 0:
```c#
                    indicesValue = VoxelTool.Vec4IToU16Indices(new(0, 5, 6, 7));
                    weightsValue = VoxelTool.ColorToU16Weights(new(0f, 1f, 0f, 0f));
                    buffer.SetVoxel((ulong)indicesValue, x, y, z, Indices);
                    buffer.SetVoxel((ulong)weightsValue, x, y, z, Weights);
```
![image](https://github.com/Zylann/godot_voxel/assets/766048/8e31fc73-5486-4f23-a6a9-4112bf4b5b5f)

My current work around is to set first texture to always be 0, and disable loading it in the shader code.

```c
    vec3 blending = get_triplanar_blend(v_normal);
    vec3 col0 = vec3(0,0,0);
    vec3 col1 = texture_array_triplanar(u_texture_array, v_pos * uv_scale, blending, v_indices.y).rgb;
    vec3 col2 = texture_array_triplanar(u_texture_array, v_pos * uv_scale, blending, v_indices.z).rgb;
    vec3 col3 = texture_array_triplanar(u_texture_array, v_pos * uv_scale, blending, v_indices.w).rgb;
```

![image](https://github.com/Zylann/godot_voxel/assets/766048/61c42fb6-dedc-4f91-bb7f-754ba44a3fb4)

In case it helps, the main part of my testing code:

```c#
                    buffer.SetVoxel((ulong)VoxelTool.Vec4IToU16Indices(new(
                        Math.Abs(gz + 0) % 16,
                        Math.Abs(gz + 1) % 16,
                        Math.Abs(gz + 2) % 16,
                        Math.Abs(gz + 3) % 16
                    )), x, y, z, Indices);
                    buffer.SetVoxel((ulong)VoxelTool.ColorToU16Weights(new(0.1f, 0.2f, 0.3f, 0.4f)), x, y, z, Weights);
```

```c
shader_type spatial;

varying vec3 v_normal;
varying vec3 v_pos;

varying vec4 C1;

void vertex() {
    v_pos = VERTEX;
    v_normal = NORMAL;
    C1 = CUSTOM1;
}

void fragment() {
    uint offset = uint(v_pos.x) % uint(32);
    uint i = floatBitsToUint(C1.x);
    uint red = i >> offset; 
    ALBEDO = vec3(
        (red & uint(1)) > uint(0) ? 1.0f : 0.0f,
        0,
        0
    );
}
```

**To Reproduce**
> Linking a minimal project that reproduces the issue may help.

Let me know if above is enough. I can put together a minimal working example if you cannot reproduce.

**Expected behavior**
> A clear and concise description of what you expected to happen.

I expect texture 0 to be treated the same as the other textures and encoding to encode 4 indices.

**Screenshots**

**Environment**
- OS: Windows 10
- Graphics card: AMD RX 6700 XT
- Godot version: 4.2.1
- Module version: 4d14257c1aaeb90d0d2daf09a74daadc353a0a0f
- Renderer(?) used: VoxelLodTerrain, ShaderMaterial, VoxelGeneratorScript, VoxelMesherTransvoxel

**Comment by AnnanFay** [comment]
Okay, figured out what I was doing wrong.

You **must** unset the default texture in the void / air voxels. Otherwise it will merge into every adjacent voxel.

Docs do mention it, but didn't realise this would include the default texturing of the air.

> This mode allows up to 16 textures and blends only the 4 most used ones per voxel.

**Comment by Zylann** [comment]
This is a lot of stuff... without a minimal test project it's hard for me to follow and figure out what could be wrong with this.
4 indices and weights are stored, not 3. Indices must be different too.

> You MUST unset the default texture in the void / air voxels. Otherwise it will merge into every adjacent voxel.

Probably makes sense. Texturing data is volumetric, and in the current implementation, that includes air nearby, before it then filters out textures with lower weight. Does that "solve" everything above?
I know it doesn't sound ideal, but it might take some time before I overhaul texturing (there are different changes/compromises I'd like to make to it)

**Comment by Zylann** [comment]
You may try with the changes in this commit 9087932d39806bfc7e335030084643e0a85c0472

**Comment by AnnanFay** [comment]
Thank you. Knowing that I need to unset air textures did solve the direct problem for me. Though removing air texturing does seem much more intuitive.

It's not clear if the change has any larger ramifications. I just started learning about SDFs this year. Maybe there are some tricks to using air textures.

The only case against it I can think of is if the system was changed to allow more blending than textures on a voxel. You could have 4x blending with only 2x textures per voxel. This would require using air-textures, or 'checkerboarding' ground textures to get 4x blending, but save some voxel bits.

**Comment by Zylann** [comment]
> The only case against it I can think of is if the system was changed to allow more blending than textures on a voxel. You could have 4x blending with only 2x textures per voxel. This would require using air-textures, or 'checkerboarding' ground textures to get 4x blending, but save some voxel bits.

I don't really understand this. It doesnt make much sense to me to have to maintain texture data in air voxels to affect solid voxels. If what you mean is to allow more than the amount of different textures stored in a voxel somehow, this is not something I'm planning to support. I think the current 4x per voxel is already too much for a variety of reasons.
