### ISSUE TITLE
mono support

### ISSUE THREAD

**Issue by lordee** [Zylann/godot_voxel#61]
Hi,

I attempted to use this with a mono enabled godot, however it broke on generating the glue code.  Am I missing anything here?  Should it work..?

I have compiled from godot git before, however I have not attempted to add a new module in.  Thanks.

**Comment by lordee** [comment]
Not sure if useful:
Generating VoxelLodTerrain.cs...
ERROR: _generate_cs_property: Condition ' getter->return_type.cname != setter->arguments.back()->get().type.cname ' is true. returned: ERR_BUG
   At: modules/mono/editor/bindings_generator.cpp:1406.
ERROR: _generate_cs_type: Failed to generate property 'view_distance' for class 'VoxelLodTerrain'.
   At: modules/mono/editor/bindings_generator.cpp:1278.
ERROR: generate_cs_api: Generation of the Core API C# project failed.
   At: modules/mono/editor/bindings_generator.cpp:1086.
ERROR: handle_cmdline_args: --generate-mono-glue: Failed to generate the C# API.
   At: modules/mono/editor/bindings_generator.cpp:3056.

**Comment by Zylann** [comment]
That one happens because I made the setter accept an `unsigned int` but the getter returns an `int`, so the C# build isn't happy. I'll fix that one, but there could be more remaining.

**Comment by Zylann** [comment]
I pushed a fix in 1ad71c5d9cb3f6569ace039ddb97f682ef57d488, can you retry?

**Comment by lordee** [comment]
While I can build against master, I'm seeing a lot of warnings for comparisons between signed and unsinged ints (vodel_data_loader etc)

**Comment by lordee** [comment]
Can confirm it builds correctly and voxelterrain node is available, am yet to test it all, but thanks for the quick response

**Comment by tinmanjuggernaut** [comment]
I don't have a C# build setup and suspect Zylann doesn't either. If you can post a list of all warnings, we could make a PR. Or if you're feeling adventurous you could try one yourself to squash those warnings.

**Comment by lordee** [comment]
Hi,

Here's a gist of the warnings:
https://gist.github.com/lordee/c01555cd222d49a94ab25f8c32891cd1

I would be happy to do a PR but it won't be for quite a while, understand that this may be way down on the list for you guys too.  Thanks for the help so far.

**Comment by Zylann** [comment]
GCC is very picky about integer signedness, while MSVC doesn't care (that's the main compiler I use). I sometimes build with MinGW just to double-check but some buggers still slip through.

**Comment by tinmanjuggernaut** [comment]
GCC doesn't complain about any of this, even with warnings=all, which is the default. I don't know how the mono build works or why GCC doesn't complain about these warnings. I see the code issues, but can't get the warnings.

**Comment by Zylann** [comment]
Would be nice to get to a stage where Mono builds so we can make a 3.1.1 branch as stated in #64
