### ISSUE TITLE
VoxelToolLodTerrain.stamp_sdf() doesn't work

### ISSUE THREAD

**Issue by Piratux** [Zylann/godot_voxel#612]
**Describe the bug**
As the title says, `VoxelToolLodTerrain.stamp_sdf()` doesn't work ~90% of the time. On other 10% of the time, I'm not getting expected mesh shape.

More precisely, by "90% of the time", I mean when I start the project, if I get unlucky (90% chance), no matter what I do, `stamp_sdf()` produces no result. In remaining case, when starting the project, if I get lucky (10% chance), I always see some result from `stamp_sdf()`.

I have checked whether `stamp_sdf()` works in the following project but I get similar results - sometimes I see mesh stamped, sometimes nothing happens:
- https://github.com/Zylann/voxelgame/tree/master/project/smooth_terrain

I have checked whether SDF data is correct with the following, but in all cases I saw no issues:
- Printed SDF data to PNGs from `_mesh_sdf.get_voxel_buffer().debug_print_sdf_y_slices(1.0)`.
- Added prints in internal `write_box_template()` function.

I see no errors in console.

**To Reproduce**
1. Download minimal reproduction project.
2. Run it with Godot.
3. Follow the instructions shown in window upon running the project (see image below).
4. Notice that `VoxelToolLodTerrain.stamp_sdf()` doesn't work. If it does work, try closing the project and running it again (because as mentioned, in some cases it works and in some cases it doesn't).
![image](https://github.com/Zylann/godot_voxel/assets/58703216/6564536d-8c5a-4a20-a96d-7947f6fcf85f)

**Expected behavior**
See `stamp_sdf()` modify terrain using mesh shape.

**Environment**
- OS: Windows 10
- Graphics card: NVIDIA GeForce GTX 650 Ti
- Godot version: v4.2.2.rc.custom_build.474589eb8 (locally compiled 4.2 Godot with voxel module)
- Module version: Commit link: https://github.com/Zylann/godot_voxel/commit/e17cb1a5fcf6e160350c89b36278ffef35681e98
- Renderer used: Forward+

**Zip with minimal reproduction project**
[stamp_sdf_issue_mrp.zip](https://github.com/Zylann/godot_voxel/files/14808650/stamp_sdf_issue_mrp.zip)

**Comment by Zylann** [comment]
Try with this fix 75cfda9854a2f45d00298a48ec84f7c9201ab606

**Comment by Piratux** [comment]
Alright, let me try.

**Comment by Piratux** [comment]
Okay, it seems that it works now, thanks.

I'm going to close this now.
