### ISSUE TITLE
Wrap around chucks

### ISSUE THREAD

**Issue by Shadowblitz16** [Zylann/godot_voxel#615]
**Is your feature request related to a problem? Please describe.**
It's related to spherical voxel planets.
I need a way to limit and wrap around the world chunks

**Describe the solution you'd like**
Can we have a the following options for chunks...
World Chunk Rows
World Chunk Columns
Wrap Chunks by X
Wrap Chunks by Z

**Describe alternatives you've considered**
I considered moving to unreal engine.

**Additional context**
I am going to try to find a shader to render the planets above a certain height

**Comment by Zylann** [comment]
Sorry but I have no plans to implement wrapping either.

**Comment by Shadowblitz16** [comment]
Now your just sounding lazy.

I would rename this to godot-minecraft-voxel-tools because you're literally tying this plugin to minecraft specific features only.

There is alot more to voxel tools then what minecraft has

**Comment by JekSun97** [comment]
> Now your just sounding lazy.
> 
> I would rename this to godot-minecraft-voxel-tools because you're literally tying this plugin to minecraft specific features.
> 
> There is alot more to voxel tools then what minecraft has to offer

I would also dream of such functionality, but the author already does enough work for the plugin.
SDF is a great achievement for an engine like Godot, so don’t blame it for laziness, learn C++ and you can add this wonderful plugin yourself, or switch to UE.

**Comment by Shadowblitz16** [comment]
> or switch to UE.

@JekSun97 that's what I am doing, I am tired of waiting for godot.
I just need a game engine that provides the community and resources to make my game.
