### ISSUE TITLE
Large VoxelBlokyLibray produce lag

### ISSUE THREAD

**Issue by ddel-rio** [Zylann/godot_voxel#619]
**Describe the bug**
As I increased the number of models in the VoxelBlokyLibray I noticed that it was getting slower.
After investigating I discovered that the get_motion function of the BoxMover class was the cause.

This is a highly limiting problem for me.
Right now the player is the only animated entity in my game, I don't even want to imagine what will happen when I create the mobs.

**To reproduce**
Simply make use of a VoxelBlokyLibray with a large number of elements.

In the attached MRP I simulate the behavior of my game with the script script_stress_test.gd.
By increasing the parameter "stress models quantity" to 10000 for example you can easily see the effects of this bug.
On the other hand if you comment line 37 of the script script_voxel_body.gd the lag disappears completely.

[mrp.zip](https://github.com/Zylann/godot_voxel/files/14876079/mrp.zip)

**Expected behavior**
The number of models in VoxelBlokyLibray should not affect the FPS of the game.

**Environment**
- OS: Windows 11
- GPU: NVIDIA GeForce RTX 4070 Laptop
- Godot Version: v4.3.dev.custom_build [f6a78f83a]
- Module Version: a0628c7d
- Renderer: Vulkan (Forward+)

**Comment by Zylann** [comment]
> As I increased the number of models in the VoxelBlokyLibray I noticed that it was getting slower.
After investigating I discovered that the get_motion function of the BoxMover class was the cause.

The number of models shouldn't slow things down, though if we're talking about extreme amounts (like 10,000) I'm curious to know how slow it becomes.
BoxMover looks up every voxel intersecting the box's motion. Each voxel is an 2-byte integer that is used to directly index *into an array of baked models data* (not even a dictionary), which is as fast as things could be. Then it does some simple checks and gets the model's bounding boxes. *So in terms of logic, the number of models in your library should not matter*. But maybe something else is affecting this?

Why do you need such a huge amount of models? Unless you already have a huge amount of content in your game, I suspect that you might be using the wrong approach for something, even though technically the engine should be able to support up to 65,536.

Looking at your project:
It is not that minimal, there are a lot things that should not be necessary for that kind of test. I have to inspect every file in every MRP and find out how to use them so it takes a bit longer the more things there is in them.

But the good news:
This is a *very stupid* bug :D It took only one character to fix it 57ccea90770dd778ebe7332b667509cc0175d74f

**Comment by ddel-rio** [comment]
> Why do you need such a huge amount of models? Unless you already have a huge amount of content in your game, I suspect that you might be using the wrong approach for something, even though technically the engine should be able to support up to 65,536.

The 10,000 models was an example quantity to do the stress test.
My game actually has 1173 models right now and counting.
However, I have not placed them manually.
I don't want to go into details that are not relevant right now but I have been able to reach that number of models thanks to a system that I have devised to make it easier for artists and designers to create new blocks and their variants (especially useful in the case of stairs and fences).

> Looking at your project:
> It is not that minimal, there are a lot things that should not be necessary for that kind of test. I have to inspect every file in every MRP, find out how to use them and make sure of what I'm running, so it takes a bit longer the more things there is in them.
> I updated the issue template to mention these things: https://github.com/Zylann/godot_voxel/commit/fa02ca163d1f7ae5b5505a3780c922f64bdf4b01

I am aware that the project I have shared is more complex than it should be and I apologize for that.
I have been accumulating bugs and doubts that I have not been able to resolve.
But since I recently came across this one that was especially blocking, I decided to directly publish all the bugs with a single mrp.
Now that I look back on it I think it would have been better to divide the project more for each bug.

> But the good news:
> This is a very stupid bug :D It took only one character to fix it https://github.com/Zylann/godot_voxel/commit/57ccea90770dd778ebe7332b667509cc0175d74f
> Thank you for raising that because it could have taken a while before being spotted.

I'm very glad it could be resolved so quickly!
I have recently tested the update and it already works perfectly, so I am closing the thread.
All the bugs I have shared are potentially dangerous to cancel my project but for me this was the worst.
Thank so much for your help.
