### ISSUE TITLE
Moving terrain around

### ISSUE THREAD

**Issue by Dimev** [Zylann/godot_voxel#62]
Currently, it's not possible to move the terrains (both normal and lod) around in the scene.

for static terrain, this may not be necessary, but it could be useful in some cases.

**Comment by Zylann** [comment]
This may be done at some point, but currently it's low priority.

**Comment by Dimev** [comment]
So It's more than transforming the meshes + collision and the viewer position + heading.

also, what are the current priorities?

**Comment by tinmanjuggernaut** [comment]
You can move voxels around, just not the whole node. Look in the dmc_test demo for an example. But you might need to change get_stats() to get_statistics() if it complains. Hasn't been updated yet.

Though I can't speak to @Zylann 's priorities, I can say he's currently working on VoxelLodTerrain infinite paging, as well as bug fixes or compiling issues as they are reported. 

I think next steps we've chatted about might include getting VLT to support editability, so he can refactor VT to be blocky only and VLT to be smooth only.

**Comment by Dimev** [comment]
Thanks
Moving voxels around can be a temporary solution, but that can get really slow if I want to do it every frame.
Also will VLT support multiple materials like VT does?

**Comment by tinmanjuggernaut** [comment]
> Moving voxels around can be a temporary solution, but that can get really slow if I want to do it every frame.

Maybe. If you increase the movement size in the demo, it moves quickly. I'm curious as to what the performance actually looks like with more objects. It might be faster than you think, especially if your code is implemented in C++. 

I'm curious about tying a voxel to a physics body. Zylann has added #33 to the future queue and this might be a simpler node that could be moved around more easily by script or maybe the physics engine.

> Also will VLT support multiple materials like VT does?

Zylann will have to answer.

**Comment by Zylann** [comment]
Supporting multiple materials in smooth terrain is a bit trickier than blocky. Blocky is litterally batching pre-made models with sharp corners so it makes sense to provide multimaterials.

Smooth terrain on the other hand is watertight and continuous, so the same problem arise as for heightmap terrain, requiring a different approach like triplanar mapping and texture arrays/splatmapping. It's possible to have multimaterials the same ways blocky does but it won't have any smooth transition.
If you need to discuss more about texturing smooth terrain, it would be better to do so in another issue.

**Comment by Dimev** [comment]
Ok, Thanks for the response

**Comment by Zylann** [comment]
The very latest commits include the ability to move, scale and rotate both terrain types.
