### ISSUE TITLE
Cannot delete saved terrain

### ISSUE THREAD

**Issue by ddel-rio** [Zylann/godot_voxel#620]
**Describe the bug**
When I try to delete a recently opened terrain I get an error saying that the file is still in use even though there is no longer any VoxelTerrain in the scene.

I'm using VoxelStreamSQLite.
This bug causes me to be unable to delete saved games.

**To reproduce**
I have simulated the behavior of my game in the attached MRP.

1. Create a world.
2. Back to menu.
3. Delete the world.

[mrp.zip](https://github.com/Zylann/godot_voxel/files/14876066/mrp.zip)

**Expected behavior**
The engine should detect when a terrain is not being used to stop using its file.

**Screenshots**

![Screenshot 2024-04-04 142826](https://github.com/Zylann/godot_voxel/assets/57621742/972e5495-c3df-44ab-b18c-097714c0d221)

**Environment**
- OS: Windows 11
- GPU: NVIDIA GeForce RTX 4070 Laptop
- Godot Version: v4.3.dev.custom_build [f6a78f83a]
- Module Version: a0628c7d
- Renderer: Vulkan (Forward+)

**Comment by Zylann** [comment]
> The engine should detect when a terrain is not being used to stop using its file.

It already does. The way it does that, is from Godot's resource reference counting. `VoxelStreamSQLite` is a resource, and when nothing else references it, it should get destroyed, in turn destroying the SQLite connection. So either you still have something in the game still referencing that instance of `VoxelStreamSQLite` (in a `preload`? Or a scene which in turn references it?), or there is some sort of leak.

**Comment by ddel-rio** [comment]
Although I have read the documentation, I did not realize that the VoxelSaveCompletionTracker class existed.
Thanks for showing it to me.

Now I have been able to do the following code and it seems to work fine:

```gdscript
var tracker: VoxelSaveCompletionTracker = terrain_manager.terrain.save_modified_blocks()
while !tracker.is_complete():
	await get_tree().process_frame
(terrain_manager.terrain.stream as VoxelStreamSQLite).database_path = ""
```

But now when I leave a world that is still loading chunks I get this error:

![Captura de pantalla 2024-04-05 184138](https://github.com/Zylann/godot_voxel/assets/57621742/dfa5abae-3019-4a71-82e2-1939c10783b2)

Should I ignore it or is it important?

**Comment by Zylann** [comment]
Those errors might not prevent the game from running in this specific case, but could indicate problems otherwise.

One option that comes to mind is to simply create a new instance of `VoxelStreamSQLite` and replace the old one. This way, the old one can just "die" off and close by itself, once all asynchronous tasks have finished referencing it. Unfortunately that doesn't go well with explicit closing. You'd have to handle the case where deleting a world is still locked for a little while after leaving a world.

If you want to carry on with the explicit "closing" approach, the engine will have to be changed to not consider a "not configured" database as not being an error and fail silently.

**Comment by ddel-rio** [comment]
Thanks, it's already solved.
It seems to save well and the errors no longer appear by making two changes:
1. Create the stream at runtime.
2. Unassign it from the terrain when saving instead of deleting the path:
```gdscript
#(terrain_manager.terrain.stream as VoxelStreamSQLite).database_path = ""
terrain_manager.terrain.stream = null
```

**Comment by Zylann** [comment]
> Unassign it from the terrain when saving instead of deleting the path:

Are you doing this only when leaving the world? If so, why not just destroy the terrain/scene? Because that would have the same effect, and I'd even recommend doing that rather than re-using the same terrain node for example.

**Comment by ddel-rio** [comment]
Yes, I do this only when leaving the world.
And it's true, it really isn't necessary to unassign the stream.
I just tried your recommendation and it works well.
