### ISSUE TITLE
GDScript breakpoints cause VoxelGeneratorScript to stop working

### ISSUE THREAD

**Issue by ArchLinus** [Zylann/godot_voxel#628]
**Describe the bug**
Whenever a breakpoint is hit in GDscript and then continued, terrains with a VoxelGeneratorScript will stop generating new blocks. It doesn't matter where the breakpoint is or when its hit, the result is the same. `_generate_block` will not get any more calls. I've tested a few other generator types and it seems that it only happens with VoxelGeneratorScript.

**To Reproduce**
1. Create the following script:

```
class_name TestGenerator
extends VoxelGeneratorScript

func _generate_block(out_buffer, origin_in_voxels, lod):
	if lod != 0:
		return

	for z in range(out_buffer.get_size().z):
		for y in range(out_buffer.get_size().y):
			for x in range(out_buffer.get_size().x):
				if y + origin_in_voxels.y == 0:
					out_buffer.set_voxel(1, x, y, z, VoxelBuffer.CHANNEL_TYPE)
```

2. Assign it to a blocky terrain
3. Place a breakpoint anywhere
4. Run the game and hit continue after breakpoint is hit
5. Observe that the terrain does not generate.

**Environment**

Godot v4.2.1.stable.mono (17ed84725) - Windows 10.0.22000 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3070 (NVIDIA; 31.0.15.5123) - 12th Gen Intel(R) Core(TM) i5-12600K (16 Threads)

**Comment by Zylann** [comment]
This is not related to the module. I suppose this is how Godot handles breakpoints in GDScript. If you want other threads to continue while one is on a breakpoint, this is something you have to request on the Godot proposals repository.

**Comment by ArchLinus** [comment]
> This is not related to the module. I suppose this is how Godot handles breakpoints in GDScript. If you want other threads to continue while one is on a breakpoint, this is something you have to request on the Godot proposals repository.

This is occurring when continuing (F12) after a breakpoint, so no threads *should* be suspended as far as I know.

**Comment by Zylann** [comment]
I don't know why it would do this, but it sounds highly related to GDScript itself. The module doesn't do anything special regarding breakpoints in GDScript.

**Comment by ArchLinus** [comment]
After doing some debugging on the C++ side, I think you're right that it's a Godot issue. It seems every `_generate_block` thread gets stuck locking mutexes in the `RemoteDebugger` class. I will take this issue up with the godot repository.

**Comment by Zylann** [comment]
Which version of Godot were you using?

**Comment by ArchLinus** [comment]
Was using 4.2.1. Seems like it was fixed on master branch: https://github.com/godotengine/godot/pull/87169. Will test it as soon as it finishes compiling.

**Comment by ArchLinus** [comment]
Can confirm its fixed on master branch.

**Comment by Zylann** [comment]
I tested 4.2.2 using debug builds locally (I use MSVC) and yeah, apparently it's caused by undefined behavior. The vanilla builds are made using MinGW (or whatever cross-compiler) instead of MSVC, which happens to not crash. But MSVC does in debug builds (to signal the mistake I think), and in release builds it just hangs.
