### ISSUE TITLE
How would I spawn the ship on a planet directly?

### ISSUE THREAD

**Issue by sagersmith8** [Zylann/godot_voxel#632]
### Description
I am wondering how to do about spawning the ship on the surface of earth. Moving the spawnPoint doesn't seem to do anything, and its unclear how to get the position of a StellarBody

**Comment by Zylann** [comment]
Sorry, what are you talking about? Is this about the [solar system demo](https://github.com/Zylann/solar_system_demo)?
If so, the voxel module is the wrong repo to ask this.

**Comment by sagersmith8** [comment]
My b, I'll ask over there
