### ISSUE TITLE
Voxel block size

### ISSUE THREAD

**Issue by SixArne** [Zylann/godot_voxel#635]
Hi, is it possible to define the voxel block size?
If so where is this option? can't seem to find it

**Comment by Zylann** [comment]
There is no specific option to change this. You have to scale the terrain currently.

Also this has been asked 3 times already:
https://github.com/Zylann/godot_voxel/issues/105
https://github.com/Zylann/godot_voxel/issues/232
https://github.com/Zylann/godot_voxel/issues/289

**Comment by Zylann** [comment]
Closing in favor of #105
