### ISSUE TITLE
Compile error on Windows 10 with Godot 3.1

### ISSUE THREAD

**Issue by Stibila** [Zylann/godot_voxel#64]
I am unable to compile Godot engine with voxel module as I am getting following error:

```
[Initial build] Compiling ==> modules\voxel\streams\voxel_block_serializer.cpp
voxel_block_serializer.cpp
modules\voxel\streams\voxel_block_serializer.cpp(90): error C3861: 'ERR_FAIL_COND_V_MSG': identifier not found
modules\voxel\streams\voxel_block_serializer.cpp(119): error C3861: 'ERR_FAIL_COND_V_MSG': identifier not found
modules\voxel\streams\voxel_block_serializer.cpp(164): error C3861: 'ERR_FAIL_COND_V_MSG': identifier not found
modules\voxel\streams\voxel_block_serializer.cpp(167): error C3861: 'ERR_FAIL_COND_V_MSG': identifier not found
scons: *** [modules\voxel\streams\voxel_block_serializer.windows.opt.tools.64.obj] Error 2
scons: building terminated because of errors.
```

I am compiling on Windows 10 Pro 64bit. I tried to compile using MinGW and MSVC with same result:
```
scons platform=windows target=release_debug
scons platform=windows target=release_debug use_mingw=yes
```

I have no problem to compile Godot without voxel module.

**Comment by tinmanjuggernaut** [comment]
I just completed a clean build of Godot/master and godot_voxel/master with mingw on win10/64 using  `gcc version 8.1.0 (x86_64-posix-seh-rev0, Built by MinGW-W64 project)`.

What mingw version and executable did you download?

Are you on both master branches?

What commit are you on? 
* Godot  4ee8ecd3
* Voxel   fec6e624f6

Btw, you can add -jX to the end of scons where X is 2x the number of cores you have for optimal multithreaded compiling (assuming you've also installed pywin32).

**Comment by Stibila** [comment]
I installed it vie scoop as per Godot [documentation](https://docs.godotengine.org/en/latest/development/compiling/compiling_for_windows.html).

`scoop install gcc python scons`

```
>gcc --version
gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0

>scoop list
Installed apps:

  7zip 19.00
  dark 3.11.1
  gcc 8.1.0
  lessmsi 1.6.91
  python 3.7.4
  scons 3.1.1
```

But as I said I have same issue when compiling with MSVC.

BTW I used godot branch 3.1, I did not try master.
About multi thread compiling, I am aware of that option, but it has nothing to do with an issue.

**Comment by tinmanjuggernaut** [comment]
VS2019 also compiles master with no warnings or errors.

Please try Godot master and let us know. Maybe that's the problem.

> About multi-thread compiling, I am aware of that option, but it has nothing to do with an issue.

I did not suggest it does. I was just saving you time.

**Comment by tinmanjuggernaut** [comment]
ERR_FAIL_COND_V_MSG is a Godot macro which looks like it was added last month.
https://github.com/godotengine/godot/blame/master/core/error_macros.h

All it does is check an error condition or quit the program if true. Instead of downloading master, you could comment out those lines or just add `#define ERR_FAIL_COND_V_MSG`  or `#define ERR_FAIL_COND_V_MSG(...)`  to the top of the file.

**Comment by Stibila** [comment]
Compiling godot/master branch works without a problem. But since I have no idea how stable it is, I'd rather stick to the godot-3.1.1-stable release.

Adding `#define ERR_FAIL_COND_V_MSG` and `#define ERR_FAIL_COND_MSG` to 2 files did solve this issue, but then I hit another error:

```
[Initial build] Compiling ==> modules\voxel\util\direct_static_body.cpp
direct_static_body.cpp
modules\voxel\util\direct_static_body.cpp(48): error C2660: 'PhysicsServer::body_add_shape': function does not take 4 arguments
E:\Workspace\Godot\godot-3.1.1-stable\servers/physics_server.h(375): note: see declaration of 'PhysicsServer::body_add_shape'
scons: *** [modules\voxel\util\direct_static_body.windows.tools.64.obj] Error 2
```

And after fixing this issue, there is a great chance, there will be another one. So as far as I know, godot_voxel/master works only with Godot/master, not with latest stable release :(

**Comment by tinmanjuggernaut** [comment]
> Compiling godot/master branch works without a problem. But since I have no idea how stable it is, I'd rather stick to the godot-3.1.1-stable release.

I regularly and severely abuse it and don't have any stability issues.

> modules\voxel\util\direct_static_body.cpp(48): error C2660: 'PhysicsServer::body_add_shape': function does not take 4 arguments

Remove the `, false` from that line. I think that is to add the shape in a disabled state, which is unnecessary.

> And after fixing this issue, there is a great chance, there will be another one. 

Maybe, but let's not worry about something that might never happen.

> So as far as I know, godot_voxel/master works only with Godot/master, not with latest stable release :(

Godot_voxel is itself alpha. However is very stable already. And new, incredible features have been added recently, so while you could go to an older revision that will compile natively against 3.1, you'll miss out on a lot. So again, let's not worry over nothing. When there's something tangible, like a compile error, then you can worry about that.

**Comment by Stibila** [comment]
OK, for now I'll check out master branches and play with it a little. But I recommend to establish new voxel branch for every stable branch in Godot project.

**Comment by tinmanjuggernaut** [comment]
It is a good idea, though @Zylann 's call. 

Did you patch the last error I gave you the fix for?

**Comment by Stibila** [comment]
Nah, maybe I'll try later. I've already spent more time on it than I intended to.

**Comment by Zylann** [comment]
We could make stable branch for Godot releases but generally the latest developments are done with bleeding-edge Godot.
Also, if you are concerned about stability, this module might be usable but is still a bit experimental. Even though large parts remained unchanged for months, I don't guarantee forward compatibility :p

**Comment by tinmanjuggernaut** [comment]
The changes I noted were all that was required to compile against the Godot 3.1 branch.

@Zylann Can you make a 3.1 branch? Then I can push a PR into it.

**Comment by Zylann** [comment]
@tinmanjuggernaut I made a 3.1 branch.

**Comment by tinmanjuggernaut** [comment]
This can be closed. The PR should have but didn't for some reason. I tested building the 3.1 branch on both Win10 and linux.
