### ISSUE TITLE
VoxelMeshSDF partition_subdiv description missing info about BAKE_MODE_APPROX_FLOODFILL

### ISSUE THREAD

**Issue by Piratux** [Zylann/godot_voxel#650]
VoxelMeshSDF partition_subdiv parameter description does not mention that partition_subdiv is also used for BAKE_MODE_APPROX_FLOODFILL method, to accelerate sign determination queries.

![image](https://github.com/Zylann/godot_voxel/assets/58703216/3bf4a7f2-8c9b-4768-8159-43151aa3151a)

**Comment by Zylann** [comment]
Added in d4b833b85ca5653dc6efc15b6446cfedc9b6274c
