### ISSUE TITLE
VoxelMeshSDF get_aabb() mentions non existant margin property

### ISSUE THREAD

**Issue by Piratux** [Zylann/godot_voxel#651]
VoxelMeshSDF get_aabb() description mentions margin instead of margin_ratio.

![image](https://github.com/Zylann/godot_voxel/assets/58703216/a9208c8e-8a5d-436f-9974-5e6274bd53e8)

**Comment by Zylann** [comment]
Fixed in c4012c9cca9b840cafcfc9b000546d27e5e110c3
