### ISSUE TITLE
Dummy page "2" not needed anymore

### ISSUE THREAD

**Issue by Piratux** [Zylann/godot_voxel#652]
Dummy page called "2" is not needed anymore in main documentation:
https://voxel-tools.readthedocs.io/en/latest/___2/

![image](https://github.com/Zylann/godot_voxel/assets/58703216/686b3ed8-51d7-4e36-a83a-bac0d7a1764b)

**Comment by Zylann** [comment]
Removed in 297286251af934ea2fb5da93e679e8b3c1ad4fb6
