### ISSUE TITLE
VoxelModifierMesh changing isolevel does not update preview

### ISSUE THREAD

**Issue by Piratux** [Zylann/godot_voxel#656]
**Describe the bug**
Changing isolevel of VoxelModifierMesh does not update preview mesh, like changing transform changes the preview.

See video:
https://github.com/Zylann/godot_voxel/assets/58703216/ada175c5-2cc3-4f5e-9c68-9e52531db2a7

**To Reproduce**
1. Create `VoxelLodTerrain` and add `VoxelGeneratorFlat` generator.
2. Under `VoxelLodTerrain` add `VoxelModifierMesh`. 
3. For `VoxelModifierMesh` create any mesh.
4. Change isolevel of `VoxelModifierMesh`.
5. Notice preview doesn't update.

**Expected behavior**
Changing isolevel, should immediately update preview mesh with new isolevel value.

**Environment**
- OS: Windows 10
- Graphics card: GTX 650 Ti
- Godot version: 4.2.2 stable
- Module version: 1.2.0
- Renderer: Forward+

**MRP**
[Test VoxelModifierMesh isolevel not auto updating.zip](https://github.com/user-attachments/files/15809813/Test.VoxelModifierMesh.isolevel.not.auto.updating.zip)

**Comment by Zylann** [comment]
Fixed in 50719b13b0c7392473717e4b606985704b823c58
