### ISSUE TITLE
Is the VoxelGraphGenerator usable as a base for the generation in a VoxelGenerationScript?

### ISSUE THREAD

**Issue by Derpysphere** [Zylann/godot_voxel#657]
or do I need to recode the GraphGen as a ScriptGenerator?

Perhaps maybe use the VoxelGraphGenerator as a pass in a Multipass generator?

To be specific, Can you use the output of a VoxelGraph as the base terrain, of say a multipass generator?
Just wondering

**Comment by Zylann** [comment]
You can invoke any generator using their `generate_block` function and passing the buffer you want to generate values in.
You can pass directly the `voxels` buffer you get from `func _generate_blocks` (though be careful to not leave any data you don't want at the final output, for example if you generate SDF but the end result will be TYPE, you should cleanup that channel when you're done using it).
You can also create the VoxelBuffer yourself as an intermediate.

**Comment by Derpysphere** [comment]
Does the VoxelGraph have a referenceable "func _generate_blocks"? or is there a way to directly get the output of a graph?

**Comment by Zylann** [comment]
`VoxelGeneratorGraph` inherits `VoxelGenerator`, therefore it has a `generate_block` function you can call.

**Comment by Derpysphere** [comment]
Ahhh so, correct me if I'm wrong, but that means that you could use its "voxels" buffer directly in a custom voxelgeneratorscript?

**Comment by Zylann** [comment]
Well, I guess yeah, you call its `generate_block` method, and it will fill the buffer you give to it.

**Comment by Derpysphere** [comment]
Awesome.

**Comment by Derpysphere** [comment]
Here's another quick question, are the multipass generators, and the Generator Scripts compatible? from reading the documentation it doesn't appear so,  but I thought I'd ask.

**Comment by Zylann** [comment]
What do you mean by "compatible"? They are definitely different in a lot of ways, but it depends what you're trying to do.

**Comment by Derpysphere** [comment]
Mainly thinking in forms of generation, like, for example, could I use a voxelgeneratorscript to create the first pass for a Multipass generator? my main problem is that I can't seem to figure out how to properly use the multipass generator, how do I use the voxel tool, if the voxel tool requires a position vector, which is not passed in the _generate_pass function?

**Comment by Zylann** [comment]
> could I use a voxelgeneratorscript to create the first pass for a Multipass generator?

Probably, though I dont see why you wouldn't directly code it in the multipass generator.

> my main problem is that I can't seem to figure out how to properly use the multipass generator

It's explained here: https://voxel-tools.readthedocs.io/en/latest/generators/#multi-pass-generation-with-voxelgeneratormultipasscb
And there is a demo here: https://github.com/Zylann/voxelgame/tree/master/project/multipass_generator

> how do I use the voxel tool, if the voxel tool requires a position vector, which is not passed in the _generate_pass function?

VoxelTool is just an interface to edit voxels. Positions you use with it depend on what you're editing, but in the case of multipass it's basically a sub-region of the world which is given to you by specialized methods on `VoxelToolMultipassGenerator` (which is passed to you from `_generate_pass`).
