### ISSUE TITLE
VoxelMeshSDF incorrect BAKE_MODE_ACCURATE_NAIVE description about sign calculation

### ISSUE THREAD

**Issue by Piratux** [Zylann/godot_voxel#658]
VoxelMeshSDF baking mode BAKE_MODE_ACCURATE_NAIVE in description mentions, that SDF sign is calculated using raycasts. However only BAKE_MODE_APPROX_FLOODFILL does this.

Other methods calculate sign based on dot product between triangle normal and position (not exactly sure how or why this works).
See https://github.com/Zylann/godot_voxel/blob/master/edition/mesh_sdf.cpp#L674

![image](https://github.com/Zylann/godot_voxel/assets/58703216/4c0cc996-d98e-4aa3-ac9e-30de0f9c7f20)

**Comment by Zylann** [comment]
Interesting. I don't remember why that is. I wonder how relevant it is to detail this so much though, it gets out of sync so easily...

**Comment by Zylann** [comment]
Changed in 1111df304a1f8b0b249b064674338d98398e95d6
