### ISSUE TITLE
Multiple materials do not work (Blocky)

### ISSUE THREAD

**Issue by CorvusUrro** [Zylann/godot_voxel#66]
Each Block will render voxels that have the material with the smallest number as material 0 (so a block with only voxels with material 1 will appear as material 0)
Adding more materials to the Block cause holes to be rendered in the block

A block with only one material in it, Rendering as material 0
![0](https://user-images.githubusercontent.com/9460162/64596037-851a0000-d3f6-11e9-8039-ee52ec37c5bc.PNG)
Same block but with a single voxel replaced that has a different material
![1](https://user-images.githubusercontent.com/9460162/64596096-a4b12880-d3f6-11e9-928b-cdb2c08fc15c.PNG)
Block with a single horizontal line of voxels replace (shown by that red rectangle) causing holes to be rendered.
![2](https://user-images.githubusercontent.com/9460162/64596276-f194ff00-d3f6-11e9-98a7-e92793794769.PNG)
![2red](https://user-images.githubusercontent.com/9460162/64596284-f35ec280-d3f6-11e9-8dab-139266cc1a90.png)

A different block with a row of voxels with alternating materials. Note the entire row is filled, just most of them are invisible.
![3](https://user-images.githubusercontent.com/9460162/64596397-2903ab80-d3f7-11e9-808f-df8f00659f6d.PNG)

**Comment by Zylann** [comment]
That might have been broken when smooth option was added to this type of terrain, I'll have a look later

**Comment by Zylann** [comment]
Indeed, this is supposed to be a sphere of water on the ground:

![image](https://user-images.githubusercontent.com/1311555/64637690-3d967280-d3fc-11e9-8500-6b7b44785fde.png)

**Comment by Zylann** [comment]
Better.

![image](https://user-images.githubusercontent.com/1311555/64644649-02e80680-d40b-11e9-807c-f5fa715e1162.png)

**Comment by Zylann** [comment]
The fixes are in 026fa9665495a0e92d1d96dafe925980c13e1793 and f59b34f1a06de99614f360eadb02e065cc2601b0 in the `lod_editing` branch, but I'm going to merge soon.

**Comment by CorvusUrro** [comment]
((Not entirely sure if it's related but I also don't fully understand the intent behind the feature and so don't want to open a new bug report, but the "color" variable on voxels doesn't do anything.

**Comment by Zylann** [comment]
Indeed, it doesn't. It was there originally for use cases involving no textures but I didn't include it in the meshing process...

**Comment by CorvusUrro** [comment]
It could be useful in my current project, To be able to alter the colour of a voxel, without needing an entirely new material.

**Comment by tinmanjuggernaut** [comment]
Maybe color could tie to vertex color, which could also be used on smooth. Actually, I guess we can just apply vertex color ourselves and apply it in the material, on smooth or blocky, so if there was a color setting, it could just auto-fill.

**Comment by Zylann** [comment]
@tinmanjuggernaut that color setting only works for the blocky meshing at the moment. Material info for smooth terrain is a different issue due to its nature.
I can apply it as vertex color on top of AO maybe.

**Comment by Zylann** [comment]
Voxel color is now applied as modulation of vertex color.

**Comment by addmix** [comment]
Did you have to write your own generator to get the multiple block types?

**Comment by menip** [comment]
@addmix yes, you need to first create the different blocks, then can set a particular voxel to that type in generator. 
If you haven't yet, take a look at https://github.com/Zylann/voxelgame
