### ISSUE TITLE
VoxelModifierMesh does not show up under VoxelTerrain

### ISSUE THREAD

**Issue by Piratux** [Zylann/godot_voxel#660]
**Describe the bug**
VoxelModifierMesh does not show up under VoxelTerrain.

See image:
![image](https://github.com/Zylann/godot_voxel/assets/58703216/4a52dfa0-8b02-43f8-80fa-67fc01d6f6be)

I'm guessing it works only under VoxelLodTerrain. In that case, it's missing configuration warning (like the one on VoxelModifierSphere):
![image](https://github.com/Zylann/godot_voxel/assets/58703216/e666d638-4576-4609-b1d0-0fa6ce531678)

**Comment by MGilleronFJ** [comment]
Modifiers only work on VoxelLodTerrain indeed.

Also, the configuration warning *does* exist for all modifiers, it's here: https://github.com/Zylann/godot_voxel/blob/297286251af934ea2fb5da93e679e8b3c1ad4fb6/modifiers/godot/voxel_modifier_gd.cpp#L161
I don't know why you aren't getting one for mesh modifiers.

**Comment by Zylann** [comment]
Added warning in aac70259edb1bec4a430ece72cb5ddef09442ff0
