### ISSUE TITLE
Godot crashes when trying to add any element to the VoxelBlockyTypeLibrary

### ISSUE THREAD

**Issue by kubaxius** [Zylann/godot_voxel#663]
**Describe the bug**

As the title says, Godot crashes when I try to add any element to the VoxelBlockyTypeLibrary. This happens both when using the "Add Element" button, and when trying to increase the size of the array. At first, I thought it was an error with my custom build, but the same happens when using the newest build from GitHub, even on a completely new project.

**To Reproduce**
1. Create VoxelBlockyTypeLibrary
2. Open it in the editor
3. Click on the Types field
4. Try to expand the Types Array either by adding element with the button, or typing new number in the "size" field
5. Godot crashes

**Environment**
- OS: Windows 10
- Graphics card: NVidia GeForce GTX 1060 6GB
- Godot version: 4.2.2
- Module commit hash: c183a8043e350ae034c2f056b4ffc69bb72dd2fd
- Renderer used: Vulkan

**Backtrace**
This is the error that I get when using Godot with --verbose argument (pastebin is down at the moment): 
[BACKTRACE.txt](https://github.com/user-attachments/files/15845054/BACKTRACE.txt)

**Comment by Zylann** [comment]
Should be fixed in f7b9af9c02124fb9eafe0ccfe4713530fee81b1b

**Comment by kubaxius** [comment]
Yep, now everything works :)
