### ISSUE TITLE
VoxelModifier get cutout around edited regions

### ISSUE THREAD

**Issue by Piratux** [Zylann/godot_voxel#666]
**Describe the bug**
VoxelModifier (including VoxelModifierSphere and VoxelModifierMesh) get cutout around edited regions.

For example if I perform VoxelTool.do_sphere, then change VoxelModifier position to be next to edited region, I can see that SDF union is not performed between edited region and VoxelModifier, like it is performed between unedited region and VoxelModifier.

See video:

https://github.com/Zylann/godot_voxel/assets/58703216/5c9dd49b-2c9b-4d0f-acf7-1f0bb2c85109

**To Reproduce**
1. Open MRP, run the game and press space on keyboard (If this won't work I'll write more precise steps).

**Expected behavior**
SDF union between edited region values and VoxelModifier values should be performed, with SDF operation Add.

**Environment**
- OS: Windows 10
- Graphics card: GTX 650 Ti
- Godot version: 4.2.2 stable
- Module version: 1.2.0
- Renderer: Forward+

**MRP**
[Test VoxelModifier cutoff.zip](https://github.com/user-attachments/files/15847219/Test.VoxelModifier.cutoff.zip)

**Comment by Zylann** [comment]
Probably related with your understanding of modifiers: https://github.com/Zylann/godot_voxel/issues/665#issuecomment-2169827384

Modifiers don't run on top of everything else. They run on top of generators. Edits cause chunks to become "edited", and the generator (then by extension, modifiers) will no longer affect it. This is mentionned here: https://voxel-tools.readthedocs.io/en/latest/generators/#modifiers
So what you get is expected.

**Comment by Piratux** [comment]
I see, thanks for the explanation.

With my previous understanding, I thought one could move modifiers freely at runtime, but as I see now, they're not meant to be moved at runtime.
