### ISSUE TITLE
Broken build on OSX

### ISSUE THREAD

**Issue by nocivus** [Zylann/godot_voxel#67]
Using current godot master (commit 24e1039eb6fe32115e8d1a62a84965e9be19a2ed) at the time of this writing, as well as godot_voxel master. Getting this: 
![image](https://user-images.githubusercontent.com/3353/64802420-86783380-d582-11e9-881e-189430e5dfb0.png)

**Comment by nocivus** [comment]
hey, pastebin doesn't let me post the entire thing, here's the beginning:

`scons: Reading SConscript files ...
YASM is necessary for WebM SIMD optimizations.
WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits or platform are supported!
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
g++ -o platform/osx/os_osx.osx.opt.tools.64.o -c -std=c++11 -g1 -O2 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.9 -Wall -Werror=return-type -DDEBUG_ENABLED -DOSX_ENABLED -DUNIX_ENABLED -DGLES_ENABLED -DAPPLE_STYLE_KEYS -DCOREAUDIO_ENABLED -DCOREMIDI_ENABLED -DPTRCALL_ENABLED -DTOOLS_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DZSTD_STATIC_LINKING_ONLY -DGLAD_ENABLED -DGLES_OVER_GL -DFREETYPE_ENABLED -DSVG_ENABLED -Ithirdparty/nanosvg -Ithirdparty/freetype/include -Ithirdparty/libpng -Ithirdparty/glad -Ithirdparty/zstd -Ithirdparty/zlib -Iplatform/osx -I. -Ieditor platform/osx/os_osx.mm
g++ -o platform/osx/godot_main_osx.osx.opt.tools.64.o -c -std=c++11 -g1 -O2 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.9 -Wall -Werror=return-type -DDEBUG_ENABLED -DOSX_ENABLED -DUNIX_ENABLED -DGLES_ENABLED -DAPPLE_STYLE_KEYS -DCOREAUDIO_ENABLED -DCOREMIDI_ENABLED -DPTRCALL_ENABLED -DTOOLS_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DZSTD_STATIC_LINKING_ONLY -DGLAD_ENABLED -DGLES_OVER_GL -DFREETYPE_ENABLED -DSVG_ENABLED -Ithirdparty/nanosvg -Ithirdparty/freetype/include -Ithirdparty/libpng -Ithirdparty/glad -Ithirdparty/zstd -Ithirdparty/zlib -Iplatform/osx -I. -Ieditor platform/osx/godot_main_osx.mm
g++ -o platform/osx/joypad_osx.osx.opt.tools.64.o -c -std=c++11 -g1 -O2 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.9 -Wall -Werror=return-type -DDEBUG_ENABLED -DOSX_ENABLED -DUNIX_ENABLED -DGLES_ENABLED -DAPPLE_STYLE_KEYS -DCOREAUDIO_ENABLED -DCOREMIDI_ENABLED -DPTRCALL_ENABLED -DTOOLS_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DZSTD_STATIC_LINKING_ONLY -DGLAD_ENABLED -DGLES_OVER_GL -DFREETYPE_ENABLED -DSVG_ENABLED -Ithirdparty/nanosvg -Ithirdparty/freetype/include -Ithirdparty/libpng -Ithirdparty/glad -Ithirdparty/zstd -Ithirdparty/zlib -Iplatform/osx -I. -Ieditor platform/osx/joypad_osx.cpp
g++ -o platform/osx/camera_osx.osx.opt.tools.64.o -c -std=c++11 -g1 -O2 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.9 -Wall -Werror=return-type -DDEBUG_ENABLED -DOSX_ENABLED -DUNIX_ENABLED -DGLES_ENABLED -DAPPLE_STYLE_KEYS -DCOREAUDIO_ENABLED -DCOREMIDI_ENABLED -DPTRCALL_ENABLED -DTOOLS_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DZSTD_STATIC_LINKING_ONLY -DGLAD_ENABLED -DGLES_OVER_GL -DFREETYPE_ENABLED -DSVG_ENABLED -Ithirdparty/nanosvg -Ithirdparty/freetype/include -Ithirdparty/libpng -Ithirdparty/glad -Ithirdparty/zstd -Ithirdparty/zlib -Iplatform/osx -I. -Ieditor platform/osx/camera_osx.mm
g++ -o main/input_default.osx.opt.tools.64.o -c -std=c++11 -g1 -O2 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.9 -Wall -Werror=return-type -DDEBUG_ENABLED -DOSX_ENABLED -DUNIX_ENABLED -DGLES_ENABLED -DAPPLE_STYLE_KEYS -DCOREAUDIO_ENABLED -DCOREMIDI_ENABLED -DPTRCALL_ENABLED -DTOOLS_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DZSTD_STATIC_LINKING_ONLY -DGLAD_ENABLED -DGLES_OVER_GL -DFREETYPE_ENABLED -DSVG_ENABLED -Ithirdparty/nanosvg -Ithirdparty/freetype/include -Ithirdparty/libpng -Ithirdparty/glad -Ithirdparty/zstd -Ithirdparty/zlib -Iplatform/osx -I. -Ieditor main/input_default.cpp
g++ -o main/main.osx.opt.tools.64.o -c -std=c++11 -g1 -O2 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.9 -Wall -Werror=return-type -DDEBUG_ENABLED -DOSX_ENABLED -DUNIX_ENABLED -DGLES_ENABLED -DAPPLE_STYLE_KEYS -DCOREAUDIO_ENABLED -DCOREMIDI_ENABLED -DPTRCALL_ENABLED -DTOOLS_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DZSTD_STATIC_LINKING_ONLY -DGLAD_ENABLED -DGLES_OVER_GL -DFREETYPE_ENABLED -DSVG_ENABLED -Ithirdparty/nanosvg -Ithirdparty/freetype/include -Ithirdparty/libpng -Ithirdparty/glad -Ithirdparty/zstd -Ithirdparty/zlib -Iplatform/osx -I. -Ieditor main/main.cpp
g++ -o main/performance.osx.opt.tools.64.o -c -std=c++11 -g1 -O2 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.9 -Wall -Werror=return-type -DDEBUG_ENABLED -DOSX_ENABLED -DUNIX_ENABLED -DGLES_ENABLED -DAPPLE_STYLE_KEYS -DCOREAUDIO_ENABLED -DCOREMIDI_ENABLED -DPTRCALL_ENABLED -DTOOLS_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DZSTD_STATIC_LINKING_ONLY -DGLAD_ENABLED -DGLES_OVER_GL -DFREETYPE_ENABLED -DSVG_ENABLED -Ithirdparty/nanosvg -Ithirdparty/freetype/include -Ithirdparty/libpng -Ithirdparty/glad -Ithirdparty/zstd -Ithirdparty/zlib -Iplatform/osx -I. -Ieditor main/performance.cpp
g++ -o main/tests/test_gdscript.osx.opt.tools.64.o -c -std=c++11 -g1 -O2 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.9 -Wall -Werror=return-type -DDEBUG_ENABLED -DOSX_ENABLED -DUNIX_ENABLED -DGLES_ENABLED -DAPPLE_STYLE_KEYS -DCOREAUDIO_ENABLED -DCOREMIDI_ENABLED -DPTRCALL_ENABLED -DTOOLS_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DZSTD_STATIC_LINKING_ONLY -DGLAD_ENABLED -DGLES_OVER_GL -DFREETYPE_ENABLED -DSVG_ENABLED -Ithirdparty/nanosvg -Ithirdparty/freetype/include -Ithirdparty/libpng -Ithirdparty/glad -Ithirdparty/zstd -Ithirdparty/zlib -Iplatform/osx -I. -Ieditor main/tests/test_gdscript.cpp
g++ -o main/tests/test_gui.osx.opt.tools.64.o -c -std=c++11 -g1 -O2 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.9 -Wall -Werror=return-type -DDEBUG_ENABLED -DOSX_ENABLED -DUNIX_ENABLED -DGLES_ENABLED -DAPPLE_STYLE_KEYS -DCOREAUDIO_ENABLED -DCOREMIDI_ENABLED -DPTRCALL_ENABLED -DTOOLS_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DZSTD_STATIC_LINKING_ONLY -DGLAD_ENABLED -DGLES_OVER_GL -DFREETYPE_ENABLED -DSVG_ENABLED -Ithirdparty/nanosvg -Ithirdparty/freetype/include -Ithirdparty/libpng -Ithirdparty/glad -Ithirdparty/zstd -Ithirdparty/zlib -Iplatform/osx -I. -Ieditor main/tests/test_gui.cpp
g++ -o main/tests/test_main.osx.opt.tools.64.o -c -std=c++11 -g1 -O2 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.9 -Wall -Werror=return-type -DDEBUG_ENABLED -DOSX_ENABLED -DUNIX_ENABLED -DGLES_ENABLED -DAPPLE_STYLE_KEYS -DCOREAUDIO_ENABLED -DCOREMIDI_ENABLED -DPTRCALL_ENABLED -DTOOLS_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DZSTD_STATIC_LINKING_ONLY -DGLAD_ENABLED -DGLES_OVER_GL -DFREETYPE_ENABLED -DSVG_ENABLED -Ithirdparty/nanosvg -Ithirdparty/freetype/include -Ithirdparty/libpng -Ithirdparty/glad -Ithirdparty/zstd -Ithirdparty/zlib -Iplatform/osx -I. -Ieditor main/tests/test_main.cpp
g++ -o main/tests/test_math.osx.opt.tools.64.o -c -std=c++11 -g1 -O2 -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.9 -Wall -Werror=return-type -DDEBUG_ENABLED -DOSX_ENABLED -DUNIX_ENABLED -DGLES_ENABLED -DAPPLE_STYLE_KEYS -DCOREAUDIO_ENABLED -DCOREMIDI_ENABLED -DPTRCALL_ENABLED -DTOOLS_ENABLED -DGDSCRIPT_ENABLED -DMINIZIP_ENABLED -DZSTD_STATIC_LINKING_ONLY -DGLAD_ENABLED -DGLES_OVER_GL -DFREETYPE_ENABLED -DSVG_ENABLED -Ithirdparty/nanosvg -Ithirdparty/freetype/include -Ithirdparty/libpng -Ithirdparty/glad -Ithirdparty/zstd -Ithirdparty/zlib -Iplatform/osx -I. -Ieditor main/tests/test_math.cpp`

Here's the file: https://we.tl/t-ZWKUuWye1g

Also, G++ info:

`g++ --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin`

**Comment by tinmanjuggernaut** [comment]
Thank you. Although that was a successful build log. We need the one with the 45 warnings and 1 error mentioned in the original post.

You're using clang, which probably has specific rules about forward declaration that MSVC and gcc don't care about. It's probably an easy fix. What happens if you add `#include "voxel_map.h"` to the top of voxel_lod_terrain.h?

**Comment by tinmanjuggernaut** [comment]
If that doesn't fix it, we'll need the full errored build log so we can fix the warnings and errors. In the meantime, can you try gcc?

https://www.cyberciti.biz/faq/howto-apple-mac-os-x-install-gcc-compiler/

Although that might give you an old 4.x version of gcc, which hopefully works. I use 8.1 fine. 7.4 I think works.

This guy compiled a new version:
https://solarianprogrammer.com/2017/05/21/compiling-gcc-macos/

After making sure it's available you'll have to tell scons to use it if it doesn't auto detect. Run scons --help and see if there's an option like on windows, 'use_mingw=yes' tells it to use mingw/gcc. Linux defaults to gcc.

Or you can specify your compiler with CXX on the commandline, eg something like: 
`scons platform=osx CXX=/usr/bin/g++ CC=/usr/bin/gcc`

**Comment by Zylann** [comment]
I'd prefer to keep forward-declarations in header files and including full declaration in cpp files as much as possible. If a type needs to be complete, it likely needs to be included in the cpp file that originally caused the error.
I would have thought to do that in `register_types.cpp` but that's already the case so I don't know,

**Comment by tinmanjuggernaut** [comment]
I believe the problem clang is complaining about is this implementation is in the header file `voxel_lod_terrain.h`, but there has only been a forward declaration of VoxelMap, no class definition by this point. Note it doesn't complain about any other usage of VoxelMap. I don't think it has anything to do with register_types.

```
	template <typename A>
	void for_all_blocks(A &action) {
		for (int lod_index = 0; lod_index < MAX_LOD; ++lod_index) {
			if (_lods[lod_index].map.is_valid()) {
				_lods[lod_index].map->for_all_blocks(action);
			}
		}
	}
```

**Comment by Zylann** [comment]
But the thing is, that template alone can't be the source of the error. The function needs to be used by a concrete one, isn't it?

**Comment by tinmanjuggernaut** [comment]
https://stackoverflow.com/questions/41713945/clang-template-incomplete-type?rq=1

> The validity of a template may be checked prior to any instantiation. [ Note: Knowing which names are type names allows the syntax of every template to be checked in this way. — end note ] The program is ill-formed, no diagnostic required, if:...

http://eel.is/c++draft/temp.res#8

**Comment by Zylann** [comment]
I think I might remove that function then. It's used only 3 times.

**Comment by tinmanjuggernaut** [comment]
@nocivus Were you able to get this working with the temporary workaround I suggested? (Insert header file)

**Comment by whpthomas** [comment]
I encountered the same problem. There are a flood of warnings "overrides a member function but is not marked 'override'", but the errors I encountered were fixed by

(1) inserting>>  #include "voxel_map.h" <<at line 5 of terrain/voxel_lod_terrain.h

(2) changing line 1316 of terrain/voxel_lod_terrain.cpp  to>> d["remaining_main_thread_blocks"] = (int)_blocks_pending_main_thread_update.size(); 

(3) changing line 352 of terrain/voxel_terrain.cpp  to>> d["remaining_main_thread_blocks"] = (int)_blocks_pending_main_thread_update.size();

That managed to build voxel on osx without errors. I have run the program and VoxelTerrain and VoxelLodTerrain nodes are both present in the interface, and the demo's appear to work.

**Comment by tinmanjuggernaut** [comment]
@whpthomas Thanks for the report.

@Zylann Linux/gcc is now complaining about this forward declaration with warnings. Can you remove that function as mentioned above we can close this and PR #65 ? Or I can insert the include voxel_map in PR #65.

**Comment by Zylann** [comment]
@tinmanjuggernaut I removed the template function in 2b15ca6457d5d6e394a2226d4850ed14778a6bec

**Comment by tinmanjuggernaut** [comment]
Thank you. Looks good. Wrapping up final patch now.
