### ISSUE TITLE
Bigger atlas for blocky terrains

### ISSUE THREAD

**Issue by joaopedrosgs** [Zylann/godot_voxel#675]
Hi! First I want to thank you for your work. This plugin is amazing and it is saving me so much time!

My question is about the atlas for blocky terrains. Currently, it is limited to 16x16 tiles, is it possible to increase this number? If not, how can I add more block textures? Should I just override the material for each block? (while keeping the number of materials low, of course)

**Comment by MGilleronFJ** [comment]
> Currently, it is limited to 16x16 tiles

It is not limited to 16. You can increase that number in the [atlas_size](https://voxel-tools.readthedocs.io/en/latest/api/VoxelBlockyModelCube/#i_atlas_size_in_tiles) property.
In fact, that's only a thing in `VoxelBlockyModelCube` (which has to know that to make it easier to generate the UVs), while `VoxelBlockyModelMesh` assumes you have set the UVs you want already on the mesh. So really there is no restriction of size.

**Comment by joaopedrosgs** [comment]
Looks like it is indeed the case. Thank you @MGilleronFJ.
Closing this issue now.
