### ISSUE TITLE
the created hole will disappear if i go far from terrain until go out of view distance and then comeback  to it

### ISSUE THREAD

**Issue by se8820726** [Zylann/godot_voxel#678]
Terrain type: VoxelTerrain
Mesher: voxelMesherTransvoxel
Generator: voxel generator noise 2d smooth
Stream: ---
Scene structure
Plugin version (or where you got it) : https://github.com/Zylann/godot_voxel/releases/tag/v1.2.0
Godot version: 4.2.2 x64 double
OS: windows 11 x64

-----

this is my main scene tree:
<img width="222" alt="image" src="https://github.com/user-attachments/assets/c017d540-4bbe-4386-b7e2-911acae012a9">

i set voxelTerrain max view distance to 128
then start game.

if i throw projectile to terrain that is in view distance the hole will create. but after creating the hole if i go back untill i dont see the terrain and then comeback to terrain to come in view distance the hole gone and not exists

https://github.com/user-attachments/assets/9328f1f2-323e-4324-85c6-66001c1ac58c

this is code of make holes in terrain:
```
@onready var _terrain: VoxelTerrain = get_parent().get_node("VoxelTerrain")
func do_sphere(center: Vector3, radius: float, add: bool):
	print(center)
        var vt := _terrain.get_voxel_tool()
	if add:
		vt.mode = VoxelTool.MODE_ADD
	else:
		vt.mode = VoxelTool.MODE_REMOVE

	vt.do_sphere(center, radius)
	

```

voxelTerrain configs:
<img width="356" alt="image" src="https://github.com/user-attachments/assets/773e8f25-dfed-4f0d-99d5-8d261f22f0ab">

project source:
[godot voxel.zip](https://github.com/user-attachments/files/16447865/godot.voxel.zip)

**Comment by MGilleronFJ** [comment]
Terrain will not "remember" when you leave a region because you haven't told it to. So when you come back it is indeed not there anymore. There is a `stream` property that takes a resource to save modified chunks that go out of bounds.
See https://voxel-tools.readthedocs.io/en/latest/streams/

**Comment by se8820726** [comment]
thank you.
It seems you have four methods for streaming:
1- voxelStreamRegionFiles
2- voxelStreamScript
3- voxelStreamSQlite
4- voxelStreamMemory

I want to eventually store the map data on the server and use it for multiplayer.
Which of these four methods do you recommend?
Based on what was written in the document, it seems there is no way to know if the save process has really completed. Is there still no way?

**Comment by Zylann** [comment]
> I want to eventually store the map data on the server and use it for multiplayer.

It is meant for file storage, but if you want to rely on that for multiplayer, that's trickier because it wasn't meant for that. 

> Which of these four methods do you recommend?

The SQLite one is currently the most capable.

> Based on what was written in the document, it seems there is no way to know if the save process has really completed

Where did you see that? Depending on what you want to do, it is possible to tell. Though saving continuously happens asynchronously otherwise, as players move around or as you request it.

**Comment by se8820726** [comment]
https://voxel-tools.readthedocs.io/en/latest/streams/ :

> Saving only occurs under the following conditions:
> 
> 1- The block gets unloaded when too far away
> 2- save_modified_blocks() is called on the terrain node (you may want to call this when the player saves, on a timer, or when quitting the game)

Alright, if I make changes to the terrain and I don't call _save_modified_blocks_ myself, then when I move back until the block gets unloaded, a background save process will start. At this moment, if I want to close the program, I need to make sure the entire save process is completed before the program closes. You mentioned that if I wait a bit, it will finish. But for any reason, it might not finish after a while. How can I know this?

Now, if I call _save_modified_blocks_ myself and after it finishes, I move back until the block gets unloaded, will the automatic save process still run in this case?

Is there a way to prevent the automatic save process from running and instead, only execute the save process with _save_modified_blocks_ whenever I want? so that I can be sure when it has finished.

My main goal is to ensure that my save file does not get corrupted, and that all data is completely saved without losing anything.

**Comment by Zylann** [comment]
> when I move back until the block gets unloaded, a background save process will start

I'm afraid that one you can't really tell easily, other than looking for the number of tasks running in `VoxelEngine.get_stats()`. And when all tasks are done you have to flush the stream.

> Now, if I call save_modified_blocks myself and after it finishes, I move back until the block gets unloaded, will the automatic save process still run in this case?

It won't run if the block wasn't modified again after your call to `save_modified_blocks`.

> Is there a way to prevent the automatic save process from running and instead, only execute the save process with save_modified_blocks whenever I want?

No. First because it's not implemented that way, and also because it's not simple at scripting level to know when to actually do that.
