### ISSUE TITLE
Collider generation doesnt seem to work any more

### ISSUE THREAD

**Issue by darrylryan** [Zylann/godot_voxel#68]
With the latest godot master the collider seems to be broken

**Comment by tinmanjuggernaut** [comment]
I just pulled from master and can use physics collision just fine. Also there's nothing that changed in Godot from my previous working build 24e1039eb to the latest one a1fcac640 that affects meshes or physics.

Could you provide more details about how you are testing against physics collision?

Are you using my demo? Some of zylann's demos don't use physics collision.

**Comment by tinmanjuggernaut** [comment]
When you turn on debug/visible collision shapes in the editor, do they render on screen?

**Comment by darrylryan** [comment]
Whoops, I meant to log this on the heightmap terrain not the voxel one. Sorry :)

**Comment by tinmanjuggernaut** [comment]
Ok, thanks for following up and closing.
