### ISSUE TITLE
Sphear example has holes in it. 

### ISSUE THREAD

**Issue by Shadowblitz16** [Zylann/godot_voxel#701]
**Describe the bug**
The planet example here https://voxel-tools.readthedocs.io/en/latest/generators/#how-generators-work generates with holes

**To Reproduce**
![image](https://github.com/user-attachments/assets/be8361b5-3886-492d-aad6-f2f9e0d3a29f)
[Uploading minewars.zip…]()

**Expected behavior**

**Screenshots**

**Environment**
- OS: Kubuntu 24.04
- Graphics card: AMD Ryzen 7 5700G With Radeon Graphics
- Godot version: 4.3
- Module version: Idk
- Renderer used: Forward +

**Comment by Zylann** [comment]
It has holes in it because the view distance is insufficient to contain it all. So what you are seeing are the edges of the loaded terrain (the viewer in editor defaults to origin)..
