### ISSUE TITLE
Attach VoxelView to editor camera

### ISSUE THREAD

**Issue by Shadowblitz16** [Zylann/godot_voxel#705]
**Is your feature request related to a problem? Please describe.**
Working with this in the editor is a pain because you can't view the voxels without manually moving a voxel view around the scene.

**Describe the solution you'd like**
Attach a VoxelView object to the editor scene's camera.

**Describe alternatives you've considered**
Bearing.

**Additional context**
This would be very helpful for development

**Comment by NoTalkOnlyProx** [comment]
I may be mistaken, but I think this feature already exists, does it not?

![image](https://github.com/user-attachments/assets/959e8b89-348a-4ff9-8df6-f05e98b2dc7b)

**Comment by MGilleronFJ** [comment]
Yes that already exists, the editor has its own internal viewer (which works even when there are no viewer node in the scene then) and you can check "Editor Viewer Follow Camera".
