### ISSUE TITLE
fast_noise_2 causing errors while building godot

### ISSUE THREAD

**Issue by OsmiumShield** [Zylann/godot_voxel#706]
I pulled the Godot source and godot_voxel from the latest versions and I'm trying to build using the instructions from the voxel tools docs. I successfully built godot and ran the executable, then put the voxel tools file into godot/modules and renamed it to "voxel"
I tried to build godot again as instructed, and got several errors, most of which seem to be related to fast_noise_2. Here's my log
`scons: Reading SConscript files ...
Auto-detected 24 CPU cores available for build parallelism. Using 23 cores by default. You can override it with the `-j` or `num_jobs` arguments.
Using SCons-detected MSVC version 14.3, arch x86_64
Building for platform "windows", architecture "x86_64", target "editor".
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
[ 27%] Linking Static Library modules\module_gdscript.windows.editor.x86_64.lib ...
[ 67%] Linking Static Library modules\module_text_server_adv.windows.editor.x86_64.lib ...
[ 69%] Linking Static Library modules\module_vhacd.windows.editor.x86_64.lib ...
[ 69%] Compiling modules\voxel\thirdparty\fast_noise_2\src\FastSIMD\FastSIMD_Level_SSE2.cpp ...
[ 69%] Compiling modules\voxel\thirdparty\fast_noise_2\src\FastSIMD\FastSIMD_Level_SSE41.cpp ...
[ 70%] Compiling modules\voxel\thirdparty\fast_noise_2\src\FastSIMD\FastSIMD_Level_AVX2.cpp ...
[ 70%] Compiling modules\voxel\thirdparty\fast_noise_2\src\FastSIMD\FastSIMD_Level_AVX512.cpp ...
[ 70%] Compiling modules\voxel\meshers\blocky\voxel_blocky_library.cpp ...
[ 70%] Compiling modules\voxel\meshers\blocky\voxel_blocky_library_base.cpp ...
[ 71%] Compiling modules\voxel\meshers\blocky\voxel_blocky_model.cpp ...
[ 71%] Compiling modules\voxel\meshers\blocky\voxel_blocky_model_cube.cpp ...
[ 71%] Compiling modules\voxel\meshers\blocky\voxel_blocky_model_empty.cpp ...
C:\Users\oswit\GodotWithVoxel\modules\voxel\thirdparty\fast_noise_2\include\FastNoise\Generators/Modifiers.inl(30): error C2039: 'GetSourceValue': is not a member of 'FS_T<FastNoise::DomainOffset,FastSIMD::SSE_T<FastSIMD::Level_SSE2>>::GenT::<lambda_1>'
C:\Users\oswit\GodotWithVoxel\modules\voxel\thirdparty\fast_noise_2\include\FastNoise\Generators/Modifiers.inl(33): note: see declaration of 'FS_T<FastNoise::DomainOffset,FastSIMD::SSE_T<FastSIMD::Level_SSE2>>::GenT::<lambda_1>'
C:\Users\oswit\GodotWithVoxel\modules\voxel\thirdparty\fast_noise_2\include\FastNoise\Generators/Modifiers.inl(30): note: the template instantiation context (the oldest one first) is
modules\voxel\thirdparty\fast_noise_2\include\FastNoise/FastNoise_BuildList.inl(107): note: see reference to function template instantiation 'FastNoise::DomainOffset *FastSIMD::ClassFactory<FastNoise::DomainOffset,FastSIMD::Level_SSE2>(FastSIMD::MemoryAllocator)' being compiled
C:\Users\oswit\GodotWithVoxel\modules\voxel\thirdparty\fast_noise_2\src\FastSIMD\Internal/SourceBuilder.inl(12): note: see reference to variable template 'const bool is_base_of_v<FastNoise::DomainOffset,FS_T<FastNoise::DomainOffset,FastSIMD::SSE_T<4> > >' being compiled
modules\voxel\thirdparty\fast_noise_2\src\FastSIMD\FastSIMD_Level_SSE2.cpp(8): note: see reference to class template instantiation 'FS_T<FastNoise::DomainOffset,FastSIMD::SSE_T<FastSIMD::Level_SSE2>>' being compiled
C:\Users\oswit\GodotWithVoxel\modules\voxel\thirdparty\fast_noise_2\include\FastNoise\Generators/Modifiers.inl(22): note: while compiling class template member function 'FastSIMD::SSE_f32x4 FS_T<FastNoise::DomainOffset,FastSIMD::SSE_T<FastSIMD::Level_SSE2>>::Gen(FastSIMD::SSE_i32x4<FastSIMD::Level_SSE2>,FastSIMD::SSE_f32x4,FastSIMD::SSE_f32x4,FastSIMD::SSE_f32x4,FastSIMD::SSE_f32x4) const'
C:\Users\oswit\GodotWithVoxel\modules\voxel\thirdparty\fast_noise_2\include\FastNoise\Generators/Modifiers.inl(22): note: see reference to function template instantiation 'FastSIMD::SSE_f32x4 FS_T<FastNoise::DomainOffset,FastSIMD::SSE_T<FastSIMD::Level_SSE2>>::GenT<FastSIMD::SSE_f32x4,FastSIMD::SSE_f32x4,FastSIMD::SSE_f32x4,FastSIMD::SSE_f32x4>(FastSIMD::SSE_i32x4<FastSIMD::Level_SSE2>,FastSIMD::SSE_f32x4,FastSIMD::SSE_f32x4,FastSIMD::SSE_f32x4,FastSIMD::SSE_f32x4) const' being compiled
[ 71%] Compiling modules\voxel\meshers\blocky\voxel_blocky_model_mesh.cpp ...
scons: *** [modules\voxel\thirdparty\fast_noise_2\src\FastSIMD\FastSIMD_Level_SSE2.windows.editor.x86_64.obj] Error 2
C:\Users\oswit\GodotWithVoxel\modules\voxel\thirdparty\fast_noise_2\include\FastNoise\Generators/Modifiers.inl(30): error C2039: 'GetSourceValue': is not a member of 'FS_T<FastNoise::DomainOffset,FastSIMD::SSE_T<FastSIMD::Level_SSE41>>::GenT::<lambda_1>'
C:\Users\oswit\GodotWithVoxel\modules\voxel\thirdparty\fast_noise_2\include\FastNoise\Generators/Modifiers.inl(33): note: see declaration of 'FS_T<FastNoise::DomainOffset,FastSIMD::SSE_T<FastSIMD::Level_SSE41>>::GenT::<lambda_1>'
C:\Users\oswit\GodotWithVoxel\modules\voxel\thirdparty\fast_noise_2\include\FastNoise\Generators/Modifiers.inl(30): note: the template instantiation context (the oldest one first) is
modules\voxel\thirdparty\fast_noise_2\include\FastNoise/FastNoise_BuildList.inl(107): note: see reference to function template instantiation 'FastNoise::DomainOffset *FastSIMD::ClassFactory<FastNoise::DomainOffset,FastSIMD::Level_SSE41>(FastSIMD::MemoryAllocator)' being compiled
C:\Users\oswit\GodotWithVoxel\modules\voxel\thirdparty\fast_noise_2\src\FastSIMD\Internal/SourceBuilder.inl(12): note: see reference to variable template 'const bool is_base_of_v<FastNoise::DomainOffset,FS_T<FastNoise::DomainOffset,FastSIMD::SSE_T<32> > >' being compiled
modules\voxel\thirdparty\fast_noise_2\src\FastSIMD\FastSIMD_Level_SSE41.cpp(8): note: see reference to class template instantiation 'FS_T<FastNoise::DomainOffset,FastSIMD::SSE_T<FastSIMD::Level_SSE41>>' being compiled
C:\Users\oswit\GodotWithVoxel\modules\voxel\thirdparty\fast_noise_2\include\FastNoise\Generators/Modifiers.inl(22): note: while compiling class template member function 'FastSIMD::SSE_f32x4 FS_T<FastNoise::DomainOffset,FastSIMD::SSE_T<FastSIMD::Level_SSE41>>::Gen(FastSIMD::SSE_i32x4<FastSIMD::Level_SSE41>,FastSIMD::SSE_f32x4,FastSIMD::SSE_f32x4,FastSIMD::SSE_f32x4,FastSIMD::SSE_f32x4) const'
C:\Users\oswit\GodotWithVoxel\modules\voxel\thirdparty\fast_noise_2\include\FastNoise\Generators/Modifiers.inl(22): note: see reference to function template instantiation 'FastSIMD::SSE_f32x4 FS_T<FastNoise::DomainOffset,FastSIMD::SSE_T<FastSIMD::Level_SSE41>>::GenT<FastSIMD::SSE_f32x4,FastSIMD::SSE_f32x4,FastSIMD::SSE_f32x4,FastSIMD::SSE_f32x4>(FastSIMD::SSE_i32x4<FastSIMD::Level_SSE41>,FastSIMD::SSE_f32x4,FastSIMD::SSE_f32x4,FastSIMD::SSE_f32x4,FastSIMD::SSE_f32x4) const' being compiled
C:\Users\oswit\GodotWithVoxel\modules\voxel\thirdparty\fast_noise_2\include\FastNoise\Generators/Modifiers.inl(30): error C2039: 'GetSourceValue': is not a member of 'FS_T<FastNoise::DomainOffset,FastSIMD::AVX512_T<FastSIMD::Level_AVX512>>::GenT::<lambda_1>'
C:\Users\oswit\GodotWithVoxel\modules\voxel\thirdparty\fast_noise_2\include\FastNoise\Generators/Modifiers.inl(33): note: see declaration of 'FS_T<FastNoise::DomainOffset,FastSIMD::AVX512_T<FastSIMD::Level_AVX512>>::GenT::<lambda_1>'
C:\Users\oswit\GodotWithVoxel\modules\voxel\thirdparty\fast_noise_2\include\FastNoise\Generators/Modifiers.inl(30): note: the template instantiation context (the oldest one first) is
modules\voxel\thirdparty\fast_noise_2\include\FastNoise/FastNoise_BuildList.inl(107): note: see reference to function template instantiation 'FastNoise::DomainOffset *FastSIMD::ClassFactory<FastNoise::DomainOffset,FastSIMD::Level_AVX512>(FastSIMD::MemoryAllocator)' being compiled
C:\Users\oswit\GodotWithVoxel\modules\voxel\thirdparty\fast_noise_2\src\FastSIMD\Internal/SourceBuilder.inl(12): note: see reference to variable template 'const bool is_base_of_v<FastNoise::DomainOffset,FS_T<FastNoise::DomainOffset,FastSIMD::AVX512_T<512> > >' being compiled
modules\voxel\thirdparty\fast_noise_2\src\FastSIMD\FastSIMD_Level_AVX512.cpp(18): note: see reference to class template instantiation 'FS_T<FastNoise::DomainOffset,FastSIMD::AVX512_T<FastSIMD::Level_AVX512>>' being compiled
C:\Users\oswit\GodotWithVoxel\modules\voxel\thirdparty\fast_noise_2\include\FastNoise\Generators/Modifiers.inl(22): note: while compiling class template member function 'FastSIMD::AVX512_f32x16 FS_T<FastNoise::DomainOffset,FastSIMD::AVX512_T<FastSIMD::Level_AVX512>>::Gen(FastSIMD::AVX512_i32x16,FastSIMD::AVX512_f32x16,FastSIMD::AVX512_f32x16,FastSIMD::AVX512_f32x16,FastSIMD::AVX512_f32x16) const'
C:\Users\oswit\GodotWithVoxel\modules\voxel\thirdparty\fast_noise_2\include\FastNoise\Generators/Modifiers.inl(22): note: see reference to function template instantiation 'FastSIMD::AVX512_f32x16 FS_T<FastNoise::DomainOffset,FastSIMD::AVX512_T<FastSIMD::Level_AVX512>>::GenT<FastSIMD::AVX512_f32x16,FastSIMD::AVX512_f32x16,FastSIMD::AVX512_f32x16,FastSIMD::AVX512_f32x16>(FastSIMD::AVX512_i32x16,FastSIMD::AVX512_f32x16,FastSIMD::AVX512_f32x16,FastSIMD::AVX512_f32x16,FastSIMD::AVX512_f32x16) const' being compiled
scons: *** [modules\voxel\thirdparty\fast_noise_2\src\FastSIMD\FastSIMD_Level_SSE41.windows.editor.x86_64.obj] Error 2
scons: *** [modules\voxel\thirdparty\fast_noise_2\src\FastSIMD\FastSIMD_Level_AVX512.windows.editor.x86_64.obj] Error 2
C:\Users\oswit\GodotWithVoxel\modules\voxel\thirdparty\fast_noise_2\include\FastNoise\Generators/Modifiers.inl(30): error C2039: 'GetSourceValue': is not a member of 'FS_T<FastNoise::DomainOffset,FastSIMD::AVX_T<FastSIMD::Level_AVX2>>::GenT::<lambda_1>'
C:\Users\oswit\GodotWithVoxel\modules\voxel\thirdparty\fast_noise_2\include\FastNoise\Generators/Modifiers.inl(33): note: see declaration of 'FS_T<FastNoise::DomainOffset,FastSIMD::AVX_T<FastSIMD::Level_AVX2>>::GenT::<lambda_1>'
C:\Users\oswit\GodotWithVoxel\modules\voxel\thirdparty\fast_noise_2\include\FastNoise\Generators/Modifiers.inl(30): note: the template instantiation context (the oldest one first) is
modules\voxel\thirdparty\fast_noise_2\include\FastNoise/FastNoise_BuildList.inl(107): note: see reference to function template instantiation 'FastNoise::DomainOffset *FastSIMD::ClassFactory<FastNoise::DomainOffset,FastSIMD::Level_AVX2>(FastSIMD::MemoryAllocator)' being compiled
C:\Users\oswit\GodotWithVoxel\modules\voxel\thirdparty\fast_noise_2\src\FastSIMD\Internal/SourceBuilder.inl(12): note: see reference to variable template 'const bool is_base_of_v<FastNoise::DomainOffset,FS_T<FastNoise::DomainOffset,FastSIMD::AVX_T<256> > >' being compiled
modules\voxel\thirdparty\fast_noise_2\src\FastSIMD\FastSIMD_Level_AVX2.cpp(18): note: see reference to class template instantiation 'FS_T<FastNoise::DomainOffset,FastSIMD::AVX_T<FastSIMD::Level_AVX2>>' being compiled
C:\Users\oswit\GodotWithVoxel\modules\voxel\thirdparty\fast_noise_2\include\FastNoise\Generators/Modifiers.inl(22): note: while compiling class template member function 'FastSIMD::AVX_f32x8 FS_T<FastNoise::DomainOffset,FastSIMD::AVX_T<FastSIMD::Level_AVX2>>::Gen(FastSIMD::AVX2_i32x8,FastSIMD::AVX_f32x8,FastSIMD::AVX_f32x8,FastSIMD::AVX_f32x8,FastSIMD::AVX_f32x8) const'
C:\Users\oswit\GodotWithVoxel\modules\voxel\thirdparty\fast_noise_2\include\FastNoise\Generators/Modifiers.inl(22): note: see reference to function template instantiation 'FastSIMD::AVX_f32x8 FS_T<FastNoise::DomainOffset,FastSIMD::AVX_T<FastSIMD::Level_AVX2>>::GenT<FastSIMD::AVX_f32x8,FastSIMD::AVX_f32x8,FastSIMD::AVX_f32x8,FastSIMD::AVX_f32x8>(FastSIMD::AVX2_i32x8,FastSIMD::AVX_f32x8,FastSIMD::AVX_f32x8,FastSIMD::AVX_f32x8,FastSIMD::AVX_f32x8) const' being compiled
scons: *** [modules\voxel\thirdparty\fast_noise_2\src\FastSIMD\FastSIMD_Level_AVX2.windows.editor.x86_64.obj] Error 2
scons: building terminated because of errors.`

**Comment by OsmiumShield** [comment]
After a lot of troubleshooting I managed to figure out how to disable fast_noise_2 in SCsub. My understanding is that everything else should work without it. I believe my problem is that SCons is grabbing an outdated version of MSVC. It says it's grabbing 14.3, but the version I have in my PATH is 19.41.34120. I've looked for hours and can't figure out how it's grabbing 14.3, or how to make it grab the correct version.

**Comment by NuclearPhoenixx** [comment]
That's weird, but I think you're correct that something is wrong with your compiler/dependencies install, because I don't have any troubles compiling the same version with the same settings.

**Comment by Zylann** [comment]
I guess you need a more recent version of MSVC. I don't have problems compiling it, I haven't heard of people having problem with it so far (it's been in the module for years), and none of the CI platforms have problems with it (Linux, Mac OS, Windows).
Maybe you need to uninstall this old version somehow? 14 seems to be almost a decade old.

**Comment by Skyanne** [comment]
This is closed as completed, but figured id chime in as i recently pulled both the godot master branch and the voxel master branch and it failed to compile, giving those same errors. I think its due to the internal version change to godot 4.4 as godot 4.3 compiles no problem

**Comment by Zylann** [comment]
> I think its due to the internal version change to godot 4.4

The version number of Godot has nothing to do with this. The version of FastNoise2 in the module has not changed for years, so whatever is causing this error is either due to the version of MSVC you have used (assuming you use it?), or something that was changed in the build system of Godot... which I have no idea what it is, because I haven't had this issue.

**Comment by Skyanne** [comment]
i assume its a change in the recent 4.4 version, im using msvc22 and 19. Using 4.3.1rc1 also seems to work doubling my thoughts its a new change introduced in 4.4

**Comment by Zylann** [comment]
Are you sure you are getting the same error?
Right now I'm investigating a different one which started happening after https://github.com/godotengine/godot/pull/91069:
```
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winbase.h(9531): error C2220: the following warning is treated as an error
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winbase.h(9531): warning C5105: macro expansion producing 'defined' has undefined behavior
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winbase.h(9531): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings
```
It is unclear what file this header is included by, compiling log hints at FastNoise2 but it could also be SQLite3. Still, that's a different error and seems to be fixed by reverting this: https://github.com/godotengine/godot/pull/91069/files#diff-d78c5c377c03dd251edc72cdb0ae7d9986fa08361eb392187218f8c670c0bc4eL797-R813

However if you do get exactly the [same errors](https://github.com/Zylann/godot_voxel/issues/706#issue-2539956403) as the OP with a recent version of MSVC, then I don't know what to do, because I just compiled everything just fine with 2019 and Godot 4.4 master.

**Comment by Zylann** [comment]
I took the opportunity to build on a different PC which has only VS 2022, and it got this error:
```
fast_noise_2\include\FastNoise\Generators/Modifiers.inl(30): error C2039: '__this': is not a member of 'FS_T<FastNoise::DomainOffset,FastSIMD::Scalar>'
fast_noise_2\include\FastNoise\Generators/Modifiers.inl(19): note: see declaration of 'FS_T<FastNoise::DomainOffset,FastSIMD::Scalar>'
fast_noise_2\include\FastNoise\Generators/Modifiers.inl(30): note: the template instantiation context (the oldest one first) is
fast_noise_2\include\FastNoise/FastNoise_BuildList.inl(107): note: see reference to function template instantiation 'FastNoise::DomainOffset *FastSIMD::ClassFactory<FastNoise::DomainOffset,FastSIMD::Level_Scalar>(FastSIMD::MemoryAllocator)' being compiled
fast_noise_2\src\FastSIMD\Internal/SourceBuilder.inl(12): note: see reference to variable template 'const bool is_base_of_v<FastNoise::DomainOffset,FS_T<FastNoise::DomainOffset,FastSIMD::Scalar> >' being compiled
fast_noise_2\src\FastSIMD\Internal/SourceBuilder.inl(12): note: see reference to class template instantiation 'FS_T<FastNoise::DomainOffset,FastSIMD::Scalar>' being compiled
fast_noise_2\include\FastNoise\Generators/Modifiers.inl(22): note: while compiling class template member function 'FastSIMD::Scalar_Float FS_T<FastNoise::DomainOffset,FastSIMD::Scalar>::Gen(FastSIMD::Scalar_Int,FastSIMD::Scalar_Float,FastSIMD::Scalar_Float,FastSIMD::Scalar_Float,FastSIMD::Scalar_Float) const'
fast_noise_2\include\FastNoise\Generators/Modifiers.inl(22): note: see reference to function template instantiation 'FastSIMD::Scalar_Float FS_T<FastNoise::DomainOffset,FastSIMD::Scalar>::GenT<FastSIMD::Scalar_Float,FastSIMD::Scalar_Float,FastSIMD::Scalar_Float,FastSIMD::Scalar_Float>(FastSIMD::Scalar_Int,FastSIMD::Scalar_Float,FastSIMD::Scalar_Float,FastSIMD::Scalar_Float,FastSIMD::Scalar_Float) const' being compiled
fast_noise_2\include\FastNoise\Generators/Modifiers.inl(30): error C2039: '__this': is not a member of 'FS_T<FastNoise::DomainOffset,FastSIMD::SSE_T<FastSIMD::Level_SSE2>>'
fast_noise_2\include\FastNoise\Generators/Modifiers.inl(19): note: see declaration of 'FS_T<FastNoise::DomainOffset,FastSIMD::SSE_T<FastSIMD::Level_SSE2>>'
fast_noise_2\include\FastNoise\Generators/Modifiers.inl(30): note: the template instantiation context (the oldest one first) is
fast_noise_2\include\FastNoise/FastNoise_BuildList.inl(107): note: see reference to function template instantiation 'FastNoise::DomainOffset *FastSIMD::ClassFactory<FastNoise::DomainOffset,FastSIMD::Level_SSE2>(FastSIMD::MemoryAllocator)' being compiled
fast_noise_2\src\FastSIMD\Internal/SourceBuilder.inl(12): note: see reference to variable template 'const bool is_base_of_v<FastNoise::DomainOffset,FS_T<FastNoise::DomainOffset,FastSIMD::SSE_T<4> > >' being compiled
fast_noise_2\src\FastSIMD\Internal/SourceBuilder.inl(12): note: see reference to class template instantiation 'FS_T<FastNoise::DomainOffset,FastSIMD::SSE_T<FastSIMD::Level_SSE2>>' being compiled
fast_noise_2\include\FastNoise\Generators/Modifiers.inl(22): note: while compiling class template member function 'FastSIMD::SSE_f32x4 FS_T<FastNoise::DomainOffset,FastSIMD::SSE_T<FastSIMD::Level_SSE2>>::Gen(FastSIMD::SSE_i32x4<FastSIMD::Level_SSE2>,FastSIMD::SSE_f32x4,FastSIMD::SSE_f32x4,FastSIMD::SSE_f32x4,FastSIMD::SSE_f32x4) const'
fast_noise_2\include\FastNoise\Generators/Modifiers.inl(22): note: see reference to function template instantiation 'FastSIMD::SSE_f32x4 FS_T<FastNoise::DomainOffset,FastSIMD::SSE_T<FastSIMD::Level_SSE2>>::GenT<FastSIMD::SSE_f32x4,FastSIMD::SSE_f32x4,FastSIMD::SSE_f32x4,FastSIMD::SSE_f32x4>(FastSIMD::SSE_i32x4<FastSIMD::Level_SSE2>,FastSIMD::SSE_f32x4,FastSIMD::SSE_f32x4,FastSIMD::SSE_f32x4,FastSIMD::SSE_f32x4) const' being compiled
```
Which is still a bit different from the OP. Curious that 2019 works and 2022 doesn't 🤔 

Also going back to OP:

> it says it's grabbing 14.3, but the version I have in my PATH is 19.41.34120

I'm quite confused by all the version schemes of VS,  but [14.3 is actually VS 2022](https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B#32-bit_and_64-bit_versions)... which might also be 19.41.34120.
So now it seems that the problem comes specifically from compiling with 2022?

**Comment by Zylann** [comment]
If you have VS 2022, you can workaround the issue by using Clang-Cl: I pushed a bunch of fixed that should allow using `clang-cl` to build on Windows.
To do this, you need to:
- Install LLVM (download binaries from https://github.com/llvm/llvm-project/releases/tag/llvmorg-19.1.0)
- Make `clang-cl` available from command line by adding the `bin` folder of LLVM to your PATH environment variable
- Add `use_llvm=yes` to your SCons command line

Also it appears that using CMake to build FastNoise2 of course doesn't have issues when using VS 2022, but it's unclear what the difference is between CMake and the [port done in SCons](https://github.com/Zylann/godot_voxel/blob/adf625d2c2578b937ce1f375a94adbea84f23fbc/thirdparty/fast_noise_2/SConscript) that would somehow make VS 2022 specifically fail to build...

**Comment by Repiteo** [comment]
> Currently trying to do that, but warnings occur despite them being [disabled](https://github.com/Zylann/godot_voxel/blob/adf625d2c2578b937ce1f375a94adbea84f23fbc/thirdparty/fast_noise_2/SConscript#L71) (???)

To clarify: clang-cl parses warn/error commands with clang syntax, not msvc. The way this conditional is handled in the main repo is `if env.msvc and not methods.using_clang(env)`, but your llvm check will work just as well.

**Comment by Zylann** [comment]
Just pushed another workaround in b440069083807a383c25b2bb2b91191b63b6c2b2
Now it builds on my machine with VS 2022.
