### ISSUE TITLE
'VoxelRaycastResult': undeclared identifier when compiling with Mono

### ISSUE THREAD

**Issue by Lathuys** [Zylann/godot_voxel#71]
Windows 10 64Bit
I followed official tutorial on compiling the Engine with mono, and when I doing final step, I'm getting this error:

```
modules\mono\glue\mono_glue.gen.cpp(12209): error C2065: 'VoxelRaycastResult': undeclared identifier
modules\mono\glue\mono_glue.gen.cpp(12209): error C2146: syntax error: missing ';' before identifier 'ret'
modules\mono\glue\mono_glue.gen.cpp(12209): error C2065: 'ret': undeclared identifier
modules\mono\glue\mono_glue.gen.cpp(12215): error C2065: 'ret': undeclared identifier
modules\mono\glue\mono_glue.gen.cpp(12216): error C2065: 'ret': undeclared identifier
```

earlier, when I was generating mono glue I got this error:
```
ERROR: BindingsGenerator::_get_type_or_placeholder: Type not found. Creating placeholder: 'VoxelRaycastResult'.
   At: modules\mono\editor\bindings_generator.cpp:2089
```

**Comment by Zylann** [comment]
I forgot to register the class here: https://github.com/Zylann/godot_voxel/blob/master/register_types.cpp

I wonder if I need to register the derived classes of `VoxelTool` as welll...

**Comment by Zylann** [comment]
I pushed a fix for that class, but I have a doubt about derived classes of `VoxelTool`. Those arent exposed either, but it just works in GDScript.
Can you retry to see if it works?

**Comment by Lathuys** [comment]
I will be able to do it on Friday

**Comment by tinmanjuggernaut** [comment]
The latest commit fixed both the errors generating glue and building the engine on Linux w/  mono 6.4. I'd say this can be closed.
