### ISSUE TITLE
Passing custom variables into voxel generator graphs

### ISSUE THREAD

**Issue by ghost** [Zylann/godot_voxel#710]
**Is your feature request related to a problem? Please describe.**
Sometimes you want to let players customize their world generation a bit. Stuff like increasing how mountainous the terrain is or the X/Y/Z scales of the terrain. Currently, there doesn't seem to be any way to read values from outside or send values inside, meaning every voxel generator graph will always produce the exact same result unless manually edited, which I would assume isn't possible outside the editor.

**Describe the solution you'd like**
There's probably a better way to implement it but one solution would be to add an array to the generator and a graph node that will grab a value by its index.

**Describe alternatives you've considered**
I've looked around quite a bit and I could be wrong but I don't see any way to do this within the current module.

Also, this is technically a separate issue, but generator-wide seeds would be very useful and they seem relatively easy to implement, considering you can probably add together the noise generator's seed plus the generator-wide seed to be able to use two seeds at once. At the moment, I've got no clue how to make worlds random instead of them all being the same without that.

**Comment by Zylann** [comment]
> there doesn't seem to be any way to read values from outside or send values inside

There is, you can modify the graph and properties of each node through the API in `VoxelGraphFunction` (which in turn you get from `VoxelGeneratorGraph->get_main_function()`.

> Stuff like increasing how mountainous the terrain is or the X/Y/Z scales of the terrain

You can achieve this by giving a name to the node you want to change at runtime, then use `find_node_by_name` to get its ID and use it to change its properties. You may duplicate the original graph, do the changes, call `compile` and then it can be run.
This is what the solar system demo uses to tweak the same generator for different planets: https://github.com/Zylann/solar_system_demo/blob/1ec891db22b41a842d48ca0c0b1c4c7c9157f6bc/solar_system/solar_system_setup.gd#L306
