### ISSUE TITLE
Rewrite the module as GDExtension

### ISSUE THREAD

**Issue by darkhog** [Zylann/godot_voxel#712]
**Is your feature request related to a problem? Please describe.**
GD Extension would make it possible to use the tool without having to do custom builds.

**Describe the solution you'd like**
Please rewrite the module as GDExtension.

**Describe alternatives you've considered**
I am not building Godot myself just to have this nor I am downloading the prebuilt release and have to fiddle with export templates to have it working.

**Additional context**
No additional context necessary.

**Comment by Zylann** [comment]
The module already compiles as a GDExtension (it supports both). It has a SConstruct file for it. To compile it as such, run `scons` in the module's root folder.

**Comment by Zylann** [comment]
Closing in favor of https://github.com/Zylann/godot_voxel/issues/333
