### ISSUE TITLE
Missing recycle_connection after get_connection

### ISSUE THREAD

**Issue by lenesxy** [Zylann/godot_voxel#713]
VoxelStreamSQLite::load_all_blocks
VoxelStreamSQLite::get_current_coordinate_format
VoxelStreamSQLite::copy_blocks_to_other_sqlite_stream[missing twice, recycle_connection() and dst_stream->recycle_connection()]

These functions seem to be missing recycle_connection() after get_connection()

**Comment by Zylann** [comment]
Should be fixed with 8aa25f33ad21ab5cd68c49e38a24ffefed587ec2
