### ISSUE TITLE
Is it possible to use NoiseGraph to generate instances only on certain surfaces?

### ISSUE THREAD

**Issue by Critsium-xy** [Zylann/godot_voxel#716]
I completed a procedural terrain generation with GeneratorScript. Voxels in different biomes are painted with different material WEIGHTS.

I need to generate grass only on surfaces painted with grass material. I think that the noise used in instancer generator is just a multiplier on density, so I wonder is it possible to use NoiseGraph to generate a noise result using the data in the WEIGHTS channel? Or is there another way to control the instance generation?

**Comment by Zylann** [comment]
By `NoiseGraph`, do you mean `VoxelGeneratorGraph`? Not sure where else that comes from.

> I need to generate grass only on surfaces painted with grass material

You can't directly do that at the moment. VoxelInstancer is based on meshes (not voxel data) and it cannot use vertex attributes yet. For now to do this you have to configure a noise (or graph) that has the same densities as the ones you used in your voxel generator.

**Comment by Critsium-xy** [comment]
One more thing, I may need to know the relation between InputX, InputZ in voxel graph and the caculated pos_world in my generator script to do this work

![image](https://github.com/user-attachments/assets/1a52e0e4-41b1-48de-9db6-14823e5b6253)

**Comment by MGilleronFJ** [comment]
`InputX`, `InputY` and `InputZ` are world voxel coordinates, the same as `pos_world` in your script.

**Comment by Zylann** [comment]
With 88bbfd48f96d5c1f14c6d77238ef35e6bd8f1394, you can now filter which texture indices instances spawn on:
![image](https://github.com/user-attachments/assets/f991269b-4465-420a-963d-8abb74568e42)

**Comment by Critsium-xy** [comment]
> With [88bbfd4](https://github.com/Zylann/godot_voxel/commit/88bbfd48f96d5c1f14c6d77238ef35e6bd8f1394), you can now filter which texture indices instances spawn on, when using `VoxelMesherTransvoxel` with `texturing_mode` set to `4-blend over 16 textures`: ![image](https://private-user-images.githubusercontent.com/1311555/391258048-f991269b-4465-420a-963d-8abb74568e42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2MDkwOTksIm5iZiI6MTczNDYwODc5OSwicGF0aCI6Ii8xMzExNTU1LzM5MTI1ODA0OC1mOTkxMjY5Yi00NDY1LTQyMGEtOTYzZC04YWJiNzQ1NjhlNDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTlUMTE0NjM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGU1OTVjM2QzNmI1ZWMzNzQ1ZTc4OTVmNWEyY2M3YTZlNGJlZjI5NDIxM2MzNDA2ZmUzNjJjNjE2ZGQ5YzkxNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.s8kYgUN1Rw01UXwYqxa4VuEmKye74AmLg72SR4jzvDw)

This is quite useful, thanks a lot for doing this!
