### ISSUE TITLE
VoxelGeneratorScript does not support detail normalmaps?

### ISSUE THREAD

**Issue by Critsium-xy** [Zylann/godot_voxel#718]
I used a script to generate the terrain, but I found that enabling detail normalmaps will cause errors every time a chunk is generated.

![image](https://github.com/user-attachments/assets/ba8f836e-40d3-4105-b259-f041fcc55b84)

Does this mean that VoxelGeneratorScript do not support detail normalmaps?

**Comment by Zylann** [comment]
Correct, `VoxelGeneratorScript` doesn't support detail normalmaps.

For it to support that, it needs two things:
- An implementation of `generate_series` in addition to `generate_block`, where you have to provide SDF values at arbitrary Vector3 positions
- A compute shader implementation of that

The first is relatively easy to expose, but will be incredibly slow if you're using GDScript (this process can get much slower than generating blocks).
The second is more tricky and needs more investigation about what to actually expose.

**Comment by Critsium-xy** [comment]
> Correct, `VoxelGeneratorScript` doesn't support detail normalmaps.
> 
> For it to support that, it needs either of two things:
> 
> * An implementation of `generate_series` in addition to `generate_block`, where you have to provide SDF values at arbitrary Vector3 positions
> * A compute shader implementation of that, because while the CPU path works, it is very slow even for C++ generators
> 
> The first is relatively easy to expose, but will be incredibly slow if you're using GDScript (this process can get much slower than generating blocks). The second is more tricky and needs more investigation about what to actually expose. This can get even more tricky depending on how you implemented your script.

I understand. Thanks a lot!
