### ISSUE TITLE
Spamming edits in VoxelLodTerrain causes some blocks to not update

### ISSUE THREAD

**Issue by Zylann** [Zylann/godot_voxel#72]
If you spam-edit voxels with a function like `vt.do_sphere(center, 3.5)` every frame, there is a chance that some of the blocks along the way won't get updated, leaving holes in the terrain at block boundaries. The block will look like it's been updated once, but only accounting for the first edits that affected it.
After spamming, if a single edit is made within the block in which the hole lies, the hole will disappear replaced with a correct mesh.
It doesn't reproduce if you sparsely perform these edits, with mouse clicks for example.

This is a meshing problem related with timing of edits. I tried turning off some threading optimizations (which can ignore block updates in case they are redundant) but it doesn't seem related to threads.
I think it's the way updates are scheduled by `VoxelLodTerrain`. Needs investigation.

Example when digging a tunnel:
![image](https://user-images.githubusercontent.com/1311555/65806011-a8c3a100-e17f-11e9-8d71-d6402dfcdcc9.png)
![image](https://user-images.githubusercontent.com/1311555/65806032-bbd67100-e17f-11e9-8952-6559f197935d.png)

**Comment by tinmanjuggernaut** [comment]
I noticed this in the opposite case of adding terrain. Trying to mimic rising bubbles from the terrain, doing one worked fine:

![projectile](https://user-images.githubusercontent.com/632766/66005785-0db02b80-e4df-11e9-8bfb-4b63924d93a6.gif)

But once I repeatedly called the code 10 times, they started leaving artifacts:

![bubbles](https://user-images.githubusercontent.com/632766/66005869-50720380-e4df-11e9-9415-fd06254d910e.gif)

**Comment by Zylann** [comment]
I can't reproduce it anymore. Not sure what would have fixed it.

**Comment by tinmanjuggernaut** [comment]
Before it couldn't even handle 10 of my voxel projectiles / bubbles without severe artifacts. Now, here's 70. It ran at 100, but shortly crashed likely due to each projectile doing its own terrain edits in _process, rather than batching it all in a single processor.  This runs as 67 fps, 130fps without.

![projectile](https://user-images.githubusercontent.com/632766/72007827-874d7780-328d-11ea-8983-c489ea82e42b.gif)

I do see artifacts remaining if the edits are on or over a LOD border, but that's to be expected.

Maybe it was an upstream change. I'd agree this can be closed.

**Comment by Zylann** [comment]
> shortly crashed likely due to each projectile doing its own terrain edits in _process

It would be slow, but should not crash...

**Comment by tinmanjuggernaut** [comment]
At 10x10 it runs for 10-20seconds then dies with this:

```
ERROR: ERROR: All memory pool allocations are in use.
   At: D:\gd\godot\core/pool_vector.h:529
CArlals hmemHorya ponol dalllocaetiorns Earex inc usee.
t   At: ioD:\gd\gondot:\co re/Ppoorl_voectgor.rh:5a29
 ERcRORra: sAhll ememd
ry pool allocations are in use.
   At: D:\gd\godot\core/pool_vector.h:529
Socket error: 10054
```

**Comment by Zylann** [comment]
Oh. Yeah, that's proper death.
I suspect it's due tu submission of very large areas every frame. Currently, voxels get *copied* (including 1 neighbor voxel in min sides, 2 neighbor voxels in max sides) before being sent to the updater, which can't get consumed fast enough so memory just piles up. Even though it's an edge case at the moment, it's candidate for another issue.

**Comment by Zylann** [comment]
Closing this for now as I havent seen it ever since.
