### ISSUE TITLE
Compiling for android fails

### ISSUE THREAD

**Issue by jarrellmark** [Zylann/godot_voxel#75]
Hi Zylann and others,

Thanks for this plugin! It will be a great time saver for making my first Godot game.

I'm having trouble compiling the android export template using this voxel plugin.

Godot for x11 compiled successfully. I have Ubuntu 18.04 and godot master branch pulled 2019-10-01.

To compile the export template, I typed this:

$ scons platform=android target=release android_arch=armv7

The error is this:

In file included from modules/voxel/register_types.cpp:12:
modules/voxel/terrain/voxel_lod_terrain.h:118:25: error: member access into incomplete type 'VoxelMap'
                                _lods[lod_index].map->for_all_blocks(action);
                                                    ^
modules/voxel/terrain/voxel_terrain.h:12:7: note: forward declaration of 'VoxelMap'
class VoxelMap;
      ^
45 warnings and 1 error generated.
scons: *** [modules/voxel/register_types.android.opt.armv7.neon.o] Error 1
scons: building terminated because of errors.

I'm trying to do this so I can export the game to Android.

As a side note, I'm trying this voxel plugin because the heighmap plugin didn't work on Android or Web. There was a flat textured image at ground level, although the collision of the terrain did work on Android and Web. And the terrain did show up properly when running from godot on linux. But on android and web, it was a flat ground (except collision was there where the terrain was supposed to be). This was with the Classic4Lite shader. I could open up another ticket for that if you want. Seemed like more of the recent development was on this project though.

**Comment by tinmanjuggernaut** [comment]
Did you pull the recent changes from voxel tools master branch? These issues were look the same as what was recently fixed, 6 hours ago.

Also what kind of mobile card are you targeting? This isn't a light weight module.

**Comment by Zylann** [comment]
@jarrellmark you could report your issues with heightmaps on the plugin repo, however you were likely hitting this issue: https://github.com/Zylann/godot_heightmap_plugin/issues/96

**Comment by jarrellmark** [comment]
Thanks @tinmanjuggernaut and @Zylann for the responses.

I pulled the latest master branch, and the problem was get fixed after recompiling. I'll close the ticket.

To your question about target hardware, @tinmanjuggernaut, I'm testing on a OnePlus 6, but I'd like to have the game run on mid range phones too, so I think I'll try another approach other than voxel for the terrain.

For the godot_heightmap_plugin issue, @Zylann, my issue does look somewhat similar to that issue Zylann/godot_heightmap_plugin#96, except I'm using GLES3 targeted to web (using webgl 2.0) and Android. I'll open up another ticket in that projects's GitHub repo with more details and pictures.
