### ISSUE TITLE
How to create a new voxel geometry/model

### ISSUE THREAD

**Issue by jensModvig** [Zylann/godot_voxel#78]
I am using the blocky terrain of this module and everything is working nicely, I am able to create new blocks easily but they have the in-build geometries of "none" or "cube". Now I am wondering how do I add a new model for one of the voxels. It would be the equivalent of creating something like a fence in a game like minecraft.
Do I need to create a new mesher or is there a simple way that I am not seeing? Like creating a new voxel object of some sort?

**Comment by Zylann** [comment]
This is more or less supported internally but it's not properly exposed yet. `Voxel` can contain arbitrary vertices which can already be used by the blocky mesher, there is just no API to modify them.

**Comment by jensModvig** [comment]
What is the priority of exposing the geometry shapes and are there any plans on loading the models from a file in the near future?
Otherwise i would probably try make it work, for my little project, I am just worried that I take it in a completely different direction and that it wont be compatible with newer versions of Godot Voxel.

Thank you btw, I was able to modify the code and hardcode a new geometry type by changing the vertices, very simple indeed, very well-made :)
![image](https://user-images.githubusercontent.com/13716895/66502597-de448480-eac5-11e9-9a42-f4995198bac9.png)

**Comment by Zylann** [comment]
There hasn't been a priority for this recently, but it could be added anytime really, because it has to be done. It's something I want to support :) 
Loading from an actual model may also be supported, under a few minor restrictions.

**Comment by wi-ski** [comment]
@jensModvig - Any chance I could convince you to push your changes? Im curious to see how you chose your approach :)

**Comment by Zylann** [comment]
The `custom_blocky_mesh` branch has initial support for custom meshes, and also custom AABBs for use with `VoxelBlockMover`. They don't really interact with the face culling system at the moment but from the few tests I've done they should work.

**Comment by Zylann** [comment]
Initial support for this has been merged to master.
