### ISSUE TITLE
Compilation does not work on Windows

### ISSUE THREAD

**Issue by SnailBones** [Zylann/godot_voxel#79]
Compiling isn't working for me with Godot 3.1 on Windows 10. I'm getting the following error:

`scons: Reading SConscript files ...
Configuring for Windows: target=debug, bits=default
 Found MSVC version 14.1, arch amd64, bits=64
YASM is necessary for WebM SIMD optimizations.
WebM SIMD optimizations are disabled. Check if your CPU architecture, CPU bits or platform are supported!
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
[  5%] [94mCompiling [95m==> [93mmain\main.cpp[0m
main.cpp
[  5%] Linking Static Library ==> main\main.windows.tools.64.lib
main\default_controller_mappings.gen.windows.tools.64.obj : warning LNK4042: object specified more than once; extras ignored
[  7%] Compiling ==> modules\register_module_types.gen.cpp
register_module_types.gen.cpp
[ 37%] Compiling ==> modules\voxel\streams\voxel_block_serializer.cpp
voxel_block_serializer.cpp
modules\voxel\streams\voxel_block_serializer.cpp(90): error C3861: 'ERR_FAIL_COND_V_MSG': identifier not found
modules\voxel\streams\voxel_block_serializer.cpp(119): error C3861: 'ERR_FAIL_COND_V_MSG': identifier not found
modules\voxel\streams\voxel_block_serializer.cpp(164): error C3861: 'ERR_FAIL_COND_V_MSG': identifier not found
modules\voxel\streams\voxel_block_serializer.cpp(167): error C3861: 'ERR_FAIL_COND_V_MSG': identifier not found
scons: *** [modules\voxel\streams\voxel_block_serializer.windows.tools.64.obj] Error 2
scons: building terminated because of errors.`

**Comment by tinmanjuggernaut** [comment]
Please use the Godot3.1 branch to compile against Godot 3.1, as stated in the docs:

https://github.com/Zylann/godot_voxel/blob/master/doc/02_build-voxel-tools.md

**Comment by SnailBones** [comment]
My bad, thanks!
