### ISSUE TITLE
Error with latest Godot dev build

### ISSUE THREAD

**Issue by drarem** [Zylann/godot_voxel#84]
50%] Compiling ==> modules\voxel\streams\voxel_block_serializer.cpp
voxel_block_serializer.cpp
modules\voxel\streams\voxel_block_serializer.cpp(90): error C3861: 'ERR_FAIL_COND_V_MSG': identifier not found
modules\voxel\streams\voxel_block_serializer.cpp(119): error C3861: 'ERR_FAIL_COND_V_MSG': identifier not found
modules\voxel\streams\voxel_block_serializer.cpp(164): error C3861: 'ERR_FAIL_COND_V_MSG': identifier not found
modules\voxel\streams\voxel_block_serializer.cpp(167): error C3861: 'ERR_FAIL_COND_V_MSG': identifier not found
scons: *** [modules\voxel\streams\voxel_block_serializer.windows.debug.64.obj] Error 2
scons: building terminated because of errors.

**Comment by tinmanjuggernaut** [comment]
Is this addressed by #64 and #79 ? 

ERR_FAIL_COND_V_MSG is not in 3.1 and you need to use the 3.1 VT branch to compile against Godot 3.1 as stated in the VT build docs.

If not, what godot and voxel tools branches and commits are you on?

**Comment by tinmanjuggernaut** [comment]
You can also download binaries here:
http://tokisan.com/godot-binaries/

**Comment by drarem** [comment]
Yep, thanks. was compiling against 3.2

**Comment by tinmanjuggernaut** [comment]
Using the latest commit 35444576ff and VT master, I can confirm it won't build. but I get different error messages.

```
Compiling ==> modules\voxel\streams\voxel_stream_image.cpp
modules\voxel\streams\voxel_stream.cpp(22): error C3861: 'ERR_EXPLAIN': identifier not found
Compiling ==> modules\voxel\streams\voxel_stream_noise.cpp
modules\voxel\streams\voxel_stream.cpp(43): error C3861: 'ERR_EXPLAIN': identifier not found
voxel_stream_noise.cpp
```

This PR changed the error macros. 
https://github.com/godotengine/godot/pull/33391

Working on a PR.

**Comment by tinmanjuggernaut** [comment]
@drarem Thanks for the report. Please check your errors as I can't repeat them.  ERR_FAIL_COND_V_MSG is defined and it compiles fine against today's master and PR #85. The changes are small enough you can do them manually.

**Comment by wi-ski** [comment]
We experienced this error and haphazardly achieved the same affect as #85

**Comment by wi-ski** [comment]
Meaning, we were finally able to compile *
