### ISSUE TITLE
Procedural Stochastic Textures by Tiling and Blending (High-Performance By-Example Noise using a Histogram-Preserving Blending Operator)

### ISSUE THREAD

**Issue by blockspacer** [Zylann/godot_voxel#90]
High-Performance By-Example Noise may be useful for terrain texturing, 2D version of shader below.

Found issues:
* Godot doesn't support `textureQueryLod`, so IDK how to properly port code line `float LOD = textureQueryLod(Tinput, uv).y / float(textureSize(invT, 0).y);`. I tried to set LOD manually to different values (1.0, 2.0, 3.0), nothing changed (IDK why, i even enabled mipmaps in texture `import` panel in Godot editor).
* **Built-in `UV` and `UV2` variables are empty in `fragment()` with smooth terrain**. Is it possible to use Procedural Stochastic Textures with godot voxel (without expensive triplanar mapping)? IDK how to go from 2D to 3D without `UV`
* Because i don't know how to access 2D UV in godot_voxel (smooth terrain), I tried to use 3D UV (based on A_uv_triplanar_pos and A_uv_power_normal) and, maybe, somehow made triplanar mapping faster (need to go from 3 triplanar texture fetches to 1 because with ByExampleProceduralNoise we will get 3*3 texture fetches - and that only for Albedo!), but found ugly seams in resulting image (triplanar 'hack' below usable only with blocky terrain or small texture pattern)
```cpp
  // seed is 0,0
  // w1, w2, w3 is A_uv_power_normal z,y,x
  if(w1>=w2 && w1>=w3){
	  uv3d = A_uv_triplanar_pos.xy+seed;
  }else if(w2>=w1 && w2>=w3){
	  uv3d = A_uv_triplanar_pos.xz+seed;
  }else if(w3>=w1 && w3>=w2){
	  uv3d = (A_uv_triplanar_pos.zy* vec2(-1.0,1.0))+seed;
  }else
    uv3d = vec2(0.5);
```

![image](https://user-images.githubusercontent.com/35254900/71449368-f25e6080-275b-11ea-9a01-93bda2fc79a6.png)

you can read about High-Performance By-Example Noise here:
+ https://eheitzresearch.wordpress.com/738-2/
+ https://blogs.unity3d.com/2019/02/14/procedural-stochastic-texturing-in-unity/
+ https://hal.inria.fr/hal-01824773/file/HPN2018.pdf
+ https://www.shadertoy.com/view/MdyfDV
+ https://github.com/UnityLabs/procedural-stochastic-texturing/blob/a77263f336611c3b7acf021d5942207ee7223602/Editor/ProceduralTexture2D/SampleProceduralTexture2DNode.cs#L132
+ http://www.jcgt.org/published/0008/04/02/paper.pdf
+ https://github.com/fegennari/3DWorld/blob/d2b1b893c4dc0b18e4592473d4ccc54dacb14fd2/shaders/bump_map.part.frag#L88

2D version of shader ported to Godot (color vectors, Gaussian input and LUT inverse histogram transformation may be generated by C++ tool from original Thomas Deliot and Eric Heitz paper https://drive.google.com/file/d/1ZvTax661MMi63cp2cPGS6iEvq7VCi0wr/view):
```cpp
shader_type canvas_item;
render_mode blend_mix;

// Textures
uniform sampler2D uniform_Tinput; // Gaussian input T(I)
uniform sampler2D uniform_invT; // Inverse histogram transformation T^{-1}
// Decorrelated color space vectors and origin
uniform vec3 colorSpaceVector1= vec3(0.345463,-0.266679,-0.0520962);
uniform vec3 colorSpaceVector2= vec3(0.923249,1.01518,0.92564);
uniform vec3 colorSpaceVector3= vec3(-0.129427,-0.245474,0.398311);
uniform vec3 colorSpaceOrigin = vec3(-0.0417463,0.301544,-0.28123); 

vec3 ReturnToOriginalColorSpace(vec3 color)
{

	vec3 result = 
		colorSpaceOrigin +
		colorSpaceVector1 * color.r +
		colorSpaceVector2 * color.g +
		colorSpaceVector3 * color.b;
    
	return result;
}

// Compute local triangle barycentric coordinates and vertex IDs
void TriangleGrid(vec2 uv,
	out float w1, out float w2, out float w3,
	out ivec2 vertex1, out ivec2 vertex2, out ivec2 vertex3)
{
	// Scaling of the input
	uv *= 3.464; // 2 * sqrt(3)

	// Skew input space into simplex triangle grid
	const mat2 gridToSkewedGrid = mat2(vec2(1.0, 0.0), vec2(-0.57735027, 1.15470054));
	vec2 skewedCoord = gridToSkewedGrid * uv;

	// Compute local triangle vertex IDs and local barycentric coordinates
	ivec2 baseId = ivec2(floor(skewedCoord));
	vec3 temp = vec3(fract(skewedCoord), 0);
	temp.z = 1.0 - temp.x - temp.y;
	if (temp.z > 0.0)
	{
		w1 = temp.z;
		w2 = temp.y;
		w3 = temp.x;
		vertex1 = baseId;
		vertex2 = baseId + ivec2(0, 1);
		vertex3 = baseId + ivec2(1, 0);
	}
	else
	{
		w1 = -temp.z;
		w2 = 1.0 - temp.y;
		w3 = 1.0 - temp.x;
		vertex1 = baseId + ivec2(1, 1);
		vertex2 = baseId + ivec2(1, 0);
		vertex3 = baseId + ivec2(0, 1);
	}
}

vec2 hash_noise(ivec2 p)
{
	return fract(sin(vec2(p) * mat2(vec2(127.1, 311.7), vec2(269.5, 183.3)) )*43758.5453);
}



// By-Example procedural noise at uv
vec3 ByExampleProceduralNoise(sampler2D Tinput, sampler2D invTex, vec2 uv)
{
	// Get triangle info
	float w1, w2, w3;
	ivec2 vertex1, vertex2, vertex3;
	TriangleGrid(uv, w1, w2, w3, vertex1, vertex2, vertex3);
		
	// Assign random offset to each triangle vertex
	vec2 uv1 = uv + hash_noise(vertex1);
	vec2 uv2 = uv + hash_noise(vertex2);
	vec2 uv3 = uv + hash_noise(vertex3);

	// Precompute UV derivatives 
	vec2 duvdx = dFdx(uv);
	vec2 duvdy = dFdy(uv);

	// Fetch Gaussian input
	vec3 G1 = textureGrad(Tinput, uv1, duvdx, duvdy).rgb;
	vec3 G2 = textureGrad(Tinput, uv2, duvdx, duvdy).rgb;
	vec3 G3 = textureGrad(Tinput, uv3, duvdx, duvdy).rgb;

	// Variance-preserving blending
	vec3 G = w1*G1 + w2*G2 + w3*G3;
	G = G - vec3(0.5);
	G = G * inversesqrt(w1*w1 + w2*w2 + w3*w3);
	//	if(_DXTScalers.x >= 0.0) G = G * _DXTScalers; // Only with DXT compression (Section 1.6)
	G = G + vec3(0.5);

	// Compute LOD level to fetch the prefiltered look-up table invT
/*#ifdef GL_ARB_texture_query_lod
	float LOD = textureQueryLod(Tinput, uv).y / float(textureSize(invT, 0).y); // textureQueryLod in Godot - FIXME
#else*/
  // see https://stackoverflow.com/a/24531164
  float mipmapLevel = 3.; // default in case extension is unavailable...
	float LOD = mipmapLevel; // FIXME
//#endif
	// Fetch prefiltered LUT (T^{-1})
	vec3 color;
	color.r	= texture(invTex, vec2(G.r, LOD)).r;
	color.g	= texture(invTex, vec2(G.g, LOD)).g;
	color.b	= texture(invTex, vec2(G.b, LOD)).b;
	
	// Original color space
	color = ReturnToOriginalColorSpace(color);

	return color;
}

void fragment(){
	vec4 ScaleTranslate = vec4(3.464);
  //vec2 screen_uv = FRAGCOORD.xy / SCREEN_PIXEL_SIZE.xy; // or resolution or smthn depends on the implementation
	COLOR = vec4(ByExampleProceduralNoise(uniform_Tinput, uniform_invT, UV * ScaleTranslate.xy + ScaleTranslate.zw), 1);
	//COLOR += vec4(ByExampleProceduralNoise(uniform_Tinput, uniform_invT, UV), 1);
	//COLOR /= 2.;
}
```

**Comment by blockspacer** [comment]
![image](https://user-images.githubusercontent.com/35254900/71449623-82eb6f80-2761-11ea-9902-c05b2d96433d.png)
Result with triplanar-looking `hack` and godot_voxel b216420a31e234fc58e5492d3481972289d1bccf
NOTE: I used godot_voxel before commit with normal mapping fixes and (Voxel Tools Issue #59).

**Comment by Zylann** [comment]
Smooth terrain doesn't have any `UV` because unwrapping such arbitrarty geometry efficiently and consistently is a really hard problem. So as you found out, triplanar mapping works instead.
In the future, `UV` might be set to something, but it won't be immediately usable as texture coordinates.

For Godot features, you may report to the Godot issue tracker.

**Comment by tinmanjuggernaut** [comment]
> IDK how to go from 2D to 3D without UV

You can use global vertex position in place of UVs. Turn on world_vertex_coords.

**Comment by blockspacer** [comment]
BTW another implementation of the stochastic shader can be found in 
 https://github.com/yaelatletl/godot_stochastic_shader
