### ISSUE TITLE
The Godot native script api seems to be broken

### ISSUE THREAD

**Issue by ChaosBeing** [Zylann/godot_voxel#92]
I've come across a curious issue while trying to start a project. As I was going to have some complex AI interactions with the world, I was going to write several scripts in c++. So far I had been using the Godot 3.2 alpha, and my small test project I'd created to make sure I'd generated all my bindings correctly executes just fine.

I'd initially planned on creating a much simpler voxel world myself, but upon finding this project I was delighted to find I could save myself the effort. However, even after recreating the bindings using the api.json file given by the most recent build of Godot with the voxel module (Windows 64 with mono, for what it's worth) Godot will crash before it can even open the project. (Godot 3.2 without the voxel module is still able to open and execute the project fine.) I can create new projects and load other old projects fine, but even creating a new project and then attempting to add native script will prevent the building of the project, and then if closed, the project cannot be reopened.

Some cursory debugging shows me that the Godot api itself seems to have become corrupted.

`Unhandled exception at 0x0000000000CD9F2A in Godot_v3.2+4569f5ec82_mono_win64.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF. occurred`

This occurs in the ARVRAnchor.cpp file, on the first line of `ARVRAnchor::___init_method_bindings()` where it attempts to call `godot::api->godot_method_bind_get_method`. The pointer to the function itself seems clean (at least, non-null) so I'd assume there must be an error occurring within the function itself. This could potentially be the first time that `godot::api` is being invoked, though, meaning it may be an issue with the class itself rather than an individual function call. (This would make some sense given the memory addressing issue.)

I'm still working on trying to narrow down the problem myself, but at this point I felt confident that the error doesn't lie on my side and I should let someone know about it. I'll update if I can find out anything more specific.

Edit: It only occurs to me now that there's another code base involved, namely `https://github.com/GodotNativeTools/godot-cpp`. I'd just assumed using the new json file generated by voxel Godot would make everything work somehow, but perhaps the bindings themselves need to be reworked. Again, I'll see if I can figure anything out.

**Comment by tinmanjuggernaut** [comment]
Building Godot with mono is temperamental and it should be removed from the equation if you are not using C#. Please try without mono. 

You're using my build of Godot + VT from November, but using the master branch of Godot-cpp? Does using the last October commit from Godot-cpp help? (probably want the latest, but maybe not) 

Next, when you use the basic C++ script shown in the Godot-cpp Readme, which just prints one line and does not create a voxel terrain, the build with VT crashes with the above error, but the official Godot 3.2 beta 5 without VT runs just fine? 

What is displayed on the console during the crash? Which you may need to enable a command line switch. 

If the console doesn't print the stack trace, please use your debugger to get one.

**Comment by tinmanjuggernaut** [comment]
I have a marching cubes implimentation I made using gdnative C++. It was compiled back in July's.

I ran it against my November VT build and it crashed as you described:

```
C:\Users\cory>D:\GD\godot_3.2+4569f5ec8_win64.exe -d -v D:\GD\govox\project-gdnative\project.godot
Godot Engine v3.2.alpha.custom_build.4569f5ec8 - https://godotengine.org
Using GLES3 video driver
OpenGL ES 3.0 Renderer: GeForce GTX 1060/PCIe/SSE2
WASAPI: wFormatTag = 65534
WASAPI: nChannels = 2
WASAPI: nSamplesPerSec = 44100
WASAPI: nAvgBytesPerSec = 352800
WASAPI: nBlockAlign = 8
WASAPI: wBitsPerSample = 32
WASAPI: cbSize = 22
WASAPI: detected 2 channels
WASAPI: audio buffer frames: 970 calculated latency: 21ms

CORE API HASH: 16844987420847489025
EDITOR API HASH: 16189665037908562130
Loading resource: res://default_env.tres
Construct gdnative interface

Destruct gdnative interface

Construct VoxelLodTerrain
Destroy VoxelLodTerrain
Destroying VoxelMap
Destroying VoxelMap
Destroying VoxelMap
Destroying VoxelMap
Destroying VoxelTerrain
Destroying VoxelMap
Loading resource: C:\Users/cory/AppData/Roaming/Godot/editor_settings-3.tres
EditorSettings: Load OK!
Loaded builtin certs
EditorSettings: Save OK!
Loading resource: res://bin/govox.gdnlib
Loading resource: res://bin/govox.gdns
Loading resource: res://scenes/Main.gd
Loading resource: res://bin/govox.gdnlib
ERROR: 'The class variable 'step' is declared but never used in the script.'
ERROR: 'The argument 'delta' is never used in the function '_process'.'
Loading resource: res://scenes/marching-cubes-cpp.tscn
Loading resource: res://bin/govox.gdns
CrashHandlerException: Program crashed
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[0] <couldn't map PC to fn name>
[1] <couldn't map PC to fn name>
[2] godot_nativescript_init
[3] godot_nativescript_init
[4] godot_nativescript_init
[5] <couldn't map PC to fn name>
[6] <couldn't map PC to fn name>
[7] <couldn't map PC to fn name>
[8] <couldn't map PC to fn name>
[9] <couldn't map PC to fn name>
[10] <couldn't map PC to fn name>
[11] <couldn't map PC to fn name>
[12] <couldn't map PC to fn name>
[13] <couldn't map PC to fn name>
[14] <couldn't map PC to fn name>
[15] <couldn't map PC to fn name>
[16] <couldn't map PC to fn name>
[17] <couldn't map PC to fn name>
[18] <couldn't map PC to fn name>
[19] <couldn't map PC to fn name>
[20] <couldn't map PC to fn name>
[21] <couldn't map PC to fn name>
[22] <couldn't map PC to fn name>
[23] <couldn't map PC to fn name>
[24] <couldn't map PC to fn name>
[25] <couldn't map PC to fn name>
[26] <couldn't map PC to fn name>
[27] <couldn't map PC to fn name>
[28] <couldn't map PC to fn name>
[29] <couldn't map PC to fn name>
[30] <couldn't map PC to fn name>
[31] <couldn't map PC to fn name>
[32] <couldn't map PC to fn name>
[33] <couldn't map PC to fn name>
[34] <couldn't map PC to fn name>
[35] <couldn't map PC to fn name>
[36] BaseThreadInitThunk
-- END OF BACKTRACE --
```

Next, I ran it against a build from two days ago with the current master Godot & VT master and it ran just fine.

I think you're at the point where you should be building your own Godot. There's no C++ required. It's more difficult to get GDNative up and running than building Godot+VT, so you're more than capable. Then you'll be able to get the latest Godot, VT, and Godot-cpp. 

I plan to update all of my builds once Godot 3.2 is finally released.

**Comment by ChaosBeing** [comment]
I built the master branches of Godot and Voxel Tools as suggested and everything works perfectly! I had assumed I was basically current with the pre-built binaries but in retrospect I really should have tried this before even posting an issue. Thank you for your time, and for the voxel tools as well of course!
