### ISSUE TITLE
Spamming edits in a large area every frame / loading too much data at once eventually causes memory to run out

### ISSUE THREAD

**Issue by Zylann** [Zylann/godot_voxel#97]
As experienced in https://github.com/Zylann/godot_voxel/issues/72#issuecomment-572217527, if you edit a large amount of blocks every frame, memory usage eventually increases to a point the engine crashes due to being out of memory.

Even though that situation is an edge case, it could be avoidable. It happens because when the terrain changes, the module currently copies voxel data (block and neighbor faces) before sending it to the meshing thread. But if the meshing thread is given more blocks to update than it can consume over a period of time, the queue will continue growing forever.

**Edit: this also happens if you setup a world with a combination of high view distance and high LOD accuracy, as this will trigger too much updates at once.**

A different approach may be taken to make this edge case much less likely to cause trouble.

### Copy on write

This sounds like a good candidate, but the voxel data needed for the meshing thread is not just one PoolVector. VoxelBuffers don't use PoolVectors. In fact, they sometimes don't even have stored data. So if CoW is implemented it may need to be done with more than just PoolVectors, or differently.
If VoxelBuffer gets changed to use PoolVector, any voxel access or modification will require locking, like it's the case with `Image`.

### Area locking

The VoxelMap from where voxels are going to be read could be sent, along with the area to polygonize. Then this area will be copied within the thread, just before being used to produce the mesh. This means the area needs to be locked for reading, during the time of copy. During this short time, the main thread will not be allowed to modify voxels in this area, but should be allowed to read them.

I like this idea, however `VoxelMap` uses a `HashMap`. If we need to read a few blocks from the thread, we need to access this hash map, so no block can be added or removed from it, *anywhere*, during this time. I'm aware of concurrent maps, but I don't know if it's the best choice here.
One way would be to get those blocks, send them to the thread, and lock them there. This must be done while preserving a consistent iteration order (which is important to avoid deadlocking if two threads access those blocks at the same time).

In any case, in the future accessing voxels will need locking of some form.

**Comment by Zylann** [comment]
On the left, what we have right now. On the right, what I've been considering so far:
![image](https://user-images.githubusercontent.com/1311555/73127489-009cd800-3fb9-11ea-8bd1-b481615330d6.png)

**Comment by voxelv** [comment]
Does "Spamming Edits" include every `buffer.set_voxel()` call in a `VoxelStream.emerge_block()`?

Regardless, I'm getting memory errors in `VoxelMesherBlocky.build()` (which seems like the same issue as this) from just having a `VoxelTerrain.view_distance` set to `384` and letting it run for a minute.
Here's a link to my project which has reproduced a memory error on both my desktop and laptop https://github.com/voxelv/voxel_test/tree/Zylann_godot_voxel_issue_97

I can also provide stack-traces if desired (as I've successfully built the godot_voxel module and engine for 3.2).

**Comment by Zylann** [comment]
> Does "Spamming Edits" include every buffer.set_voxel() call in a VoxelStream.emerge_block()?

No, only modifications that involve recomputing a mesh. Note that if multiple `set_voxel` calls are made on the same block plenty of times the same frame, that only counts for 1 update still.
The problem becomes apparent if many blocks get affected at once, and frequently.

**Comment by voxelv** [comment]
I suspect my "world" is probably the problem as I'm having it set every 4th voxel in each axis to a voxel (similar to SkyGrid https://i.ytimg.com/vi/5dhs3ithXDA/maxresdefault.jpg)

**Comment by voxelv** [comment]
I bet a quick way to hit it would be to max-out the mesher with something like:
```gdscript
for x in range(buffer.get_size_x()):
	for y in range(buffer.get_size_y()):
		for z in range(buffer.get_size_z()):
			if (x + y + z) % 2 == 0:
				buffer.set_voxel(1, x, y, z, channel)
```

**Comment by Zylann** [comment]
> I suspect my "world" is probably the problem as I'm having it set every 4th voxel in each axis to a voxel (similar to SkyGrid https://i.ytimg.com/vi/5dhs3ithXDA/maxresdefault.jpg)

Yeah, that must be it^^
That is approaching the worst possible case scenario (the absolute worst being a perfect interleaving of air and cube every unit).
This forces every loaded block to allocate full 16x16x16 memory, and that doesn't go well with the current copy model.
Locking as described in https://github.com/Zylann/godot_voxel/issues/97#issuecomment-578444315 would solve this.

**Comment by voxelv** [comment]
It sure looks cool when it does work ;) 

![20200229_015119](https://user-images.githubusercontent.com/6580714/75784923-cd680a00-5d17-11ea-9f82-e73abaf6ea32.png)

**Comment by tinmanjuggernaut** [comment]
I've found it's pretty easy to get this error just by having certain LOD settings and view distances on VLT (though I'm also running into it easily with VT and FastNoiseSIMD).
```
ERROR: ERROR: All memory pool allocations are in use.
   At: D:\gd\godot\core/pool_vector.h:529
```

Using noise algorithms, generating a height of 0-512:
LOD4, 2048 - very slow, then crashes
LOD4, 1500 - starts sluggish, then ok
LOD5, 4096 - works 
LOD5, 8192 - crashes
LOD6, 8192 - works

Higher than 6 does better. In fact, it's far faster to get going with LOD7/4096 than LOD4/1500.

I discovered this while almost done with FastNoiseSIMD implementation. I thought it was my code, but it seems to have these same effects of any of the 4 noise methods used: OpenSimplexNoise, FastNoise, FastNoiseSIMD, FastNoiseSIMD-singular.

Within Godot I noted that the static memory peaks at 232mb, and dynamic peaks at 76. But the Godot process goes up to about 3GB before finally crashing (though I have 8GB free, why would it die?).

On Linux it stayed under 1GB. Overall things seem to run far better on linux and it's about 30-100% faster. I haven't run into the memory crashes, but I hadn't discovered the issue with the lower LODs yet, so I'll try again next time I've rebooted.

**Comment by Zylann** [comment]
It is well known now that any setup requiring an initial loading of the world with too many high-res blocks at once can make this happen. For now those setups won't be supported until the data storage refactoring is done.

If you really want high-density blocks environment over large distances, a workaround would be to setup view distance lower, and slowly increase it during the game.

Note that despite the future improvement, there will be a limit to how much data can be held in memory anyways, which can be mitigated with other means such as uniform compression (not automatic, you may do that in the generator) or delta compression (mentionned in other issue).

**Comment by Anyeos** [comment]
> Note that despite the future improvement, there will be a limit to how much data can be held in memory anyways, which can be mitigated with other means such as uniform compression (not automatic, you may do that in the generator) or delta compression (mentionned in other issue).

Yes, I guess that you are saying is that there are a fixed physical memory on a computer, but that does not mean that the code must fail because it not contemplate some aspects of memory handling. The code must be robust enought so if there are no memory it can handle it on some way.

**Comment by Zylann** [comment]
@Anyeos are you referring to the fact it should not crash due to an out-of-memory? (but rather print errors in some way, though printing also allocates memory)

**Comment by Anyeos** [comment]
Zylann I mean something that test if the memory was allocated before trying to use it. And I dont know if Godot throw exceptions about memory allocation.
The crash normally are because there are a Pointer that points to no memory because that was not allocated. 

But I think everything is possible so I think can be possible implement a better aproach to handle the things but not only memory.
That is why I upvote for the proposal.

**Comment by Zylann** [comment]
> I mean check if the memory was allocated before trying to use it. Or if Godot throw exceptions about memory allocation, to use that.

I can check, but if allocation returns null there is still a high chance that something else I don't control will crash for the same reason :/ 
Although, the first culprit here is `PoolVector`'s arbitrary limitations (so *meshes*, not voxel data), which may happen even if I implemented this proposal lol

**Comment by Anyeos** [comment]
If it is better and if you can, do it. Because if you do the right things, there are less chance to fails.
For now I think it is not your fail but Godot. I expect that Godot 4 have that solved. Apparently they are not using anymore the pool and now allocates memory dynamically.

**Comment by Zylann** [comment]
The concern from the first post has mostly been addressed since: voxels are no longer copied for a long time before being processed. The PoolVector limitation is also no longer existing in Godot 4. Can't do much about Godot 3's limitation, but if it leads to a crash originating from the module please report. Checks were also added in places where allocation can fail, but as stated earlier it is too likely Godot will cause a crash anyways after not succeeding to allocate something.
